import { createHash, randomUUID } from "node:crypto";
import type { DashboardDatabase } from "../db/DashboardDatabase.js";
import { nowIso } from "../db/DashboardDatabase.js";
import { FindingRepository } from "../db/DashboardRepositories.js";
import type { ComparisonFindingResult, ComparisonResult, DashboardFindingSummary, RegressionFlag } from "../types/DashboardTypes.js";
import { ScanComparisonCoverageService } from "./ScanComparisonCoverageService.js";
import { redactDashboardValue, safeJson } from "../security/Redaction.js";

export const COMPARISON_ENGINE_VERSION = "3.0.0";
const COVERAGE_VERSION = "3.0.0";
type Occurrence = { id: string; finding_id: string; fingerprint: string; module: string; finding_category: string; severity: string; confidence: string; safe_endpoint: string; safe_actor_relationship: string | null; safe_tenant_or_role_boundary: string | null; safe_state_boundary: string | null; workflow_case_alias: string | null; coverage_reference_json: string; source_kind: string; evidence_summary: string; http_method: string };
export interface ComparisonFindingQuery { page?: number; pageSize?: number; classification?: string; regression?: boolean; severity?: string; module?: string; coverage?: string; sort?: string; direction?: string; }
export const comparisonFindingPageSizeMaximum = 100;

export class ScanComparisonService {
  private readonly findings: FindingRepository;
  private readonly coverage: ScanComparisonCoverageService;
  public constructor(private readonly database: DashboardDatabase) { this.findings = new FindingRepository(database); this.coverage = new ScanComparisonCoverageService(database); }

  public compare(oldScanId: string, newScanId: string, options: { createdByUserId?: string; recompute?: boolean } = {}): ComparisonResult {
    if (oldScanId === newScanId) throw new Error("Choose two different scans to compare.");
    const prior = !options.recompute ? this.database.db.prepare("SELECT id FROM scan_comparisons WHERE older_scan_id=? AND newer_scan_id=? AND engine_version=? AND deleted_at IS NULL").get(oldScanId, newScanId, COMPARISON_ENGINE_VERSION) as { id: string } | undefined : undefined;
    if (prior) return this.get(prior.id);
    const oldScan = this.scan(oldScanId), newScan = this.scan(newScanId), id = randomUUID(), created = nowIso();
    const engine = options.recompute ? `${COMPARISON_ENGINE_VERSION}+${created.replace(/\D/g, "")}` : COMPARISON_ENGINE_VERSION;
    const oldQuality = this.coverage.sourceQuality(oldScanId), newQuality = this.coverage.sourceQuality(newScanId);
    this.database.db.prepare(`INSERT INTO scan_comparisons (id,project_id,target_id,older_scan_id,newer_scan_id,state,compatibility_state,source_quality_older,source_quality_newer,created_by_user_id,created_at,engine_version,coverage_algorithm_version,finding_fingerprint_version,summary_json,coverage_summary_json,warning_json) VALUES (?,?,?,?,?,'ANALYZING','ANALYZING',?,?,?,?,?,?,'hmac-v1','{}','{}','[]')`).run(id, newScan.project_id ?? oldScan.project_id, newScan.target_id ?? oldScan.target_id, oldScanId, newScanId, oldQuality, newQuality, this.user(options.createdByUserId), created, engine, COVERAGE_VERSION);
    try { this.analyze(id, oldScan, newScan, oldQuality, newQuality); } catch (error) { this.database.db.prepare("UPDATE scan_comparisons SET state='FAILED',compatibility_state='FAILED',failure_category=?,completed_at=? WHERE id=?").run(error instanceof Error ? error.name : "FAILED", nowIso(), id); throw error; }
    return this.get(id);
  }

  public get(id: string, query?: ComparisonFindingQuery): ComparisonResult {
    const row = this.database.db.prepare("SELECT * FROM scan_comparisons WHERE id=? AND deleted_at IS NULL").get(id) as any;
    if (!row) throw new Error("Comparison was not found.");
    const findingPage = query ? this.findingRows(id, query) : undefined;
    const items = (findingPage?.rows ?? this.database.db.prepare("SELECT * FROM scan_comparison_findings WHERE comparison_id=? ORDER BY classification,finding_id").all(id) as any[]).map((v) => this.item(v));
    const c = parse<any>(row.coverage_summary_json, {});
    const modules = (this.database.db.prepare("SELECT module_id moduleId,older_state olderState,newer_state newerState,comparable,reason_code reasonCode,safe_reason reason FROM scan_comparison_module_coverage WHERE comparison_id=? ORDER BY module_id").all(id) as any[]).map((v) => ({ ...v, comparable: Boolean(v.comparable) }));
    const workflows = (this.database.db.prepare("SELECT workflow_id workflowId,older_configured olderConfigured,newer_configured newerConfigured,older_case_count olderCaseCount,newer_case_count newerCaseCount,matched_case_count matchedCases,missing_case_count missingCases,changed_case_count changedCases,executed_matched_case_count executedMatchedCases,comparable,safe_reason reason FROM scan_comparison_workflow_coverage WHERE comparison_id=? ORDER BY workflow_id").all(id) as any[]).map((v) => ({ ...v, olderConfigured: Boolean(v.olderConfigured), newerConfigured: Boolean(v.newerConfigured), comparable: Boolean(v.comparable) }));
    const cases = this.database.db.prepare("SELECT workflow_id workflowId,safe_case_fingerprint safeCaseFingerprint,safe_case_alias safeCaseAlias,state,compatibility,reason_code reasonCode,safe_reason reason FROM scan_comparison_case_coverage WHERE comparison_id=? ORDER BY workflow_id,safe_case_alias").all(id) as any[];
    return { schemaVersion: 3, comparisonId: id, state: row.state, engineVersion: row.engine_version, oldScanId: row.older_scan_id, newScanId: row.newer_scan_id, compatible: row.compatibility_state === "COMPATIBLE", compatibilityState: row.compatibility_state, sourceQuality: { older: row.source_quality_older, newer: row.source_quality_newer }, warnings: parse(row.warning_json, []), coverage: { sameTarget: Boolean(c.sameTarget), scopeState: c.scopeState ?? "INCOMPARABLE", authenticationState: c.authenticationState ?? "INCOMPARABLE", identityState: c.identityState ?? "INCOMPARABLE", oldProfile: c.oldProfile ?? "unknown", newProfile: c.newProfile ?? "unknown", oldCompletedModules: c.oldCompletedModules ?? [], newCompletedModules: c.newCompletedModules ?? [], sharedModules: c.sharedModules ?? [], omittedModules: c.omittedModules ?? [], addedModules: c.addedModules ?? [], modules, workflows, cases }, planDiff: parse(c.planDiffJson ?? "[]", []), summary: parse(row.summary_json, summary([])), items, ...(findingPage ? { findingPage: { page: findingPage.page, pageSize: findingPage.pageSize, total: findingPage.total, totalPages: findingPage.totalPages } } : {}), findings: { new: cls(items,"NEW"), persisting: cls(items,"PERSISTING"), changed: cls(items,"CHANGED"), resolved: cls(items,"RESOLVED"), notRetested: cls(items,"NOT_RETESTED"), incomparable: cls(items,"INCOMPARABLE"), regressions: items.filter((v) => v.regressionFlags.includes("REGRESSION")) } };
  }

  private findingRows(id: string, query: ComparisonFindingQuery): { rows: any[]; page: number; pageSize: number; total: number; totalPages: number } {
    const classifications = new Set(["NEW","PERSISTING","CHANGED","RESOLVED","NOT_RETESTED","INCOMPARABLE"]);
    const sorts: Record<string, string> = { classification: "cf.classification", severity: "CASE COALESCE(f.effective_severity,f.current_scanner_severity) WHEN 'Critical' THEN 4 WHEN 'High' THEN 3 WHEN 'Medium' THEN 2 WHEN 'Low' THEN 1 ELSE 0 END", module: "f.module", coverage: "cf.coverage_state", title: "f.canonical_title", created: "cf.created_at" };
    if (query.classification && !classifications.has(query.classification)) throw new Error("Unsupported comparison classification filter.");
    const sort = query.sort ?? "classification"; if (!sorts[sort]) throw new Error("Unsupported comparison finding sort field.");
    const direction = (query.direction ?? "asc").toLowerCase(); if (direction !== "asc" && direction !== "desc") throw new Error("Unsupported comparison finding sort direction.");
    const pageSize = Math.min(Math.max(Math.trunc(query.pageSize ?? 25), 1), comparisonFindingPageSizeMaximum), page = Math.max(Math.trunc(query.page ?? 1), 1);
    const clauses = ["cf.comparison_id = ?"], values: Array<string | number> = [id];
    if (query.classification) { clauses.push("cf.classification = ?"); values.push(query.classification); }
    if (query.regression === true) clauses.push("cf.regression_flags_json LIKE '%\"REGRESSION\"%'");
    if (query.regression === false) clauses.push("cf.regression_flags_json NOT LIKE '%\"REGRESSION\"%'");
    if (query.severity) { clauses.push("COALESCE(f.effective_severity,f.current_scanner_severity) = ?"); values.push(query.severity); }
    if (query.module) { clauses.push("f.module = ?"); values.push(query.module); }
    if (query.coverage) { clauses.push("cf.coverage_state = ?"); values.push(query.coverage); }
    const where = clauses.join(" AND ");
    const total = (this.database.db.prepare(`SELECT COUNT(*) count FROM scan_comparison_findings cf JOIN findings f ON f.id=cf.finding_id WHERE ${where}`).get(...values) as { count: number }).count;
    const rows = this.database.db.prepare(`SELECT cf.* FROM scan_comparison_findings cf JOIN findings f ON f.id=cf.finding_id WHERE ${where} ORDER BY ${sorts[sort]} ${direction.toUpperCase()}, cf.finding_id ASC LIMIT ? OFFSET ?`).all(...values, pageSize, (page - 1) * pageSize) as any[];
    return { rows, page, pageSize, total, totalPages: Math.max(1, Math.ceil(total / pageSize)) };
  }

  public list(filter: { targetId?: string; projectId?: string; limit?: number; organizationId?: string } = {}): any[] { const clauses=["c.deleted_at IS NULL"], values:any[]=[]; if(filter.organizationId){clauses.push("os.organization_id=? AND ns.organization_id=?");values.push(filter.organizationId,filter.organizationId);} if(filter.targetId){clauses.push("c.target_id=?");values.push(filter.targetId);} if(filter.projectId){clauses.push("c.project_id=?");values.push(filter.projectId);} values.push(Math.min(Math.max(filter.limit??50,1),100)); return this.database.db.prepare(`SELECT c.id,c.older_scan_id olderScanId,c.newer_scan_id newerScanId,c.state,c.compatibility_state compatibilityState,c.summary_json summaryJson,c.created_at createdAt,c.completed_at completedAt,os.profile olderProfile,ns.profile newerProfile,ns.target_origin target FROM scan_comparisons c JOIN scans os ON os.id=c.older_scan_id JOIN scans ns ON ns.id=c.newer_scan_id WHERE ${clauses.join(" AND ")} ORDER BY c.created_at DESC LIMIT ?`).all(...values) as any[]; }
  public candidates(targetId?: string,organizationId?:string): any[] { const rows=this.database.db.prepare(`SELECT id,target_id,target_origin,profile,status,source,created_at,completed_at,duration_ms,planned_module_count,completed_module_count,finding_count FROM scans WHERE deleted_at IS NULL AND status IN ('COMPLETED','IMPORTED','CANCELLED','FAILED','INTERRUPTED') ${targetId?"AND target_id=?":""} ${organizationId?"AND organization_id=?":""} ORDER BY created_at DESC LIMIT 100`).all(...(targetId?[targetId]:[]),...(organizationId?[organizationId]:[])) as any[]; return rows.map((v,i)=>({id:v.id,shortId:v.id.slice(0,8),targetId:v.target_id,target:v.target_origin,profile:v.profile,status:v.status,source:v.source,createdAt:v.created_at,completedAt:v.completed_at,durationMs:v.duration_ms,moduleCoverage:`${v.completed_module_count}/${v.planned_module_count}`,findingCount:v.finding_count,compatibilityLabel:["COMPLETED","IMPORTED"].includes(v.status)?i<2?"Recommended":"Compatible":"Partially comparable"})); }
  public export(id:string, format:"json"|"markdown"):string { const value=redactDashboardValue(this.get(id)) as ComparisonResult; if(format==="json")return JSON.stringify(value,null,2); const lines=["# RouteCairn Scan Comparison","",`- Comparison: \`${value.comparisonId}\``,`- Older scan: \`${value.oldScanId}\``,`- Newer scan: \`${value.newScanId}\``,`- Compatibility: ${value.compatibilityState}`,"","## Summary","",...Object.entries(value.summary).map(([k,v])=>`- ${k}: ${v}`),"","## Findings",""]; for(const item of value.items)lines.push(`### ${item.classification}: ${md(item.finding.title)}`,"",`- Module: ${md(item.finding.module)}`,`- Endpoint: \`${md(item.finding.endpoint)}\``,`- Reason: ${item.reasonCode}`,`- Explanation: ${md(item.explanation)}`,`- Regression flags: ${item.regressionFlags.join(", ")||"None"}`,""); return lines.join("\n"); }
  public delete(id:string):void { this.database.db.prepare("UPDATE scan_comparisons SET deleted_at=? WHERE id=?").run(nowIso(),id); }

  private analyze(id:string, oldScan:any, newScan:any, oldQuality:string, newQuality:string):void {
    const old=this.occurrences(oldScan.id), newer=this.occurrences(newScan.id), oldMap=new Map(old.map(v=>[v.fingerprint,v])), used=new Set<string>(), results:ComparisonFindingResult[]=[];
    for(const current of newer){ const exact=oldMap.get(current.fingerprint); const fallback=exact?undefined:old.find(v=>!used.has(v.id)&&key(v)===key(current)); if(exact){used.add(exact.id);results.push(this.present(exact,current));} else if(fallback){used.add(fallback.id);results.push(make(this.finding(current.finding_id),"INCOMPARABLE",[],"INCOMPATIBLE","SECURITY_BOUNDARY_CHANGED","The endpoint and category match, but the durable actor or security-boundary identity changed.",fallback,current,[{field:"securityBoundary",older:boundary(fallback),newer:boundary(current),direction:"CHANGED"}],delta(fallback,current)));} else results.push(this.added(current,oldScan.created_at,newScan.created_at)); }
    for(const previous of old)if(!used.has(previous.id)&&!newer.some(v=>v.fingerprint===previous.fingerprint)){const coverage=this.coverage.evaluateFinding(oldScan.id,newScan.id,previous);results.push(make(this.finding(previous.finding_id),coverage.disposition==="ADEQUATE"?"RESOLVED":coverage.disposition,[],coverage.disposition,coverage.reasonCode,coverage.disposition==="ADEQUATE"?`${coverage.explanation} The previous finding was not reproduced.`:coverage.explanation,previous,undefined,[],{coverageFacts:coverage.facts}));}
    this.persistCoverage(id,oldScan.id,newScan.id);
    const oldModules=this.coverage.modules(oldScan.id).filter(v=>v.status==="COMPLETED").map(v=>v.module_id).sort(), newModules=this.coverage.modules(newScan.id).filter(v=>v.status==="COMPLETED").map(v=>v.module_id).sort(), shared=oldModules.filter(v=>newModules.includes(v)), omitted=oldModules.filter(v=>!newModules.includes(v)), added=newModules.filter(v=>!oldModules.includes(v));
    const sameTarget=(oldScan.target_id&&newScan.target_id)?oldScan.target_id===newScan.target_id:oldScan.target_origin===newScan.target_origin, scopeState=this.coverage.scopeState(oldScan.id,newScan.id), authenticationState=this.coverage.compareAuthentication(oldScan.id,newScan.id), identityState=this.coverage.compareIdentity(oldScan.id,newScan.id), warnings:string[]=[];
    if(!sameTarget)warnings.push("Targets differ; resolution semantics are incomparable."); if(oldScan.profile!==newScan.profile)warnings.push("Profiles differ; coverage is evaluated from resolved modules and cases rather than profile names."); if(newQuality==="IMPORTED_FINDINGS_ONLY")warnings.push("The newer import lacks coverage metadata and cannot prove resolution."); if(!["EQUIVALENT_FOR_FINDING","EXPANDED"].includes(scopeState))warnings.push(`Scope comparison is ${scopeState.toLowerCase().replaceAll("_"," ")}.`); if(authenticationState!=="EQUIVALENT")warnings.push("Authentication semantics changed or are unavailable.");
    const planDiff=this.planDiff(oldScan.id,newScan.id), compatibility=sameTarget&&shared.length&&newQuality!=="IMPORTED_FINDINGS_ONLY"?(warnings.length?"PARTIALLY_COMPARABLE":"COMPATIBLE"):"WEAK_COMPATIBILITY", state=oldQuality.includes("PARTIAL")||newQuality.includes("PARTIAL")||newQuality==="IMPORTED_FINDINGS_ONLY"?"PARTIAL":"COMPLETED";
    this.database.transaction(()=>{const insert=this.database.db.prepare("INSERT INTO scan_comparison_findings (id,comparison_id,finding_id,older_occurrence_id,newer_occurrence_id,classification,coverage_state,reason_code,safe_explanation,material_changes_json,regression_flags_json,safe_evidence_delta_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)");for(const v of results)insert.run(v.id,id,v.finding.id,v.olderOccurrenceId??null,v.newerOccurrenceId??null,v.classification,v.coverageState,v.reasonCode,v.explanation,safeJson(v.materialChanges),safeJson(v.regressionFlags),safeJson(v.evidenceDelta),nowIso());const coverage={sameTarget,scopeState,authenticationState,identityState,oldProfile:oldScan.profile,newProfile:newScan.profile,oldCompletedModules:oldModules,newCompletedModules:newModules,sharedModules:shared,omittedModules:omitted,addedModules:added,planDiffJson:JSON.stringify(planDiff)};this.database.db.prepare("UPDATE scan_comparisons SET state=?,compatibility_state=?,completed_at=?,summary_json=?,coverage_summary_json=?,warning_json=?,older_plan_fingerprint=?,newer_plan_fingerprint=? WHERE id=?").run(state,compatibility,nowIso(),safeJson(summary(results)),safeJson(coverage),safeJson(warnings),this.planHash(oldScan.id),this.planHash(newScan.id),id);});
  }

  private persistCoverage(id:string, oldId:string, newId:string):void { const om=new Map(this.coverage.modules(oldId).map(v=>[v.module_id,v])),nm=new Map(this.coverage.modules(newId).map(v=>[v.module_id,v])),mi=this.database.db.prepare("INSERT INTO scan_comparison_module_coverage VALUES (?,?,?,?,?,?,?)");for(const moduleId of [...new Set([...om.keys(),...nm.keys()])].sort()){const a=om.get(moduleId),b=nm.get(moduleId),ok=a?.status==="COMPLETED"&&b?.status==="COMPLETED",code=!a?"MODULE_ADDED":!b?"MODULE_NOT_PLANNED":b.status!=="COMPLETED"?"MODULE_NOT_COMPLETED":"MODULE_COMPLETED",reason=!a?"Module was added in the newer scan.":!b?"Module was omitted from the newer scan.":ok?"Module completed in both scans.":`Newer module state is ${b.status}.`;mi.run(id,moduleId,a?.status??"NOT_PLANNED",b?.status??"NOT_PLANNED",ok?1:0,code,reason);} const workflows=["object-pair","field-exposure","authorization-matrix","equivalent-route","collection-authorization","bulk-authorization","file-authorization"],oc=this.coverage.cases(oldId),nc=this.coverage.cases(newId),wi=this.database.db.prepare("INSERT INTO scan_comparison_workflow_coverage VALUES (?,?,?,?,?,?,?,?,?,?,?,?)"),ci=this.database.db.prepare("INSERT INTO scan_comparison_case_coverage VALUES (?,?,?,?,?,?,?,?,?,?)");for(const workflow of workflows){const a=oc.filter(v=>v.workflow_id===workflow),b=nc.filter(v=>v.workflow_id===workflow);let matched=0,missing=0,changed=0,executed=0;for(const oldCase of a){const exact=b.find(v=>v.safe_case_fingerprint===oldCase.safe_case_fingerprint),alias=b.find(v=>v.safe_case_alias===oldCase.safe_case_alias),next=exact??alias,state=!next?"CASE_MISSING":!exact?"CASE_CHANGED":next.execution_state==="COMPLETED"&&next.request_transmitted?"CASE_MATCHED_EXECUTED":next.execution_state==="BLOCKED"||next.execution_state==="BUDGET_EXHAUSTED"?"CASE_BLOCKED":"CASE_MATCHED_NOT_EXECUTED";if(!next)missing++;else if(!exact)changed++;else{matched++;if(state==="CASE_MATCHED_EXECUTED")executed++;}ci.run(id,workflow,oldCase.safe_case_fingerprint,oldCase.safe_case_alias,state,state==="CASE_MATCHED_EXECUTED"?"COMPATIBLE":state==="CASE_CHANGED"?"INCOMPARABLE":"NOT_RETESTED",state==="CASE_MATCHED_EXECUTED"?"COMPATIBLE_CASE_COVERAGE":state,state==="CASE_MATCHED_EXECUTED"?"The same safe case semantics completed in both scans.":state.replaceAll("_"," ").toLowerCase(),oldCase.id,next?.id??null);}const ok=a.length>0&&missing===0&&changed===0&&executed===a.length,reason=a.length===0&&b.length===0?"Workflow was not configured in either scan.":ok?"All older workflow cases were matched and executed.":"One or more older cases were missing, changed, blocked, or not executed.";wi.run(id,workflow,a.length?1:0,b.length?1:0,a.length,b.length,matched,missing,changed,executed,ok?1:0,reason);}}
  private present(a:Occurrence,b:Occurrence):ComparisonFindingResult {const changes=changesFor(a,b),flags:RegressionFlag[]=[];if(rank(b.severity)>rank(a.severity))flags.push("SEVERITY_INCREASE");if(conf(b.confidence)>conf(a.confidence))flags.push("CONFIDENCE_INCREASE");return make(this.finding(b.finding_id),changes.length?"CHANGED":"PERSISTING",flags,"OBSERVED_BOTH",changes.length?"MATERIAL_SECURITY_CHANGE":"SAME_SECURITY_SEMANTICS",changes.length?"The same durable finding appears in both scans with material security-relevant changes.":"The same durable finding appears in both scans with materially equivalent security semantics.",a,b,changes,delta(a,b));}
  private added(v:Occurrence,oldTime:string,newTime:string):ComparisonFindingResult {const recur=Boolean(this.database.db.prepare("SELECT 1 FROM finding_occurrences WHERE finding_id=? AND created_at<? LIMIT 1").get(v.finding_id,oldTime)),regress=recur&&Boolean(this.database.db.prepare("SELECT 1 FROM finding_remediation_history WHERE finding_id=? AND new_state='FIXED_VERIFIED' AND created_at<? LIMIT 1").get(v.finding_id,newTime)),flags:RegressionFlag[]=regress?["REGRESSION"]:recur?["RECURRENCE"]:[];return make(this.finding(v.finding_id),"NEW",flags,"OBSERVED_NEWER",regress?"VERIFIED_REGRESSION":recur?"RECURRENCE":"NO_COMPATIBLE_BASELINE_IDENTITY",regress?"A previously verified-resolved durable finding is demonstrably present again.":recur?"A previously observed issue appears again without proof of prior remediation.":"The newer scan contains a durable finding identity absent from the older baseline.",undefined,v,[],{newerEvidenceSummary:v.evidence_summary});}
  private item(v:any):ComparisonFindingResult{return{id:v.id,finding:this.finding(v.finding_id),classification:v.classification,regressionFlags:parse(v.regression_flags_json,[]),coverageState:v.coverage_state,reasonCode:v.reason_code,explanation:v.safe_explanation,...(v.older_occurrence_id?{olderOccurrenceId:v.older_occurrence_id}:{}),...(v.newer_occurrence_id?{newerOccurrenceId:v.newer_occurrence_id}:{}),materialChanges:parse(v.material_changes_json,[]),evidenceDelta:parse(v.safe_evidence_delta_json,{})};}
  private scan(id:string):any {const v=this.database.db.prepare("SELECT id,created_at,project_id,target_id,profile,target_origin FROM scans WHERE id=? AND deleted_at IS NULL").get(id);if(!v)throw new Error(`Scan ${id} was not found.`);return v;}
  private occurrences(id:string):Occurrence[]{return this.database.db.prepare("SELECT o.id,o.finding_id,f.fingerprint,o.module,o.finding_category,o.severity,o.confidence,o.safe_endpoint,o.safe_actor_relationship,o.safe_tenant_or_role_boundary,o.safe_state_boundary,o.workflow_case_alias,o.coverage_reference_json,o.source_kind,o.evidence_summary,f.http_method FROM finding_occurrences o JOIN findings f ON f.id=o.finding_id WHERE o.scan_id=? ORDER BY f.fingerprint").all(id) as Occurrence[];}
  private finding(id:string):DashboardFindingSummary {const v=this.findings.get(id);if(!v)throw new Error(`Comparison finding ${id} is unavailable.`);return v;}
  private user(id?:string):string|null{return id&&(this.database.db.prepare("SELECT 1 FROM dashboard_users WHERE id=?").get(id))?id:null;}
  private snapshot(id:string,column:string):string|undefined{return(this.database.db.prepare(`SELECT ${column} value FROM scan_plan_snapshots WHERE scan_id=?`).get(id)as any)?.value;}
  private planHash(id:string):string|null{const v=this.snapshot(id,"redacted_plan_json");return v?createHash("sha256").update(v).digest("hex"):null;}
  private planDiff(a:string,b:string):ComparisonResult["planDiff"]{return[{area:"Scope",column:"scope_summary_json"},{area:"Authentication",column:"authentication_summary_json"},{area:"Limits",column:"limits_json"},{area:"Evidence",column:"evidence_policy_json"},{area:"Browser",column:"browser_policy_summary_json"},{area:"Workflows",column:"controlled_workflow_summary_json"}].map(({area,column})=>{const older=this.snapshot(a,column),newer=this.snapshot(b,column);return{area,key:column.replace(/_json$/,"") ,category:older===newer?"UNCHANGED":older===undefined?"ADDED":newer===undefined?"REMOVED":"CHANGED",...(older===undefined?{}:{older:parse(older,older)}),...(newer===undefined?{}:{newer:parse(newer,newer)}),affectsComparability:older!==newer&&["Scope","Authentication","Evidence","Workflows"].includes(area)};});}
}

function make(finding:DashboardFindingSummary,classification:ComparisonFindingResult["classification"],regressionFlags:RegressionFlag[],coverageState:string,reasonCode:string,explanation:string,older:Occurrence|undefined,newer:Occurrence|undefined,materialChanges:ComparisonFindingResult["materialChanges"],evidenceDelta:Record<string,unknown>):ComparisonFindingResult{return{id:randomUUID(),finding,classification,regressionFlags,coverageState,reasonCode,explanation,...(older?{olderOccurrenceId:older.id}:{}),...(newer?{newerOccurrenceId:newer.id}:{}),materialChanges,evidenceDelta:redactDashboardValue(evidenceDelta)as Record<string,unknown>};}
function changesFor(a:Occurrence,b:Occurrence){const out:ComparisonFindingResult["materialChanges"]=[];if(a.severity!==b.severity)out.push({field:"severity",older:a.severity,newer:b.severity,direction:rank(b.severity)>rank(a.severity)?"WORSENED":"IMPROVED"});if(a.confidence!==b.confidence)out.push({field:"confidence",older:a.confidence,newer:b.confidence,direction:conf(b.confidence)>conf(a.confidence)?"INCREASED":"DECREASED"});return out;}
function delta(a:Occurrence,b:Occurrence){return{olderSummary:a.evidence_summary,newerSummary:b.evidence_summary,changed:a.evidence_summary!==b.evidence_summary};} function key(v:Occurrence){return[v.module,v.finding_category,v.http_method,v.safe_endpoint].join("\0");} function boundary(v:Occurrence){return[v.safe_actor_relationship,v.safe_tenant_or_role_boundary,v.safe_state_boundary].filter(Boolean).join(" | ")||"general";} function rank(v:string){return({Info:0,Low:1,Medium:2,High:3,Critical:4}as any)[v]??0;} function conf(v:string){return({Low:0,Medium:1,High:2,Confirmed:3,CONFIRMED:3}as any)[v]??0;}
function summary(v:ComparisonFindingResult[]):ComparisonResult["summary"]{return{new:cls(v,"NEW").length,regressions:v.filter(x=>x.regressionFlags.includes("REGRESSION")).length,recurrences:v.filter(x=>x.regressionFlags.includes("RECURRENCE")).length,persisting:cls(v,"PERSISTING").length,changed:cls(v,"CHANGED").length,resolved:cls(v,"RESOLVED").length,notRetested:cls(v,"NOT_RETESTED").length,incomparable:cls(v,"INCOMPARABLE").length,severityIncreases:v.filter(x=>x.regressionFlags.includes("SEVERITY_INCREASE")).length};} function cls(v:ComparisonFindingResult[],c:ComparisonFindingResult["classification"]){return v.filter(x=>x.classification===c);} function parse<T>(v:string,f:T):T{try{return JSON.parse(v)as T;}catch{return f;}} function md(v:string){return v.replace(/[\\`*_{}[\]()#+.!|>-]/g,"\\$&");}
