import { createHash, createPublicKey, randomBytes, randomUUID, verify, type JsonWebKey } from "node:crypto";
import type { DashboardDatabase } from "../db/DashboardDatabase.js";
import { nowIso } from "../db/DashboardDatabase.js";
import { HttpClient } from "../../core/http/HttpClient.js";

export class SsoService {
  public constructor(private readonly database: DashboardDatabase) {}
  public create(input: { organizationId: string; name: string; issuer: string; authorizationEndpoint: string; tokenEndpoint: string; jwksUri: string; clientId: string; clientSecretEnv: string; scopes: string[]; allowedDomains: string[]; enabled: boolean }, actor: string): string { const id=randomUUID(),now=nowIso(); this.database.db.prepare(`INSERT INTO sso_providers (id,organization_id,name,issuer,authorization_endpoint,token_endpoint,jwks_uri,client_id,client_secret_env,scopes_json,allowed_domains_json,enabled,created_by,created_at,updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(id,input.organizationId,input.name,input.issuer,input.authorizationEndpoint,input.tokenEndpoint,input.jwksUri,input.clientId,input.clientSecretEnv,JSON.stringify(input.scopes),JSON.stringify(input.allowedDomains),input.enabled?1:0,actor,now,now); return id; }
  public list(organizationId?: string): unknown[] { const rows=(organizationId?this.database.db.prepare("SELECT * FROM sso_providers WHERE organization_id=? ORDER BY name").all(organizationId):this.database.db.prepare("SELECT id,name,issuer,enabled FROM sso_providers WHERE enabled=1 ORDER BY name").all()) as Provider[]; return rows.map((r)=>({id:r.id,name:r.name,issuer:r.issuer,enabled:r.enabled===1,...(organizationId?{clientId:r.client_id,clientSecretEnvironment:r.client_secret_env,secretAvailable:Boolean(process.env[r.client_secret_env]),scopes:JSON.parse(r.scopes_json),allowedDomains:JSON.parse(r.allowed_domains_json)}:{})})); }
  public start(providerId: string, redirectUri: string): string { const p=this.provider(providerId);this.database.db.prepare("DELETE FROM sso_login_states WHERE expires_at<=?").run(nowIso()); const verifier=randomBytes(48).toString("base64url"),state=randomBytes(32).toString("base64url"),nonce=randomBytes(32).toString("base64url"),challenge=createHash("sha256").update(verifier).digest("base64url"); this.database.db.prepare("INSERT INTO sso_login_states (state_hash,provider_id,verifier,nonce,redirect_uri,expires_at) VALUES (?, ?, ?, ?, ?, ?)").run(hash(state),p.id,verifier,nonce,redirectUri,new Date(Date.now()+10*60_000).toISOString()); const u=new URL(p.authorization_endpoint); u.searchParams.set("response_type","code");u.searchParams.set("client_id",p.client_id);u.searchParams.set("redirect_uri",redirectUri);u.searchParams.set("scope",(JSON.parse(p.scopes_json) as string[]).join(" "));u.searchParams.set("state",state);u.searchParams.set("nonce",nonce);u.searchParams.set("code_challenge",challenge);u.searchParams.set("code_challenge_method","S256"); return u.toString(); }
  public async callback(providerId:string,state:string,code:string):Promise<string>{ const p=this.provider(providerId); const login=this.database.db.prepare("SELECT * FROM sso_login_states WHERE state_hash=? AND provider_id=?").get(hash(state),providerId) as LoginState|undefined; if(!login||login.consumed_at||Date.parse(login.expires_at)<=Date.now())throw new Error("SSO_STATE_REJECTED"); const secret=process.env[p.client_secret_env];if(!secret)throw new Error("SSO_CLIENT_SECRET_UNAVAILABLE");this.database.db.prepare("UPDATE sso_login_states SET consumed_at=? WHERE state_hash=? AND consumed_at IS NULL").run(nowIso(),hash(state)); const token=await this.postForm(p.token_endpoint,{grant_type:"authorization_code",code,redirect_uri:login.redirect_uri,client_id:p.client_id,client_secret:secret,code_verifier:login.verifier}); const idToken=String(token.id_token??""); const claims=await this.verifyIdToken(p,idToken,login.nonce); const subject=String(claims.sub??""); if(!subject)throw new Error("SSO_SUBJECT_MISSING"); let identity=this.database.db.prepare(`SELECT i.user_id FROM sso_identities i JOIN dashboard_users u ON u.id=i.user_id AND u.enabled=1 JOIN organization_memberships m ON m.user_id=i.user_id AND m.organization_id=? WHERE i.provider_id=? AND i.subject=?`).get(p.organization_id,providerId,subject) as {user_id:string}|undefined; if(!identity){const email=String(claims.email??"").toLowerCase();const domains=JSON.parse(p.allowed_domains_json) as string[];if(!email||claims.email_verified!==true||(domains.length&&!domains.includes(email.split("@")[1]??"")))throw new Error("SSO_IDENTITY_NOT_PRELINKED");const user=this.database.db.prepare("SELECT u.id FROM dashboard_users u JOIN organization_memberships m ON m.user_id=u.id AND m.organization_id=? WHERE u.normalized_login=? AND u.enabled=1").get(p.organization_id,email) as {id:string}|undefined;if(!user)throw new Error("SSO_IDENTITY_NOT_PRELINKED");this.database.db.prepare("INSERT INTO sso_identities (provider_id,subject,user_id,email_fingerprint,created_at,last_login_at) VALUES (?, ?, ?, ?, ?, ?)").run(providerId,subject,user.id,hash(email),nowIso(),nowIso());identity={user_id:user.id};}else this.database.db.prepare("UPDATE sso_identities SET last_login_at=? WHERE provider_id=? AND subject=?").run(nowIso(),providerId,subject);return identity.user_id; }
  private provider(id:string):Provider{const p=this.database.db.prepare("SELECT * FROM sso_providers WHERE id=? AND enabled=1").get(id) as Provider|undefined;if(!p)throw new Error("SSO_PROVIDER_NOT_FOUND");return p;}
  private async postForm(url:string,values:Record<string,string>):Promise<Record<string,unknown>>{return this.httpJson(url,"POST",{"content-type":"application/x-www-form-urlencoded"},new URLSearchParams(values).toString());}
  private async httpJson(url:string,method:"GET"|"POST",headers:Record<string,string>={},body?:string):Promise<Record<string,unknown>>{const client=new HttpClient({userAgent:"RouteCairn-SSO/1",timeoutMs:10_000,bodyPreviewBytes:128*1024,maxResponseBytes:128*1024});try{const r=await client.send({url,method,headers,...(body?{body}:{}),disableRedirects:true,disableRetries:true});if(r.error||!r.statusCode||r.statusCode<200||r.statusCode>=300)throw new Error("SSO_UPSTREAM_FAILED");return JSON.parse(r.bodyPreview??"{}") as Record<string,unknown>;}finally{await client.close();}}
  private async verifyIdToken(p:Provider,token:string,nonce:string):Promise<Record<string,unknown>>{if(token.length>128*1024)throw new Error("SSO_ID_TOKEN_INVALID");const parts=token.split(".");if(parts.length!==3)throw new Error("SSO_ID_TOKEN_INVALID");const header=JSON.parse(Buffer.from(parts[0]!,"base64url").toString()) as {alg?:string;kid?:string};const claims=JSON.parse(Buffer.from(parts[1]!,"base64url").toString()) as Record<string,unknown>;if(header.alg!=="RS256"||!header.kid)throw new Error("SSO_ID_TOKEN_ALGORITHM_REJECTED");const jwks=await this.httpJson(p.jwks_uri,"GET");const jwk=(Array.isArray(jwks.keys)?jwks.keys:[]).find((k:any)=>k?.kid===header.kid&&k?.kty==="RSA"&&(!k.use||k.use==="sig")&&(!k.alg||k.alg==="RS256")) as JsonWebKey|undefined;if(!jwk||!verify("RSA-SHA256",Buffer.from(`${parts[0]}.${parts[1]}`),createPublicKey({key:jwk,format:"jwk"}),Buffer.from(parts[2]!,"base64url")))throw new Error("SSO_ID_TOKEN_SIGNATURE_REJECTED");const now=Date.now(),exp=Number(claims.exp),nbf=claims.nbf===undefined?undefined:Number(claims.nbf),iat=claims.iat===undefined?undefined:Number(claims.iat);if(claims.iss!==p.issuer||!(claims.aud===p.client_id||(Array.isArray(claims.aud)&&claims.aud.includes(p.client_id)))||!Number.isFinite(exp)||exp*1000<=now-60_000||(nbf!==undefined&&(!Number.isFinite(nbf)||nbf*1000>now+60_000))||(iat!==undefined&&(!Number.isFinite(iat)||iat*1000>now+5*60_000))||claims.nonce!==nonce)throw new Error("SSO_ID_TOKEN_CLAIMS_REJECTED");return claims;}
}
function hash(v:string){return createHash("sha256").update("routecairn-sso-v1\0").update(v).digest("hex");}
interface Provider{id:string;organization_id:string;name:string;issuer:string;authorization_endpoint:string;token_endpoint:string;jwks_uri:string;client_id:string;client_secret_env:string;scopes_json:string;allowed_domains_json:string;enabled:number}
interface LoginState{verifier:string;nonce:string;redirect_uri:string;expires_at:string;consumed_at:string|null}
