import { createHash, randomBytes } from "node:crypto";
import { spawn } from "node:child_process";
import { connect as connectHttp2, constants as h2, type ClientHttp2Session } from "node:http2";
import { connect as connectTcp, isIP, type Socket } from "node:net";
import { connect as connectTls, type TLSSocket } from "node:tls";
import { Agent, request as undiciRequest } from "undici";
import { createPinnedConnector, resolvePinnedDestination } from "../../core/http/PinnedHttpTransport.js";
import type { DnsResolver } from "../../core/http/HttpTypes.js";

export interface ProtocolTransportOptions { allowedPrivateOrigins: readonly string[]; timeoutMs: number; maxBytes: number; abortSignal?: AbortSignal; dnsResolver?: DnsResolver; }
export interface StreamMessage { type?: string; value: unknown; }
export interface WebSocketResult { statusCode: number; protocol?: string; messages: StreamMessage[]; }
export interface Http2Result { statusCode?: number; protocol: "h2" | "h2c"; headers: Record<string, string | string[]>; body: Buffer; grpcStatus?: number; grpcMessages: Buffer[]; errorCode?: string; }
export interface Http2DesyncResult { probe: Http2Result; sentinel: Http2Result; sameSession: true; }
export interface SseResult { statusCode: number; body: string; eventCount: number; contentType?: string; }
export interface BoundedHttpResult { statusCode: number; headers: Record<string, string | string[]>; body: Buffer; }
export interface Http3Result { statusCode: number; protocol: "h3"; body: Buffer; }
export interface Http3DesyncResult { probeStatus?: number; sentinelStatus?: number; protocol: "h3"; sameConnectionProcess: true; probeAccepted: boolean; sentinelClean: boolean; }
let curlHttp3Capability: boolean | undefined;

export async function ensureHttp3Runtime(options: ProtocolTransportOptions): Promise<void> { await requireCurlHttp3(options); }

export async function runHttp3Authorization(urlValue: string, method: "GET" | "HEAD" | "OPTIONS", headers: Readonly<Record<string, string>>, options: ProtocolTransportOptions): Promise<Http3Result> {
  const url = new URL(urlValue); if (url.protocol !== "https:") throw new Error("HTTP3_HTTPS_REQUIRED"); await requireCurlHttp3(options); const pin = await resolvePinnedDestination({ hostname: url.hostname, protocol: "https:", port: url.port || "443" }, { allowedPrivateOrigins: options.allowedPrivateOrigins, dnsTimeoutMs: Math.min(options.timeoutMs, 5000), maxDnsAnswers: 16, ...(options.dnsResolver ? { dnsResolver: options.dnsResolver } : {}) });
  const nonce = `ROUTECAIRN_${randomBytes(12).toString("hex")}`; const config = ["silent", "show-error", "http3-only", `noproxy = ${quoteCurl("*")}`, `max-time = ${Math.max(1, Math.ceil(options.timeoutMs / 1000))}`, `request = ${quoteCurl(method)}`, `url = ${quoteCurl(url.href)}`, `resolve = ${quoteCurl(`${url.hostname}:${url.port || "443"}:${pin.address.address}`)}`, ...Object.entries(headers).map(([name, value]) => `header = ${quoteCurl(`${name}: ${value}`)}`), `write-out = ${quoteCurl(`\n${nonce}:%{http_code}:%{http_version}:%{remote_ip}\n`)}`].join("\n");
  const result = await runCurl(["--config", "-"], `${config}\n`, options.maxBytes + 4096, options.timeoutMs, options.abortSignal); const marker = Buffer.from(`\n${nonce}:`); const index = result.stdout.lastIndexOf(marker); if (index < 0) throw new Error("HTTP3_METADATA_MISSING"); const metadata = result.stdout.subarray(index + marker.length).toString("utf8").trim().split(":"); const statusCode = Number(metadata[0]); const httpVersion = metadata[1]; const remoteIp = metadata.slice(2).join(":"); if (!Number.isInteger(statusCode) || httpVersion !== "3") throw new Error("HTTP3_NEGOTIATION_FAILED"); if (!sameIpValue(remoteIp, pin.address.address)) throw new Error("PINNED_REMOTE_ADDRESS_MISMATCH"); const body = result.stdout.subarray(0, index); if (body.length > options.maxBytes) throw new Error("HTTP3_RESPONSE_LIMIT_EXCEEDED"); return { statusCode, protocol: "h3", body };
}

export async function runHttp3Desync(urlValue: string, headers: Readonly<Record<string, string>>, body: Buffer, declaredLength: number, sentinelPath: string, allowedStatuses: readonly number[], options: ProtocolTransportOptions): Promise<Http3DesyncResult> {
  const url = new URL(urlValue); if (url.protocol !== "https:") throw new Error("HTTP3_HTTPS_REQUIRED"); const sentinel = new URL(sentinelPath, url); if (sentinel.origin !== url.origin) throw new Error("HTTP3_SENTINEL_ORIGIN_MISMATCH"); await requireCurlHttp3(options); const pin = await resolvePinnedDestination({ hostname: url.hostname, protocol: "https:", port: url.port || "443" }, { allowedPrivateOrigins: options.allowedPrivateOrigins, dnsTimeoutMs: Math.min(options.timeoutMs, 5000), maxDnsAnswers: 16, ...(options.dnsResolver ? { dnsResolver: options.dnsResolver } : {}) });
  const first = `ROUTECAIRN_PROBE_${randomBytes(10).toString("hex")}`, second = `ROUTECAIRN_SENTINEL_${randomBytes(10).toString("hex")}`; const common = ["silent", "show-error", "http3-only", `noproxy = ${quoteCurl("*")}`, `max-time = ${Math.max(1, Math.ceil(options.timeoutMs / 1000))}`, `resolve = ${quoteCurl(`${url.hostname}:${url.port || "443"}:${pin.address.address}`)}`, ...Object.entries(headers).map(([name, value]) => `header = ${quoteCurl(`${name}: ${value}`)}`)]; const encoded = body.toString("base64");
  const config = [...common, `request = ${quoteCurl("POST")}`, `url = ${quoteCurl(url.href)}`, `header = ${quoteCurl(`content-length: ${declaredLength}`)}`, `header = ${quoteCurl("content-type: application/octet-stream")}`, `data-binary = ${quoteCurl(encoded)}`, `write-out = ${quoteCurl(`\n${first}:%{http_code}:%{http_version}:%{remote_ip}\n`)}`, "next", ...common, `request = ${quoteCurl("GET")}`, `url = ${quoteCurl(sentinel.href)}`, `write-out = ${quoteCurl(`\n${second}:%{http_code}:%{http_version}:%{remote_ip}\n`)}`].join("\n");
  const result = await runCurl(["--config", "-"], `${config}\n`, options.maxBytes * 2 + 8192, options.timeoutMs * 2, options.abortSignal, true); const probe = curlMetadata(result.stdout, first); const sentinelResult = curlMetadata(result.stdout, second); if (!probe || !sentinelResult) throw new Error("HTTP3_SENTINEL_NOT_EXECUTED"); for (const item of [probe, sentinelResult]) { if (item.version !== "3") throw new Error("HTTP3_NEGOTIATION_FAILED"); if (!sameIpValue(item.remoteIp, pin.address.address)) throw new Error("PINNED_REMOTE_ADDRESS_MISMATCH"); } const probeAccepted = allowedStatuses.includes(probe.statusCode) && result.exitCode === 0; const sentinelClean = allowedStatuses.includes(sentinelResult.statusCode); return { probeStatus: probe.statusCode, sentinelStatus: sentinelResult.statusCode, protocol: "h3", sameConnectionProcess: true, probeAccepted, sentinelClean };
}

export async function runBoundedHttp(urlValue: string, method: string, headers: Readonly<Record<string, string>>, body: Buffer | undefined, options: ProtocolTransportOptions): Promise<BoundedHttpResult> {
  const controller = new AbortController(); const abort = () => controller.abort(); options.abortSignal?.addEventListener("abort", abort, { once: true }); const timer = setTimeout(abort, options.timeoutMs); const dispatcher = new Agent({ connect: createPinnedConnector({ allowedPrivateOrigins: options.allowedPrivateOrigins, dnsTimeoutMs: Math.min(options.timeoutMs, 5000), maxDnsAnswers: 16, ...(options.dnsResolver ? { dnsResolver: options.dnsResolver } : {}) }), pipelining: 0 });
  try { const response = await undiciRequest(new URL(urlValue), { method, headers, ...(body ? { body } : {}), dispatcher, signal: controller.signal }); const chunks: Buffer[] = []; let size = 0; try { for await (const chunk of response.body) { const value = Buffer.from(chunk); size += value.length; if (size > options.maxBytes) throw new Error("HTTP_RESPONSE_LIMIT_EXCEEDED"); chunks.push(value); } } finally { response.body.destroy(); } return { statusCode: response.statusCode, headers: normalizeUndiciHeaders(response.headers), body: Buffer.concat(chunks) }; }
  finally { clearTimeout(timer); options.abortSignal?.removeEventListener("abort", abort); await dispatcher.close(); }
}

export async function runSse(urlValue: string, method: "GET" | "POST", headers: Readonly<Record<string, string>>, body: string | undefined, maxEvents: number, options: ProtocolTransportOptions): Promise<SseResult> {
  const url = new URL(urlValue); const controller = new AbortController(); let timedOut = false; const abort = () => controller.abort(); options.abortSignal?.addEventListener("abort", abort, { once: true }); const timer = setTimeout(() => { timedOut = true; controller.abort(); }, options.timeoutMs);
  const dispatcher = new Agent({ connect: createPinnedConnector({ allowedPrivateOrigins: options.allowedPrivateOrigins, dnsTimeoutMs: Math.min(options.timeoutMs, 5000), maxDnsAnswers: 16, ...(options.dnsResolver ? { dnsResolver: options.dnsResolver } : {}) }), pipelining: 0 });
  try {
    const response = await undiciRequest(url, { method, headers: { Accept: "text/event-stream", ...headers }, ...(body !== undefined ? { body } : {}), dispatcher, signal: controller.signal }); const chunks: Buffer[] = []; let size = 0; let eventCount = 0;
    try { for await (const chunk of response.body) { const value = Buffer.from(chunk); size += value.length; if (size > options.maxBytes) throw new Error("SSE_RESPONSE_LIMIT_EXCEEDED"); chunks.push(value); eventCount = completeSseEvents(Buffer.concat(chunks).toString("utf8")); if (eventCount >= maxEvents) break; } } catch (error) { if (!timedOut || error instanceof Error && error.message === "SSE_RESPONSE_LIMIT_EXCEEDED") throw error; } finally { response.body.destroy(); }
    const rawContentType = response.headers["content-type"]; const contentType = Array.isArray(rawContentType) ? rawContentType.join(", ") : rawContentType;
    return { statusCode: response.statusCode, body: Buffer.concat(chunks).toString("utf8"), eventCount, ...(contentType ? { contentType } : {}) };
  } finally { clearTimeout(timer); options.abortSignal?.removeEventListener("abort", abort); await dispatcher.close(); }
}

export async function runWebSocket(urlValue: string, headers: Readonly<Record<string, string>>, subprotocols: readonly string[], outbound: readonly unknown[], maxMessages: number, options: ProtocolTransportOptions, waitForTypeBeforeRest?: string): Promise<WebSocketResult> {
  const url = new URL(urlValue); const socket = await pinnedSocket(url, options, ["http/1.1"]); const key = randomBytes(16).toString("base64");
  const requestHeaders: Record<string, string> = { Host: url.host, Upgrade: "websocket", Connection: "Upgrade", "Sec-WebSocket-Key": key, "Sec-WebSocket-Version": "13", ...headers };
  if (subprotocols.length) requestHeaders["Sec-WebSocket-Protocol"] = subprotocols.join(", ");
  const request = `GET ${url.pathname}${url.search} HTTP/1.1\r\n${Object.entries(requestHeaders).map(([name, value]) => `${name}: ${value}`).join("\r\n")}\r\n\r\n`;
  socket.write(request); const initial = await readUntil(socket, Buffer.from("\r\n\r\n"), options.timeoutMs, 32 * 1024, options.abortSignal); const boundary = initial.indexOf("\r\n\r\n");
  const head = initial.subarray(0, boundary).toString("latin1"); const lines = head.split("\r\n"); const statusCode = Number(lines[0]?.split(" ")[1]); const responseHeaders = Object.fromEntries(lines.slice(1).map((line) => { const p = line.indexOf(":"); return p > 0 ? [line.slice(0, p).toLowerCase(), line.slice(p + 1).trim()] : [line, ""]; }));
  const expected = createHash("sha1").update(`${key}258EAFA5-E914-47DA-95CA-C5AB0DC85B11`).digest("base64");
  if (statusCode !== 101 || responseHeaders["sec-websocket-accept"] !== expected || responseHeaders.upgrade?.toLowerCase() !== "websocket" || !responseHeaders.connection?.toLowerCase().split(/\s*,\s*/).includes("upgrade")) { socket.destroy(); return { statusCode: Number.isFinite(statusCode) ? statusCode : 0, messages: [] }; }
  const initialOutbound = waitForTypeBeforeRest ? outbound.slice(0, 1) : outbound; for (const message of initialOutbound) socket.write(encodeFrame(Buffer.from(JSON.stringify(message), "utf8"), 1)); let deferredSent = !waitForTypeBeforeRest;
  const messages: StreamMessage[] = []; let pending = initial.subarray(boundary + 4); let totalBytes = pending.length; if (totalBytes > options.maxBytes) { socket.destroy(); throw new Error("WEBSOCKET_RESPONSE_LIMIT_EXCEEDED"); } let fragmented: { opcode: number; chunks: Buffer[] } | undefined; const deadline = Date.now() + options.timeoutMs;
  try {
    while (messages.length < maxMessages && Date.now() < deadline) {
      const parsed = parseFrame(pending); if (!parsed) { let chunk: Buffer; try { chunk = await readChunk(socket, Math.max(1, deadline - Date.now()), options.abortSignal); } catch (error) { if (error instanceof Error && error.message === "PROTOCOL_READ_TIMEOUT") break; throw error; } totalBytes += chunk.length; if (totalBytes > options.maxBytes) throw new Error("WEBSOCKET_RESPONSE_LIMIT_EXCEEDED"); pending = Buffer.concat([pending, chunk]); continue; }
      pending = pending.subarray(parsed.bytes); if (parsed.opcode === 8) break; if (parsed.opcode === 9) { socket.write(encodeFrame(parsed.payload, 10)); continue; } if (parsed.opcode !== 0 && parsed.opcode !== 1 && parsed.opcode !== 2) continue;
      let payload = parsed.payload; if (parsed.opcode === 0) { if (!fragmented) continue; fragmented.chunks.push(parsed.payload); if (!parsed.fin) continue; payload = Buffer.concat(fragmented.chunks); fragmented = undefined; } else if (!parsed.fin) { fragmented = { opcode: parsed.opcode, chunks: [parsed.payload] }; continue; }
      const text = payload.toString("utf8"); let value: unknown = text; try { value = JSON.parse(text); } catch { /* text frame */ } const type = value && typeof value === "object" && typeof (value as Record<string, unknown>).type === "string" ? String((value as Record<string, unknown>).type) : undefined; messages.push({ ...(type ? { type } : {}), value }); if (!deferredSent && type === waitForTypeBeforeRest) { for (const message of outbound.slice(1)) socket.write(encodeFrame(Buffer.from(JSON.stringify(message), "utf8"), 1)); deferredSent = true; }
    }
  } finally { if (!socket.destroyed) { socket.write(encodeFrame(Buffer.alloc(0), 8)); socket.destroy(); } }
  return { statusCode, ...(responseHeaders["sec-websocket-protocol"] ? { protocol: responseHeaders["sec-websocket-protocol"] } : {}), messages };
}

export async function runHttp2(urlValue: string, method: string, headers: Readonly<Record<string, string>>, body: Buffer | undefined, maxMessages: number, options: ProtocolTransportOptions, declaredLength?: number): Promise<Http2Result> {
  const url = new URL(urlValue); const opened = await openHttp2(url, options);
  try { return await requestOnSession(opened.session, url, method, headers, body, maxMessages, options, declaredLength); }
  finally { opened.session.close(); if (!opened.socket.destroyed) opened.socket.destroy(); }
}

export async function runHttp2Desync(urlValue: string, method: string, headers: Readonly<Record<string, string>>, body: Buffer, declaredLength: number, sentinelPath: string, options: ProtocolTransportOptions): Promise<Http2DesyncResult> {
  const url = new URL(urlValue); const sentinelUrl = new URL(sentinelPath, url); if (sentinelUrl.origin !== url.origin) throw new Error("HTTP2_SENTINEL_ORIGIN_MISMATCH"); const opened = await openHttp2(url, options); const protocol = url.protocol === "https:" ? "h2" : "h2c";
  try {
    const probe = await requestOnSession(opened.session, url, method, headers, body, 1, options, declaredLength);
    let sentinel: Http2Result;
    try { sentinel = await requestOnSession(opened.session, sentinelUrl, "GET", headers, undefined, 1, options); }
    catch (error) { sentinel = { protocol, headers: {}, body: Buffer.alloc(0), grpcMessages: [], errorCode: error instanceof Error ? error.message : "HTTP2_SENTINEL_FAILURE" }; }
    return { probe, sentinel, sameSession: true };
  } finally { opened.session.close(); if (!opened.socket.destroyed) opened.socket.destroy(); }
}

async function openHttp2(url: URL, options: ProtocolTransportOptions): Promise<{ session: ClientHttp2Session; socket: Socket | TLSSocket }> {
  const socket = await pinnedSocket(url, options, url.protocol === "https:" ? ["h2"] : undefined); if (url.protocol === "https:" && (socket as TLSSocket).alpnProtocol !== "h2") { socket.destroy(); throw new Error("HTTP2_NEGOTIATION_FAILED"); }
  const session = connectHttp2(`${url.protocol}//${url.host}`, { createConnection: () => socket });
  session.on("error", () => { /* individual request/session state is reported by the active case */ });
  try { await onceSession(session, options.timeoutMs, options.abortSignal); return { session, socket }; }
  catch (error) { session.destroy(); socket.destroy(); throw error; }
}

async function requestOnSession(session: ClientHttp2Session, url: URL, method: string, headers: Readonly<Record<string, string>>, body: Buffer | undefined, maxMessages: number, options: ProtocolTransportOptions, declaredLength?: number): Promise<Http2Result> {
  const requestHeaders: Record<string, string | number> = { [h2.HTTP2_HEADER_METHOD]: method, [h2.HTTP2_HEADER_PATH]: `${url.pathname}${url.search}`, [h2.HTTP2_HEADER_SCHEME]: url.protocol.slice(0, -1), [h2.HTTP2_HEADER_AUTHORITY]: url.host, ...headers }; if (declaredLength !== undefined) requestHeaders[h2.HTTP2_HEADER_CONTENT_LENGTH] = declaredLength;
  return await new Promise<Http2Result>((resolve, reject) => {
    let stream: ReturnType<ClientHttp2Session["request"]>; try { stream = session.request(requestHeaders, { endStream: !body?.length }); } catch (error) { reject(error); return; }
    let responseHeaders: Record<string, string | string[]> = {}; const chunks: Buffer[] = []; let size = 0; let settled = false;
    const timer = setTimeout(() => finish(new Error("HTTP2_REQUEST_TIMEOUT")), options.timeoutMs); const abort = () => finish(new Error("HTTP2_REQUEST_ABORTED")); options.abortSignal?.addEventListener("abort", abort, { once: true });
    const finish = (error?: Error, errorCode?: string) => { if (settled) return; settled = true; clearTimeout(timer); options.abortSignal?.removeEventListener("abort", abort); stream.close(); if (error && !errorCode) reject(error); else { const bodyBuffer = Buffer.concat(chunks); const grpc = parseGrpcFrames(bodyBuffer, maxMessages); const statusCode = Number(responseHeaders[":status"]); const status = grpcStatus(responseHeaders); resolve({ ...(Number.isFinite(statusCode) && statusCode > 0 ? { statusCode } : {}), protocol: url.protocol === "https:" ? "h2" : "h2c", headers: responseHeaders, body: bodyBuffer, ...(status !== undefined ? { grpcStatus: status } : {}), grpcMessages: grpc, ...(errorCode ? { errorCode } : {}) }); } };
    stream.on("response", (incoming) => { responseHeaders = normalizeHeaders(incoming); }); stream.on("trailers", (incoming) => { responseHeaders = { ...responseHeaders, ...normalizeHeaders(incoming) }; }); stream.on("data", (chunk: Buffer) => { size += chunk.byteLength; if (size > options.maxBytes) { finish(undefined, "HTTP2_RESPONSE_LIMIT_EXCEEDED"); return; } chunks.push(Buffer.from(chunk)); }); stream.on("end", () => finish()); stream.on("error", (error: NodeJS.ErrnoException) => finish(undefined, error.code ?? error.message)); if (body?.length) stream.end(body); else stream.end();
  });
}

async function pinnedSocket(url: URL, options: ProtocolTransportOptions, alpn?: string[]): Promise<Socket | TLSSocket> {
  const secure = url.protocol === "https:" || url.protocol === "wss:"; const protocol = secure ? "https:" : "http:";
  const pin = await resolvePinnedDestination({ hostname: url.hostname, protocol, port: url.port || (secure ? "443" : "80") }, { allowedPrivateOrigins: options.allowedPrivateOrigins, dnsTimeoutMs: Math.min(options.timeoutMs, 5000), maxDnsAnswers: 16, ...(options.dnsResolver ? { dnsResolver: options.dnsResolver } : {}) });
  return await new Promise<Socket | TLSSocket>((resolve, reject) => {
    let settled = false; const finish = (error?: Error, socket?: Socket | TLSSocket) => { if (settled) return; settled = true; clearTimeout(timer); options.abortSignal?.removeEventListener("abort", abort); if (error) { socket?.destroy(); reject(error); } else resolve(socket!); };
    const timer = setTimeout(() => finish(new Error("PROTOCOL_CONNECT_TIMEOUT"), socket), options.timeoutMs); const abort = () => finish(new Error("PROTOCOL_CONNECT_ABORTED"), socket); let socket: Socket | TLSSocket;
    if (secure) socket = connectTls({ host: pin.address.address, port: Number(pin.port), servername: isIP(pin.hostname) ? undefined : pin.hostname, ALPNProtocols: alpn ?? ["http/1.1"], rejectUnauthorized: true }, () => remoteMatches(socket, pin.address.address) ? finish(undefined, socket) : finish(new Error("PINNED_REMOTE_ADDRESS_MISMATCH"), socket));
    else socket = connectTcp({ host: pin.address.address, port: Number(pin.port), family: pin.address.family }, () => remoteMatches(socket, pin.address.address) ? finish(undefined, socket) : finish(new Error("PINNED_REMOTE_ADDRESS_MISMATCH"), socket));
    socket.once("error", (e) => finish(e, socket)); options.abortSignal?.addEventListener("abort", abort, { once: true });
  });
}

function encodeFrame(payload: Buffer, opcode: number): Buffer { const mask = randomBytes(4); const length = payload.byteLength; const extra = length < 126 ? 0 : length <= 0xffff ? 2 : 8; const frame = Buffer.alloc(2 + extra + 4 + length); frame[0] = 0x80 | opcode; frame[1] = 0x80 | (length < 126 ? length : length <= 0xffff ? 126 : 127); let offset = 2; if (extra === 2) { frame.writeUInt16BE(length, offset); offset += 2; } else if (extra === 8) { frame.writeBigUInt64BE(BigInt(length), offset); offset += 8; } mask.copy(frame, offset); offset += 4; for (let i = 0; i < length; i++) frame[offset + i] = payload[i]! ^ mask[i % 4]!; return frame; }
function parseFrame(buffer: Buffer): { fin: boolean; opcode: number; payload: Buffer; bytes: number } | undefined { if (buffer.length < 2) return; if ((buffer[0]! & 0x70) !== 0) throw new Error("WEBSOCKET_RESERVED_BITS_SET"); const fin = Boolean(buffer[0]! & 0x80), opcode = buffer[0]! & 0x0f, masked = Boolean(buffer[1]! & 0x80); if (masked) throw new Error("WEBSOCKET_SERVER_MASKED_FRAME"); let length = buffer[1]! & 0x7f, offset = 2; if (length === 126) { if (buffer.length < 4) return; length = buffer.readUInt16BE(2); offset = 4; } else if (length === 127) { if (buffer.length < 10) return; const n = buffer.readBigUInt64BE(2); if (n > BigInt(Number.MAX_SAFE_INTEGER)) throw new Error("WEBSOCKET_FRAME_TOO_LARGE"); length = Number(n); offset = 10; } if (opcode >= 8 && (!fin || length > 125)) throw new Error("WEBSOCKET_CONTROL_FRAME_INVALID"); if (buffer.length < offset + length) return; const payload = Buffer.from(buffer.subarray(offset, offset + length)); return { fin, opcode, payload, bytes: offset + length }; }
function readUntil(socket: Socket | TLSSocket, delimiter: Buffer, timeout: number, max: number, signal?: AbortSignal): Promise<Buffer> { return new Promise((resolve, reject) => { let value = Buffer.alloc(0), settled = false; const timer = setTimeout(() => done(new Error("PROTOCOL_READ_TIMEOUT")), timeout); const abort = () => done(new Error("PROTOCOL_READ_ABORTED")); const closed = () => done(new Error("PROTOCOL_SOCKET_CLOSED")); const failed = (error: Error) => done(error); const data = (chunk: Buffer) => { value = Buffer.concat([value, chunk]); if (value.length > max) done(new Error("PROTOCOL_HEADER_LIMIT_EXCEEDED")); else if (value.indexOf(delimiter) >= 0) done(); }; const done = (error?: Error) => { if (settled) return; settled = true; clearTimeout(timer); socket.off("data", data); socket.off("error", failed); socket.off("end", closed); socket.off("close", closed); signal?.removeEventListener("abort", abort); error ? reject(error) : resolve(value); }; socket.on("data", data); socket.once("error", failed); socket.once("end", closed); socket.once("close", closed); signal?.addEventListener("abort", abort, { once: true }); }); }
function readChunk(socket: Socket | TLSSocket, timeout: number, signal?: AbortSignal): Promise<Buffer> { return new Promise((resolve, reject) => { let settled = false; const timer = setTimeout(() => done(new Error("PROTOCOL_READ_TIMEOUT")), timeout); const abort = () => done(new Error("PROTOCOL_READ_ABORTED")); const closed = () => done(new Error("PROTOCOL_SOCKET_CLOSED")); const failed = (error: Error) => done(error); const data = (chunk: Buffer) => done(undefined, chunk); const done = (error?: Error, value?: Buffer) => { if (settled) return; settled = true; clearTimeout(timer); socket.off("data", data); socket.off("error", failed); socket.off("end", closed); socket.off("close", closed); signal?.removeEventListener("abort", abort); error ? reject(error) : resolve(value!); }; socket.once("data", data); socket.once("error", failed); socket.once("end", closed); socket.once("close", closed); signal?.addEventListener("abort", abort, { once: true }); }); }
function onceSession(session: ClientHttp2Session, timeout: number, signal?: AbortSignal): Promise<void> { return new Promise((resolve, reject) => { if (!session.connecting) return resolve(); const timer = setTimeout(() => done(new Error("HTTP2_SESSION_TIMEOUT")), timeout); const abort = () => done(new Error("HTTP2_SESSION_ABORTED")); const done = (error?: Error) => { clearTimeout(timer); signal?.removeEventListener("abort", abort); session.off("connect", connected); session.off("error", failed); error ? reject(error) : resolve(); }; const connected = () => done(); const failed = (e: Error) => done(e); session.once("connect", connected); session.once("error", failed); signal?.addEventListener("abort", abort, { once: true }); }); }
function normalizeHeaders(value: Record<string, string | string[] | number | undefined>): Record<string, string | string[]> { return Object.fromEntries(Object.entries(value).filter(([, v]) => v !== undefined).map(([k, v]) => [k, Array.isArray(v) ? v : String(v)])); }
function parseGrpcFrames(body: Buffer, max: number): Buffer[] { const frames: Buffer[] = []; let offset = 0; while (offset + 5 <= body.length && frames.length < max) { const length = body.readUInt32BE(offset + 1); if (offset + 5 + length > body.length) break; frames.push(body.subarray(offset + 5, offset + 5 + length)); offset += 5 + length; } return frames; }
function grpcStatus(headers: Record<string, string | string[]>): number | undefined { const value = headers["grpc-status"]; const parsed = Number(Array.isArray(value) ? value[0] : value); return Number.isFinite(parsed) ? parsed : undefined; }
function remoteMatches(socket: Socket | TLSSocket, expected: string): boolean { const actual = socket.remoteAddress?.toLowerCase(); const wanted = expected.toLowerCase(); return actual === wanted || actual === `::ffff:${wanted}` || (actual?.replace(/^::ffff:/, "") === wanted); }
function completeSseEvents(value: string): number { return value.split(/\r?\n\r?\n/).slice(0, -1).filter((block) => block.split(/\r?\n/).some((line) => line.startsWith("data:") || line.startsWith("event:"))).length; }
function normalizeUndiciHeaders(value: Record<string, string | string[] | undefined>): Record<string, string | string[]> { return Object.fromEntries(Object.entries(value).filter((entry): entry is [string, string | string[]] => entry[1] !== undefined)); }
function quoteCurl(value: string): string { return `"${value.replace(/\\/g, "\\\\").replace(/"/g, "\\\"").replace(/\r/g, "").replace(/\n/g, "\\n")}"`; }
function sameIpValue(actual: string, expected: string): boolean { const left = actual.toLowerCase().replace(/^\[|\]$/g, ""); const right = expected.toLowerCase().replace(/^\[|\]$/g, ""); return left === right || left === `::ffff:${right}` || left.replace(/^::ffff:/, "") === right; }
async function requireCurlHttp3(options: ProtocolTransportOptions): Promise<void> { if (curlHttp3Capability === undefined) { try { const version = await runCurl(["--version"], undefined, 64 * 1024, Math.min(options.timeoutMs, 5000), options.abortSignal); curlHttp3Capability = /\bHTTP3\b/i.test(version.stdout.toString("utf8")); } catch (error) { if (options.abortSignal?.aborted) throw error; curlHttp3Capability = false; } } if (!curlHttp3Capability) throw new Error("HTTP3_RUNTIME_UNAVAILABLE"); }
function curlMetadata(stdout: Buffer, nonce: string): { statusCode: number; version: string; remoteIp: string } | undefined { const marker = Buffer.from(`\n${nonce}:`); const index = stdout.lastIndexOf(marker); if (index < 0) return; const line = stdout.subarray(index + marker.length).toString("utf8").split(/\r?\n/, 1)[0]?.trim() ?? ""; const parts = line.split(":"); const statusCode = Number(parts[0]); if (!Number.isInteger(statusCode)) return; return { statusCode, version: parts[1] ?? "", remoteIp: parts.slice(2).join(":") }; }
function runCurl(args: string[], stdin: string | undefined, maxOutput: number, timeoutMs: number, signal?: AbortSignal, allowNonzero = false): Promise<{ stdout: Buffer; stderr: Buffer; exitCode: number }> { return new Promise((resolve, reject) => { const child = spawn(process.platform === "win32" ? "curl.exe" : "curl", args, { windowsHide: true, stdio: ["pipe", "pipe", "pipe"] }); const out: Buffer[] = [], err: Buffer[] = []; let size = 0, errorSize = 0, settled = false; const timer = setTimeout(() => finish(new Error("HTTP3_RUNTIME_TIMEOUT")), timeoutMs); const abort = () => finish(new Error("HTTP3_RUNTIME_ABORTED")); const finish = (error?: Error, exitCode = -1) => { if (settled) return; settled = true; clearTimeout(timer); signal?.removeEventListener("abort", abort); if (error) { child.kill(); reject(error); } else resolve({ stdout: Buffer.concat(out), stderr: Buffer.concat(err), exitCode }); }; child.once("error", finish); child.stdout.on("data", (chunk: Buffer) => { size += chunk.length; if (size > maxOutput) finish(new Error("HTTP3_RESPONSE_LIMIT_EXCEEDED")); else out.push(Buffer.from(chunk)); }); child.stderr.on("data", (chunk: Buffer) => { errorSize += chunk.length; if (errorSize <= 64 * 1024) err.push(Buffer.from(chunk)); }); child.once("close", (code) => code === 0 || allowNonzero ? finish(undefined, code ?? -1) : finish(new Error(`HTTP3_RUNTIME_EXIT_${code ?? "UNKNOWN"}`))); signal?.addEventListener("abort", abort, { once: true }); if (stdin !== undefined) child.stdin.end(stdin); else child.stdin.end(); }); }
