import { createHash, randomBytes } from "node:crypto";
import { authHeadersForProfile, authenticationLifecycleSecrets, type AuthProfile } from "../../core/auth/AuthProfile.js";
import type { ScanContext } from "../../core/engine/ScanContext.js";
import type { Finding } from "../../core/findings/Finding.js";
import { RiskScorer } from "../../core/findings/RiskScorer.js";
import { bodyPreviewForAnalysis } from "../../core/http/TransientResponseAnalysis.js";
import type { HttpResponse } from "../../core/http/HttpTypes.js";
import type { MutationJournalStage, MutationOutcome } from "../../core/offensive/ControlledMutationTypes.js";
import type { ModuleResult, RouteCairnPlugin } from "../../core/plugins/Plugin.js";
import { decodeBoundedContent, ensureHttp3Runtime, runBoundedHttp, runGrpcStream, runHttp2, runHttp2Desync, runHttp3Authorization, runHttp3Desync, runInterruptedUpload, runSse, runWebSocket, runWebTransportDatagrams, type BoundedHttpResult, type Http2Result, type ProtocolTransportOptions, type SseResult, type StreamMessage } from "./ProtocolTransports.js";
import type { CrossProtocolIdentityCasePlan, GraphqlIncrementalCasePlan, GraphqlMutationCasePlan, GraphqlPersistedQueryCasePlan, GraphqlSubscriptionCasePlan, GrpcCasePlan, MultipartCasePlan, ProtocolActorPlan, ProtocolCaseObservation, ProtocolSecurityCasePlan, ProtocolSecurityPlan, ProtocolSecurityReport, ProxyChainDesyncCasePlan, StreamingUploadInterruptCasePlan, WebSocketAuthStateMachineCasePlan, WebSocketCasePlan } from "./ProtocolSecurityTypes.js";

import { parseGraphqlParts } from "./ProtocolGraphqlMultipart.js";

type ActionResponse = HttpResponse & { transientBody?: Buffer };
const protocolRequestStart = new WeakMap<ScanContext, number>();
function protocolCapacity(context: ScanContext, count = 1): boolean { const start = protocolRequestStart.get(context); return start !== undefined && context.requestLedger.snapshot().scanTransmitted - start + count <= context.options.plan.protocolSecurity!.maxRequests; }

export class ProtocolSecurityModule implements RouteCairnPlugin {
  public readonly name = "protocol-security";
  public readonly description = "Runs bounded streaming, message-state, GraphQL, gRPC, WebTransport, upload, compression, identity-parity, and HTTP desynchronization contracts.";
  public readonly phase = "analysis" as const;
  public async run(context: ScanContext): Promise<ModuleResult> {
    const report = await executeProtocolSecurity(context);
    return { pluginName: this.name, protocolSecurity: report, findings: findings(report), notes: [...report.notes] };
  }
}

export async function executeProtocolSecurity(context: ScanContext): Promise<ProtocolSecurityReport> {
  const plan = context.options.plan.protocolSecurity;
  if (!plan?.enabled) return disabledReport();
  const http = context.createApiGraphqlHttpClient(plan.maxRequests, plan.maxResponseBytes); const cleanup = context.createWorkflowCleanupHttpClient(Math.max(2, plan.cases.length * 2), plan.maxResponseBytes);
  const observations: ProtocolCaseObservation[] = [];
  protocolRequestStart.set(context, context.requestLedger.snapshot().scanTransmitted);
  try {
    for (const item of plan.cases) observations.push(await executeCase(context, http, cleanup, plan, item));
  } finally { context.finishCleanup(cleanup); protocolRequestStart.delete(context); }
  const report: ProtocolSecurityReport = { enabled: true, plannedCases: plan.cases.length, executedCases: observations.length, passedCases: count(observations, "PASS"), failedCases: count(observations, "FAIL"), inconclusiveCases: count(observations, "INCONCLUSIVE"), blockedCases: count(observations, "BLOCKED"), observations, notes: [...plan.notes, "HTTP/3 uses the packaged native QUIC runtime with pinned DNS and no HTTP/2 or HTTP/1.1 downgrade."] };
  context.state.recordProtocolSecurity(report); return report;
}

async function executeCase(context: ScanContext, http: ReturnType<ScanContext["createApiGraphqlHttpClient"]>, cleanup: ReturnType<ScanContext["createWorkflowCleanupHttpClient"]>, plan: ProtocolSecurityPlan, item: ProtocolSecurityCasePlan): Promise<ProtocolCaseObservation> {
  const actor = plan.actors.find((value) => value.id === item.actorId)!; const profile = profileFor(context, actor);
  const recovery = context.options.workflowRecovery?.workflow === "protocolSecurity" && context.options.workflowRecovery.sourceCaseId === item.id;
  if (!recovery && !protocolCapacity(context)) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED");
  if (!recovery && item.requireVerifiedIdentity && identityBlocked(context, actor)) return observation(item, actor, "BLOCKED", "VERIFIED_IDENTITY_REQUIRED");
  if (actor.authSlot !== "anonymous" && !profile) return observation(item, actor, "BLOCKED", "ACTOR_CREDENTIAL_UNAVAILABLE");
  const secrets = profile ? authenticationLifecycleSecrets(profile) : {}; let headers: Record<string, string>;
  try { headers = { ...(profile ? authHeadersForProfile(profile) : {}), ...expandRecord(item.headers, secrets) }; if (Object.keys(headers).some((name) => /^(host|connection|proxy-connection|upgrade|expect|trailer|transfer-encoding|content-length|sec-websocket-.+|:.+)$/i.test(name))) return observation(item, actor, "BLOCKED", "TRANSPORT_HEADER_OVERRIDE_FORBIDDEN"); item = { ...item, expectation: { ...item.expectation, ...(item.expectation.equals !== undefined ? { equals: expand(item.expectation.equals, secrets) } : {}) } } as ProtocolSecurityCasePlan; } catch { return observation(item, actor, "BLOCKED", "SECRET_REFERENCE_UNAVAILABLE"); }
  const transportOptions: ProtocolTransportOptions = { allowedPrivateOrigins: [plan.targetOrigin], timeoutMs: plan.maxDurationMs, maxBytes: plan.maxResponseBytes, ...(context.options.config.transport.trustedCaPem ? { tlsCa: context.options.config.transport.trustedCaPem } : {}), ...(context.options.abortSignal ? { abortSignal: context.options.abortSignal } : {}) };
  try {
    if (recovery && stateChanging(item)) return await executeStateChange(context, cleanup, item, actor, secrets, async () => { throw new Error("RECOVERY_ACTION_REPLAY_FORBIDDEN"); });
    if (item.kind === "WEBSOCKET") {
      const messages = item.messages.map((v) => expand(v, secrets)); const messageBody = JSON.stringify(messages); if (!withinRequestLimit(context, messageBody)) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); let stream: Awaited<ReturnType<typeof runWebSocket>> | undefined; const action = async () => { stream = await raw(context, { url: item.url, method: "GET", headers }, () => runWebSocket(item.url, headers, item.subprotocols, messages, item.maxMessages, transportOptions)); return stream ? syntheticProtocolResponse(item.url, stream.statusCode) : budgetResponse(item.url); };
      if (!item.readOnly) return executeStateChange(context, cleanup, item, actor, secrets, action, (_response, cleanupOutcome) => stream ? { ...streamObservation(item, actor, stream.statusCode, stream.messages, stream.protocol), ...(cleanupOutcome ? { cleanupOutcome } : {}) } : observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED", undefined, 0, 0, undefined, cleanupOutcome));
      await action(); if (!stream) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); return streamObservation(item, actor, stream.statusCode, stream.messages, stream.protocol);
    }
    if (item.kind === "WEBSOCKET_AUTH_STATE_MACHINE") return await executeWebSocketStateMachine(context, cleanup, item, actor, headers, secrets, transportOptions);
    if (item.kind === "GRAPHQL_INCREMENTAL") return await executeGraphqlIncremental(context, item, actor, headers, secrets, transportOptions);
    if (item.kind === "GRAPHQL_PERSISTED_QUERY") return await executePersistedQuery(context, item, actor, headers, secrets, transportOptions);
    if (item.kind === "GRAPHQL_FEDERATION") {
      const document = item.operation === "SERVICE_SDL" ? "query RouteCairnService { _service { sdl } }" : "query RouteCairnEntities($representations: [_Any!]!) { _entities(representations: $representations) { __typename } }"; const body = JSON.stringify({ query: document, variables: item.operation === "ENTITIES" ? { representations: expand(item.representations, secrets) } : {} }); if (!withinRequestLimit(context, body)) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); const result = await raw(context, { url: item.url, method: "POST", headers: { ...headers, "content-type": "application/json" }, body }, () => runBoundedHttp(item.url, "POST", { ...headers, "content-type": "application/json" }, Buffer.from(body), transportOptions)); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); return boundedObservation(item, actor, result);
    }
    if (item.kind === "GRAPHQL_SUBSCRIPTION_REAUTH") return await executeSubscriptionReauth(context, item, actor, headers, secrets, transportOptions);
    if (item.kind === "GRAPHQL_SUBSCRIPTION") return await executeSubscription(context, item, actor, headers, secrets, transportOptions);
    if (item.kind === "SSE") {
      const body = item.body === undefined ? undefined : JSON.stringify(expand(item.body, secrets)); if (body !== undefined && !withinRequestLimit(context, body)) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); const requestHeaders = { ...headers, ...(body !== undefined ? { "Content-Type": "application/json" } : {}) }; const result = await raw(context, { url: item.url, method: item.method, headers: requestHeaders, ...(body !== undefined ? { body } : {}) }, () => runSse(item.url, item.method, requestHeaders, body, item.maxEvents, transportOptions)); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED");
      return sseResultObservation(item, actor, result);
    }
    if (item.kind === "GRAPHQL_MUTATION") return await executeMutation(context, http, cleanup, item, actor, headers, secrets);
    if (item.kind === "MULTIPART_UPLOAD") return await executeMultipart(context, cleanup, item, actor, headers, secrets);
    if (item.kind === "GRPC_UNARY" || item.kind === "GRPC_SERVER_STREAM" || item.kind === "GRPC_CLIENT_STREAM" || item.kind === "GRPC_BIDI_STREAM") {
      const refs = item.payloadSecretRefs ?? (item.payloadSecretRef ? [item.payloadSecretRef] : []); const payloads = refs.map((ref) => secretBuffer(secrets[ref])); if (!payloads.length || payloads.some((value) => !value)) return observation(item, actor, "BLOCKED", "PAYLOAD_SECRET_UNAVAILABLE"); const values = payloads as Buffer[]; const framedBytes = values.reduce((n, value) => n + value.length + 5, 0); if (framedBytes > plan.maxRequestBytes) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); const body = item.kind === "GRPC_UNARY" || item.kind === "GRPC_SERVER_STREAM" ? grpcFrame(values[0]!) : Buffer.concat(values.map(grpcFrame));
      const grpcHeaders = { ...headers, "content-type": "application/grpc", te: "trailers" }; let grpcResult: Http2Result | undefined; const action = async () => { grpcResult = await raw(context, { url: item.url, method: "POST", headers: grpcHeaders, body }, () => item.kind === "GRPC_CLIENT_STREAM" || item.kind === "GRPC_BIDI_STREAM" ? runGrpcStream(item.url, grpcHeaders, values, item.maxMessages, item.interMessageDelayMs, transportOptions) : runHttp2(item.url, "POST", grpcHeaders, body, item.maxMessages, transportOptions)); return grpcResult ? syntheticProtocolResponse(item.url, grpcResult.statusCode) : budgetResponse(item.url); }; const evaluate = (_response: ActionResponse, cleanupOutcome?: ProtocolCaseObservation["cleanupOutcome"]) => { if (!grpcResult) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED", undefined, 0, 0, undefined, cleanupOutcome); const allowed = item.expectation.allowedStatuses.includes(grpcResult.statusCode ?? 0) && grpcResult.grpcStatus === 0 && grpcResult.grpcMessages.length >= item.expectation.minMessages && /^application\/grpc\b/i.test(String(grpcResult.headers["content-type"] ?? "")); const denied = item.expectation.deniedStatuses.includes(grpcResult.statusCode ?? 0) || grpcResult.grpcStatus !== undefined && grpcResult.grpcStatus !== 0; const result = decisionObservation(item, actor, grpcResult.statusCode, allowed, denied, grpcResult.grpcMessages.length, 0, grpcResult.protocol, grpcResult.errorCode); return { ...result, ...(cleanupOutcome ? { cleanupOutcome } : {}) }; };
      if (!item.readOnly) return executeStateChange(context, cleanup, item, actor, secrets, action, evaluate); const response = await action(); return evaluate(response);
    }
    if (item.kind === "WEBTRANSPORT_DATAGRAM") { if (item.authenticationMode === "DATAGRAM" && context.options.plan.targetAuthorization?.bugBounty && !context.options.plan.targetAuthorization.bugBounty.authenticationPermitted) return observation(item, actor, "BLOCKED", "TARGET_AUTHORIZATION_AUTHENTICATION_PROHIBITED"); if (item.authenticationMode === "NONE" && Object.keys(headers).length) return observation(item, actor, "BLOCKED", "WEBTRANSPORT_CONNECT_HEADERS_UNSUPPORTED"); const datagrams = item.datagramSecretRefs.map((ref) => secretBuffer(secrets[ref])); if (datagrams.some((value) => !value)) return observation(item, actor, "BLOCKED", "DATAGRAM_SECRET_UNAVAILABLE"); const values = datagrams as Buffer[]; if (!withinRequestLimit(context, Buffer.concat(values))) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); const result = await raw(context, { url: item.url, method: "CONNECT", headers: {}, body: Buffer.concat(values) }, () => runWebTransportDatagrams(item.url, values, item.maxDatagrams, transportOptions)); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); const matching = result.receivedDatagrams.filter((value) => matches(parseJson(value.toString("utf8")), item.expectation)); const allowed = item.expectation.allowedStatuses.includes(result.statusCode) && matching.length >= Math.max(1, item.expectation.minMessages); const denied = item.expectation.deniedStatuses.includes(result.statusCode); return decisionObservation(item, actor, result.statusCode, allowed, denied, result.receivedDatagrams.length, 0, result.protocol); }
    if (item.kind === "STREAMING_UPLOAD_INTERRUPT") return await executeStreamingInterrupt(context, cleanup, item, actor, headers, secrets, transportOptions);
    if (item.kind === "COMPRESSION_BOUNDARY") { const body = item.bodySecretRef ? secretBuffer(secrets[item.bodySecretRef]) : undefined; if (item.bodySecretRef && !body) return observation(item, actor, "BLOCKED", "BODY_SECRET_UNAVAILABLE"); if (body && !withinRequestLimit(context, body)) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); const requestHeaders = { ...headers, "accept-encoding": item.encoding, ...(body ? { "content-encoding": item.encoding, "content-type": "application/octet-stream" } : {}) }; const result = await raw(context, { url: item.url, method: item.method, headers: requestHeaders, ...(body ? { body } : {}) }, () => runBoundedHttp(item.url, item.method, requestHeaders, body, transportOptions)); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); const contentEncoding = String(result.headers["content-encoding"] ?? "").toLowerCase(); if (contentEncoding === item.encoding) { try { decodeBoundedContent(result.body, item.encoding, item.maxExpandedBytes); } catch (error) { const reason = error instanceof Error ? safeReason(error.message) : "DECOMPRESSION_FAILURE"; return observation(item, actor, reason === "DECOMPRESSION_EXPANSION_LIMIT_EXCEEDED" ? "PASS" : "INCONCLUSIVE", reason, result.statusCode, 0, 0); } } return boundedObservation(item, actor, result); }
    if (item.kind === "CROSS_PROTOCOL_IDENTITY") return await executeCrossProtocolIdentity(context, item, actor, headers, secrets, transportOptions);
    if (item.kind === "PROXY_CHAIN_DESYNCHRONIZATION") return await executeProxyChainDesync(context, http, item, actor, headers, secrets, transportOptions);
    if (item.kind === "HTTP2_AUTHORIZATION") {
      const result = await raw(context, { url: item.url, method: item.method, headers }, () => runHttp2(item.url, item.method, headers, undefined, 1, transportOptions)); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); return statusObservation(item, actor, result);
    }
    if (item.kind === "HTTP2_DESYNCHRONIZATION") {
      const body = secretBuffer(secrets[item.bodySecretRef]); if (!body) return observation(item, actor, "BLOCKED", "BODY_SECRET_UNAVAILABLE"); if (!withinRequestLimit(context, body)) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); if (Date.parse(item.authorization.expiresAt) <= Date.now()) return observation(item, actor, "BLOCKED", "AUTHORIZATION_EXPIRED_AT_EXECUTION"); if (context.options.plan.targetAuthorization?.bugBounty) return observation(item, actor, "BLOCKED", "DESYNCHRONIZATION_NOT_PERMITTED_IN_BUG_BOUNTY_MODE");
      const result = await rawPair(context, { url: item.url, method: "POST", headers, body }, { url: new URL(item.sentinelPath, item.url).toString(), method: "GET", headers }, () => runHttp2Desync(item.url, "POST", headers, body, Math.max(0, body.length + item.declaredLengthDelta), item.sentinelPath, transportOptions)); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED");
      const probeAccepted = item.expectation.allowedStatuses.includes(result.probe.statusCode ?? 0) && !result.probe.errorCode; const sentinelClean = item.expectation.allowedStatuses.includes(result.sentinel.statusCode ?? 0) && !result.sentinel.errorCode; const failed = probeAccepted || !sentinelClean; return observation(item, actor, failed ? "FAIL" : "PASS", probeAccepted ? "HTTP2_LENGTH_MISMATCH_ACCEPTED" : !sentinelClean ? "HTTP2_SENTINEL_CONTAMINATED" : "HTTP2_LENGTH_MISMATCH_REJECTED_AND_SENTINEL_CLEAN", result.sentinel.statusCode, 0, 0, result.sentinel.protocol);
    }
    if (item.kind === "HTTP3_AUTHORIZATION") {
      await ensureHttp3Runtime(transportOptions);
      const result = await raw(context, { url: item.url, method: item.method, headers }, () => runHttp3Authorization(item.url, item.method as "GET" | "HEAD" | "OPTIONS", headers, transportOptions)); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); const value = parseJson(result.body.toString("utf8")); const allowed = item.expectation.allowedStatuses.includes(result.statusCode) && matches(value, item.expectation); const denied = item.expectation.deniedStatuses.includes(result.statusCode); return decisionObservation(item, actor, result.statusCode, allowed, denied, 0, 0, result.protocol);
    }
    if (item.kind !== "HTTP3_DESYNCHRONIZATION") return observation(item, actor, "BLOCKED", "PROTOCOL_KIND_UNAVAILABLE");
    const h3Body = secretBuffer(secrets[item.bodySecretRef]); if (!h3Body) return observation(item, actor, "BLOCKED", "BODY_SECRET_UNAVAILABLE"); if (!withinRequestLimit(context, h3Body)) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); if (Date.parse(item.authorization.expiresAt) <= Date.now()) return observation(item, actor, "BLOCKED", "AUTHORIZATION_EXPIRED_AT_EXECUTION"); if (context.options.plan.targetAuthorization?.bugBounty) return observation(item, actor, "BLOCKED", "DESYNCHRONIZATION_NOT_PERMITTED_IN_BUG_BOUNTY_MODE"); await ensureHttp3Runtime(transportOptions);
    const h3Result = await rawPair(context, { url: item.url, method: "POST", headers, body: h3Body }, { url: new URL(item.sentinelPath, item.url).toString(), method: "GET", headers }, () => runHttp3Desync(item.url, headers, h3Body, Math.max(0, h3Body.length + item.declaredLengthDelta), item.sentinelPath, item.expectation.allowedStatuses, transportOptions)); if (!h3Result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); const h3Failed = h3Result.probeAccepted || !h3Result.sentinelClean; return observation(item, actor, h3Failed ? "FAIL" : "PASS", h3Result.probeAccepted ? "HTTP3_LENGTH_MISMATCH_ACCEPTED" : !h3Result.sentinelClean ? "HTTP3_SENTINEL_CONTAMINATED" : "HTTP3_LENGTH_MISMATCH_REJECTED_AND_SENTINEL_CLEAN", h3Result.sentinelStatus, 0, 0, h3Result.protocol);
  } catch (error) { const reason = error instanceof Error ? safeReason(error.message) : "PROTOCOL_TRANSPORT_FAILURE"; return observation(item, actor, /^(?:HTTP3_RUNTIME_UNAVAILABLE|TARGET_AUTHORIZATION_|PROTOCOL_SCOPE_BLOCKED_)/.test(reason) ? "BLOCKED" : "INCONCLUSIVE", reason); }
}

async function executeSubscription(context: ScanContext, item: GraphqlSubscriptionCasePlan, actor: ProtocolActorPlan, headers: Record<string, string>, secrets: Record<string, string>, options: ProtocolTransportOptions): Promise<ProtocolCaseObservation> {
  if (item.transport === "SSE") {
    const body = JSON.stringify({ query: item.document, ...(item.operationName ? { operationName: item.operationName } : {}), variables: expand(item.variables, secrets) }); if (!withinRequestLimit(context, body)) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); const requestHeaders = { ...headers, "Content-Type": "application/json" }; const result = await raw(context, { url: item.url, method: "POST", headers: requestHeaders, body }, () => runSse(item.url, "POST", requestHeaders, body, item.maxMessages, options)); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); return sseResultObservation(item, actor, result);
  }
  const protocol = item.transport === "GRAPHQL_TRANSPORT_WS" ? "graphql-transport-ws" : "graphql-ws"; const id = createHash("sha256").update(item.comparisonFingerprint).digest("hex").slice(0, 12); const payload = { query: item.document, ...(item.operationName ? { operationName: item.operationName } : {}), variables: expand(item.variables, secrets) };
  const messages = [{ type: "connection_init", ...(item.connectionPayload !== undefined ? { payload: expand(item.connectionPayload, secrets) } : {}) }, item.transport === "GRAPHQL_TRANSPORT_WS" ? { id, type: "subscribe", payload } : { id, type: "start", payload }];
  if (!withinRequestLimit(context, JSON.stringify(messages))) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED");
  const result = await raw(context, { url: item.url, method: "GET", headers }, () => runWebSocket(item.url, headers, [protocol], messages, item.maxMessages, options, "connection_ack")); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); if (result.statusCode === 101 && result.protocol !== protocol) return observation(item, actor, "FAIL", "WEBSOCKET_SUBPROTOCOL_MISMATCH", result.statusCode, result.messages.length, 0, result.protocol); return streamObservation(item, actor, result.statusCode, result.messages, result.protocol);
}

async function executeWebSocketStateMachine(context: ScanContext, cleanup: ReturnType<ScanContext["createWorkflowCleanupHttpClient"]>, item: WebSocketAuthStateMachineCasePlan, actor: ProtocolActorPlan, headers: Record<string, string>, secrets: Record<string, string>, options: ProtocolTransportOptions): Promise<ProtocolCaseObservation> {
  const states = item.states.map((state) => expand(state, secrets) as typeof state); const outbound = states.flatMap((state) => state.send === undefined ? [] : [state.send]); if (!withinRequestLimit(context, JSON.stringify(outbound))) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); let result: Awaited<ReturnType<typeof runWebSocket>> | undefined;
  const action = async () => { result = await raw(context, { url: item.url, method: "GET", headers }, () => runWebSocket(item.url, headers, item.subprotocols, outbound, item.maxMessages, options, undefined, states)); return result ? syntheticProtocolResponse(item.url, result.statusCode) : budgetResponse(item.url); };
  const evaluate = (_response: ActionResponse, cleanupOutcome?: ProtocolCaseObservation["cleanupOutcome"]) => { if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED", undefined, 0, 0, undefined, cleanupOutcome); let cursor = 0; let matched = 0; for (const state of states) { if (!state.expectType && !state.expectJsonPath) continue; const index = result.messages.findIndex((message, i) => i >= cursor && (!state.expectType || message.type === state.expectType) && (!state.expectJsonPath || JSON.stringify(at(message.value, state.expectJsonPath)) === JSON.stringify(state.equals))); if (index < 0) break; cursor = index + 1; matched += 1; } const expected = states.filter((state) => state.expectType || state.expectJsonPath).length; const allowed = item.expectation.allowedStatuses.includes(result.statusCode) && matched === expected && matched >= item.expectation.minMessages; const denied = item.expectation.deniedStatuses.includes(result.statusCode) || result.messages.some((message) => message.type === "error" || message.type === "connection_error"); const value = decisionObservation(item, actor, result.statusCode, allowed, denied, result.messages.length, 0, result.protocol); return { ...value, structuralCount: matched, ...(cleanupOutcome ? { cleanupOutcome } : {}) }; };
  if (!item.readOnly) return executeStateChange(context, cleanup, item, actor, secrets, action, evaluate); const response = await action(); return evaluate(response);
}

async function executeGraphqlIncremental(context: ScanContext, item: GraphqlIncrementalCasePlan, actor: ProtocolActorPlan, headers: Record<string, string>, secrets: Record<string, string>, options: ProtocolTransportOptions): Promise<ProtocolCaseObservation> {
  const body = JSON.stringify({ query: item.document, ...(item.operationName ? { operationName: item.operationName } : {}), variables: expand(item.variables, secrets) }); if (!withinRequestLimit(context, body)) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); const requestHeaders = { ...headers, accept: "multipart/mixed; deferSpec=20220824, application/json", "content-type": "application/json" }; const result = await raw(context, { url: item.url, method: "POST", headers: requestHeaders, body }, () => runBoundedHttp(item.url, "POST", requestHeaders, Buffer.from(body), options)); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); const parts = parseGraphqlParts(result, item.maxParts); const paths = new Set(parts.flatMap((part) => graphqlIncrementalPaths(part))); const pathMatch = item.expectedPaths.every((path) => paths.has(path)); const complete = parts.at(-1)?.hasNext === false || parts.length === 1 && !/^multipart\/mixed/i.test(String(result.headers["content-type"])) && parts[0]?.hasNext !== true && parts[0]?.data !== undefined; const graphqlDenied = parts.some((part) => part && typeof part === "object" && Array.isArray(part.errors) && part.errors.length > 0); const allowed = item.expectation.allowedStatuses.includes(result.statusCode) && parts.length >= item.expectation.minMessages && pathMatch && complete && !graphqlDenied; const denied = item.expectation.deniedStatuses.includes(result.statusCode) || graphqlDenied; return { ...decisionObservation(item, actor, result.statusCode, allowed, denied, parts.length, 0), structuralCount: paths.size };
}

async function executePersistedQuery(context: ScanContext, item: GraphqlPersistedQueryCasePlan, actor: ProtocolActorPlan, headers: Record<string, string>, secrets: Record<string, string>, options: ProtocolTransportOptions): Promise<ProtocolCaseObservation> {
  const variables = expand(item.variables, secrets); const extension = { persistedQuery: { version: 1, sha256Hash: item.sha256Hash } }; const payloads = item.negotiation === "REGISTER_THEN_HASH" ? [{ query: item.document, ...(item.operationName ? { operationName: item.operationName } : {}), variables, extensions: extension }, { ...(item.operationName ? { operationName: item.operationName } : {}), variables, extensions: extension }] : [{ ...(item.operationName ? { operationName: item.operationName } : {}), variables, extensions: extension }]; let last: BoundedHttpResult | undefined; const statuses: number[] = [];
  for (const payload of payloads) { const body = JSON.stringify(payload); if (!withinRequestLimit(context, body)) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); last = await raw(context, { url: item.url, method: "POST", headers: { ...headers, "content-type": "application/json" }, body }, () => runBoundedHttp(item.url, "POST", { ...headers, "content-type": "application/json" }, Buffer.from(body), options)); if (!last) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); statuses.push(last.statusCode); }
  const final = boundedObservation(item, actor, last!); if (statuses.every((value) => item.expectation.allowedStatuses.includes(value))) return final; return decisionObservation(item, actor, last!.statusCode, false, statuses.some((value) => item.expectation.deniedStatuses.includes(value)), 0, 0);
}

async function executeSubscriptionReauth(context: ScanContext, item: Extract<ProtocolSecurityCasePlan, { kind: "GRAPHQL_SUBSCRIPTION_REAUTH" }>, actor: ProtocolActorPlan, headers: Record<string, string>, secrets: Record<string, string>, options: ProtocolTransportOptions): Promise<ProtocolCaseObservation> {
  const protocol = item.transport === "GRAPHQL_TRANSPORT_WS" ? "graphql-transport-ws" : "graphql-ws"; const payload = { query: item.document, ...(item.operationName ? { operationName: item.operationName } : {}), variables: expand(item.variables, secrets) }; const subscribe = item.transport === "GRAPHQL_TRANSPORT_WS" ? { id: "routecairn", type: "subscribe", payload } : { id: "routecairn", type: "start", payload }; const attempts = [item.initialConnectionPayload, item.reauthConnectionPayload]; const results: Awaited<ReturnType<typeof runWebSocket>>[] = [];
  for (const connectionPayload of attempts) { const messages = [{ type: "connection_init", ...(connectionPayload !== undefined ? { payload: expand(connectionPayload, secrets) } : {}) }, subscribe]; if (!withinRequestLimit(context, JSON.stringify(messages))) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); const result = await raw(context, { url: item.url, method: "GET", headers }, () => runWebSocket(item.url, headers, [protocol], messages, item.maxMessages, options, "connection_ack")); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); results.push(result); }
  const classify = (result: Awaited<ReturnType<typeof runWebSocket>>) => { const matching = result.messages.filter((message) => (!item.expectation.messageType || message.type === item.expectation.messageType) && matches(message.value, item.expectation)); const allowed = item.expectation.allowedStatuses.includes(result.statusCode) && result.protocol === protocol && matching.length >= item.expectation.minMessages; const denied = item.expectation.deniedStatuses.includes(result.statusCode) || result.messages.some((message) => message.type === "error" || message.type === "connection_error"); return allowed ? "ALLOW" as const : denied ? "DENY" as const : "UNKNOWN" as const; }; const initial = classify(results[0]!); const reauthorized = classify(results[1]!); const messageCount = results.reduce((n, result) => n + result.messages.length, 0); if (initial === "UNKNOWN" || reauthorized === "UNKNOWN") return observation(item, actor, "INCONCLUSIVE", "SUBSCRIPTION_REAUTH_RESPONSE_UNCLASSIFIED", results[1]!.statusCode, messageCount, 0, results[1]!.protocol); const matched = initial === item.initialDecision && (item.expectation.decision === "OBSERVE" || reauthorized === item.expectation.decision); return observation(item, actor, matched ? "PASS" : "FAIL", matched ? "SUBSCRIPTION_REAUTH_CONTRACT_MATCHED" : "SUBSCRIPTION_REAUTH_CONTRACT_FAILED", results[1]!.statusCode, messageCount, 0, results[1]!.protocol);
}

async function executeStreamingInterrupt(context: ScanContext, cleanup: ReturnType<ScanContext["createWorkflowCleanupHttpClient"]>, item: StreamingUploadInterruptCasePlan, actor: ProtocolActorPlan, headers: Record<string, string>, secrets: Record<string, string>, options: ProtocolTransportOptions): Promise<ProtocolCaseObservation> {
  const body = secretBuffer(secrets[item.bodySecretRef]); if (!body) return observation(item, actor, "BLOCKED", "BODY_SECRET_UNAVAILABLE"); if (!withinRequestLimit(context, body)) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); let verification: BoundedHttpResult | undefined;
  return executeStateChange(context, cleanup, item, actor, secrets, async () => { verification = await rawPair(context, { url: item.url, method: item.method, headers, body }, { url: item.verificationUrl, method: item.verificationMethod, headers }, async () => { await runInterruptedUpload(item.url, item.method, headers, body, item.chunkBytes, item.interruptAfterBytes, options); return runBoundedHttp(item.verificationUrl, item.verificationMethod, headers, undefined, options); }); return verification ? syntheticResponse(item.verificationUrl, verification) : budgetResponse(item.url); }, (_response, cleanupOutcome) => verification ? { ...boundedObservation(item, actor, verification), ...(cleanupOutcome ? { cleanupOutcome } : {}) } : observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED", undefined, 0, 0, undefined, cleanupOutcome));
}

async function executeCrossProtocolIdentity(context: ScanContext, item: CrossProtocolIdentityCasePlan, actor: ProtocolActorPlan, actorHeaders: Record<string, string>, secrets: Record<string, string>, options: ProtocolTransportOptions): Promise<ProtocolCaseObservation> {
  const fingerprints: string[] = []; const statuses: number[] = []; let status: number | undefined;
  for (const leg of item.legs) { const headers = { ...actorHeaders, ...expandRecord(leg.headers, secrets) }; const payload = leg.payloadSecretRef ? secretBuffer(secrets[leg.payloadSecretRef]) : undefined; if (leg.payloadSecretRef && !payload) return observation(item, actor, "BLOCKED", "PAYLOAD_SECRET_UNAVAILABLE"); if (payload && !withinRequestLimit(context, payload)) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); const transmission = { url: leg.url, method: leg.protocol === "WEBTRANSPORT" ? "CONNECT" : leg.method, headers, ...(payload ? { body: payload } : {}) }; let value: Buffer;
    if (leg.protocol === "HTTP1") { const result = await raw(context, transmission, () => runBoundedHttp(leg.url, leg.method, headers, payload, options)); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); status = result.statusCode; value = result.body; }
    else if (leg.protocol === "HTTP2" || leg.protocol === "GRPC") { const result = await raw(context, transmission, () => runHttp2(leg.url, leg.method, headers, leg.protocol === "GRPC" && payload ? grpcFrame(payload) : payload, 1, options)); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); status = result.statusCode; value = leg.protocol === "GRPC" ? (result.grpcMessages[0] ?? Buffer.alloc(0)) : result.body; }
    else if (leg.protocol === "HTTP3") { await ensureHttp3Runtime(options); const result = await raw(context, transmission, () => runHttp3Authorization(leg.url, leg.method as "GET" | "HEAD" | "OPTIONS", headers, options)); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); status = result.statusCode; value = result.body; }
    else if (leg.protocol === "WEBTRANSPORT") { if (Object.keys(headers).length) return observation(item, actor, "BLOCKED", "WEBTRANSPORT_CONNECT_HEADERS_UNSUPPORTED"); const result = await raw(context, transmission, () => runWebTransportDatagrams(leg.url, [payload!], 1, options)); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); status = result.statusCode; value = result.receivedDatagrams[0] ?? Buffer.alloc(0); }
    else { const result = await raw(context, transmission, () => runWebSocket(leg.url, headers, [], [], 1, options)); if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); status = result.statusCode; value = Buffer.from(JSON.stringify(result.messages[0]?.value ?? null)); }
    if (status !== undefined) statuses.push(status); const selected = leg.jsonPath ? at(parseJson(value.toString("utf8")), leg.jsonPath) : parseJson(value.toString("utf8")); if (selected === undefined || selected === null || value.length === 0) return observation(item, actor, "INCONCLUSIVE", "CROSS_PROTOCOL_IDENTITY_EVIDENCE_MISSING", status); fingerprints.push(createHash("sha256").update(stableSerialize(selected)).digest("hex"));
  }
  const consistent = new Set(fingerprints).size === 1; if (!consistent) return { ...observation(item, actor, "FAIL", "CROSS_PROTOCOL_IDENTITY_MISMATCH", status), structuralCount: fingerprints.length }; const allowed = statuses.length === item.legs.length && statuses.every((value) => item.expectation.allowedStatuses.includes(value)); const denied = statuses.some((value) => item.expectation.deniedStatuses.includes(value)); return { ...decisionObservation(item, actor, status, allowed, denied, 0, 0), structuralCount: fingerprints.length };
}

async function executeProxyChainDesync(context: ScanContext, http: ReturnType<ScanContext["createApiGraphqlHttpClient"]>, item: ProxyChainDesyncCasePlan, actor: ProtocolActorPlan, headers: Record<string, string>, secrets: Record<string, string>, options: ProtocolTransportOptions): Promise<ProtocolCaseObservation> {
  if (Date.parse(item.authorization.expiresAt) <= Date.now()) return observation(item, actor, "BLOCKED", "AUTHORIZATION_EXPIRED_AT_EXECUTION");
  if (context.options.plan.targetAuthorization?.bugBounty) return observation(item, actor, "BLOCKED", "DESYNCHRONIZATION_NOT_PERMITTED_IN_BUG_BOUNTY_MODE");
  const proof = item.topologyProof;
  if (!proof) return observation(item, actor, "INCONCLUSIVE", "PROXY_DEPLOYMENT_AND_TRACE_PROOF_REQUIRED");
  const body = secretBuffer(secrets[item.bodySecretRef]); if (!body) return observation(item, actor, "BLOCKED", "BODY_SECRET_UNAVAILABLE");
  if (!withinRequestLimit(context, body)) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED");
  const protocols = item.frontendProtocols ?? [...new Set(item.proxyChain.map((hop) => hop.protocol))]; let inconclusive = false; let tested = 0;
  for (const protocol of protocols) {
    if (Date.parse(item.authorization.expiresAt) <= Date.now()) return observation(item, actor, "BLOCKED", "AUTHORIZATION_EXPIRED_AT_EXECUTION");
    if ((protocol === "H1") === (item.framing === "CONTENT_LENGTH_DELTA")) { inconclusive = true; continue; }
    const canary = randomBytes(16).toString("hex"); const proofUrl = new URL(proof.url); proofUrl.searchParams.set("routecairn_canary", canary);
    const scopedHeaders = { ...headers, "X-RouteCairn-Chain-Canary": canary };
    const readProof = async () => {
      const response = await http.send({ url: proofUrl.toString(), method: "GET", headers: scopedHeaders, skipCache: true, disableRetries: true, disableRedirects: true, retainBodyPreview: true });
      const value = parseJson(bodyPreviewForAnalysis(response) ?? "");
      const trace = Object.entries(response.headers).find(([name]) => name.toLowerCase() === proof.traceHeader.toLowerCase())?.[1];
      return response.statusCode === 200 && trace === proof.hopIds.join(",") && value !== null && typeof value === "object" && at(value, "deploymentSha256") === proof.deploymentSha256 && at(value, "canary") === canary && Array.isArray(at(value, "hopIds")) && JSON.stringify(at(value, "hopIds")) === JSON.stringify(proof.hopIds) && typeof at(value, "violation") === "boolean" ? { violation: at(value, "violation") as boolean, sentinel: at(value, "sentinel") === true } : undefined;
    };
    const before = await readProof(); if (before?.violation !== false) { inconclusive = true; continue; }
    let accepted = false; let clean = true; let unavailable = false;
    if (protocol === "H1") {
      const result = await http.sendRawHttp1({ url: item.url, method: "POST", headers: scopedHeaders, body: body.toString("utf8"), sentinelPath: item.sentinelPath, variant: item.framing as "CL_TE" | "TE_CL", marker: canary });
      unavailable = Boolean(result.error); accepted = result.statusCodes.some((status) => item.expectation.allowedStatuses.includes(status));
    } else if (protocol === "H2") {
      const result = await rawPair(context, { url: item.url, method: "POST", headers: scopedHeaders, body }, { url: new URL(item.sentinelPath, item.url).toString(), method: "GET", headers: scopedHeaders }, () => runHttp2Desync(item.url, "POST", scopedHeaders, body, Math.max(0, body.length + item.declaredLengthDelta), item.sentinelPath, options));
      if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED");
      unavailable = Boolean(result.probe.errorCode && result.probe.errorCode !== "ERR_HTTP2_STREAM_ERROR") || Boolean(result.sentinel.errorCode); accepted = item.expectation.allowedStatuses.includes(result.probe.statusCode ?? 0); clean = item.expectation.allowedStatuses.includes(result.sentinel.statusCode ?? 0);
    } else {
      await ensureHttp3Runtime(options); const result = await rawPair(context, { url: item.url, method: "POST", headers: scopedHeaders, body }, { url: new URL(item.sentinelPath, item.url).toString(), method: "GET", headers: scopedHeaders }, () => runHttp3Desync(item.url, scopedHeaders, body, Math.max(0, body.length + item.declaredLengthDelta), item.sentinelPath, item.expectation.allowedStatuses, options));
      if (!result) return observation(item, actor, "BLOCKED", "REQUEST_BUDGET_EXHAUSTED"); accepted = result.probeAccepted; clean = result.sentinelClean;
    }
    const after = await readProof(); tested += 1;
    if (after?.violation === true) return { ...observation(item, actor, "FAIL", "PROXY_CHAIN_CANARY_BOUND_MISROUTING_PROVEN"), structuralCount: tested };
    if (after?.violation !== false || !after.sentinel || unavailable || accepted || !clean) inconclusive = true;
  }
  return { ...observation(item, actor, inconclusive || !tested ? "INCONCLUSIVE" : "PASS", inconclusive || !tested ? "PROXY_CHAIN_MATRIX_INCOMPLETE_OR_AMBIGUITY_ONLY" : "VERIFIED_PROXY_CHAIN_REJECTED_AMBIGUITY"), structuralCount: tested };
}

async function executeMutation(context: ScanContext, http: ReturnType<ScanContext["createApiGraphqlHttpClient"]>, cleanup: ReturnType<ScanContext["createWorkflowCleanupHttpClient"]>, item: GraphqlMutationCasePlan, actor: ProtocolActorPlan, headers: Record<string, string>, secrets: Record<string, string>): Promise<ProtocolCaseObservation> {
  const body = JSON.stringify({ query: item.document, ...(item.operationName ? { operationName: item.operationName } : {}), variables: expand(item.variables, secrets) }); if (!withinRequestLimit(context, body)) return observation(item, actor, "BLOCKED", "REQUEST_BODY_LIMIT_EXCEEDED"); return executeStateChange(context, cleanup, item, actor, secrets, async () => http.send({ url: item.url, method: "POST", headers: { ...headers, "Content-Type": "application/json" }, body, retainBodyPreview: true, disableRetries: true, disableRedirects: true, skipCache: true }));
}

async function executeMultipart(context: ScanContext, cleanup: ReturnType<ScanContext["createWorkflowCleanupHttpClient"]>, item: MultipartCasePlan, actor: ProtocolActorPlan, headers: Record<string, string>, secrets: Record<string, string>): Promise<ProtocolCaseObservation> {
  const boundary = `routecairn-${createHash("sha256").update(item.comparisonFingerprint).digest("hex").slice(0, 24)}`; const parts: Buffer[] = [];
  for (const [name, value] of Object.entries(item.fields)) parts.push(Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="${name}"\r\nContent-Type: application/json\r\n\r\n${JSON.stringify(expand(value, secrets))}\r\n`));
  for (const file of item.files) { const content = secretBuffer(secrets[file.contentSecretRef]); if (!content) return observation(item, actor, "BLOCKED", "UPLOAD_SECRET_UNAVAILABLE"); parts.push(Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="${file.fieldName}"; filename="${file.fileName.replace(/["\r\n]/g, "_")}"\r\nContent-Type: ${file.contentType}\r\n\r\n`), content, Buffer.from("\r\n")])); }
  parts.push(Buffer.from(`--${boundary}--\r\n`)); const body = Buffer.concat(parts); if (!withinRequestLimit(context, body)) return observation(item, actor, "BLOCKED", "MULTIPART_BODY_LIMIT_EXCEEDED");
  const requestHeaders = { ...headers, "Content-Type": `multipart/form-data; boundary=${boundary}` }; const action = async () => { const result = await raw(context, { url: item.url, method: "POST", headers: requestHeaders, body }, () => runBoundedHttp(item.url, "POST", requestHeaders, body, { allowedPrivateOrigins: [context.options.plan.protocolSecurity!.targetOrigin], timeoutMs: context.options.plan.protocolSecurity!.maxDurationMs, maxBytes: context.options.plan.protocolSecurity!.maxResponseBytes, ...(context.options.config.transport.trustedCaPem ? { tlsCa: context.options.config.transport.trustedCaPem } : {}), ...(context.options.abortSignal ? { abortSignal: context.options.abortSignal } : {}) })); return result ? syntheticResponse(item.url, result) : budgetResponse(item.url); };
  if (!item.readOnly) return executeStateChange(context, cleanup, item, actor, secrets, action); const response = await action(); return httpObservation(item, actor, response, "NOT_REQUIRED");
}

async function executeStateChange(context: ScanContext, cleanupTransport: ReturnType<ScanContext["createWorkflowCleanupHttpClient"]>, item: GraphqlMutationCasePlan | MultipartCasePlan | WebSocketCasePlan | WebSocketAuthStateMachineCasePlan | GrpcCasePlan | StreamingUploadInterruptCasePlan, actor: ProtocolActorPlan, secrets: Record<string, string>, action: () => Promise<ActionResponse>, evaluate?: (response: ActionResponse, cleanupOutcome: ProtocolCaseObservation["cleanupOutcome"]) => ProtocolCaseObservation): Promise<ProtocolCaseObservation> {
  const auth = item.authorization!; const cleanup = item.cleanup!;
  const cleanupProfile = profileFor(context, actor); const cleanupActorHeaders = cleanupProfile ? authHeadersForProfile(cleanupProfile) : {};
  const recoveryRequested = context.options.workflowRecovery?.workflow === "protocolSecurity" && context.options.workflowRecovery.sourceCaseId === item.id;
  if (!recoveryRequested && Date.parse(auth.expiresAt) <= Date.now()) return observation(item, actor, "BLOCKED", "AUTHORIZATION_EXPIRED_AT_EXECUTION");
  const cleanupBody = cleanup.body === undefined ? undefined : JSON.stringify(expand(cleanup.body, secrets)); if (cleanupBody && !withinRequestLimit(context, cleanupBody)) return observation(item, actor, "BLOCKED", "CLEANUP_BODY_LIMIT_EXCEEDED");
  const caseId = `protocol-security-${item.id}`; const state = new Map<string, unknown>(); const recovering = context.mutations.register("protocolSecurity", caseId, item, { state }); const journal = context.mutations.journal; const lock = context.mutations.lock(); let held = false; let armed = recovering; let response: ActionResponse | undefined; let cleanupOutcome: ProtocolCaseObservation["cleanupOutcome"] = "CLEANUP_FAILED";
  if (!recovering && Date.parse(auth.expiresAt) <= Date.now()) return observation(item, actor, "BLOCKED", "AUTHORIZATION_EXPIRED_AT_EXECUTION");
  try {
    await lock.acquire(caseId); held = true;
    if (!recovering && Date.parse(auth.expiresAt) <= Date.now()) return observation(item, actor, "BLOCKED", "AUTHORIZATION_EXPIRED_AT_EXECUTION");
    await journal.append(entry(item, caseId, "AUTHORIZED"));
    if (!recovering) {
      await journal.append(entry(item, caseId, "MUTATION_ARMED")); armed = true; await context.mutations.checkpoint(caseId);
      try { response = await action(); await journal.append(entry(item, caseId, "MUTATION_SENT")); } catch { /* any possibly transmitted action still reaches cleanup */ }
    }
    if (armed) {
      try { const cleanupResponse = await cleanupTransport.send({ url: expandString(cleanup.url, secrets), method: cleanup.method, headers: { ...cleanupActorHeaders, ...(cleanupBody !== undefined ? { "Content-Type": "application/json" } : {}), ...expandRecord(cleanup.headers, secrets) }, ...(cleanupBody !== undefined ? { body: cleanupBody } : {}), retainBodyPreview: false, disableRetries: true, disableRedirects: true, skipCache: true }); cleanupOutcome = cleanup.statusIn.includes(cleanupResponse.statusCode ?? 0) ? "ROLLBACK_VERIFIED" : "CLEANUP_FAILED"; }
      catch { cleanupOutcome = "CLEANUP_FAILED"; }
      await journal.append(entry(item, caseId, cleanupOutcome === "ROLLBACK_VERIFIED" ? "ROLLBACK_VERIFIED" : "CLEANUP_FAILED", cleanupOutcome === "ROLLBACK_VERIFIED" ? "ROLLBACK_VERIFIED" : "CLEANUP_FAILED"));
    }
  }
  catch { cleanupOutcome = "CLEANUP_FAILED"; if (armed) await journal.append(entry(item, caseId, "CLEANUP_FAILED", "CLEANUP_FAILED")).catch(() => undefined); }
  finally { if (held) await lock.release().catch(() => undefined); }
  if (recovering) return observation(item, actor, cleanupOutcome === "ROLLBACK_VERIFIED" ? "PASS" : "INCONCLUSIVE", cleanupOutcome === "ROLLBACK_VERIFIED" ? "RECOVERY_CLEANUP_VERIFIED" : "RECOVERY_CLEANUP_FAILED", undefined, 0, 0, undefined, cleanupOutcome);
  if (!response) return observation(item, actor, "INCONCLUSIVE", "MUTATION_TRANSPORT_OR_JOURNAL_FAILURE", undefined, 0, 0, undefined, cleanupOutcome); return evaluate ? evaluate(response, cleanupOutcome) : httpObservation(item, actor, response, cleanupOutcome);
}

function streamObservation(item: ProtocolSecurityCasePlan, actor: ProtocolActorPlan, status: number, messages: StreamMessage[], protocol?: string): ProtocolCaseObservation { if (status === 101 && item.kind === "WEBSOCKET" && item.subprotocols.length && (!protocol || !item.subprotocols.includes(protocol))) return observation(item, actor, "FAIL", "WEBSOCKET_SUBPROTOCOL_MISMATCH", status, messages.length, 0, protocol); const matching = messages.filter((m) => (!item.expectation.messageType || m.type === item.expectation.messageType) && matches(m.value, item.expectation)); const allowed = item.expectation.allowedStatuses.includes(status) && matching.length >= item.expectation.minMessages; const denied = item.expectation.deniedStatuses.includes(status) || messages.some((m) => m.type === "error" || m.type === "connection_error"); return decisionObservation(item, actor, status, allowed, denied, messages.length, 0, protocol); }
function sseResultObservation(item: ProtocolSecurityCasePlan, actor: ProtocolActorPlan, response: SseResult): ProtocolCaseObservation { const max = "maxEvents" in item ? item.maxEvents : "maxMessages" in item ? item.maxMessages : 50; const events = parseSse(response.body).slice(0, max); const matching = events.filter((event) => (!item.expectation.messageType || event.event === item.expectation.messageType) && matches(event.value, item.expectation)); const allowed = item.expectation.allowedStatuses.includes(response.statusCode) && matching.length >= item.expectation.minMessages && /^text\/event-stream\b/i.test(response.contentType ?? ""); const denied = item.expectation.deniedStatuses.includes(response.statusCode); return decisionObservation(item, actor, response.statusCode, allowed, denied, 0, events.length); }
function httpObservation(item: ProtocolSecurityCasePlan, actor: ProtocolActorPlan, response: ActionResponse, cleanupOutcome: ProtocolCaseObservation["cleanupOutcome"]): ProtocolCaseObservation { const status = response.statusCode; const value = parseJson(bodyPreviewForAnalysis(response) ?? response.transientBody?.toString("utf8")); const graphqlDenied = item.kind === "GRAPHQL_MUTATION" && Boolean(value && typeof value === "object" && Array.isArray((value as Record<string, unknown>).errors) && !((value as Record<string, unknown>).data)); const allowed = item.expectation.allowedStatuses.includes(status ?? 0) && !graphqlDenied; const denied = item.expectation.deniedStatuses.includes(status ?? 0) || graphqlDenied; const shapeMatched = matches(value, item.expectation); const base = decisionObservation(item, actor, status, allowed && shapeMatched, denied, 0, 0, undefined, response.error?.name); return { ...base, ...(cleanupOutcome ? { cleanupOutcome } : {}) }; }
function boundedObservation(item: ProtocolSecurityCasePlan, actor: ProtocolActorPlan, response: BoundedHttpResult): ProtocolCaseObservation { const value = parseJson(response.body.toString("utf8")); const graphqlDenied = item.kind.startsWith("GRAPHQL_") && Boolean(value && typeof value === "object" && Array.isArray((value as Record<string, unknown>).errors) && !(value as Record<string, unknown>).data); return decisionObservation(item, actor, response.statusCode, item.expectation.allowedStatuses.includes(response.statusCode) && !graphqlDenied && matches(value, item.expectation), item.expectation.deniedStatuses.includes(response.statusCode) || graphqlDenied, 0, 0); }
function statusObservation(item: ProtocolSecurityCasePlan, actor: ProtocolActorPlan, result: Http2Result): ProtocolCaseObservation { const shapeMatched = matches(parseJson(result.body.toString("utf8")), item.expectation); return decisionObservation(item, actor, result.statusCode, item.expectation.allowedStatuses.includes(result.statusCode ?? 0) && shapeMatched, item.expectation.deniedStatuses.includes(result.statusCode ?? 0), 0, 0, result.protocol, result.errorCode); }
function decisionObservation(item: ProtocolSecurityCasePlan, actor: ProtocolActorPlan, status: number | undefined, allowed: boolean, denied: boolean, messages: number, events: number, protocol?: string, transportError?: string): ProtocolCaseObservation { if (transportError) return observation(item, actor, "INCONCLUSIVE", safeReason(transportError), status, messages, events, protocol); const observed = allowed ? "ALLOW" : denied ? "DENY" : "UNKNOWN"; const expected = item.expectation.decision; const outcome = observed === "UNKNOWN" ? "INCONCLUSIVE" : expected === "OBSERVE" || observed === expected ? "PASS" : "FAIL"; const reason = outcome === "PASS" ? "PROTOCOL_EXPECTATION_MATCHED" : outcome === "INCONCLUSIVE" ? "PROTOCOL_RESPONSE_UNCLASSIFIED" : expected === "DENY" && observed === "ALLOW" ? "PROTOCOL_AUTHORIZATION_BYPASS" : "PROTOCOL_REQUIRED_ACCESS_DENIED"; return observation(item, actor, outcome, reason, status, messages, events, protocol); }
function observation(item: ProtocolSecurityCasePlan, actor: ProtocolActorPlan, outcome: ProtocolCaseObservation["outcome"], reason: string, statusCode?: number, messageCount = 0, eventCount = 0, negotiatedProtocol?: string, cleanupOutcome?: ProtocolCaseObservation["cleanupOutcome"]): ProtocolCaseObservation { return { caseId: item.id, label: item.label, kind: item.kind, riskClass: item.riskClass, actorAlias: actor.safeAlias, outcome, reason, ...(statusCode !== undefined ? { statusCode } : {}), ...(negotiatedProtocol ? { negotiatedProtocol } : {}), messageCount, eventCount, ...(cleanupOutcome ? { cleanupOutcome } : {}), comparisonFingerprint: item.comparisonFingerprint }; }
function profileFor(context: ScanContext, actor: ProtocolActorPlan): AuthProfile | undefined { return actor.authSlot === "anonymous" ? undefined : actor.authSlot === "primary" ? context.options.authProfile : actor.authSlot === "account_a" ? context.options.authProfileSet?.accountA : context.options.authProfileSet?.accountB; }
function identityBlocked(context: ScanContext, actor: ProtocolActorPlan): boolean { if (actor.authSlot === "anonymous") return false; const report = context.state.getIdentityVerification(); const result = actor.authSlot === "primary" ? report?.primary : actor.authSlot === "account_a" ? report?.accountA : report?.accountB; return !result?.verified; }
function stateChanging(item: ProtocolSecurityCasePlan): item is GraphqlMutationCasePlan | MultipartCasePlan | WebSocketCasePlan | WebSocketAuthStateMachineCasePlan | GrpcCasePlan | StreamingUploadInterruptCasePlan { return item.kind === "GRAPHQL_MUTATION" || item.kind === "STREAMING_UPLOAD_INTERRUPT" || (item.kind === "MULTIPART_UPLOAD" || item.kind === "WEBSOCKET" || item.kind === "WEBSOCKET_AUTH_STATE_MACHINE" || item.kind === "GRPC_UNARY" || item.kind === "GRPC_SERVER_STREAM" || item.kind === "GRPC_CLIENT_STREAM" || item.kind === "GRPC_BIDI_STREAM") && !item.readOnly; }
function expand(value: unknown, secrets: Record<string, string>): unknown { if (Array.isArray(value)) return value.map((v) => expand(v, secrets)); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, expand(v, secrets)])); return typeof value === "string" ? expandString(value, secrets) : value; }
function expandString(value: string, secrets: Record<string, string>): string { return value.replace(/\{\{SECRET:([A-Za-z0-9._-]+)\}\}/g, (_m, name: string) => { if (secrets[name] === undefined) throw new Error("SECRET_REFERENCE_UNAVAILABLE"); return secrets[name]!; }); }
function expandRecord(value: Readonly<Record<string, string>>, secrets: Record<string, string>): Record<string, string> { return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, expandString(v, secrets)])); }
function secretBuffer(value: string | undefined): Buffer | undefined { if (value === undefined) return; if (value.startsWith("base64:")) { const encoded = value.slice(7); const decoded = Buffer.from(encoded, "base64"); if (decoded.toString("base64").replace(/=+$/, "") !== encoded.replace(/=+$/, "")) throw new Error("PAYLOAD_BASE64_INVALID"); return decoded; } return Buffer.from(value, "utf8"); }
function matches(value: unknown, expectation: ProtocolSecurityCasePlan["expectation"]): boolean { if (!expectation.jsonPath) return true; const actual = at(value, expectation.jsonPath); return expectation.equals === undefined ? actual !== undefined : JSON.stringify(actual) === JSON.stringify(expectation.equals); }
function at(value: unknown, path: string): unknown { let current = value; for (const part of path.replace(/\[(\d+)\]/g, ".$1").split(".")) { if (!current || typeof current !== "object") return; current = (current as Record<string, unknown>)[part]; } return current; }
function parseJson(value: string | undefined): unknown { try { return value === undefined ? undefined : JSON.parse(value); } catch { return value; } }
function stableSerialize(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stableSerialize).join(",")}]`; if (value && typeof value === "object") return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${stableSerialize(item)}`).join(",")}}`; return JSON.stringify(value) ?? "undefined"; }
function parseSse(value: string): Array<{ event?: string; value: unknown }> { const blocks = value.split(/\r?\n\r?\n/); blocks.pop(); return blocks.filter(Boolean).map((block) => { let event: string | undefined; const data: string[] = []; for (const line of block.split(/\r?\n/)) { if (line.startsWith("event:")) event = line.slice(6).trim(); if (line.startsWith("data:")) data.push(line.slice(5).trimStart()); } const text = data.join("\n"); return { ...(event ? { event } : {}), value: parseJson(text) }; }); }
function graphqlIncrementalPaths(value: unknown): string[] { if (!value || typeof value !== "object") return []; const record = value as Record<string, unknown>; const direct = Array.isArray(record.path) ? [record.path.map(String).join(".")] : []; const nested = Array.isArray(record.incremental) ? record.incremental.flatMap(graphqlIncrementalPaths) : []; return [...direct, ...nested]; }
function grpcFrame(payload: Buffer): Buffer { const frame = Buffer.alloc(5 + payload.length); frame.writeUInt32BE(payload.length, 1); payload.copy(frame, 5); return frame; }
interface ProtocolTransmission { url: string; method: string; headers: Readonly<Record<string, string>>; body?: string | Buffer; }
async function raw<T>(context: ScanContext, request: ProtocolTransmission, operation: () => Promise<T>): Promise<T | undefined> {
  const audit = (outcome: "sent" | "scope-skipped" | "budget-skipped", error?: string) => context.state.recordRequestAudit({ requestedUrl: "redacted://protocol-security", method: "PROTOCOL", outcome, requestHeaders: {}, redirectChain: [], source: "http", ...(error ? { error } : {}) });
  if (!protocolCapacity(context) || !context.requestLedger.hasCapacity("SCAN")) { audit("budget-skipped", "Protocol request budget exhausted."); return; }
  const denied = await authorizeRaw(context, request); if (denied) { audit("scope-skipped", denied); throw new Error(denied); }
  try { const result = await context.requestLedger.transmit("SCAN", context.options.abortSignal, operation); if (!result.accepted) { audit("budget-skipped", "Protocol request budget exhausted."); return; } audit("sent"); return result.value; } catch (error) { audit("sent", error instanceof Error ? safeReason(error.message) : "PROTOCOL_TRANSPORT_FAILURE"); throw error; }
}
async function rawPair<T>(context: ScanContext, probe: ProtocolTransmission, sentinel: ProtocolTransmission, operation: () => Promise<T>): Promise<T | undefined> {
  const auditPair = (outcome: "sent" | "scope-skipped" | "budget-skipped", error?: string) => { for (const method of ["PROTOCOL_PROBE", "PROTOCOL_SENTINEL"]) context.state.recordRequestAudit({ requestedUrl: "redacted://protocol-security", method, outcome, requestHeaders: {}, redirectChain: [], source: "http", ...(error ? { error } : {}) }); };
  if (!protocolCapacity(context, 2) || !context.requestLedger.hasCapacity("SCAN", 2)) { auditPair("budget-skipped", "Protocol request budget exhausted."); return; }
  const authorization = context.scopeMatcher.authorization; authorization?.requireRemainingBudget(2); await authorization?.waitForRate(context.options.abortSignal, 2);
  for (const request of [probe, sentinel]) { const denied = checkRaw(context, request); if (denied) { auditPair("scope-skipped", denied); throw new Error(denied); } }
  for (const request of [probe, sentinel]) { const denied = context.scopeMatcher.authorization?.reserve(httpScopeUrl(request.url), request.method, request.body); if (denied) { const reason = `TARGET_AUTHORIZATION_${denied}`; auditPair("scope-skipped", reason); throw new Error(reason); } }
  await context.requestLedger.waitForBurst(context.options.abortSignal, 2); if (!context.requestLedger.tryReserve("SCAN")) { auditPair("budget-skipped", "Protocol request budget exhausted."); return; }
  try { const result = await context.requestLedger.transmit("SCAN", context.options.abortSignal, operation, { rateAlreadyReserved: true }); if (!result.accepted) { auditPair("budget-skipped", "Protocol request budget exhausted."); return; } auditPair("sent"); return result.value; } catch (error) { auditPair("sent", error instanceof Error ? safeReason(error.message) : "PROTOCOL_TRANSPORT_FAILURE"); throw error; }
}
async function authorizeRaw(context: ScanContext, request: ProtocolTransmission): Promise<string | undefined> { await context.scopeMatcher.authorization?.waitForRate(context.options.abortSignal); return authorizeRawNow(context, request); }
function authorizeRawNow(context: ScanContext, request: ProtocolTransmission): string | undefined {
  const denied = checkRaw(context, request); if (denied) return denied;
  const authorizationDenied = context.scopeMatcher.authorization?.reserve(httpScopeUrl(request.url), request.method, request.body); return authorizationDenied ? `TARGET_AUTHORIZATION_${authorizationDenied}` : undefined;
}
function checkRaw(context: ScanContext, request: ProtocolTransmission): string | undefined {
  const url = httpScopeUrl(request.url); const scope = context.scopeMatcher.decide(url, request.method, request.body); if (!scope.allowed) return `PROTOCOL_SCOPE_BLOCKED_${scope.reason}`;
  const authorization = context.scopeMatcher.authorization; if (authorization?.plan.bugBounty && !authorization.plan.bugBounty.authenticationPermitted && Object.keys(request.headers).some((name) => !["accept", "content-type", "user-agent", "range", "cache-control", "if-none-match", "if-modified-since", "te"].includes(name.toLowerCase()))) return "TARGET_AUTHORIZATION_AUTHENTICATION_PROHIBITED";
  const denied = authorization?.check(url, request.method, request.body); return denied ? `TARGET_AUTHORIZATION_${denied}` : undefined;
}
function httpScopeUrl(value: string): string { const url = new URL(value); if (url.protocol === "ws:") url.protocol = "http:"; else if (url.protocol === "wss:") url.protocol = "https:"; return url.toString(); }
function entry(item: ProtocolSecurityCasePlan, caseId: string, stage: MutationJournalStage, outcome?: MutationOutcome) { return { caseId, stage, mode: "CONTROLLED_MUTATION" as const, targetOrigin: new URL(item.url).origin, targetIdentityFingerprint: item.comparisonFingerprint, ...(outcome ? { outcome } : {}), note: "Protocol security entry; credentials, payloads, variables, files, and response bodies omitted." }; }
function count(items: readonly ProtocolCaseObservation[], outcome: ProtocolCaseObservation["outcome"]): number { return items.filter((v) => v.outcome === outcome).length; }
function safeReason(value: string): string { const normalized = value.toUpperCase().replace(/[^A-Z0-9_]+/g, "_").slice(0, 100); return normalized || "PROTOCOL_TRANSPORT_FAILURE"; }
function withinRequestLimit(context: ScanContext, value: string | Buffer): boolean { return Buffer.byteLength(value) <= (context.options.plan.protocolSecurity?.maxRequestBytes ?? 0); }
function syntheticResponse(url: string, value: BoundedHttpResult): ActionResponse { return { requestedUrl: url, finalUrl: url, method: "POST", statusCode: value.statusCode, headers: value.headers, bodyHash: createHash("sha256").update(value.body).digest("hex"), responseTimeMs: 0, redirectChain: [], bytesRead: value.body.length, transientBody: value.body }; }
function syntheticProtocolResponse(url: string, statusCode?: number): ActionResponse { return { requestedUrl: url, finalUrl: url, method: "POST", ...(statusCode !== undefined ? { statusCode } : {}), headers: {}, responseTimeMs: 0, redirectChain: [] }; }
function budgetResponse(url: string): ActionResponse { return { requestedUrl: url, finalUrl: url, method: "POST", headers: {}, responseTimeMs: 0, redirectChain: [], error: { name: "RequestBudgetExceeded", message: "Protocol request budget exhausted." } }; }
function findings(report: ProtocolSecurityReport): Finding[] { const scorer = new RiskScorer(); return report.observations.filter((v) => v.outcome === "FAIL" && (v.reason === "PROTOCOL_AUTHORIZATION_BYPASS" || v.reason === "CROSS_PROTOCOL_IDENTITY_MISMATCH" || v.reason === "SUBSCRIPTION_REAUTH_CONTRACT_FAILED" || v.kind.includes("DESYNCHRONIZATION"))).map((v) => { const type = v.kind.includes("GRAPHQL") ? "GraphQL Authorization Issue" as const : v.kind.includes("DESYNCHRONIZATION") ? "HTTP Desynchronization" as const : "API Authorization Issue" as const; const severity = v.kind.includes("DESYNCHRONIZATION") ? "Critical" as const : "High" as const; const base = { id: `protocol-${createHash("sha256").update(v.comparisonFingerprint).digest("hex").slice(0, 12)}`, title: `Protocol security expectation failed: ${v.label}`, type, severity, confidence: "High" as const, url: "redacted://protocol-target", method: v.kind, ...(v.statusCode ? { statusCode: v.statusCode } : {}), evidence: { url: "redacted://protocol-target", method: v.kind, ...(v.statusCode ? { statusCode: v.statusCode } : {}), source: `protocol-security:${v.caseId}`, severityReason: v.reason, reproductionNotes: ["Repeat only the explicit bounded case with the same actor and expectation.", "Message, event, protobuf, upload, credential, variable, and response payloads are intentionally omitted."] }, impact: "A protocol-specific path contradicted its declared authorization or message-isolation contract.", recommendation: "Apply the same authorization policy before protocol upgrade, subscription, resolver, stream, upload, and multiplexed request handling; bind each message to the authenticated principal and request context.", manualTestingSuggestions: ["Review server-side protocol and authorization traces for this exact case."], tags: ["protocol-security", v.kind.toLowerCase()], falsePositiveStatus: "likely-valid" as const, workflowCase: { id: v.caseId, comparisonFingerprint: v.comparisonFingerprint, ...(v.cleanupOutcome ? { cleanupOutcome: v.cleanupOutcome } : {}) }, sourceModule: "protocol-security", timestamp: new Date().toISOString() }; return { ...base, riskScore: scorer.score(base) }; }); }
function disabledReport(): ProtocolSecurityReport { return { enabled: false, plannedCases: 0, executedCases: 0, passedCases: 0, failedCases: 0, inconclusiveCases: 0, blockedCases: 0, observations: [], notes: ["Protocol security testing was not configured."] }; }
