import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { z } from "zod";
import type { RouteCairnScope } from "../../config/ConfigSchema.js";
import type { AuthProfile } from "../../core/auth/AuthProfile.js";
import type { AuthProfileSet } from "../../core/auth/AuthProfileSet.js";
import { AppError } from "../../core/errors/AppError.js";
import { ScopeMatcher } from "../../core/scope/ScopeMatcher.js";
import type { ProtocolSecurityPlan } from "./ProtocolSecurityTypes.js";

const id = z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,119}$/);
const status = z.array(z.number().int().min(100).max(599)).min(1).max(30);
const headers = z.record(z.string().max(1000)).default({});
const expectation = z.object({ decision: z.enum(["ALLOW", "DENY", "OBSERVE"]), allowedStatuses: status.default([200, 201, 202, 204]), deniedStatuses: status.default([400, 401, 403, 404, 405]), messageType: z.string().min(1).max(100).optional(), jsonPath: z.string().min(1).max(160).optional(), equals: z.unknown().optional(), minMessages: z.number().int().min(0).max(50).default(1) }).strict();
const actor = z.object({ id, safeAlias: z.string().min(1).max(80), authSlot: z.enum(["anonymous", "primary", "account_a", "account_b"]), relationship: z.string().min(1).max(120) }).strict();
const authorization = z.object({ environment: z.enum(["LOCAL", "TEST", "STAGING"]), operator: z.string().min(1).max(160), ticket: z.string().min(1).max(160), authorizedAt: z.string().datetime(), expiresAt: z.string().datetime(), confirmation: z.literal("I_AUTHORIZE_PROTOCOL_STATE_CHANGES"), disposableResources: z.literal(true) }).strict();
const desyncAuthorization = authorization.omit({ confirmation: true, disposableResources: true }).extend({ confirmation: z.literal("I_AUTHORIZE_BOUNDED_PROTOCOL_DESYNCHRONIZATION") }).strict();
const cleanup = z.object({ url: z.string().url().max(2048), method: z.enum(["GET", "HEAD", "OPTIONS", "POST", "PATCH", "PUT", "DELETE"]), headers, body: z.unknown().optional(), statusIn: status }).strict();
const base = { id, label: z.string().min(1).max(180), actorId: id, requireVerifiedIdentity: z.boolean().default(true), url: z.string().url().max(2048), headers, expectation };
const webSocket = z.object({ ...base, kind: z.literal("WEBSOCKET"), subprotocols: z.array(z.string().regex(/^[!#$%&'*+\-.0-9A-Z^_`a-z|~]+$/)).max(4).default([]), messages: z.array(z.unknown()).max(16).default([]), maxMessages: z.number().int().min(1).max(50).default(8), readOnly: z.boolean().default(true), authorization: authorization.optional(), cleanup: cleanup.optional() }).strict();
const webSocketState = z.object({ ...base, kind: z.literal("WEBSOCKET_AUTH_STATE_MACHINE"), subprotocols: z.array(z.string().regex(/^[!#$%&'*+\-.0-9A-Z^_`a-z|~]+$/)).max(4).default([]), states: z.array(z.object({ send: z.unknown().optional(), expectType: z.string().min(1).max(100).optional(), expectJsonPath: z.string().min(1).max(160).optional(), equals: z.unknown().optional() }).strict().refine((v) => v.send !== undefined || v.expectType !== undefined || v.expectJsonPath !== undefined, "State must send or expect a message.")).min(1).max(16), maxMessages: z.number().int().min(1).max(50).default(8), readOnly: z.boolean().default(true), authorization: authorization.optional(), cleanup: cleanup.optional() }).strict();
const sse = z.object({ ...base, kind: z.literal("SSE"), method: z.literal("GET").default("GET"), body: z.undefined().optional(), maxEvents: z.number().int().min(1).max(50).default(8) }).strict();
const mutation = z.object({ ...base, kind: z.literal("GRAPHQL_MUTATION"), operationName: z.string().min(1).max(120).optional(), document: z.string().min(1).max(65536), variables: z.record(z.unknown()).default({}), authorization, cleanup }).strict();
const subscription = z.object({ ...base, kind: z.literal("GRAPHQL_SUBSCRIPTION"), transport: z.enum(["GRAPHQL_TRANSPORT_WS", "LEGACY_GRAPHQL_WS", "SSE"]), operationName: z.string().min(1).max(120).optional(), document: z.string().min(1).max(65536), variables: z.record(z.unknown()).default({}), connectionPayload: z.unknown().optional(), maxMessages: z.number().int().min(1).max(50).default(8) }).strict();
const gqlRead = { ...base, operationName: z.string().min(1).max(120).optional(), document: z.string().min(1).max(65536), variables: z.record(z.unknown()).default({}) };
const incremental = z.object({ ...gqlRead, kind: z.literal("GRAPHQL_INCREMENTAL"), maxParts: z.number().int().min(1).max(50).default(8), expectedPaths: z.array(z.string().min(1).max(160)).max(32).default([]) }).strict();
const persisted = z.object({ ...gqlRead, kind: z.literal("GRAPHQL_PERSISTED_QUERY"), sha256Hash: z.string().regex(/^[a-f0-9]{64}$/), negotiation: z.enum(["HASH_ONLY", "REGISTER_THEN_HASH"]).default("HASH_ONLY") }).strict();
const federation = z.object({ ...base, kind: z.literal("GRAPHQL_FEDERATION"), operation: z.enum(["SERVICE_SDL", "ENTITIES"]), representations: z.array(z.record(z.unknown())).min(1).max(16).optional() }).strict();
const subscriptionReauth = z.object({ ...gqlRead, kind: z.literal("GRAPHQL_SUBSCRIPTION_REAUTH"), transport: z.enum(["GRAPHQL_TRANSPORT_WS", "LEGACY_GRAPHQL_WS"]), initialConnectionPayload: z.unknown().optional(), reauthConnectionPayload: z.unknown(), initialDecision: z.enum(["ALLOW", "DENY"]).default("DENY"), maxMessages: z.number().int().min(2).max(50).default(8) }).strict();
const grpc = z.object({ ...base, kind: z.enum(["GRPC_UNARY", "GRPC_SERVER_STREAM", "GRPC_CLIENT_STREAM", "GRPC_BIDI_STREAM"]), payloadSecretRef: id.optional(), payloadSecretRefs: z.array(id).min(1).max(16).optional(), maxMessages: z.number().int().min(1).max(50).default(8), interMessageDelayMs: z.number().int().min(0).max(1000).default(0), readOnly: z.boolean().default(true), authorization: authorization.optional(), cleanup: cleanup.optional() }).strict();
const multipart = z.object({ ...base, kind: z.literal("MULTIPART_UPLOAD"), fields: z.record(z.unknown()).default({}), files: z.array(z.object({ fieldName: id, fileName: z.string().min(1).max(200).refine((value) => !/[\r\n]/.test(value), "Filename contains invalid characters."), contentType: z.string().regex(/^[A-Za-z0-9!#$&^_.+*\/-]{1,160}$/), contentSecretRef: id }).strict()).min(1).max(8), readOnly: z.boolean().default(false), authorization: authorization.optional(), cleanup: cleanup.optional() }).strict();
const http2Auth = z.object({ ...base, kind: z.literal("HTTP2_AUTHORIZATION"), method: z.enum(["GET", "HEAD", "OPTIONS"]) }).strict();
const http2Desync = z.object({ ...base, kind: z.literal("HTTP2_DESYNCHRONIZATION"), method: z.literal("POST"), bodySecretRef: id, declaredLengthDelta: z.union([z.literal(-1), z.literal(1)]), sentinelPath: z.string().startsWith("/").max(1000), authorization: desyncAuthorization }).strict();
const http3Auth = z.object({ ...base, kind: z.literal("HTTP3_AUTHORIZATION"), method: z.enum(["GET", "HEAD", "OPTIONS"]) }).strict();
const http3Desync = z.object({ ...base, kind: z.literal("HTTP3_DESYNCHRONIZATION"), method: z.literal("POST"), bodySecretRef: id, declaredLengthDelta: z.union([z.literal(-1), z.literal(1)]), sentinelPath: z.string().startsWith("/").max(1000), authorization: desyncAuthorization }).strict();
const webTransport = z.object({ ...base, kind: z.literal("WEBTRANSPORT_DATAGRAM"), authenticationMode: z.enum(["NONE", "DATAGRAM"]).default("NONE"), datagramSecretRefs: z.array(id).min(1).max(16), maxDatagrams: z.number().int().min(1).max(50).default(8), readOnly: z.literal(true) }).strict();
const streamingUpload = z.object({ ...base, kind: z.literal("STREAMING_UPLOAD_INTERRUPT"), method: z.enum(["POST", "PUT", "PATCH"]), bodySecretRef: id, chunkBytes: z.number().int().min(1).max(65536), interruptAfterBytes: z.number().int().min(1).max(2 * 1024 * 1024), verificationUrl: z.string().url().max(2048), verificationMethod: z.enum(["GET", "HEAD"]), authorization, cleanup }).strict();
const compression = z.object({ ...base, kind: z.literal("COMPRESSION_BOUNDARY"), method: z.enum(["GET", "POST"]), encoding: z.enum(["gzip", "deflate", "br"]), bodySecretRef: id.optional(), maxExpandedBytes: z.number().int().min(1024).max(16 * 1024 * 1024), readOnly: z.literal(true) }).strict();
const identityLeg = z.object({ protocol: z.enum(["HTTP1", "HTTP2", "HTTP3", "WEBSOCKET", "WEBTRANSPORT", "GRPC"]), url: z.string().url().max(2048), method: z.enum(["GET", "HEAD", "OPTIONS", "POST"]), headers, payloadSecretRef: id.optional(), jsonPath: z.string().min(1).max(160).optional() }).strict();
const identity = z.object({ ...base, kind: z.literal("CROSS_PROTOCOL_IDENTITY"), legs: z.array(identityLeg).min(2).max(5), readOnly: z.literal(true) }).strict();
const proxyHop = z.object({ origin: z.string().url().max(2048), protocol: z.enum(["H1", "H2", "H3"]) }).strict();
const proxyDesync = z.object({ ...base, kind: z.literal("PROXY_CHAIN_DESYNCHRONIZATION"), method: z.literal("POST"), bodySecretRef: id, framing: z.enum(["CONTENT_LENGTH_DELTA", "CL_TE", "TE_CL"]), declaredLengthDelta: z.union([z.literal(-1), z.literal(1)]), sentinelPath: z.string().startsWith("/").max(1000), proxyChain: z.array(proxyHop).min(1).max(4), authorization: desyncAuthorization }).strict();
const grpcUnary = grpc.extend({ kind: z.literal("GRPC_UNARY"), payloadSecretRef: id, payloadSecretRefs: z.undefined().optional() }); const grpcStream = grpc.extend({ kind: z.literal("GRPC_SERVER_STREAM"), payloadSecretRef: id, payloadSecretRefs: z.undefined().optional() }); const grpcClient = grpc.extend({ kind: z.literal("GRPC_CLIENT_STREAM"), payloadSecretRef: z.undefined().optional(), payloadSecretRefs: z.array(id).min(1).max(16) }); const grpcBidi = grpc.extend({ kind: z.literal("GRPC_BIDI_STREAM"), payloadSecretRef: z.undefined().optional(), payloadSecretRefs: z.array(id).min(1).max(16) });
const caseSchema = z.discriminatedUnion("kind", [webSocket, webSocketState, sse, mutation, subscription, incremental, persisted, federation, subscriptionReauth, grpcUnary, grpcStream, grpcClient, grpcBidi, multipart, http2Auth, http2Desync, http3Auth, http3Desync, webTransport, streamingUpload, compression, identity, proxyDesync]);

export const protocolSecurityInputSchema = z.object({ schemaVersion: z.literal(1).default(1), maxRequests: z.number().int().min(1).max(200).default(40), maxRequestBytes: z.number().int().min(1).max(2 * 1024 * 1024).default(256 * 1024), maxResponseBytes: z.number().int().min(1024).max(1024 * 1024).default(65536), maxDurationMs: z.number().int().min(1000).max(60000).default(15000), actors: z.array(actor).min(1).max(8), cases: z.array(caseSchema).min(1).max(100) }).strict();
export type ProtocolSecurityInput = z.infer<typeof protocolSecurityInputSchema>;

export async function loadProtocolSecurityInput(path: string): Promise<ProtocolSecurityInput> {
  const raw = await readFile(path);
  if (raw.byteLength > 1024 * 1024) throw new AppError("Protocol security manifest exceeds 1 MiB.", "PROTOCOL_SECURITY_FILE_TOO_LARGE");
  let value: unknown; try { value = JSON.parse(raw.toString("utf8").replace(/^\uFEFF/, "")); } catch { throw new AppError("Protocol security manifest is not valid JSON.", "PROTOCOL_SECURITY_JSON_INVALID"); }
  const parsed = protocolSecurityInputSchema.safeParse(value); if (!parsed.success) throw new AppError(parsed.error.message, "PROTOCOL_SECURITY_INPUT_INVALID"); return parsed.data;
}

export function planProtocolSecurity(input: ProtocolSecurityInput, context: { target: string; scope: RouteCairnScope; authProfile?: AuthProfile; authProfileSet?: AuthProfileSet }): ProtocolSecurityPlan {
  const parsed = protocolSecurityInputSchema.parse(input); const targetOrigin = new URL(context.target).origin; const matcher = new ScopeMatcher(context.target, context.scope);
  unique(parsed.actors.map((v) => v.id), "actor"); unique(parsed.cases.map((v) => v.id), "case"); const actorIds = new Set(parsed.actors.map((v) => v.id));
  for (const item of parsed.cases) {
    if (!actorIds.has(item.actorId)) fail(`Case ${item.id} references an unknown actor.`, "PROTOCOL_SECURITY_UNKNOWN_ACTOR");
    if (item.kind === "WEBTRANSPORT_DATAGRAM" && parsed.actors.find((value) => value.id === item.actorId)?.authSlot !== "anonymous" && item.authenticationMode !== "DATAGRAM") fail(`Authenticated WebTransport case ${item.id} must declare DATAGRAM authentication.`, "PROTOCOL_SECURITY_WEBTRANSPORT_AUTH_MODE_REQUIRED");
    validateUrl(item.url, item.kind, targetOrigin, matcher, methodFor(item)); if (/\{\{/.test(item.url)) fail(`Case ${item.id} URL must be exact and cannot contain templates.`, "PROTOCOL_SECURITY_URL_TEMPLATE_FORBIDDEN"); validateHeaders(item.headers, item.id); validateTemplates(item.headers, `${item.id}.headers`); validateTemplates(item.expectation.equals, `${item.id}.expectation.equals`); disjoint(item.expectation.allowedStatuses, item.expectation.deniedStatuses);
    if (item.kind === "WEBSOCKET") validateTemplates(item.messages, `${item.id}.messages`);
    if (item.kind === "WEBSOCKET_AUTH_STATE_MACHINE") validateTemplates(item.states, `${item.id}.states`);
    if (item.kind === "SSE") validateTemplates(item.body, `${item.id}.body`);
    if (item.kind === "GRAPHQL_MUTATION" || item.kind === "GRAPHQL_SUBSCRIPTION" || item.kind === "GRAPHQL_INCREMENTAL" || item.kind === "GRAPHQL_PERSISTED_QUERY" || item.kind === "GRAPHQL_SUBSCRIPTION_REAUTH") validateTemplates(item.variables, `${item.id}.variables`);
    if (item.kind === "GRAPHQL_SUBSCRIPTION") validateTemplates(item.connectionPayload, `${item.id}.connectionPayload`);
    if (item.kind === "GRAPHQL_SUBSCRIPTION_REAUTH") { graphql(item.document, "subscription", item.id); validateTemplates(item.initialConnectionPayload, `${item.id}.initialConnectionPayload`); validateTemplates(item.reauthConnectionPayload, `${item.id}.reauthConnectionPayload`); }
    if (item.kind === "GRAPHQL_INCREMENTAL") { graphqlQuery(item.document, item.id); if (!/@(?:defer|stream)\b/.test(item.document)) fail(`GraphQL incremental case ${item.id} must contain @defer or @stream.`, "PROTOCOL_SECURITY_GRAPHQL_INCREMENTAL_DIRECTIVE_REQUIRED"); }
    if (item.kind === "GRAPHQL_PERSISTED_QUERY") { graphqlQuery(item.document, item.id); const actual = createHash("sha256").update(item.document).digest("hex"); if (actual !== item.sha256Hash) fail(`Persisted query hash for ${item.id} does not match the document.`, "PROTOCOL_SECURITY_PERSISTED_QUERY_HASH_MISMATCH"); }
    if (item.kind === "GRAPHQL_FEDERATION") { validateTemplates(item.representations, `${item.id}.representations`); if (item.operation === "ENTITIES" && !item.representations?.length) fail(`Federation entities case ${item.id} requires representations.`, "PROTOCOL_SECURITY_FEDERATION_REPRESENTATIONS_REQUIRED"); }
    if (item.kind === "MULTIPART_UPLOAD") validateTemplates(item.fields, `${item.id}.fields`);
    if (item.kind === "MULTIPART_UPLOAD") for (const [name] of Object.entries(item.fields)) if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,119}$/.test(name)) fail(`Multipart field name in ${item.id} is invalid.`, "PROTOCOL_SECURITY_MULTIPART_FIELD_INVALID");
    if (item.kind === "GRAPHQL_MUTATION") { graphql(item.document, "mutation", item.id); validateApproval(item.authorization); validateCleanup(item.cleanup, targetOrigin, matcher, item.id); }
    if (item.kind === "GRAPHQL_SUBSCRIPTION") { graphql(item.document, "subscription", item.id); const scheme = new URL(item.url).protocol; if (item.transport === "SSE" ? !["http:", "https:"].includes(scheme) : !["ws:", "wss:"].includes(scheme)) fail(`GraphQL subscription ${item.id} URL scheme does not match its transport.`, "PROTOCOL_SECURITY_SUBSCRIPTION_SCHEME_INVALID"); }
    if (item.kind === "MULTIPART_UPLOAD" && !item.readOnly) { if (!item.authorization || !item.cleanup) fail(`State-changing multipart case ${item.id} requires authorization and cleanup.`, "PROTOCOL_SECURITY_MUTATION_SAFETY_REQUIRED"); validateApproval(item.authorization!); validateCleanup(item.cleanup!, targetOrigin, matcher, item.id); }
    if ((item.kind === "WEBSOCKET" || item.kind === "WEBSOCKET_AUTH_STATE_MACHINE" || item.kind === "GRPC_UNARY" || item.kind === "GRPC_SERVER_STREAM" || item.kind === "GRPC_CLIENT_STREAM" || item.kind === "GRPC_BIDI_STREAM") && !item.readOnly) { if (!item.authorization || !item.cleanup) fail(`State-changing protocol case ${item.id} requires authorization and cleanup.`, "PROTOCOL_SECURITY_MUTATION_SAFETY_REQUIRED"); validateApproval(item.authorization); validateCleanup(item.cleanup, targetOrigin, matcher, item.id); }
    if (item.kind === "HTTP2_DESYNCHRONIZATION") { validateDesyncApproval(item.authorization); validateSentinel(item.url, item.sentinelPath, targetOrigin, matcher, item.id); }
    if (item.kind === "HTTP3_DESYNCHRONIZATION") { validateDesyncApproval(item.authorization); validateSentinel(item.url, item.sentinelPath, targetOrigin, matcher, item.id); }
    if (item.kind === "PROXY_CHAIN_DESYNCHRONIZATION") { validateDesyncApproval(item.authorization); validateSentinel(item.url, item.sentinelPath, targetOrigin, matcher, item.id); for (const hop of item.proxyChain) { const origin = new URL(hop.origin); validateUrlSecrets(origin); if (origin.origin !== targetOrigin) fail(`Proxy hop for ${item.id} must use the exact approved target origin.`, "PROTOCOL_SECURITY_PROXY_HOP_OUT_OF_SCOPE"); } }
    if (item.kind === "STREAMING_UPLOAD_INTERRUPT") { validateApproval(item.authorization); validateCleanup(item.cleanup, targetOrigin, matcher, item.id); validateExactUrl(item.verificationUrl, item.verificationMethod, targetOrigin, matcher, item.id); if (item.interruptAfterBytes > parsed.maxRequestBytes) fail(`Upload interruption for ${item.id} exceeds maxRequestBytes.`, "PROTOCOL_SECURITY_UPLOAD_INTERRUPT_LIMIT"); }
    if (item.kind === "CROSS_PROTOCOL_IDENTITY") for (const leg of item.legs) { validateUrl(leg.url, leg.protocol === "WEBSOCKET" ? "WEBSOCKET" : leg.protocol === "WEBTRANSPORT" ? "WEBTRANSPORT_DATAGRAM" : "CROSS_PROTOCOL_IDENTITY", targetOrigin, matcher, leg.method); validateHeaders(leg.headers, `${item.id}.leg`); validateTemplates(leg.headers, `${item.id}.leg.headers`); if ((leg.protocol === "HTTP1" || leg.protocol === "HTTP2" || leg.protocol === "HTTP3") && !["GET", "HEAD", "OPTIONS"].includes(leg.method)) fail(`HTTP identity leg ${item.id} must use a read-only method.`, "PROTOCOL_SECURITY_IDENTITY_METHOD_INVALID"); if (leg.protocol === "HTTP3" && new URL(leg.url).protocol !== "https:") fail(`HTTP/3 identity leg ${item.id} requires HTTPS.`, "PROTOCOL_SECURITY_HTTP3_HTTPS_REQUIRED"); if (leg.protocol === "WEBSOCKET" && (leg.method !== "GET" || !["ws:", "wss:"].includes(new URL(leg.url).protocol))) fail(`WebSocket identity leg ${item.id} requires GET and a WebSocket URL.`, "PROTOCOL_SECURITY_IDENTITY_METHOD_INVALID"); if (leg.protocol === "GRPC" && (leg.method !== "POST" || !leg.payloadSecretRef)) fail(`gRPC identity leg ${item.id} requires POST and one payload fixture.`, "PROTOCOL_SECURITY_IDENTITY_METHOD_INVALID"); if (leg.protocol === "WEBTRANSPORT" && (new URL(leg.url).protocol !== "https:" || leg.method !== "GET" || !leg.payloadSecretRef)) fail(`WebTransport identity leg ${item.id} requires HTTPS, GET, and one payload fixture.`, "PROTOCOL_SECURITY_WEBTRANSPORT_IDENTITY_INVALID"); }
    if ((item.kind === "HTTP3_AUTHORIZATION" || item.kind === "HTTP3_DESYNCHRONIZATION" || item.kind === "WEBTRANSPORT_DATAGRAM") && new URL(item.url).protocol !== "https:") fail(`HTTP/3 case ${item.id} requires HTTPS.`, "PROTOCOL_SECURITY_HTTP3_HTTPS_REQUIRED");
  }
  const requiredRequests = parsed.cases.reduce((total, item) => total + (item.kind === "HTTP2_DESYNCHRONIZATION" || item.kind === "HTTP3_DESYNCHRONIZATION" || item.kind === "STREAMING_UPLOAD_INTERRUPT" ? 2 : item.kind === "PROXY_CHAIN_DESYNCHRONIZATION" ? item.proxyChain.length * 2 : item.kind === "GRAPHQL_PERSISTED_QUERY" && item.negotiation === "REGISTER_THEN_HASH" || item.kind === "GRAPHQL_SUBSCRIPTION_REAUTH" ? 2 : item.kind === "CROSS_PROTOCOL_IDENTITY" ? item.legs.length : 1), 0);
  if (requiredRequests > parsed.maxRequests) fail(`Protocol plan requires ${requiredRequests} requests but maxRequests is ${parsed.maxRequests}.`, "PROTOCOL_SECURITY_REQUEST_BUDGET_INSUFFICIENT");
  const cases = parsed.cases.map((item) => ({ ...item, riskClass: riskClass(item.kind), comparisonFingerprint: createHash("sha256").update("protocol-security-v1\0").update(JSON.stringify(item)).digest("hex") }));
  return deepFreeze({ schemaVersion: 1, enabled: true, targetOrigin, maxRequests: parsed.maxRequests, maxRequestBytes: parsed.maxRequestBytes, maxResponseBytes: parsed.maxResponseBytes, maxDurationMs: parsed.maxDurationMs, actors: parsed.actors, cases, notes: ["Streaming payloads are bounded and represented only by counts and structural outcomes.", "WebTransport credentials, when used, are explicit secret-backed application datagrams because the native client does not inject HTTP authentication headers into Extended CONNECT.", "State changes require expiring non-production authorization and verified cleanup."] } as ProtocolSecurityPlan);
}

function methodFor(item: ProtocolSecurityInput["cases"][number]): string { return "method" in item ? item.method : item.kind === "WEBSOCKET" || item.kind === "WEBSOCKET_AUTH_STATE_MACHINE" || item.kind === "GRAPHQL_SUBSCRIPTION_REAUTH" || (item.kind === "GRAPHQL_SUBSCRIPTION" && item.transport !== "SSE") ? "GET" : "POST"; }
function validateUrl(value: string, kind: string, origin: string, matcher: ScopeMatcher, method: string): void { const u = new URL(value); validateUrlSecrets(u); const ws = kind === "WEBSOCKET" || kind === "WEBSOCKET_AUTH_STATE_MACHINE" || kind === "GRAPHQL_SUBSCRIPTION_REAUTH" || (kind === "GRAPHQL_SUBSCRIPTION" && (u.protocol === "ws:" || u.protocol === "wss:")); const normalizedOrigin = ws ? `${u.protocol === "wss:" ? "https:" : "http:"}//${u.host}` : u.origin; if (normalizedOrigin !== origin) fail("Protocol case URL must use the exact target origin.", "PROTOCOL_SECURITY_CROSS_ORIGIN"); if (ws ? !["ws:", "wss:"].includes(u.protocol) : !["http:", "https:"].includes(u.protocol)) fail("Protocol case URL uses an incompatible scheme.", "PROTOCOL_SECURITY_SCHEME_INVALID"); const scopeUrl = ws ? `${u.protocol === "wss:" ? "https:" : "http:"}//${u.host}${u.pathname}${u.search}` : u.href; const decision = matcher.decide(scopeUrl, method); if (!decision.allowed) fail(`Protocol case is out of scope: ${decision.reason}.`, "PROTOCOL_SECURITY_OUT_OF_SCOPE"); }
function validateExactUrl(value: string, method: string, origin: string, matcher: ScopeMatcher, label: string): void { const url = new URL(value); validateUrlSecrets(url); if (url.origin !== origin || /\{\{/.test(value) || !matcher.decide(value, method).allowed) fail(`URL for ${label} must be exact, in scope, and on the target origin.`, "PROTOCOL_SECURITY_RELATED_URL_OUT_OF_SCOPE"); }
function validateCleanup(value: z.infer<typeof cleanup>, origin: string, matcher: ScopeMatcher, label: string): void { const url = new URL(value.url); validateUrlSecrets(url); if (/\{\{/.test(value.url) || url.origin !== origin || !matcher.decide(value.url, value.method).allowed) fail(`Cleanup for ${label} must be an exact in-scope URL.`, "PROTOCOL_SECURITY_CLEANUP_OUT_OF_SCOPE"); validateHeaders(value.headers, `${label}.cleanup`); validateTemplates(value.headers, `${label}.cleanup.headers`); validateTemplates(value.body, `${label}.cleanup.body`); }
function validateApproval(value: z.infer<typeof authorization>): void { validWindow(value.authorizedAt, value.expiresAt); }
function validateDesyncApproval(value: z.infer<typeof desyncAuthorization>): void { validWindow(value.authorizedAt, value.expiresAt); }
function validWindow(start: string, end: string): void { const a = Date.parse(start), b = Date.parse(end), now = Date.now(); if (!(a <= now && now < b) || b - a > 24 * 60 * 60 * 1000) fail("Authorization must be active and no longer than 24 hours.", "PROTOCOL_SECURITY_AUTHORIZATION_INVALID"); }
function graphql(document: string, operation: "mutation" | "subscription", label: string): void { const stripped = document.replace(/#[^\n\r]*/g, " ").trim(); if (!new RegExp(`^${operation}\\b`, "i").test(stripped)) fail(`GraphQL case ${label} must contain an explicit ${operation} operation.`, "PROTOCOL_SECURITY_GRAPHQL_OPERATION_INVALID"); if (depth(stripped) > 16) fail("GraphQL document exceeds depth 16.", "PROTOCOL_SECURITY_GRAPHQL_DEPTH_EXCEEDED"); }
function graphqlQuery(document: string, label: string): void { const stripped = document.replace(/#[^\n\r]*/g, " ").trim(); if (!/^(?:query\b|\{)/i.test(stripped)) fail(`GraphQL case ${label} must contain an explicit read-only query.`, "PROTOCOL_SECURITY_GRAPHQL_OPERATION_INVALID"); if (depth(stripped) > 16) fail("GraphQL document exceeds depth 16.", "PROTOCOL_SECURITY_GRAPHQL_DEPTH_EXCEEDED"); }
function validateHeaders(value: Record<string, string>, label: string): void { for (const [k, v] of Object.entries(value)) if (/^(authorization|cookie|proxy-authorization|x-api-key|host|connection|proxy-connection|upgrade|expect|trailer|transfer-encoding|content-length|sec-websocket-.+|:.+)$/i.test(k) || /[\r\n]/.test(k + v)) fail(`Headers for ${label} contain authentication material, transport-owned fields, or invalid characters.`, "PROTOCOL_SECURITY_HEADER_INVALID"); }
function validateTemplates(value: unknown, label: string): void { if (Array.isArray(value)) return value.forEach((v, i) => validateTemplates(v, `${label}[${i}]`)); if (value && typeof value === "object") return Object.entries(value as Record<string, unknown>).forEach(([k, v]) => validateTemplates(v, `${label}.${k}`)); if (typeof value !== "string") return; const withoutReferences = value.replace(/\{\{SECRET:[A-Za-z0-9._-]+\}\}/g, ""); if (/\{\{|\}\}/.test(withoutReferences)) fail(`${label} contains an invalid template reference.`, "PROTOCOL_SECURITY_TEMPLATE_INVALID"); if (/(?:bearer\s+|password|api[_-]?key|access[_-]?token|refresh[_-]?token)/i.test(withoutReferences)) fail(`${label} contains literal secret-like material.`, "PROTOCOL_SECURITY_LITERAL_SECRET_FORBIDDEN"); }
function validateSentinel(base: string, path: string, origin: string, matcher: ScopeMatcher, label: string): void { if (/\{\{|\}\}/.test(path)) fail(`Sentinel for ${label} must be exact.`, "PROTOCOL_SECURITY_SENTINEL_INVALID"); const url = new URL(path, base); validateUrlSecrets(url); if (url.origin !== origin || !matcher.decide(url.href, "GET").allowed) fail(`Sentinel for ${label} must be an exact in-scope path on the target origin.`, "PROTOCOL_SECURITY_SENTINEL_OUT_OF_SCOPE"); }
function validateUrlSecrets(url: URL): void { if (url.username || url.password) fail("Protocol URLs cannot contain credentials.", "PROTOCOL_SECURITY_URL_CREDENTIALS_FORBIDDEN"); for (const key of url.searchParams.keys()) if (/(?:token|secret|session|cookie|auth|password|api[_-]?key|jwt|sig(?:nature)?|credential)/i.test(key)) fail("Protocol URLs cannot contain credential-bearing query parameters.", "PROTOCOL_SECURITY_URL_SECRET_FORBIDDEN"); }
function disjoint(a: readonly number[], b: readonly number[]): void { if (a.some((v) => b.includes(v))) fail("Allowed and denied status sets overlap.", "PROTOCOL_SECURITY_STATUS_OVERLAP"); }
function unique(values: string[], label: string): void { if (new Set(values).size !== values.length) fail(`Duplicate ${label} identifiers.`, "PROTOCOL_SECURITY_DUPLICATE_ID"); }
function depth(v: string): number { let d = 0, m = 0; for (const c of v) { if (c === "{") m = Math.max(m, ++d); else if (c === "}") d--; } return m; }
function riskClass(kind: ProtocolSecurityInput["cases"][number]["kind"]): "LOW" | "MODERATE" | "HIGH" | "CRITICAL" { if (kind.includes("DESYNCHRONIZATION")) return "CRITICAL"; if (kind === "STREAMING_UPLOAD_INTERRUPT") return "HIGH"; if (kind === "SSE" || kind === "HTTP2_AUTHORIZATION" || kind === "HTTP3_AUTHORIZATION") return "LOW"; return "MODERATE"; }
function fail(message: string, code: string): never { throw new AppError(message, code); }
function deepFreeze<T>(v: T): T { if (v && typeof v === "object" && !Object.isFrozen(v)) { Object.freeze(v); for (const x of Object.values(v as Record<string, unknown>)) deepFreeze(x); } return v; }
