// Generated by scripts/standards-catalog.ts from hash-verified official sources.
export const officialCatalogSha256 = "891e22e7757ece8d76f883e7960821f579b5c621e8bc01914f8a4a8fb717ec5c";
export const officialCatalogCounts = {"OWASP_WSTG":97,"OWASP_ASVS":345,"OWASP_API_TOP_10":10,"CWE":969,"CAPEC":615} as const;
export const officialSourceLockSha256 = "02728fb53cc7a48884e6f305920f16b5c6d7a27b52400ccd61b5f00580bb2fe3";
export const standardsMappingSha256 = "6af2866307f7dc58a5742b5bec0fdc973c0d045974635b04d952928aeea25c3c";
