import { createHash, createHmac } from "node:crypto";
import { authenticationLifecycleSecrets, authHeadersForProfile, type AuthProfile } from "../../core/auth/AuthProfile.js";
import type { ScanContext } from "../../core/engine/ScanContext.js";
import type { Finding, FindingType } from "../../core/findings/Finding.js";
import { RiskScorer } from "../../core/findings/RiskScorer.js";
import type { HttpRequest, HttpResponse } from "../../core/http/HttpTypes.js";
import type { RequestSafetyBroker } from "../../core/http/RequestSafetyBroker.js";
import { bodyPreviewForAnalysis, headersForAnalysis } from "../../core/http/TransientResponseAnalysis.js";
import { GlobalMutationLock, MutationJournal } from "../../core/offensive/MutationJournal.js";
import type { MutationJournalStage, MutationOutcome } from "../../core/offensive/ControlledMutationTypes.js";
import type { ModuleResult, RouteCairnPlugin } from "../../core/plugins/Plugin.js";
import type { BillingAssertionObservation, BillingCaseObservation, BillingEntitlementReport, BillingStepObservation } from "../../reports/BillingEntitlementReport.js";
import { parseSafeFieldPath, valueAtSafePath } from "../fieldExposureTesting/SafeFieldPath.js";
import { billingEntitlementCategories, type BillingActorPlan, type BillingAssertionPlan, type BillingAuthSlot, type BillingEntitlementCasePlan, type BillingEntitlementPlan, type BillingEndpointPlan, type BillingOutcome, type BillingStepPlan } from "./BillingEntitlementTypes.js";

interface Snapshot { response: HttpResponse; statusCode?: number; json?: unknown; shapeFingerprint: string }
interface StepRuntime { observation: BillingStepObservation; snapshots: Snapshot[] }

export class BillingEntitlementModule implements RouteCairnPlugin {
  public readonly name = "billing-entitlement-security"; public readonly description = "Validates synthetic checkout, billing, subscription, entitlement, and premium-access security contracts without executing real payments."; public readonly phase = "analysis" as const;
  public async run(context: ScanContext): Promise<ModuleResult> { const report = await executeBillingEntitlement(context); return { pluginName: this.name, billingEntitlement: report, findings: findingsFromReport(report), notes: report.notes }; }
}

export async function executeBillingEntitlement(context: ScanContext): Promise<BillingEntitlementReport> {
  const plan = context.options.plan.billingEntitlement; if (!plan) return disabledReport(); const transport = context.createBillingEntitlementHttpClient(plan.maxRequests, plan.maxResponseBytes, plan.maxConcurrency); const journal = context.mutations.journal; const lock = context.mutations.lock(); const observations: BillingCaseObservation[] = [];
  const snapshot = (): BillingEntitlementReport => {
  const coverage = Object.fromEntries(billingEntitlementCategories.map((category) => { const items = observations.filter((item) => item.category === category); return [category, { planned: plan.cases.filter((item) => item.category === category).length, executed: items.filter((item) => item.outcome !== "BLOCKED").length, passed: items.filter((item) => item.outcome === "PASS").length, failed: items.filter((item) => item.outcome === "FAIL").length }]; })) as BillingEntitlementReport["coverage"];
  return { enabled: true, providerKind: plan.provider.kind, providerMode: plan.provider.mode, realPaymentExecution: "FORBIDDEN", plannedCases: plan.cases.length, executedCases: observations.filter((item) => item.outcome !== "BLOCKED").length, passedCases: count(observations, "PASS"), failedCases: count(observations, "FAIL"), inconclusiveCases: count(observations, "INCONCLUSIVE"), blockedCases: count(observations, "BLOCKED"), requestsTransmitted: observations.flatMap((item) => item.steps).reduce((sum, step) => sum + step.attemptsTransmitted, 0), requestBudget: plan.maxRequests, synchronizedGroups: observations.flatMap((item) => item.steps).filter((step) => step.synchronized).length, cleanupRequired: plan.cases.filter((item) => item.cleanupRequired).length, cleanupFailed: observations.filter((item) => item.cleanupOutcome === "CLEANUP_FAILED").length, endpointInventory: plan.endpoints.map((endpoint) => ({ safeAlias: endpoint.safeAlias, kind: endpoint.kind, pathTemplate: endpoint.pathTemplate, allowedOriginCount: endpoint.allowedOrigins.length })), observations, coverage, notes: [...plan.notes, "Operational evidence stores safe endpoint aliases and path templates, status counts, structural fingerprints, proof dimensions, and cleanup state only.", "FAIL requires a contradicted explicit payment-domain contract; missing state, transport ambiguity, unsafe runtime expansion, or unavailable secrets remain blocked or inconclusive."] };
  };
  context.partialModules.set("billing-entitlement", () => { const report = snapshot(); return { pluginName: "billing-entitlement", billingEntitlement: report, findings: findingsFromReport(report) }; });
  for (const testCase of plan.cases) {
    if (context.options.abortSignal?.aborted && !context.options.workflowRecovery) break; if (changesState(testCase) && (context.options.workflowRecovery ? [] : await journal.unresolvedCaseIds()).length) { observations.push(blockedCase(plan, testCase, "UNRESOLVED_PRIOR_CLEANUP")); continue; } try { observations.push(await executeCase(context, transport, journal, lock, plan, testCase)); } finally { await lock.release(); context.finishCaseCleanup(); await context.options.checkpointReport?.(); } }
  return snapshot();
}

async function executeCase(context: ScanContext, transport: RequestSafetyBroker, journal: MutationJournal, lock: GlobalMutationLock, plan: BillingEntitlementPlan, testCase: BillingEntitlementCasePlan): Promise<BillingCaseObservation> {
  const actors = new Map(plan.actors.map((value) => [value.id, value])); const endpoints = new Map(plan.endpoints.map((value) => [value.id, value])); const captures = new Map<string, unknown>(); const runtimes = new Map<string, StepRuntime>(); const observations: BillingStepObservation[] = []; const mainSteps = testCase.steps.filter((step) => step.phase !== "CLEANUP"); const cleanupSteps = testCase.steps.filter((step) => step.phase === "CLEANUP"); const journalCaseId = `billing-entitlement-${testCase.id}`; const notes: string[] = []; let lockHeld = false; let transmittedMutation = Boolean(context.options.workflowRecovery); let stopped: BillingOutcome | undefined;
  const recovering = context.mutations.register("billingEntitlement", journalCaseId, testCase, { captures, runtimes });
  const cleanupTransport = context.createWorkflowCleanupHttpClient(300, context.options.plan.billingEntitlement!.maxResponseBytes);
  if (changesState(testCase)) try { await lock.acquire(journalCaseId); lockHeld = true; await journal.append(journalEntry(plan, testCase, journalCaseId, "AUTHORIZED")); } catch { if (lockHeld) await lock.release().catch(() => undefined); return blockedCase(plan, testCase, "DURABLE_MUTATION_LOCK_OR_JOURNAL_UNAVAILABLE"); }
  try {
    for (const step of recovering ? [] : mainSteps) { if (stopped === "BLOCKED" || stopped === "INCONCLUSIVE") break; const runtime = await executeStep(context, transport, journal, plan, testCase, journalCaseId, actors.get(step.actorId)!, endpoints.get(step.endpointId)!, step, captures, false); runtimes.set(step.id, runtime); observations.push(runtime.observation); if (step.request.stateChanging && runtime.observation.attemptsTransmitted > 0) transmittedMutation = true; await context.mutations.checkpoint(journalCaseId); if (runtime.observation.outcome === "BLOCKED" || runtime.observation.outcome === "INCONCLUSIVE") stopped = runtime.observation.outcome; }
  } finally {
    if (transmittedMutation) for (const step of cleanupSteps) { const runtime = await executeStep(context, cleanupTransport, journal, plan, testCase, journalCaseId, actors.get(step.actorId)!, endpoints.get(step.endpointId)!, step, captures, true); runtimes.set(step.id, runtime); observations.push(runtime.observation); await context.mutations.checkpoint(journalCaseId); }
  }
  const mainAssertions = testCase.assertions.filter((value) => value.scope === "MAIN").map((value) => evaluateAssertion(value, captures, runtimes, context)); const cleanupAssertions = transmittedMutation ? testCase.assertions.filter((value) => value.scope === "CLEANUP").map((value) => evaluateAssertion(value, captures, runtimes, context)) : []; const cleanupObservations = observations.filter((step) => step.phase === "CLEANUP"); let cleanupOutcome: BillingCaseObservation["cleanupOutcome"] = !testCase.cleanupRequired ? "NOT_REQUIRED" : !transmittedMutation ? "CLEANUP_NOT_REACHED" : cleanupObservations.length === cleanupSteps.length && cleanupObservations.every((step) => step.outcome === "PASS") && cleanupAssertions.every((value) => value.outcome === "PASS") ? "ROLLBACK_VERIFIED" : "CLEANUP_FAILED";
  const mainObservations = observations.filter((step) => step.phase !== "CLEANUP"); const outcome: BillingOutcome = mainObservations.some((step) => step.outcome === "BLOCKED") ? "BLOCKED" : mainObservations.some((step) => step.outcome === "INCONCLUSIVE") || mainAssertions.some((value) => value.outcome === "INCONCLUSIVE") ? "INCONCLUSIVE" : mainObservations.some((step) => step.outcome === "FAIL") || mainAssertions.some((value) => value.outcome === "FAIL") ? "FAIL" : "PASS";
  if (lockHeld) { try { const stage: MutationJournalStage = !transmittedMutation ? "SEALED" : cleanupOutcome === "ROLLBACK_VERIFIED" ? "ROLLBACK_VERIFIED" : "CLEANUP_FAILED"; const mutationOutcome: MutationOutcome = !transmittedMutation ? "BLOCKED_BY_SAFETY" : cleanupOutcome === "ROLLBACK_VERIFIED" ? "ROLLBACK_VERIFIED" : "CLEANUP_FAILED"; await journal.append(journalEntry(plan, testCase, journalCaseId, stage, mutationOutcome)); } catch { if (transmittedMutation) cleanupOutcome = "CLEANUP_FAILED"; notes.push("The billing fixture cleanup journal could not be durably sealed."); } finally { await lock.release().catch(() => notes.push("The global mutation lock could not be removed automatically.")); } }
  if (cleanupOutcome === "CLEANUP_FAILED") notes.push("Synthetic billing fixture cleanup failed; the fixture must not be reused until reconciled."); captures.clear(); runtimes.clear(); return { caseId: testCase.id, label: testCase.label, category: testCase.category, outcome, cleanupOutcome, comparisonFingerprint: testCase.comparisonFingerprint, actorAliases: [...new Set(testCase.steps.map((step) => actors.get(step.actorId)!.safeAlias))], endpointAliases: [...new Set(testCase.steps.map((step) => endpoints.get(step.endpointId)!.safeAlias))], steps: observations, assertions: mainAssertions, cleanupAssertions, notes };
}

async function executeStep(context: ScanContext, transport: RequestSafetyBroker, journal: MutationJournal, plan: BillingEntitlementPlan, testCase: BillingEntitlementCasePlan, journalCaseId: string, actor: BillingActorPlan, endpoint: BillingEndpointPlan, step: BillingStepPlan, captures: Map<string, unknown>, cleanupDuty: boolean): Promise<StepRuntime> {
  if (step.request.stateChanging && !cleanupDuty && !authorizationValid(testCase)) return emptyRuntime(step, actor, endpoint, "BLOCKED", "AUTHORIZATION_EXPIRED_AT_EXECUTION"); const prepared = prepareRequest(context, plan, actor, step, captures); if (!prepared) return emptyRuntime(step, actor, endpoint, "BLOCKED", "SECRET_REFERENCE_OR_SYNTHETIC_BOUNDARY_FAILED");
  if (step.request.stateChanging) try { for (let attempt = 0; attempt < step.execution.attempts; attempt += 1) await journal.append({ ...journalEntry(plan, testCase, journalCaseId, cleanupDuty ? "ROLLBACK_SENT" : "MUTATION_ARMED"), requestMethod: prepared.method, requestUrl: `redacted://billing${endpoint.pathTemplate}`, ...(prepared.body ? { requestBodyAttestation: journal.attestBody(prepared.body) } : {}), note: `Synthetic billing fixture ${step.operation}; attempt ${attempt + 1}; body, identifiers, and provider material omitted.` }); } catch { return emptyRuntime(step, actor, endpoint, "BLOCKED", "MUTATION_INTENT_NOT_DURABLE"); }
  let responses: HttpResponse[] = []; let dispatchSkewMs: number | undefined;
  try { if (step.execution.mode === "SYNCHRONIZED") { const result = await transport.sendSynchronizedMutations(Array.from({ length: step.execution.attempts }, () => ({ ...prepared, headers: { ...prepared.headers } }))); responses = result.responses; dispatchSkewMs = result.dispatchSkewMs; } else for (let attempt = 0; attempt < step.execution.attempts; attempt += 1) responses.push(await transport.send({ ...prepared, headers: { ...prepared.headers } })); } catch { return emptyRuntime(step, actor, endpoint, step.request.stateChanging ? "INCONCLUSIVE" : "BLOCKED", "TRANSPORT_EXCEPTION_AFTER_POSSIBLE_TRANSMISSION", step.request.stateChanging ? step.execution.attempts : 0); }
  const snapshots = responses.map(snapshotFor); const transmitted = responses.filter(potentiallyTransmitted).length;
  if (step.request.stateChanging) try { for (const snapshot of snapshots) await journal.append({ ...journalEntry(plan, testCase, journalCaseId, cleanupDuty ? "ROLLBACK_SENT" : "MUTATION_SENT"), requestMethod: prepared.method, requestUrl: `redacted://billing${endpoint.pathTemplate}`, ...(snapshot.statusCode ? { responseStatus: snapshot.statusCode } : {}), responseHash: snapshot.response.bodyHash, note: "Synthetic billing response body and headers omitted." }); } catch { return { ...emptyRuntime(step, actor, endpoint, "INCONCLUSIVE", "POST_TRANSMISSION_JOURNAL_FAILURE", Math.max(transmitted, step.execution.attempts)), snapshots }; }
  const selected = snapshots.at(-1); const recorded: string[] = []; if (step.captures.length) { if (!selected) return { ...emptyRuntime(step, actor, endpoint, "INCONCLUSIVE", "CAPTURE_RESPONSE_UNAVAILABLE", step.request.stateChanging ? step.execution.attempts : 0), snapshots }; for (const capture of step.captures) { const value = capture.source === "JSON" ? valueAtSafePath(selected.json && typeof selected.json === "object" ? selected.json as Record<string, unknown> : undefined, safePath(capture.path)).value : header(selected.response, capture.header); if (value === undefined || value !== null && typeof value === "object") return { ...emptyRuntime(step, actor, endpoint, "INCONCLUSIVE", "CAPTURE_VALUE_UNAVAILABLE", step.request.stateChanging ? Math.max(transmitted, step.execution.attempts) : transmitted), snapshots }; captures.set(capture.name, value); recorded.push(capture.name); } }
  const classified = classify(step, snapshots, dispatchSkewMs); return { snapshots, observation: { stepId: step.id, phase: step.phase, actorAlias: actor.safeAlias, endpointAlias: endpoint.safeAlias, endpointKind: endpoint.kind, operation: step.operation, pathTemplate: endpoint.pathTemplate, method: step.request.method, stateChanging: step.request.stateChanging, syntheticSigned: Boolean(step.request.hmac), attemptsPlanned: step.execution.attempts, attemptsTransmitted: transmitted, synchronized: step.execution.mode === "SYNCHRONIZED" && dispatchSkewMs !== undefined && dispatchSkewMs <= step.execution.maxDispatchSkewMs, ...(dispatchSkewMs !== undefined ? { dispatchSkewMs: Math.round(dispatchSkewMs * 1000) / 1000 } : {}), statusCodes: snapshots.flatMap((value) => value.statusCode === undefined ? [] : [value.statusCode]), authorizedCount: classified.authorized, deniedCount: classified.denied, acceptedCount: classified.accepted, rejectedCount: classified.rejected, capturesRecorded: recorded, responseShapeFingerprints: snapshots.map((value) => value.shapeFingerprint), outcome: classified.outcome, reasonCode: classified.reasonCode } };
}

function prepareRequest(context: ScanContext, plan: BillingEntitlementPlan, actor: BillingActorPlan, step: BillingStepPlan, captures: Map<string, unknown>): HttpRequest | undefined { try { const actorProfile = profileFor(context, actor.authSlot); const secretProfile = profileFor(context, step.request.secretSource); if (actor.authSlot !== "anonymous" && !actorProfile || step.request.secretSource !== "anonymous" && !secretProfile) return undefined; const secrets = secretProfile ? authenticationLifecycleSecrets(secretProfile) : {}; const url = expand(step.request.urlTemplate, secrets, captures); const parsed = new URL(url); if (parsed.origin !== plan.targetOrigin || !context.scopeMatcher.decide(url, step.request.method).allowed || step.request.stateChanging && !pathWithin(parsed.pathname, plan.provider.fixturePathPrefix)) return undefined; const headers: Record<string, string> = { ...(actor.sendAuthentication && actorProfile ? authHeadersForProfile(actorProfile) : {}) }; for (const [name, value] of Object.entries(step.request.headers)) setHeader(headers, name, expand(value, secrets, captures)); if (step.request.stateChanging) { setHeader(headers, "X-RouteCairn-Synthetic-Billing", `${plan.provider.kind}:${plan.provider.mode}`); setHeader(headers, "X-RouteCairn-Real-Payment", "forbidden"); } let body: string | undefined; if (step.request.fields !== undefined) { const fields = expandValue(step.request.fields, secrets, captures); if (step.request.bodyFormat === "FORM") { if (!fields || typeof fields !== "object" || Array.isArray(fields)) return undefined; body = new URLSearchParams(Object.entries(fields as Record<string, unknown>).map(([key, value]) => [key, String(value)] as [string, string])).toString(); setHeader(headers, "Content-Type", "application/x-www-form-urlencoded"); } else { body = JSON.stringify(fields); setHeader(headers, "Content-Type", "application/json"); } } if (step.request.hmac) applyHmac(headers, body ?? "", step.request.hmac, context); return { url, method: step.request.method, headers, ...(body !== undefined ? { body } : {}), skipCache: true, disableRetries: true, disableRedirects: true, retainBodyPreview: true, streamLimitBytes: plan.maxResponseBytes, maxStreamContentLength: plan.maxResponseBytes }; } catch { return undefined; } }
function applyHmac(headers: Record<string, string>, body: string, hmac: NonNullable<BillingStepPlan["request"]["hmac"]>, context: ScanContext): void { const profile = profileFor(context, hmac.secretSource); const secrets = profile ? authenticationLifecycleSecrets(profile) : {}; const key = secrets[hmac.secretRef]; if (!key) throw new Error("key"); let message = body; if (hmac.messageFormat === "TIMESTAMP_DOT_BODY") { const timestamp = secrets[hmac.timestampSecretRef!]; if (!timestamp) throw new Error("timestamp"); setHeader(headers, hmac.timestampHeader!, timestamp); message = `${timestamp}.${body}`; } let signature = createHmac(hmac.algorithm, key).update(message).digest(hmac.encoding === "HEX" ? "hex" : "base64"); if (hmac.tamper) signature = `${signature.slice(0, -1)}${signature.endsWith("a") ? "b" : "a"}`; setHeader(headers, hmac.header, `${hmac.prefix}${signature}`); }
function classify(step: BillingStepPlan, snapshots: Snapshot[], dispatchSkewMs?: number): { outcome: BillingOutcome; reasonCode: string; authorized: number; denied: number; accepted: number; rejected: number } { const statuses = snapshots.flatMap((value) => value.statusCode === undefined ? [] : [value.statusCode]); if (statuses.length !== snapshots.length || snapshots.some((value) => value.response.error)) return { outcome: "INCONCLUSIVE", reasonCode: "RESPONSE_UNCLASSIFIED", authorized: 0, denied: 0, accepted: 0, rejected: 0 }; if (step.execution.mode === "SYNCHRONIZED" && (dispatchSkewMs === undefined || dispatchSkewMs > step.execution.maxDispatchSkewMs)) return { outcome: "INCONCLUSIVE", reasonCode: "DISPATCH_SKEW_EXCEEDED", authorized: 0, denied: 0, accepted: 0, rejected: 0 }; if (!step.expectation) return { outcome: statuses.every((status) => status >= 200 && status < 300) ? "PASS" : "INCONCLUSIVE", reasonCode: statuses.every((status) => status >= 200 && status < 300) ? "OBSERVATION_SUCCEEDED" : "OBSERVATION_STATUS_UNAVAILABLE", authorized: 0, denied: 0, accepted: 0, rejected: 0 }; const expected = step.expectation; const authorized = statuses.filter((status) => expected.allowedStatuses.includes(status)).length; const denied = statuses.filter((status) => expected.deniedStatuses.includes(status)).length; const accepted = statuses.filter((status) => expected.acceptedStatuses.includes(status)).length; const rejected = statuses.filter((status) => expected.rejectedStatuses.includes(status)).length; const authMatched = expected.authorization === "ALLOW" ? authorized === statuses.length : denied === statuses.length; const businessMatched = expected.businessRule === "NOT_EVALUATED" || (expected.businessRule === "ACCEPT" ? accepted === statuses.length : rejected === statuses.length); const unclassified = authorized + denied < statuses.length || expected.businessRule !== "NOT_EVALUATED" && accepted + rejected < statuses.length; return { outcome: unclassified ? "INCONCLUSIVE" : authMatched && businessMatched ? "PASS" : "FAIL", reasonCode: unclassified ? "RESPONSE_UNCLASSIFIED" : authMatched && businessMatched ? "EXPECTATIONS_MATCHED" : !authMatched ? "AUTHORIZATION_EXPECTATION_CONTRADICTED" : "BUSINESS_RULE_EXPECTATION_CONTRADICTED", authorized, denied, accepted, rejected }; }
function evaluateAssertion(assertion: BillingAssertionPlan, captures: Map<string, unknown>, runtimes: Map<string, StepRuntime>, context: ScanContext): BillingAssertionObservation { try { let matched = false; if (assertion.kind === "VALUE_EQUALS_SECRET" || assertion.kind === "VALUE_NOT_EQUALS_SECRET") { const value = required(captures, assertion.capture); const expected = secret(context, assertion.secretSource, assertion.secretRef); if (expected === undefined) throw new Error(); matched = assertion.kind === "VALUE_EQUALS_SECRET" ? String(value) === expected : String(value) !== expected; } else if (assertion.kind === "VALUE_EQUALS_LITERAL") matched = JSON.stringify(required(captures, assertion.capture)) === JSON.stringify(assertion.expected); else if (assertion.kind === "NUMERIC_DELTA" || assertion.kind === "EVENT_COUNT_DELTA") matched = compare(number(captures, assertion.after) - number(captures, assertion.before), assertion.operator, assertion.expected); else if (assertion.kind === "STATE_TRANSITION") matched = assertion.allowed.some((edge) => edge.from === String(required(captures, assertion.before)) && edge.to === String(required(captures, assertion.after))); else if ("stepId" in assertion) { const step = runtimes.get(assertion.stepId)?.observation; if (!step) throw new Error(); const value = assertion.outcome === "ACCEPTED" ? step.acceptedCount : assertion.outcome === "REJECTED" ? step.rejectedCount : assertion.outcome === "AUTHORIZED" ? step.authorizedCount : step.deniedCount; matched = compare(value, assertion.operator, assertion.expected); } return { assertionId: assertion.id, kind: assertion.kind, dimension: assertion.dimension, outcome: matched ? "PASS" : "FAIL", reasonCode: matched ? "PAYMENT_INVARIANT_SATISFIED" : "PAYMENT_INVARIANT_CONTRADICTED" }; } catch { return { assertionId: assertion.id, kind: assertion.kind, dimension: assertion.dimension, outcome: "INCONCLUSIVE", reasonCode: "PAYMENT_INVARIANT_INPUT_UNAVAILABLE" }; } }
function snapshotFor(response: HttpResponse): Snapshot { const body = bodyPreviewForAnalysis(response) ?? ""; let json: unknown; try { json = JSON.parse(body); } catch { json = undefined; } const shape = json === undefined ? `text:${response.contentType ?? "unknown"}` : JSON.stringify(jsonShape(json)); return { response, ...(response.statusCode !== undefined ? { statusCode: response.statusCode } : {}), ...(json !== undefined ? { json } : {}), shapeFingerprint: createHash("sha256").update(shape).digest("hex") }; }
function emptyRuntime(step: BillingStepPlan, actor: BillingActorPlan, endpoint: BillingEndpointPlan, outcome: BillingOutcome, reasonCode: string, attemptsTransmitted = 0): StepRuntime { return { snapshots: [], observation: { stepId: step.id, phase: step.phase, actorAlias: actor.safeAlias, endpointAlias: endpoint.safeAlias, endpointKind: endpoint.kind, operation: step.operation, pathTemplate: endpoint.pathTemplate, method: step.request.method, stateChanging: step.request.stateChanging, syntheticSigned: Boolean(step.request.hmac), attemptsPlanned: step.execution.attempts, attemptsTransmitted, synchronized: false, statusCodes: [], authorizedCount: 0, deniedCount: 0, acceptedCount: 0, rejectedCount: 0, capturesRecorded: [], responseShapeFingerprints: [], outcome, reasonCode } }; }
function authorizationValid(value: BillingEntitlementCasePlan): boolean { const now = Date.now(); return value.authorization.mode === "CONTROLLED_SYNTHETIC_BILLING" && value.authorization.authorizationIdentityConfirmed && value.authorization.changeTicketConfirmed && value.authorization.confirmationAccepted && value.authorization.disposableFixtures && Boolean(value.authorization.authorizedAt) && Date.parse(value.authorization.authorizedAt!) <= now && Boolean(value.authorization.expiresAt) && Date.parse(value.authorization.expiresAt!) > now; }
function changesState(value: BillingEntitlementCasePlan): boolean { return value.steps.some((step) => step.request.stateChanging); }
function profileFor(context: ScanContext, slot: BillingAuthSlot): AuthProfile | undefined { if (slot === "anonymous") return undefined; if (slot === "primary") return context.options.authProfile; return slot === "account_a" ? context.options.authProfileSet?.accountA : context.options.authProfileSet?.accountB; }
function secret(context: ScanContext, slot: BillingAuthSlot, name: string): string | undefined { const profile = profileFor(context, slot); return profile ? authenticationLifecycleSecrets(profile)[name] : undefined; }
function expand(value: string, secrets: Record<string, string>, captures: Map<string, unknown>): string { return value.replace(/\{\{(SECRET|CAPTURE):([A-Za-z0-9._-]+)\}\}/g, (_match, kind: string, name: string) => { const result = kind === "SECRET" ? secrets[name] : captures.get(name); if (result === undefined || result === null || typeof result === "object") throw new Error("missing"); return String(result); }); }
function expandValue(value: unknown, secrets: Record<string, string>, captures: Map<string, unknown>): unknown { if (Array.isArray(value)) return value.map((entry) => expandValue(entry, secrets, captures)); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([key, entry]) => [key, expandValue(entry, secrets, captures)])); return typeof value === "string" ? expand(value, secrets, captures) : value; }
function safePath(path: string): ReturnType<typeof parseSafeFieldPath> { return parseSafeFieldPath(path, { maxDepth: 8, maxArrayIndex: 100, code: "BILLING_ENTITLEMENT_FIELD_PATH_INVALID" }); }
function header(response: HttpResponse, name: string): string | undefined { const value = Object.entries(headersForAnalysis(response)).find(([key]) => key.toLowerCase() === name.toLowerCase())?.[1]; return typeof value === "string" ? value : value?.join(", "); }
function setHeader(headers: Record<string, string>, name: string, value: string): void { const existing = Object.keys(headers).find((key) => key.toLowerCase() === name.toLowerCase()); headers[existing ?? name] = value; }
function pathWithin(pathname: string, prefix: string): boolean { const normalized = prefix.endsWith("/") ? prefix.slice(0, -1) : prefix; return pathname === normalized || pathname.startsWith(`${normalized}/`); }
function required(captures: Map<string, unknown>, name: string): unknown { if (!captures.has(name)) throw new Error("capture"); return captures.get(name); }
function number(captures: Map<string, unknown>, name: string): number { const value = Number(required(captures, name)); if (!Number.isFinite(value)) throw new Error("number"); return value; }
function compare(left: number, operator: "EQ" | "LT" | "LTE" | "GT" | "GTE", right: number): boolean { return operator === "EQ" ? left === right : operator === "LT" ? left < right : operator === "LTE" ? left <= right : operator === "GT" ? left > right : left >= right; }
function jsonShape(value: unknown): unknown { if (Array.isArray(value)) return [value.length ? jsonShape(value[0]) : "empty"]; if (value && typeof value === "object") return Object.fromEntries(Object.keys(value as Record<string, unknown>).sort().map((key) => [key, jsonShape((value as Record<string, unknown>)[key])])); return value === null ? "null" : typeof value; }
function potentiallyTransmitted(response: HttpResponse): boolean { return !["RequestBudgetExceeded", "OutOfScopeRequest", "ControlledMutationBlocked"].includes(response.error?.name ?? ""); }
function count(values: BillingCaseObservation[], outcome: BillingOutcome): number { return values.filter((value) => value.outcome === outcome).length; }
function journalEntry(plan: BillingEntitlementPlan, value: BillingEntitlementCasePlan, caseId: string, stage: MutationJournalStage, outcome?: MutationOutcome) { return { caseId, stage, mode: "CONTROLLED_MUTATION" as const, targetOrigin: plan.targetOrigin, targetIdentityFingerprint: value.comparisonFingerprint, ...(outcome ? { outcome } : {}), note: "Synthetic billing fixture entry; no payment instruments, provider credentials, event values, identities, request bodies, or response bodies retained." }; }
function blockedCase(plan: BillingEntitlementPlan, value: BillingEntitlementCasePlan, reason: string): BillingCaseObservation { const actors = new Map(plan.actors.map((item) => [item.id, item])); const endpoints = new Map(plan.endpoints.map((item) => [item.id, item])); return { caseId: value.id, label: value.label, category: value.category, outcome: "BLOCKED", cleanupOutcome: "CLEANUP_NOT_REACHED", comparisonFingerprint: value.comparisonFingerprint, actorAliases: [...new Set(value.steps.map((step) => actors.get(step.actorId)?.safeAlias ?? "unknown"))], endpointAliases: [...new Set(value.steps.map((step) => endpoints.get(step.endpointId)?.safeAlias ?? "unknown"))], steps: [], assertions: [], cleanupAssertions: [], notes: [reason] }; }
function findingType(category: BillingEntitlementCasePlan["category"]): FindingType { if (["CLIENT_PRICE_MANIPULATION", "PRODUCT_PLAN_SUBSTITUTION"].includes(category)) return "Checkout Integrity Issue"; if (["DUPLICATE_WEBHOOK_PROCESSING", "REPLAYED_PAYMENT_EVENT"].includes(category)) return "Payment Event Idempotency Issue"; if (category === "PAYMENT_EVENT_RACE") return "Payment Event Race Condition"; if (["CROSS_ACCOUNT_PREMIUM_ACCESS", "SUBSCRIPTION_OWNERSHIP_CONFUSION"].includes(category)) return "Premium Access Authorization Issue"; if (["CANCELLATION_ENTITLEMENT_PERSISTENCE", "REFUND_DOWNGRADE_CONSISTENCY"].includes(category)) return "Subscription State Consistency Issue"; return "Payment Entitlement Issue"; }
function findingsFromReport(report: BillingEntitlementReport): Finding[] { const scorer = new RiskScorer(); return report.observations.filter((value) => value.outcome === "FAIL").map((value) => { const failed = value.steps.find((step) => step.outcome === "FAIL") ?? value.steps.find((step) => step.phase === "ACTION"); const type = findingType(value.category); const base = { id: `finding-${createHash("sha1").update(`billing:${value.comparisonFingerprint}`).digest("hex").slice(0, 12)}`, title: `${value.category.toLowerCase().replace(/_/g, " ")} contract was contradicted`, type, severity: "High" as const, confidence: "High" as const, url: failed ? `redacted://billing${failed.pathTemplate}` : "redacted://billing", method: failed?.method ?? "N/A", ...(failed?.statusCodes[0] ? { statusCode: failed.statusCodes[0] } : {}), evidence: { url: failed ? `redacted://billing${failed.pathTemplate}` : "redacted://billing", method: failed?.method ?? "N/A", ...(failed?.statusCodes[0] ? { statusCode: failed.statusCodes[0] } : {}), source: `billing-entitlement-security:${value.caseId}`, severityReason: `Explicit ${value.category} synthetic billing contract was contradicted.`, reproductionNotes: [`Comparison fingerprint ${value.comparisonFingerprint}.`, "Only a test-provider fixture was exercised; payment instruments, provider credentials, request/response values, account identifiers, and signatures are absent."] }, impact: "A billing or subscription workflow may grant incorrect entitlement, accept manipulated commercial terms, process a payment event more than once, or expose premium state across account boundaries.", recommendation: "Derive commercial terms and entitlement from authoritative server-side product and verified payment state, enforce ownership and atomic idempotency, reconcile cancellation/refund transitions, and retain this synthetic case as a regression test.", manualTestingSuggestions: ["Reconcile the disposable billing fixture before reuse.", "Repeat only this bounded synthetic case after remediation."], tags: ["billing-entitlement-security", value.category.toLowerCase()], falsePositiveStatus: "likely-valid" as const, workflowCase: { id: value.caseId, comparisonFingerprint: value.comparisonFingerprint, cleanupOutcome: value.cleanupOutcome }, sourceModule: "billing-entitlement-security", timestamp: new Date().toISOString() }; return { ...base, riskScore: scorer.score(base) }; }); }
function disabledReport(): BillingEntitlementReport { return { enabled: false, realPaymentExecution: "FORBIDDEN", plannedCases: 0, executedCases: 0, passedCases: 0, failedCases: 0, inconclusiveCases: 0, blockedCases: 0, requestsTransmitted: 0, requestBudget: 0, synchronizedGroups: 0, cleanupRequired: 0, cleanupFailed: 0, endpointInventory: [], observations: [], coverage: Object.fromEntries(billingEntitlementCategories.map((category) => [category, { planned: 0, executed: 0, passed: 0, failed: 0 }])) as BillingEntitlementReport["coverage"], notes: ["No synthetic billing and entitlement manifest was supplied."] }; }
