import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { z } from "zod";
import type { RouteCairnScope } from "../../config/ConfigSchema.js";
import { authenticationLifecycleSecrets, type AuthProfile } from "../../core/auth/AuthProfile.js";
import type { AuthProfileSet } from "../../core/auth/AuthProfileSet.js";
import { AppError } from "../../core/errors/AppError.js";
import { securityContractFingerprint } from "../../core/comparisons/SecurityContractFingerprint.js";
import { ScopeMatcher } from "../../core/scope/ScopeMatcher.js";
import { parseSafeFieldPath } from "../fieldExposureTesting/SafeFieldPath.js";
import { billingEntitlementCategories, type BillingActorPlan, type BillingAssertionPlan, type BillingAuthSlot, type BillingEntitlementCasePlan, type BillingEntitlementPlan, type BillingProofDimension } from "./BillingEntitlementTypes.js";

const maxFileBytes = 512 * 1024;
const identifier = z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,119}$/);
const authSlot = z.enum(["anonymous", "primary", "account_a", "account_b"]);
const reference = /\{\{(SECRET|CAPTURE):([A-Za-z0-9._-]{1,100})\}\}/g;
const forbiddenHeader = /^(?:host|content-length|connection|transfer-encoding|upgrade|expect|te|trailer|x-routecairn-synthetic-billing|x-routecairn-real-payment)$/i;
const forbiddenInstrument = /(?:^|[_-])(?:card(?:number)?|pan|cvv|cvc|payment[_-]?method|payment[_-]?token|confirmation[_-]?token|client[_-]?secret|bank[_-]?account|iban|routing[_-]?number|cryptogram)(?:$|[_-])/i;
const sensitiveKey = /(?:price|amount|currency|product|plan|subscription|payment|transaction|event|customer|account|tenant|owner|entitlement|token|secret|credential|authorization|idempotency|email|user(?:id)?)/i;
const providerSchema = z.object({ kind: z.enum(["STRIPE_TEST", "ADYEN_TEST", "BRAINTREE_SANDBOX", "PAYPAL_SANDBOX", "PADDLE_SANDBOX", "CUSTOM_SYNTHETIC"]), mode: z.enum(["TEST", "SANDBOX", "LOCAL_EMULATOR"]), fixturePathPrefix: z.string().startsWith("/").max(500), realPaymentExecution: z.literal("FORBIDDEN") }).strict();
const actorSchema = z.object({ id: identifier, safeAlias: z.string().min(1).max(80), authSlot, sendAuthentication: z.boolean().optional(), relationship: z.string().min(1).max(100), principalId: z.string().min(1).max(256).optional(), tenantId: z.string().min(1).max(256).optional() }).strict();
const endpointSchema = z.object({ id: identifier, safeAlias: z.string().min(1).max(100), kind: z.enum(["CHECKOUT_VALIDATION", "SYNTHETIC_WEBHOOK", "ENTITLEMENT_STATE", "SUBSCRIPTION_STATE", "PREMIUM_ACCESS", "FIXTURE_CONTROL"]), pathTemplate: z.string().startsWith("/").max(1000), allowedOrigins: z.array(z.string().url().max(1000)).min(1).max(8) }).strict();
const authorizationSchema = z.object({ mode: z.enum(["OBSERVE_ONLY", "CONTROLLED_SYNTHETIC_BILLING"]), environment: z.enum(["LOCAL", "TEST", "STAGING"]), confirmation: z.literal("I_AUTHORIZE_SYNTHETIC_BILLING_TESTING").optional(), authorizedBy: z.string().min(2).max(160).optional(), changeTicket: z.string().min(1).max(160).optional(), authorizedAt: z.string().datetime().optional(), expiresAt: z.string().datetime().optional(), disposableFixtures: z.boolean().default(false) }).strict();
const hmacSchema = z.object({ kind: z.literal("HMAC"), algorithm: z.enum(["sha256", "sha512"]).default("sha256"), secretSource: authSlot, secretRef: identifier, header: z.string().min(1).max(100), encoding: z.enum(["HEX", "BASE64"]).default("HEX"), prefix: z.string().max(40).default(""), messageFormat: z.enum(["BODY", "TIMESTAMP_DOT_BODY"]).default("BODY"), timestampHeader: z.string().min(1).max(100).optional(), timestampSecretRef: identifier.optional(), tamper: z.boolean().default(false) }).strict();
const requestSchema = z.object({ method: z.enum(["GET", "HEAD", "OPTIONS", "POST", "PATCH", "PUT", "DELETE"]), urlTemplate: z.string().min(1).max(4096), stateChanging: z.boolean().default(false), secretSource: authSlot.default("anonymous"), headers: z.record(z.string().max(8192)).default({}), bodyFormat: z.enum(["JSON", "FORM"]).optional(), fields: z.unknown().optional(), hmac: hmacSchema.optional() }).strict();
const captureSchema = z.discriminatedUnion("source", [z.object({ name: identifier, source: z.literal("JSON"), path: z.string().min(1).max(160) }).strict(), z.object({ name: identifier, source: z.literal("HEADER"), header: z.string().min(1).max(100) }).strict()]);
const executionSchema = z.object({ mode: z.enum(["ONCE", "SEQUENTIAL_DUPLICATE", "SYNCHRONIZED"]).default("ONCE"), attempts: z.number().int().min(1).max(5).default(1), maxDispatchSkewMs: z.number().int().min(1).max(5000).default(250) }).strict().default({});
const expectationSchema = z.object({ authorization: z.enum(["ALLOW", "DENY"]), businessRule: z.enum(["ACCEPT", "REJECT", "NOT_EVALUATED"]), allowedStatuses: z.array(z.number().int().min(100).max(599)).min(1).max(20).default([200, 201, 202, 204, 400, 409, 422]), deniedStatuses: z.array(z.number().int().min(100).max(599)).min(1).max(20).default([401, 403, 404]), acceptedStatuses: z.array(z.number().int().min(100).max(599)).min(1).max(20).default([200, 201, 202, 204]), rejectedStatuses: z.array(z.number().int().min(100).max(599)).min(1).max(20).default([400, 409, 422]) }).strict();
const stepSchema = z.object({ id: identifier, phase: z.enum(["PRE_STATE", "ACTION", "VERIFY", "CLEANUP"]), actorId: identifier, endpointId: identifier, operation: z.enum(["OBSERVE", "CHECKOUT_VALIDATION", "SYNTHETIC_PAYMENT_EVENT", "CANCEL_FIXTURE", "REFUND_FIXTURE", "DOWNGRADE_FIXTURE", "PREMIUM_ACCESS_PROBE", "SUBSCRIPTION_ACCESS_PROBE", "RESET_FIXTURE"]), request: requestSchema, execution: executionSchema, expectation: expectationSchema.optional(), captures: z.array(captureSchema).max(20).default([]) }).strict();
const dimension = z.enum(["PRICE", "PRODUCT", "PLAN", "PAYMENT_VERIFICATION", "ENTITLEMENT", "SUBSCRIPTION_STATUS", "REFUND_STATUS", "OWNER", "ACCESS", "EVENT_COUNT"]);
const assertionBase = { id: identifier, scope: z.enum(["MAIN", "CLEANUP"]), dimension } as const;
const assertionSchema = z.discriminatedUnion("kind", [
  z.object({ ...assertionBase, kind: z.literal("VALUE_EQUALS_SECRET"), capture: identifier, secretSource: authSlot, secretRef: identifier }).strict(),
  z.object({ ...assertionBase, kind: z.literal("VALUE_NOT_EQUALS_SECRET"), capture: identifier, secretSource: authSlot, secretRef: identifier }).strict(),
  z.object({ ...assertionBase, kind: z.literal("VALUE_EQUALS_LITERAL"), capture: identifier, expected: z.union([z.string().max(100), z.number().finite(), z.boolean(), z.null()]) }).strict(),
  z.object({ ...assertionBase, kind: z.enum(["NUMERIC_DELTA", "EVENT_COUNT_DELTA"]), before: identifier, after: identifier, operator: z.enum(["EQ", "LT", "LTE", "GT", "GTE"]), expected: z.number().finite().min(-1e12).max(1e12) }).strict(),
  z.object({ ...assertionBase, kind: z.literal("STATE_TRANSITION"), before: identifier, after: identifier, allowed: z.array(z.object({ from: z.string().min(1).max(100), to: z.string().min(1).max(100) }).strict()).min(1).max(50) }).strict(),
  z.object({ ...assertionBase, kind: z.literal("ACTION_OUTCOME_COUNT"), stepId: identifier, outcome: z.enum(["ACCEPTED", "REJECTED", "AUTHORIZED", "DENIED"]), operator: z.enum(["EQ", "LT", "LTE", "GT", "GTE"]), expected: z.number().int().min(0).max(5) }).strict()
]);
const caseSchema = z.object({ id: identifier, label: z.string().min(1).max(160), category: z.enum(billingEntitlementCategories), authorization: authorizationSchema, cleanupRequired: z.boolean().default(false), steps: z.array(stepSchema).min(1).max(40), assertions: z.array(assertionSchema).min(1).max(40) }).strict();
export const billingEntitlementInputSchema = z.object({ schemaVersion: z.literal(1).default(1), maxCases: z.number().int().min(1).max(30).default(20), maxRequests: z.number().int().min(1).max(300).default(120), maxResponseBytes: z.number().int().min(512).max(262144).default(65536), maxConcurrency: z.number().int().min(2).max(5).default(3), provider: providerSchema, actors: z.array(actorSchema).min(1).max(10), endpoints: z.array(endpointSchema).min(1).max(60), cases: z.array(caseSchema).min(1).max(30) }).strict();
export type BillingEntitlementInput = z.infer<typeof billingEntitlementInputSchema>;
type PlannerContext = { target: string; scope: RouteCairnScope; authProfile?: AuthProfile; authProfileSet?: AuthProfileSet; now?: Date };

export async function loadBillingEntitlementInput(path: string): Promise<BillingEntitlementInput> { const raw = await readFile(path); if (raw.byteLength > maxFileBytes) throw new AppError("Billing manifest exceeds 512 KiB.", "BILLING_ENTITLEMENT_FILE_TOO_LARGE"); let value: unknown; try { value = JSON.parse(raw.toString("utf8").replace(/^\uFEFF/, "")); } catch { throw new AppError("Billing manifest is not valid JSON.", "BILLING_ENTITLEMENT_JSON_INVALID"); } assertSafeObject(value); const parsed = billingEntitlementInputSchema.safeParse(value); if (!parsed.success) throw new AppError(parsed.error.message, "BILLING_ENTITLEMENT_INPUT_INVALID"); return parsed.data; }

export function planBillingEntitlement(input: BillingEntitlementInput, context: PlannerContext): BillingEntitlementPlan {
  assertSafeObject(input); const parsed = billingEntitlementInputSchema.parse(input); const origin = new URL(context.target).origin; const matcher = new ScopeMatcher(context.target, context.scope); const profiles = profileMap(context); const now = context.now ?? new Date();
  if (parsed.cases.length > parsed.maxCases) throw new AppError("Billing cases exceed maxCases.", "BILLING_ENTITLEMENT_LIMIT_EXCEEDED"); validateProvider(parsed.provider.fixturePathPrefix);
  unique(parsed.actors.map((value) => value.id), "actor"); unique(parsed.endpoints.map((value) => value.id), "endpoint"); unique(parsed.cases.map((value) => value.id), "case"); validateActorIsolation(parsed.actors, profiles);
  const actors = parsed.actors.map((value): BillingActorPlan => { safeLabel(value.safeAlias, `actor ${value.id}`); safeLabel(value.relationship, `actor ${value.id} relationship`); const profile = profiles[value.authSlot]; const sendAuthentication = value.sendAuthentication ?? value.authSlot !== "anonymous"; if (value.authSlot === "anonymous" && sendAuthentication) throw new AppError(`Anonymous actor ${value.id} cannot authenticate.`, "BILLING_ENTITLEMENT_ACTOR_INVALID"); if (value.authSlot !== "anonymous" && !profile) throw new AppError(`Actor ${value.id} requires a profile.`, "BILLING_ENTITLEMENT_CREDENTIAL_REQUIRED"); if (value.principalId && profile?.principalId && value.principalId !== profile.principalId) throw new AppError(`Actor ${value.id} principal differs from its profile.`, "BILLING_ENTITLEMENT_IDENTITY_MISMATCH"); if (value.tenantId && profile?.tenantId && value.tenantId !== profile.tenantId) throw new AppError(`Actor ${value.id} tenant differs from its profile.`, "BILLING_ENTITLEMENT_IDENTITY_MISMATCH"); const principal = value.principalId ?? profile?.principalId; const tenant = value.tenantId ?? profile?.tenantId; return { id: value.id, safeAlias: value.safeAlias, authSlot: value.authSlot, sendAuthentication, relationship: value.relationship, ...(principal ? { principalFingerprint: digest(`principal\0${principal}`) } : {}), ...(tenant ? { tenantFingerprint: digest(`tenant\0${tenant}`) } : {}) }; });
  const actorById = new Map(actors.map((value) => [value.id, value]));
  const endpoints = parsed.endpoints.map((value) => { safeLabel(value.safeAlias, `endpoint ${value.id}`); if (/[?#\r\n\0]/.test(value.pathTemplate) || /\.\.(?:\/|\\)/.test(value.pathTemplate)) throw new AppError(`Endpoint ${value.id} has an unsafe path template.`, "BILLING_ENTITLEMENT_PATH_INVALID"); const allowedOrigins = [...new Set(value.allowedOrigins.map(normalizeOrigin))]; if (allowedOrigins.some((value) => value !== origin || !matcher.decide(`${value}/`, "GET").allowed)) throw new AppError(`Endpoint ${value.id} must use the exact owned target origin.`, "BILLING_ENTITLEMENT_ORIGIN_INVALID"); return { ...value, allowedOrigins }; });
  const endpointById = new Map(endpoints.map((value) => [value.id, value])); let requestCount = 0;
  const cases = parsed.cases.map((value): BillingEntitlementCasePlan => { safeLabel(value.label, `case ${value.id}`); requestCount += value.steps.reduce((sum, step) => sum + step.execution.attempts, 0); validateCase(value, parsed.provider.fixturePathPrefix, actorById, endpointById, profiles, matcher, origin, parsed.maxConcurrency, now); const authorization = { mode: value.authorization.mode, environment: value.authorization.environment, authorizationIdentityConfirmed: Boolean(value.authorization.authorizedBy), changeTicketConfirmed: Boolean(value.authorization.changeTicket), ...(value.authorization.authorizedAt ? { authorizedAt: value.authorization.authorizedAt } : {}), ...(value.authorization.expiresAt ? { expiresAt: value.authorization.expiresAt } : {}), disposableFixtures: value.authorization.disposableFixtures, confirmationAccepted: value.authorization.confirmation === "I_AUTHORIZE_SYNTHETIC_BILLING_TESTING" }; return { id: value.id, label: value.label, category: value.category, authorization, cleanupRequired: value.cleanupRequired, steps: JSON.parse(JSON.stringify(value.steps)) as BillingEntitlementCasePlan["steps"], assertions: JSON.parse(JSON.stringify(value.assertions)) as BillingAssertionPlan[], comparisonFingerprint: caseFingerprint(value, actors, endpoints, parsed.provider) }; });
  if (requestCount > parsed.maxRequests) throw new AppError(`Billing plan requires ${requestCount} requests, exceeding maxRequests.`, "BILLING_ENTITLEMENT_LIMIT_EXCEEDED");
  return { schemaVersion: 1, enabled: true, targetOrigin: origin, maxCases: parsed.maxCases, maxRequests: parsed.maxRequests, maxResponseBytes: parsed.maxResponseBytes, maxConcurrency: parsed.maxConcurrency, provider: parsed.provider, actors, endpoints, cases, notes: ["This engine can call only exact owned application fixture paths using a test, sandbox, local-emulator, or custom-synthetic provider declaration.", "Real payment execution, payment instruments, provider API calls, checkout redirects, charge confirmation, capture, and settlement are forbidden by both planning and execution.", "Synthetic events may be signed over the exact serialized body in case-local memory; all mutations are journaled, never retried, never redirected, bounded to five attempts, and require verified fixture cleanup."] };
}

function validateCase(value: z.infer<typeof caseSchema>, fixturePrefix: string, actors: ReadonlyMap<string, BillingActorPlan>, endpoints: ReadonlyMap<string, BillingEntitlementPlan["endpoints"][number]>, profiles: Readonly<Record<BillingAuthSlot, AuthProfile | undefined>>, matcher: ScopeMatcher, origin: string, maxConcurrency: number, now: Date): void {
  unique(value.steps.map((step) => step.id), `step in ${value.id}`); unique(value.assertions.map((assertion) => assertion.id), `assertion in ${value.id}`); const captures = new Map<string, "MAIN" | "CLEANUP">(); const steps = new Map<string, z.infer<typeof stepSchema>>(); let mutationCount = 0; let cleanupStarted = false;
  for (const step of value.steps) {
    const actor = actors.get(step.actorId); const endpoint = endpoints.get(step.endpointId); if (!actor) throw new AppError(`Unknown actor in ${value.id}/${step.id}.`, "BILLING_ENTITLEMENT_ACTOR_INVALID"); if (!endpoint) throw new AppError(`Unknown endpoint in ${value.id}/${step.id}.`, "BILLING_ENTITLEMENT_ENDPOINT_INVALID"); if (step.phase === "CLEANUP") cleanupStarted = true; else if (cleanupStarted) throw new AppError(`Cleanup steps must be last in ${value.id}.`, "BILLING_ENTITLEMENT_CLEANUP_INVALID");
    validateOperation(step, endpoint.kind); validateExecution(step, value.category, maxConcurrency); validateRequest(step.request, step.operation, step.phase, fixturePrefix, endpoint.allowedOrigins, matcher, origin, profiles, captures, `${value.id}/${step.id}`); validateExpectation(step, `${value.id}/${step.id}`); if (step.request.stateChanging) mutationCount += step.execution.attempts;
    for (const capture of step.captures) { if (captures.has(capture.name)) throw new AppError(`Capture ${capture.name} is assigned twice.`, "BILLING_ENTITLEMENT_CAPTURE_INVALID"); if (capture.source === "JSON") safePath(capture.path); captures.set(capture.name, step.phase === "CLEANUP" ? "CLEANUP" : "MAIN"); } steps.set(step.id, step);
  }
  for (const assertion of value.assertions) validateAssertion(assertion, captures, steps, profiles, value.id);
  const mainDimensions = new Set(value.assertions.filter((assertion) => assertion.scope === "MAIN").map((assertion) => assertion.dimension)); validateCategory(value, mainDimensions, actors);
  if (mutationCount) validateAuthorization(value, now); else if (value.authorization.mode !== "OBSERVE_ONLY") throw new AppError(`Read-only case ${value.id} must use OBSERVE_ONLY.`, "BILLING_ENTITLEMENT_AUTHORIZATION_INVALID");
  const cleanup = value.steps.filter((step) => step.phase === "CLEANUP"); if (mutationCount && (!value.cleanupRequired || !cleanup.some((step) => step.request.stateChanging) || !cleanup.some((step) => !step.request.stateChanging) || !value.assertions.some((assertion) => assertion.scope === "CLEANUP"))) throw new AppError(`Mutating case ${value.id} requires cleanup mutation, cleanup verification, and cleanup assertion.`, "BILLING_ENTITLEMENT_CLEANUP_REQUIRED"); if (!mutationCount && (value.cleanupRequired || cleanup.length || value.assertions.some((assertion) => assertion.scope === "CLEANUP"))) throw new AppError(`Read-only case ${value.id} cannot declare cleanup.`, "BILLING_ENTITLEMENT_CLEANUP_INVALID");
}
function validateProvider(prefix: string): void { if (prefix === "/" || /[?#\r\n\0]/.test(prefix) || /\.\.(?:\/|\\)/.test(prefix) || !/(?:test|fixture|sandbox|emulat|synthetic)/i.test(prefix)) throw new AppError("fixturePathPrefix must be a dedicated test, fixture, sandbox, emulator, or synthetic path.", "BILLING_ENTITLEMENT_PROVIDER_INVALID"); }
function validateOperation(step: z.infer<typeof stepSchema>, kind: string): void { const mapping: Record<string, readonly string[]> = { OBSERVE: ["ENTITLEMENT_STATE", "SUBSCRIPTION_STATE", "PREMIUM_ACCESS", "FIXTURE_CONTROL"], CHECKOUT_VALIDATION: ["CHECKOUT_VALIDATION"], SYNTHETIC_PAYMENT_EVENT: ["SYNTHETIC_WEBHOOK"], CANCEL_FIXTURE: ["FIXTURE_CONTROL", "SUBSCRIPTION_STATE"], REFUND_FIXTURE: ["FIXTURE_CONTROL", "SUBSCRIPTION_STATE"], DOWNGRADE_FIXTURE: ["FIXTURE_CONTROL", "SUBSCRIPTION_STATE"], PREMIUM_ACCESS_PROBE: ["PREMIUM_ACCESS"], SUBSCRIPTION_ACCESS_PROBE: ["SUBSCRIPTION_STATE"], RESET_FIXTURE: ["FIXTURE_CONTROL"] }; if (!mapping[step.operation]?.includes(kind)) throw new AppError(`Operation ${step.operation} cannot target ${kind}.`, "BILLING_ENTITLEMENT_OPERATION_INVALID"); const mutationOperation = ["CHECKOUT_VALIDATION", "SYNTHETIC_PAYMENT_EVENT", "CANCEL_FIXTURE", "REFUND_FIXTURE", "DOWNGRADE_FIXTURE", "RESET_FIXTURE"].includes(step.operation); if (step.request.stateChanging !== mutationOperation) throw new AppError(`Operation ${step.operation} has an invalid mutation declaration.`, "BILLING_ENTITLEMENT_MUTATION_DECLARATION_REQUIRED"); if (step.phase === "PRE_STATE" || step.phase === "VERIFY") { if (step.operation !== "OBSERVE" && !["PREMIUM_ACCESS_PROBE", "SUBSCRIPTION_ACCESS_PROBE"].includes(step.operation)) throw new AppError(`${step.phase} step must be read-only.`, "BILLING_ENTITLEMENT_OPERATION_INVALID"); } if (step.phase === "CLEANUP" && !["RESET_FIXTURE", "OBSERVE"].includes(step.operation)) throw new AppError("Cleanup is limited to fixture reset and verification.", "BILLING_ENTITLEMENT_CLEANUP_INVALID"); }
function validateExecution(step: z.infer<typeof stepSchema>, category: z.infer<typeof caseSchema>["category"], maxConcurrency: number): void { const execution = step.execution; if (execution.mode === "ONCE" && execution.attempts !== 1) throw new AppError(`ONCE step ${step.id} requires one attempt.`, "BILLING_ENTITLEMENT_EXECUTION_INVALID"); if (execution.mode !== "ONCE" && execution.attempts < 2) throw new AppError(`Duplicate step ${step.id} requires at least two attempts.`, "BILLING_ENTITLEMENT_EXECUTION_INVALID"); if (execution.mode === "SYNCHRONIZED" && (!step.request.stateChanging || execution.attempts > maxConcurrency || category !== "PAYMENT_EVENT_RACE")) throw new AppError(`Synchronized step ${step.id} is not a bounded payment-event race.`, "BILLING_ENTITLEMENT_EXECUTION_INVALID"); if (execution.mode !== "SYNCHRONIZED" && category === "PAYMENT_EVENT_RACE" && step.phase === "ACTION") throw new AppError("Payment-event race requires a synchronized action.", "BILLING_ENTITLEMENT_EXECUTION_INVALID"); }
function validateRequest(request: z.infer<typeof requestSchema>, operation: string, phase: string, fixturePrefix: string, origins: readonly string[], matcher: ScopeMatcher, origin: string, profiles: Readonly<Record<BillingAuthSlot, AuthProfile | undefined>>, captures: ReadonlyMap<string, "MAIN" | "CLEANUP">, label: string): void { const unsafe = ["POST", "PATCH", "PUT", "DELETE"].includes(request.method); if (unsafe !== request.stateChanging) throw new AppError(`Request ${label} has an invalid stateChanging declaration.`, "BILLING_ENTITLEMENT_MUTATION_DECLARATION_REQUIRED"); if ((request.fields === undefined) !== (request.bodyFormat === undefined)) throw new AppError(`Request ${label} must declare bodyFormat and fields together.`, "BILLING_ENTITLEMENT_REQUEST_INVALID"); const parsed = templateUrl(request.urlTemplate); if (parsed.origin !== origin || !origins.includes(parsed.origin) || !matcher.decide(parsed.toString(), request.method).allowed) throw new AppError(`Request ${label} is outside the exact owned target origin or scope.`, "BILLING_ENTITLEMENT_SCOPE_INVALID"); if (request.stateChanging && !pathWithin(parsed.pathname, fixturePrefix)) throw new AppError(`Mutation ${label} is outside the dedicated fixture path.`, "BILLING_ENTITLEMENT_REAL_PAYMENT_BOUNDARY"); if (request.stateChanging && request.fields === undefined) throw new AppError(`Mutation ${label} requires an explicit synthetic fixture body.`, "BILLING_ENTITLEMENT_REQUEST_INVALID"); for (const [name, entry] of Object.entries(request.headers)) { if (forbiddenHeader.test(name) || /[\r\n\0]/.test(name + entry)) throw new AppError(`Unsafe or reserved header in ${label}.`, "BILLING_ENTITLEMENT_REQUEST_INVALID"); validateSensitive(name, entry, label); }
  inspectFields(request.fields, label); for (const [name, entry] of parsed.searchParams) validateSensitive(name, entry, label); validateReferences(request, profiles, captures, phase === "CLEANUP" ? "CLEANUP" : "MAIN", label); if (request.hmac) { if (operation !== "SYNTHETIC_PAYMENT_EVENT" || !request.stateChanging || request.method !== "POST" || request.fields === undefined) throw new AppError(`HMAC in ${label} is limited to synthetic POST events.`, "BILLING_ENTITLEMENT_HMAC_INVALID"); const hmac = request.hmac; if (forbiddenHeader.test(hmac.header) || /[\r\n\0]/.test(hmac.header + hmac.prefix + (hmac.timestampHeader ?? "")) || Object.keys(request.headers).some((name) => name.toLowerCase() === hmac.header.toLowerCase())) throw new AppError(`HMAC headers in ${label} are unsafe or duplicated.`, "BILLING_ENTITLEMENT_HMAC_INVALID"); requireSecret(profiles, hmac.secretSource, hmac.secretRef, label); if (hmac.messageFormat === "TIMESTAMP_DOT_BODY") { if (!hmac.timestampHeader || !hmac.timestampSecretRef || forbiddenHeader.test(hmac.timestampHeader)) throw new AppError(`Timestamped HMAC in ${label} is incomplete.`, "BILLING_ENTITLEMENT_HMAC_INVALID"); requireSecret(profiles, hmac.secretSource, hmac.timestampSecretRef, label); } else if (hmac.timestampHeader || hmac.timestampSecretRef) throw new AppError(`Body HMAC in ${label} cannot declare timestamp fields.`, "BILLING_ENTITLEMENT_HMAC_INVALID"); } }
function validateExpectation(step: z.infer<typeof stepSchema>, label: string): void { if (step.phase === "ACTION" && !step.expectation) throw new AppError(`Action ${label} requires an expectation.`, "BILLING_ENTITLEMENT_EXPECTATION_REQUIRED"); if (step.phase !== "ACTION" && step.expectation) throw new AppError(`Only actions may declare expectations in ${label}.`, "BILLING_ENTITLEMENT_EXPECTATION_INVALID"); if (!step.expectation) return; const value = step.expectation; if (value.authorization === "DENY" && value.businessRule !== "NOT_EVALUATED") throw new AppError(`Denied action ${label} cannot claim a business-rule decision.`, "BILLING_ENTITLEMENT_EXPECTATION_INVALID"); if (value.allowedStatuses.some((status) => value.deniedStatuses.includes(status)) || value.acceptedStatuses.some((status) => value.rejectedStatuses.includes(status)) || [...value.acceptedStatuses, ...value.rejectedStatuses].some((status) => !value.allowedStatuses.includes(status))) throw new AppError(`Action ${label} has overlapping or inconsistent status classes.`, "BILLING_ENTITLEMENT_EXPECTATION_INVALID"); }
function validateAssertion(assertion: z.infer<typeof assertionSchema>, captures: ReadonlyMap<string, "MAIN" | "CLEANUP">, steps: ReadonlyMap<string, z.infer<typeof stepSchema>>, profiles: Readonly<Record<BillingAuthSlot, AuthProfile | undefined>>, caseId: string): void { const refs = "capture" in assertion ? [assertion.capture] : "before" in assertion ? [assertion.before, assertion.after] : []; for (const ref of refs) { const captureScope = captures.get(ref); if (!captureScope) throw new AppError(`Assertion ${assertion.id} references an unknown capture.`, "BILLING_ENTITLEMENT_ASSERTION_INVALID"); if (assertion.scope === "MAIN" && captureScope === "CLEANUP") throw new AppError(`Main assertion ${assertion.id} cannot use cleanup state.`, "BILLING_ENTITLEMENT_ASSERTION_INVALID"); if (assertion.scope === "CLEANUP" && captureScope !== "CLEANUP" && !("before" in assertion && ref === assertion.before)) throw new AppError(`Cleanup assertion ${assertion.id} requires cleanup verification state.`, "BILLING_ENTITLEMENT_ASSERTION_INVALID"); } if (assertion.kind === "ACTION_OUTCOME_COUNT" && (!steps.has(assertion.stepId) || steps.get(assertion.stepId)?.phase !== "ACTION")) throw new AppError(`Assertion ${assertion.id} references an unknown action.`, "BILLING_ENTITLEMENT_ASSERTION_INVALID"); if (assertion.kind === "VALUE_EQUALS_SECRET" || assertion.kind === "VALUE_NOT_EQUALS_SECRET") requireSecret(profiles, assertion.secretSource, assertion.secretRef, `${caseId}/${assertion.id}`); if (assertion.kind === "VALUE_EQUALS_LITERAL" && typeof assertion.expected === "string" && (sensitiveKey.test(assertion.dimension) || /@|bearer\s|https?:\/\//i.test(assertion.expected))) throw new AppError(`Assertion ${assertion.id} must use a secret reference for sensitive values.`, "BILLING_ENTITLEMENT_LITERAL_SECRET_REJECTED"); }
function validateCategory(value: z.infer<typeof caseSchema>, dimensions: ReadonlySet<BillingProofDimension>, actors: ReadonlyMap<string, BillingActorPlan>): void { const required: Record<z.infer<typeof caseSchema>["category"], readonly BillingProofDimension[]> = { CLIENT_PRICE_MANIPULATION: ["PRICE"], PRODUCT_PLAN_SUBSTITUTION: ["PRODUCT", "PLAN"], UNVERIFIED_PAYMENT_ENTITLEMENT: ["PAYMENT_VERIFICATION", "ENTITLEMENT"], CANCELLATION_ENTITLEMENT_PERSISTENCE: ["SUBSCRIPTION_STATUS", "ENTITLEMENT"], DUPLICATE_WEBHOOK_PROCESSING: ["EVENT_COUNT"], REPLAYED_PAYMENT_EVENT: ["EVENT_COUNT"], CROSS_ACCOUNT_PREMIUM_ACCESS: ["ACCESS"], REFUND_DOWNGRADE_CONSISTENCY: ["REFUND_STATUS", "ENTITLEMENT"], SUBSCRIPTION_OWNERSHIP_CONFUSION: ["OWNER", "ACCESS"], PAYMENT_EVENT_RACE: ["EVENT_COUNT"] }; if (!required[value.category].some((item) => dimensions.has(item))) throw new AppError(`Case ${value.id} lacks its required authoritative proof dimension.`, "BILLING_ENTITLEMENT_CATEGORY_PROOF_REQUIRED"); const actions = value.steps.filter((step) => step.phase === "ACTION"); const operationRequired: Partial<Record<z.infer<typeof caseSchema>["category"], readonly z.infer<typeof stepSchema>["operation"][]>> = { CLIENT_PRICE_MANIPULATION: ["CHECKOUT_VALIDATION"], PRODUCT_PLAN_SUBSTITUTION: ["CHECKOUT_VALIDATION"], UNVERIFIED_PAYMENT_ENTITLEMENT: ["SYNTHETIC_PAYMENT_EVENT"], CANCELLATION_ENTITLEMENT_PERSISTENCE: ["CANCEL_FIXTURE"], REFUND_DOWNGRADE_CONSISTENCY: ["REFUND_FIXTURE", "DOWNGRADE_FIXTURE"], CROSS_ACCOUNT_PREMIUM_ACCESS: ["PREMIUM_ACCESS_PROBE"], SUBSCRIPTION_OWNERSHIP_CONFUSION: ["SUBSCRIPTION_ACCESS_PROBE"] }; const requiredOperations = operationRequired[value.category]; if (requiredOperations && !actions.some((step) => requiredOperations.includes(step.operation))) throw new AppError(`Case ${value.id} lacks its required billing operation.`, "BILLING_ENTITLEMENT_CATEGORY_ACTION_REQUIRED"); if (["DUPLICATE_WEBHOOK_PROCESSING", "REPLAYED_PAYMENT_EVENT"].includes(value.category) && !actions.some((step) => step.operation === "SYNTHETIC_PAYMENT_EVENT" && step.execution.mode === "SEQUENTIAL_DUPLICATE")) throw new AppError(`Case ${value.id} requires duplicate synthetic events.`, "BILLING_ENTITLEMENT_CATEGORY_ACTION_REQUIRED"); if (value.category === "PAYMENT_EVENT_RACE" && !actions.some((step) => step.operation === "SYNTHETIC_PAYMENT_EVENT" && step.execution.mode === "SYNCHRONIZED")) throw new AppError(`Case ${value.id} requires synchronized synthetic events.`, "BILLING_ENTITLEMENT_CATEGORY_ACTION_REQUIRED"); if (["CROSS_ACCOUNT_PREMIUM_ACCESS", "SUBSCRIPTION_OWNERSHIP_CONFUSION"].includes(value.category)) { const slots = new Set(actions.map((step) => actors.get(step.actorId)?.authSlot)); if (!slots.has("account_a") || !slots.has("account_b")) throw new AppError(`Case ${value.id} requires distinct Account A and Account B actors.`, "BILLING_ENTITLEMENT_ACTOR_MATRIX_REQUIRED"); } }
function validateAuthorization(value: z.infer<typeof caseSchema>, now: Date): void { const auth = value.authorization; if (auth.mode !== "CONTROLLED_SYNTHETIC_BILLING" || auth.confirmation !== "I_AUTHORIZE_SYNTHETIC_BILLING_TESTING" || !auth.authorizedBy || !auth.changeTicket || !auth.authorizedAt || !auth.expiresAt || !auth.disposableFixtures) throw new AppError(`Case ${value.id} lacks controlled synthetic billing authorization.`, "BILLING_ENTITLEMENT_AUTHORIZATION_REQUIRED"); const start = Date.parse(auth.authorizedAt); const end = Date.parse(auth.expiresAt); if (start > now.getTime() || end <= now.getTime() || end <= start) throw new AppError(`Authorization for ${value.id} is not currently valid.`, "BILLING_ENTITLEMENT_AUTHORIZATION_EXPIRED"); }
function validateReferences(request: z.infer<typeof requestSchema>, profiles: Readonly<Record<BillingAuthSlot, AuthProfile | undefined>>, captures: ReadonlyMap<string, "MAIN" | "CLEANUP">, scope: "MAIN" | "CLEANUP", label: string): void { for (const value of stringValues(request)) for (const match of value.matchAll(reference)) { if (match[1] === "SECRET") requireSecret(profiles, request.secretSource, match[2]!, label); else { const captureScope = captures.get(match[2]!); if (!captureScope || (scope === "MAIN" && captureScope === "CLEANUP")) throw new AppError(`Unknown or future capture in ${label}.`, "BILLING_ENTITLEMENT_REFERENCE_INVALID"); } } for (const value of stringValues(request)) { const residual = value.replace(reference, ""); if (/\{\{|\}\}/.test(residual)) throw new AppError(`Malformed template in ${label}.`, "BILLING_ENTITLEMENT_REFERENCE_INVALID"); } }
function inspectFields(value: unknown, label: string, key = ""): void { if (forbiddenInstrument.test(key)) throw new AppError(`Payment instrument field ${key} is forbidden in ${label}.`, "BILLING_ENTITLEMENT_REAL_PAYMENT_BOUNDARY"); if (Array.isArray(value)) { value.forEach((entry) => inspectFields(entry, label, key)); return; } if (value && typeof value === "object") { for (const [child, entry] of Object.entries(value as Record<string, unknown>)) inspectFields(entry, label, child); return; } if (typeof value === "string" && sensitiveKey.test(key)) validateSensitive(key, value, label); }
function validateSensitive(key: string, value: string, label: string): void { if (!sensitiveKey.test(key)) return; const refs = value.match(reference) ?? []; const framing = value.replace(reference, "").trim(); if (!refs.length || !/^(?:Bearer|Basic)?[\s,;:=._-]*$/i.test(framing)) throw new AppError(`Sensitive value ${key} in ${label} must be reference-only.`, "BILLING_ENTITLEMENT_LITERAL_SECRET_REJECTED"); }
function requireSecret(profiles: Readonly<Record<BillingAuthSlot, AuthProfile | undefined>>, slot: BillingAuthSlot, name: string, label: string): void { const profile = profiles[slot]; if (!profile || !Object.prototype.hasOwnProperty.call(authenticationLifecycleSecrets(profile), name)) throw new AppError(`Secret ${name} for ${label} is unavailable from ${slot}.`, "BILLING_ENTITLEMENT_SECRET_REQUIRED"); }
function pathWithin(pathname: string, prefix: string): boolean { const normalized = prefix.endsWith("/") ? prefix.slice(0, -1) : prefix; return pathname === normalized || pathname.startsWith(`${normalized}/`); }
function templateUrl(value: string): URL { try { const parsed = new URL(value.replace(reference, "routecairn-placeholder")); if (!["http:", "https:"].includes(parsed.protocol) || parsed.username || parsed.password) throw new Error(); return parsed; } catch { throw new AppError("Billing URL template is invalid.", "BILLING_ENTITLEMENT_URL_INVALID"); } }
function normalizeOrigin(value: string): string { const parsed = new URL(value); if (!["http:", "https:"].includes(parsed.protocol) || parsed.pathname !== "/" || parsed.search || parsed.hash || parsed.username || parsed.password) throw new AppError("Billing allowed origin must be exact.", "BILLING_ENTITLEMENT_ORIGIN_INVALID"); return parsed.origin; }
function safePath(path: string): void { parseSafeFieldPath(path, { maxDepth: 8, maxArrayIndex: 100, code: "BILLING_ENTITLEMENT_FIELD_PATH_INVALID" }); }
function stringValues(value: unknown): string[] { if (typeof value === "string") return [value]; if (Array.isArray(value)) return value.flatMap(stringValues); if (value && typeof value === "object") return Object.values(value as Record<string, unknown>).flatMap(stringValues); return []; }
function assertSafeObject(value: unknown): void { if (Array.isArray(value)) { value.forEach(assertSafeObject); return; } if (!value || typeof value !== "object") return; for (const [key, child] of Object.entries(value as Record<string, unknown>)) { if (["__proto__", "prototype", "constructor"].includes(key)) throw new AppError(`Unsafe object key ${key}.`, "BILLING_ENTITLEMENT_INPUT_INVALID"); assertSafeObject(child); } }
function profileMap(context: PlannerContext): Readonly<Record<BillingAuthSlot, AuthProfile | undefined>> { return { anonymous: undefined, primary: context.authProfile, account_a: context.authProfileSet?.accountA, account_b: context.authProfileSet?.accountB }; }
function validateActorIsolation(actors: readonly z.infer<typeof actorSchema>[], profiles: Readonly<Record<BillingAuthSlot, AuthProfile | undefined>>): void { const slots = new Set(actors.map((value) => value.authSlot)); if (!slots.has("account_a") || !slots.has("account_b")) return; const left = profiles.account_a; const right = profiles.account_b; if (!left || !right) return; if (left.principalId && right.principalId && left.principalId === right.principalId) throw new AppError("Account A and Account B must declare different principals.", "BILLING_ENTITLEMENT_ACTOR_ISOLATION_REQUIRED"); if (credentialFingerprint(left) === credentialFingerprint(right)) throw new AppError("Account A and Account B must use different authentication material.", "BILLING_ENTITLEMENT_ACTOR_ISOLATION_REQUIRED"); }
function credentialFingerprint(profile: AuthProfile): string { return digest(JSON.stringify({ headers: Object.entries(profile.headers).sort(([a], [b]) => a.localeCompare(b)), cookies: profile.cookies.map((value) => ({ name: value.name, value: value.value, domain: value.domain ?? "", path: value.path ?? "" })).sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b))) })); }
function unique(values: readonly string[], label: string): void { if (new Set(values).size !== values.length) throw new AppError(`Duplicate ${label} identifier.`, "BILLING_ENTITLEMENT_DUPLICATE_ID"); }
function safeLabel(value: string, label: string): void { if (/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value) || /bearer\s|https?:\/\/|[?&=]/i.test(value) || /^[A-Za-z0-9_-]{40,}$/.test(value)) throw new AppError(`${label} appears identifying or secret-like.`, "BILLING_ENTITLEMENT_UNSAFE_LABEL"); }
function digest(value: string): string { return createHash("sha256").update(`routecairn-billing-v1\0${value}`).digest("hex"); }
function caseFingerprint(value: z.infer<typeof caseSchema>, actors: BillingEntitlementPlan["actors"], endpoints: BillingEntitlementPlan["endpoints"], provider: BillingEntitlementPlan["provider"]): string {
  const actorIds = new Set(value.steps.map((step) => step.actorId));
  const endpointIds = new Set(value.steps.map((step) => step.endpointId));
  return securityContractFingerprint("billing-entitlement-security", {
    schemaVersion: 1,
    provider,
    category: value.category,
    actors: actors.filter((actor) => actorIds.has(actor.id)),
    endpoints: endpoints.filter((endpoint) => endpointIds.has(endpoint.id)),
    authorization: value.authorization,
    cleanupRequired: value.cleanupRequired,
    steps: value.steps,
    assertions: value.assertions
  });
}
