import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { z } from "zod";
import type { RouteCairnScope } from "../../config/ConfigSchema.js";
import { authenticationLifecycleSecrets, type AuthProfile } from "../../core/auth/AuthProfile.js";
import type { AuthProfileSet } from "../../core/auth/AuthProfileSet.js";
import { AppError } from "../../core/errors/AppError.js";
import { securityContractFingerprint } from "../../core/comparisons/SecurityContractFingerprint.js";
import { ScopeMatcher } from "../../core/scope/ScopeMatcher.js";
import { parseSafeFieldPath } from "../fieldExposureTesting/SafeFieldPath.js";
import { operationalEndpointCategories, type OperationalActorPlan, type OperationalAuthSlot, type OperationalEndpointCasePlan, type OperationalEndpointSecurityPlan } from "./OperationalEndpointSecurityTypes.js";

const maxFileBytes = 512 * 1024;
const identifier = z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,119}$/);
const authSlot = z.enum(["anonymous", "primary", "account_a", "account_b"]);
const statusList = z.array(z.number().int().min(100).max(599)).min(1).max(30);
const reference = /\{\{(SECRET|CAPTURE):([A-Za-z0-9._-]{1,100})\}\}/g;
const exactCapture = /^\{\{CAPTURE:([A-Za-z0-9._-]{1,100})\}\}$/;
const secretKey = /(?:signature|token|secret|key|credential|authorization|password|amount|currency|product|price|recipient)/i;
const forbiddenHeader = /^(?:host|content-length|connection|transfer-encoding|upgrade|expect|te|trailer)$/i;

const actorSchema = z.object({ id: identifier, safeAlias: z.string().min(1).max(80), authSlot, sendAuthentication: z.boolean().optional(), relationship: z.string().min(1).max(120), principalId: z.string().min(1).max(256).optional(), tenantId: z.string().min(1).max(256).optional() }).strict();
const endpointSchema = z.object({ id: identifier, safeAlias: z.string().min(1).max(100), kind: z.enum(["WEBHOOK", "CRON", "JOB", "INCIDENT", "HEALTH", "ADMIN", "WORKER"]), pathTemplate: z.string().startsWith("/").max(1000), allowedOrigins: z.array(z.string().url().max(1000)).min(1).max(8), declaredWorkloadLimit: z.number().int().min(1).max(100000).optional() }).strict();
const authorizationSchema = z.object({ mode: z.enum(["OBSERVE_ONLY", "CONTROLLED_OPERATIONAL_FLOW"]), environment: z.enum(["LOCAL", "TEST", "STAGING", "PRODUCTION"]), confirmation: z.literal("I_AUTHORIZE_CONTROLLED_OPERATIONAL_ENDPOINT_TESTING").optional(), authorizedBy: z.string().min(2).max(160).optional(), changeTicket: z.string().min(1).max(160).optional(), authorizedAt: z.string().datetime().optional(), expiresAt: z.string().datetime().optional(), disposableTarget: z.boolean().default(false), productionAcknowledged: z.boolean().default(false) }).strict();
const captureSchema = z.discriminatedUnion("source", [z.object({ name: identifier, source: z.literal("JSON"), path: z.string().min(1).max(160) }).strict(), z.object({ name: identifier, source: z.literal("HEADER"), header: z.string().min(1).max(100) }).strict()]);
const assertionSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("STATUS_IN"), values: statusList }).strict(), z.object({ kind: z.literal("STATUS_NOT_IN"), values: statusList }).strict(),
  z.object({ kind: z.literal("DECISION"), expected: z.enum(["ALLOW", "DENY"]), allowedStatuses: statusList.default([200, 201, 202, 204]), deniedStatuses: statusList.default([400, 401, 403, 404, 405, 409, 410, 422, 429]) }).strict(),
  z.object({ kind: z.literal("HEADER_PRESENT"), header: z.string().min(1).max(100) }).strict(), z.object({ kind: z.literal("HEADER_ABSENT"), header: z.string().min(1).max(100) }).strict(),
  z.object({ kind: z.literal("JSON_FIELD_PRESENT"), path: z.string().min(1).max(160) }).strict(), z.object({ kind: z.literal("JSON_FIELD_ABSENT"), path: z.string().min(1).max(160), classification: z.enum(["SECRET", "INTERNAL", "PERSONAL", "OPERATIONAL"]) }).strict(),
  z.object({ kind: z.literal("JSON_EQUALS_SECRET"), path: z.string().min(1).max(160), secretSource: authSlot, secretRef: identifier }).strict(),
  z.object({ kind: z.literal("CAPTURE_EQUALS_SECRET"), capture: identifier, secretSource: authSlot, secretRef: identifier }).strict(), z.object({ kind: z.literal("CAPTURE_NOT_EQUALS_SECRET"), capture: identifier, secretSource: authSlot, secretRef: identifier }).strict(),
  z.object({ kind: z.literal("NUMERIC_DELTA"), before: identifier, after: identifier, operator: z.enum(["EQ", "LTE", "GTE"]), expected: z.number().finite().min(-1e12).max(1e12) }).strict(),
  z.object({ kind: z.literal("BODY_FINGERPRINT"), expectedSha256: z.string().regex(/^[a-f0-9]{64}$/i) }).strict(), z.object({ kind: z.literal("RESPONSE_FINGERPRINT_MATCH"), stepId: identifier }).strict(), z.object({ kind: z.literal("RESPONSE_FINGERPRINT_DIFFERENT"), stepId: identifier }).strict()
]);
const hmacSchema = z.object({ kind: z.literal("HMAC"), algorithm: z.enum(["sha256", "sha512"]).default("sha256"), secretSource: authSlot, secretRef: identifier, header: z.string().min(1).max(100), encoding: z.enum(["HEX", "BASE64"]).default("HEX"), prefix: z.string().max(40).default(""), messageFormat: z.enum(["BODY", "TIMESTAMP_DOT_BODY"]).default("BODY"), timestampHeader: z.string().min(1).max(100).optional(), timestampSecretRef: identifier.optional(), tamper: z.boolean().default(false) }).strict();
const requestSchema = z.object({ method: z.enum(["GET", "HEAD", "OPTIONS", "POST", "PATCH", "PUT", "DELETE"]), urlTemplate: z.string().min(1).max(4096), stateChanging: z.boolean().default(false), secretSource: authSlot.default("anonymous"), headers: z.record(z.string().max(8192)).default({}), bodyFormat: z.enum(["JSON", "FORM", "RAW"]).optional(), fields: z.unknown().optional(), hmac: hmacSchema.optional() }).strict();
const stepSchema = z.object({ id: identifier, phase: z.enum(["PRE_STATE", "ACTION", "VERIFY", "CLEANUP"]), actorId: identifier, endpointId: identifier, waitBeforeMs: z.number().int().min(0).max(3_600_000).default(0), request: requestSchema, captures: z.array(captureSchema).max(16).default([]), assertions: z.array(assertionSchema).max(24).default([]) }).strict();
const caseSchema = z.object({ id: identifier, label: z.string().min(1).max(160), category: z.enum(operationalEndpointCategories), authorization: authorizationSchema, cleanupRequired: z.boolean().default(false), steps: z.array(stepSchema).min(1).max(40) }).strict();
export const operationalEndpointSecurityInputSchema = z.object({ schemaVersion: z.literal(1).default(1), maxCases: z.number().int().min(1).max(60).default(30), maxStepsPerCase: z.number().int().min(1).max(40).default(20), maxRequests: z.number().int().min(1).max(500).default(120), maxResponseBytes: z.number().int().min(512).max(1024 * 1024).default(65536), actors: z.array(actorSchema).min(1).max(10), endpoints: z.array(endpointSchema).min(1).max(100), cases: z.array(caseSchema).min(1).max(60) }).strict();
export type OperationalEndpointSecurityInput = z.infer<typeof operationalEndpointSecurityInputSchema>;
type PlannerContext = { target: string; scope: RouteCairnScope; authProfile?: AuthProfile; authProfileSet?: AuthProfileSet; now?: Date };

export async function loadOperationalEndpointSecurityInput(path: string): Promise<OperationalEndpointSecurityInput> { const raw = await readFile(path); if (raw.byteLength > maxFileBytes) throw new AppError(`Operational endpoint manifest exceeds ${maxFileBytes} bytes.`, "OPERATIONAL_ENDPOINT_FILE_TOO_LARGE"); let value: unknown; try { value = JSON.parse(raw.toString("utf8").replace(/^\uFEFF/, "")); } catch { throw new AppError("Operational endpoint manifest is not valid JSON.", "OPERATIONAL_ENDPOINT_JSON_INVALID"); } const parsed = operationalEndpointSecurityInputSchema.safeParse(value); if (!parsed.success) throw new AppError(parsed.error.message, "OPERATIONAL_ENDPOINT_INPUT_INVALID"); return parsed.data; }

export function planOperationalEndpointSecurity(input: OperationalEndpointSecurityInput, context: PlannerContext): OperationalEndpointSecurityPlan {
  const parsed = operationalEndpointSecurityInputSchema.parse(input); if (parsed.cases.length > parsed.maxCases) throw new AppError("Operational cases exceed maxCases.", "OPERATIONAL_ENDPOINT_LIMIT_EXCEEDED");
  const matcher = new ScopeMatcher(context.target, context.scope); const profiles = profileMap(context); ensureUnique(parsed.actors.map((item) => item.id), "actor"); ensureUnique(parsed.endpoints.map((item) => item.id), "endpoint"); ensureUnique(parsed.cases.map((item) => item.id), "case"); validateActorIsolation(parsed.actors, profiles);
  const actors = parsed.actors.map((value): OperationalActorPlan => { assertSafeLabel(value.safeAlias, `actor ${value.id}`); assertSafeLabel(value.relationship, `actor ${value.id} relationship`); const profile = profiles[value.authSlot]; const sendAuthentication = value.sendAuthentication ?? value.authSlot !== "anonymous"; if (value.authSlot === "anonymous" && sendAuthentication) throw new AppError(`Anonymous actor ${value.id} cannot send authentication.`, "OPERATIONAL_ENDPOINT_ACTOR_INVALID"); if (value.authSlot !== "anonymous" && !profile) throw new AppError(`Actor ${value.id} requires an auth profile.`, "OPERATIONAL_ENDPOINT_CREDENTIAL_REQUIRED"); if (value.principalId && profile?.principalId && value.principalId !== profile.principalId) throw new AppError(`Actor ${value.id} principal metadata differs from its profile.`, "OPERATIONAL_ENDPOINT_IDENTITY_MISMATCH"); if (value.tenantId && profile?.tenantId && value.tenantId !== profile.tenantId) throw new AppError(`Actor ${value.id} tenant metadata differs from its profile.`, "OPERATIONAL_ENDPOINT_IDENTITY_MISMATCH"); const principal = value.principalId ?? profile?.principalId; const tenant = value.tenantId ?? profile?.tenantId; return { id: value.id, safeAlias: value.safeAlias, authSlot: value.authSlot, sendAuthentication, relationship: value.relationship, ...(principal ? { principalFingerprint: digest(`principal\0${principal}`) } : {}), ...(tenant ? { tenantFingerprint: digest(`tenant\0${tenant}`) } : {}) }; });
  const actorById = new Map(actors.map((item) => [item.id, item]));
  const endpoints = parsed.endpoints.map((value) => { assertSafeLabel(value.safeAlias, `endpoint ${value.id}`); if (/[?#\r\n\0]/.test(value.pathTemplate) || /\.\.(?:\/|\\)/.test(value.pathTemplate)) throw new AppError(`Endpoint ${value.id} has an unsafe pathTemplate.`, "OPERATIONAL_ENDPOINT_PATH_INVALID"); const allowedOrigins = [...new Set(value.allowedOrigins.map(normalizeOrigin))]; for (const origin of allowedOrigins) if (!matcher.decide(`${origin}/`, "GET").allowed) throw new AppError(`Endpoint ${value.id} origin is outside scope.`, "OPERATIONAL_ENDPOINT_ORIGIN_INVALID"); return { id: value.id, safeAlias: value.safeAlias, kind: value.kind, pathTemplate: value.pathTemplate, allowedOrigins, ...(value.declaredWorkloadLimit !== undefined ? { declaredWorkloadLimit: value.declaredWorkloadLimit } : {}) }; });
  const endpointById = new Map(endpoints.map((item) => [item.id, item])); let requests = 0; const now = context.now ?? new Date();
  const cases = parsed.cases.map((value) => { assertSafeLabel(value.label, `case ${value.id}`); if (value.steps.length > parsed.maxStepsPerCase) throw new AppError(`Case ${value.id} exceeds maxStepsPerCase.`, "OPERATIONAL_ENDPOINT_LIMIT_EXCEEDED"); requests += value.steps.length; validateCase(value, actorById, endpointById, profiles, matcher, now); return { id: value.id, label: value.label, category: value.category, authorization: { mode: value.authorization.mode, environment: value.authorization.environment, ...(value.authorization.authorizedAt ? { authorizedAt: value.authorization.authorizedAt } : {}), ...(value.authorization.expiresAt ? { expiresAt: value.authorization.expiresAt } : {}), authorizationIdentityConfirmed: Boolean(value.authorization.authorizedBy), changeTicketConfirmed: Boolean(value.authorization.changeTicket), disposableTarget: value.authorization.disposableTarget, productionAcknowledged: value.authorization.productionAcknowledged, confirmationAccepted: value.authorization.confirmation === "I_AUTHORIZE_CONTROLLED_OPERATIONAL_ENDPOINT_TESTING" }, cleanupRequired: value.cleanupRequired, steps: value.steps, comparisonFingerprint: caseFingerprint(value, actors, endpoints) } satisfies OperationalEndpointCasePlan; });
  if (requests > parsed.maxRequests) throw new AppError(`Operational plan requires ${requests} requests, exceeding maxRequests.`, "OPERATIONAL_ENDPOINT_LIMIT_EXCEEDED");
  return { schemaVersion: 1, enabled: true, targetOrigin: new URL(context.target).origin, maxCases: parsed.maxCases, maxStepsPerCase: parsed.maxStepsPerCase, maxRequests: parsed.maxRequests, maxResponseBytes: parsed.maxResponseBytes, actors, endpoints, cases, notes: ["Webhook HMACs are computed from the exact serialized body in worker memory; secrets and generated signatures are never persisted.", "Replay, idempotency, ordering, payload, cron, and workload conclusions require explicit response or authoritative capture assertions.", "Every state-changing operational request is individually authorized, journaled before transmission, never retried, never redirected, and followed by cleanup or disposable-target sealing."] };
}

function validateCase(value: z.infer<typeof caseSchema>, actors: ReadonlyMap<string, OperationalActorPlan>, endpoints: ReadonlyMap<string, OperationalEndpointSecurityPlan["endpoints"][number]>, profiles: Readonly<Record<OperationalAuthSlot, AuthProfile | undefined>>, matcher: ScopeMatcher, now: Date): void {
  ensureUnique(value.steps.map((step) => step.id), `step in ${value.id}`); const captures = new Set<string>(); const priorSteps = new Set<string>(); const hasMutation = value.steps.some((step) => step.phase !== "CLEANUP" && step.request.stateChanging); let assertions = 0; let mutations = 0;
  for (const step of value.steps) {
    const actor = actors.get(step.actorId); const endpoint = endpoints.get(step.endpointId); if (!actor) throw new AppError(`Unknown actor in ${value.id}/${step.id}.`, "OPERATIONAL_ENDPOINT_UNKNOWN_ACTOR"); if (!endpoint) throw new AppError(`Unknown endpoint in ${value.id}/${step.id}.`, "OPERATIONAL_ENDPOINT_UNKNOWN_ENDPOINT");
    if (step.phase !== "CLEANUP" && (!isWorkflowCategory(value.category) || step.request.stateChanging || !hasMutation)) validateCategoryEndpoint(value.category, endpoint.kind); if (["POST", "PATCH", "PUT", "DELETE"].includes(step.request.method) && !step.request.stateChanging) throw new AppError(`Unsafe method ${value.id}/${step.id} requires stateChanging=true.`, "OPERATIONAL_ENDPOINT_MUTATION_DECLARATION_REQUIRED"); if (step.request.stateChanging) mutations++;
    validateHeaders(step.request.headers, `${value.id}/${step.id}`); validateBody(step.request, `${value.id}/${step.id}`); validateUrl(step.request.urlTemplate, step.request.method, endpoint.allowedOrigins, matcher, captures, `${value.id}/${step.id}`); validateReferences(step.request.urlTemplate, step.request.headers, step.request.fields, step.request.secretSource, profiles, captures, `${value.id}/${step.id}`);
    if (step.request.hmac) { const hmac = step.request.hmac; if (endpoint.kind !== "WEBHOOK") throw new AppError(`HMAC signing is limited to webhook endpoints.`, "OPERATIONAL_ENDPOINT_HMAC_INVALID"); if (!step.request.stateChanging || step.request.method !== "POST" || step.request.fields === undefined) throw new AppError(`Webhook HMAC in ${value.id}/${step.id} requires a state-changing POST body.`, "OPERATIONAL_ENDPOINT_HMAC_INVALID"); if (forbiddenHeader.test(hmac.header) || /[\r\n\0]/.test(hmac.header + hmac.prefix + (hmac.timestampHeader ?? ""))) throw new AppError(`HMAC header configuration in ${value.id}/${step.id} is unsafe.`, "OPERATIONAL_ENDPOINT_HMAC_INVALID"); if (Object.keys(step.request.headers).some((name) => name.toLowerCase() === hmac.header.toLowerCase())) throw new AppError(`HMAC header in ${value.id}/${step.id} cannot also be supplied manually.`, "OPERATIONAL_ENDPOINT_HMAC_INVALID"); requireSecret(profiles, hmac.secretSource, hmac.secretRef, `${value.id}/${step.id}`); if (hmac.messageFormat === "TIMESTAMP_DOT_BODY") { if (!hmac.timestampHeader || !hmac.timestampSecretRef || forbiddenHeader.test(hmac.timestampHeader)) throw new AppError(`Timestamped HMAC in ${value.id}/${step.id} requires a safe timestampHeader and timestampSecretRef.`, "OPERATIONAL_ENDPOINT_HMAC_INVALID"); requireSecret(profiles, hmac.secretSource, hmac.timestampSecretRef, `${value.id}/${step.id}`); } else if (hmac.timestampHeader || hmac.timestampSecretRef) throw new AppError(`Body-only HMAC in ${value.id}/${step.id} must not declare timestamp fields.`, "OPERATIONAL_ENDPOINT_HMAC_INVALID"); }
    for (const capture of step.captures) { if (captures.has(capture.name)) throw new AppError(`Capture ${capture.name} is assigned twice.`, "OPERATIONAL_ENDPOINT_CAPTURE_INVALID"); if (capture.source === "JSON") safePath(capture.path); captures.add(capture.name); }
    for (const assertion of step.assertions) { assertions++; if (["JSON_FIELD_PRESENT", "JSON_FIELD_ABSENT", "JSON_EQUALS_SECRET"].includes(assertion.kind)) safePath((assertion as { path: string }).path); if (assertion.kind === "JSON_EQUALS_SECRET") requireSecret(profiles, assertion.secretSource, assertion.secretRef, `${value.id}/${step.id}`); if (assertion.kind === "CAPTURE_EQUALS_SECRET" || assertion.kind === "CAPTURE_NOT_EQUALS_SECRET") { if (!captures.has(assertion.capture)) throw new AppError(`Assertion in ${value.id}/${step.id} references an unavailable capture.`, "OPERATIONAL_ENDPOINT_CAPTURE_INVALID"); requireSecret(profiles, assertion.secretSource, assertion.secretRef, `${value.id}/${step.id}`); } if (assertion.kind === "NUMERIC_DELTA" && (!captures.has(assertion.before) || !captures.has(assertion.after))) throw new AppError(`Numeric delta in ${value.id}/${step.id} requires earlier/current captures.`, "OPERATIONAL_ENDPOINT_CAPTURE_INVALID"); if ((assertion.kind === "RESPONSE_FINGERPRINT_MATCH" || assertion.kind === "RESPONSE_FINGERPRINT_DIFFERENT") && !priorSteps.has(assertion.stepId)) throw new AppError(`Response comparison in ${value.id}/${step.id} must reference an earlier step.`, "OPERATIONAL_ENDPOINT_ASSERTION_INVALID"); if (assertion.kind === "DECISION" && assertion.allowedStatuses.some((status) => assertion.deniedStatuses.includes(status))) throw new AppError(`Decision statuses overlap in ${value.id}/${step.id}.`, "OPERATIONAL_ENDPOINT_ASSERTION_INVALID"); }
    if ((step.phase === "VERIFY" || step.phase === "CLEANUP") && step.assertions.length === 0) throw new AppError(`${step.phase} step ${value.id}/${step.id} requires an assertion.`, "OPERATIONAL_ENDPOINT_ASSERTION_REQUIRED"); priorSteps.add(step.id);
  }
  if (!assertions) throw new AppError(`Case ${value.id} requires a security assertion.`, "OPERATIONAL_ENDPOINT_ASSERTION_REQUIRED"); const main = value.steps.filter((step) => step.phase !== "CLEANUP");
  if (value.category === "WEBHOOK_SIGNATURE_REJECTION") { const valid = main.filter((step) => step.request.hmac && !step.request.hmac.tamper); const tampered = main.filter((step) => step.request.hmac?.tamper); if (!valid.length || !tampered.length || !valid.some((left) => tampered.some((right) => replayFingerprint(left) === replayFingerprint(right)))) throw new AppError(`Signature-rejection case ${value.id} requires valid and tampered HMAC attempts over the same request.`, "OPERATIONAL_ENDPOINT_SIGNATURE_PAIR_REQUIRED"); }
  if (["WEBHOOK_REPLAY_PROTECTION", "WEBHOOK_IDEMPOTENCY", "CRON_REPLAY_PROTECTION"].includes(value.category)) { const attempts = main.filter((step) => step.request.stateChanging); const fingerprints = attempts.map(replayFingerprint); if (attempts.length < 2 || new Set(fingerprints).size === fingerprints.length) throw new AppError(`Replay/idempotency case ${value.id} requires at least two identical ordered attempts.`, "OPERATIONAL_ENDPOINT_REPLAY_STEPS_REQUIRED"); }
  if (value.category === "WEBHOOK_IDEMPOTENCY" && !hasNumericBound(value)) throw new AppError(`Idempotency case ${value.id} requires an authoritative numeric-delta assertion.`, "OPERATIONAL_ENDPOINT_IDEMPOTENCY_ASSERTION_REQUIRED");
  if (value.category === "WEBHOOK_EVENT_ORDERING") { const events = main.filter((step) => step.request.stateChanging); if (events.length < 2 || new Set(events.map(replayFingerprint)).size < 2 || !hasStateValueAssertion(value)) throw new AppError(`Event-ordering case ${value.id} requires two distinct events and an authoritative final-state assertion.`, "OPERATIONAL_ENDPOINT_ORDERING_ASSERTION_REQUIRED"); }
  if (value.category === "WEBHOOK_PAYLOAD_INTEGRITY" && secretBackedAssertionCount(value) < 3) throw new AppError(`Payload-integrity case ${value.id} requires secret-backed authoritative amount, currency, and product assertions.`, "OPERATIONAL_ENDPOINT_PAYLOAD_ASSERTION_REQUIRED");
  if (value.category === "HEALTH_INFORMATION_EXPOSURE" && value.steps.some((step) => step.request.stateChanging || !["GET", "HEAD"].includes(step.request.method))) throw new AppError(`Health exposure cases must be read-only GET or HEAD requests.`, "OPERATIONAL_ENDPOINT_HEALTH_METHOD_INVALID");
  if (value.category === "CRON_SCOPE_WORKLOAD_LIMIT") { const endpointsUsed = main.map((step) => endpoints.get(step.endpointId)!); const limits = endpointsUsed.map((item) => item.declaredWorkloadLimit).filter((item): item is number => item !== undefined); const hasBound = limits.length > 0 && value.steps.some((step) => step.assertions.some((assertion) => assertion.kind === "NUMERIC_DELTA" && assertion.operator === "LTE" && assertion.expected <= Math.min(...limits))); if (!hasBound) throw new AppError(`Cron workload case ${value.id} requires a declared endpoint limit and matching numeric upper bound.`, "OPERATIONAL_ENDPOINT_WORKLOAD_ASSERTION_REQUIRED"); }
  if (value.category === "HEALTH_INFORMATION_EXPOSURE" && !value.steps.some((step) => step.assertions.some((assertion) => assertion.kind === "JSON_FIELD_ABSENT"))) throw new AppError(`Health case ${value.id} requires sensitive-field absence assertions.`, "OPERATIONAL_ENDPOINT_HEALTH_ASSERTION_REQUIRED");
  const actorCount = new Set(main.map((step) => step.actorId)).size; if (["CRON_AUTHENTICATION", "JOB_AUTHORIZATION", "INCIDENT_ACCESS_CONTROL", "ADMIN_WORKER_AUTHORIZATION"].includes(value.category) && actorCount < 2) throw new AppError(`Authorization case ${value.id} requires at least two actors.`, "OPERATIONAL_ENDPOINT_ACTOR_MATRIX_REQUIRED");
  if (mutations) validateAuthorization(value, now); if (value.cleanupRequired && !value.steps.some((step) => step.phase === "CLEANUP")) throw new AppError(`Case ${value.id} requires cleanup.`, "OPERATIONAL_ENDPOINT_CLEANUP_REQUIRED"); if (!value.cleanupRequired && value.steps.some((step) => step.phase === "CLEANUP")) throw new AppError(`Case ${value.id} has undeclared cleanup steps.`, "OPERATIONAL_ENDPOINT_CLEANUP_DECLARATION_INVALID"); if (mutations && !value.cleanupRequired && !value.authorization.disposableTarget) throw new AppError(`Mutating case ${value.id} requires cleanup or a disposable target.`, "OPERATIONAL_ENDPOINT_CLEANUP_REQUIRED");
}

function validateCategoryEndpoint(category: z.infer<typeof caseSchema>["category"], kind: string): void { const expected = category.startsWith("WEBHOOK_") ? "WEBHOOK" : category.startsWith("CRON_") ? "CRON" : category === "JOB_AUTHORIZATION" ? "JOB" : category === "INCIDENT_ACCESS_CONTROL" ? "INCIDENT" : category === "HEALTH_INFORMATION_EXPOSURE" ? "HEALTH" : undefined; if (expected && kind !== expected) throw new AppError(`Category ${category} cannot target endpoint kind ${kind}.`, "OPERATIONAL_ENDPOINT_KIND_MISMATCH"); if (category === "ADMIN_WORKER_AUTHORIZATION" && !["ADMIN", "WORKER"].includes(kind)) throw new AppError(`Admin/worker case targets an invalid endpoint kind.`, "OPERATIONAL_ENDPOINT_KIND_MISMATCH"); }
function isWorkflowCategory(category: z.infer<typeof caseSchema>["category"]): boolean { return category.startsWith("WEBHOOK_") || category.startsWith("CRON_"); }
function validateAuthorization(value: z.infer<typeof caseSchema>, now: Date): void { const auth = value.authorization; if (auth.mode !== "CONTROLLED_OPERATIONAL_FLOW" || auth.confirmation !== "I_AUTHORIZE_CONTROLLED_OPERATIONAL_ENDPOINT_TESTING" || !auth.authorizedBy || !auth.changeTicket || !auth.authorizedAt || !auth.expiresAt) throw new AppError(`Mutating case ${value.id} lacks explicit controlled authorization.`, "OPERATIONAL_ENDPOINT_AUTHORIZATION_REQUIRED"); const start = Date.parse(auth.authorizedAt); const end = Date.parse(auth.expiresAt); if (start > now.getTime() || end <= now.getTime() || end <= start) throw new AppError(`Authorization for ${value.id} is not currently valid.`, "OPERATIONAL_ENDPOINT_AUTHORIZATION_EXPIRED"); if (auth.environment === "PRODUCTION" && !auth.productionAcknowledged) throw new AppError(`Production case ${value.id} requires acknowledgement.`, "OPERATIONAL_ENDPOINT_PRODUCTION_ACK_REQUIRED"); }
function validateBody(request: z.infer<typeof requestSchema>, label: string): void { if ((request.fields === undefined) !== (request.bodyFormat === undefined)) throw new AppError(`Request ${label} must declare bodyFormat and fields together.`, "OPERATIONAL_ENDPOINT_BODY_INVALID"); if (request.bodyFormat === "RAW" && typeof request.fields !== "string") throw new AppError(`RAW body in ${label} must be a string template.`, "OPERATIONAL_ENDPOINT_BODY_INVALID"); walk(request.fields, (entry, key) => { if (typeof entry === "string" && secretKey.test(key) && ![...entry.matchAll(reference)].length) throw new AppError(`Sensitive field ${key} in ${label} must use a secret reference.`, "OPERATIONAL_ENDPOINT_LITERAL_SECRET_REJECTED"); }); }
function validateHeaders(headers: Record<string, string>, label: string): void { for (const [name, value] of Object.entries(headers)) if (forbiddenHeader.test(name) || /[\r\n\0]/.test(name + value)) throw new AppError(`Unsafe header in ${label}.`, "OPERATIONAL_ENDPOINT_HEADER_INVALID"); }
function validateUrl(template: string, method: string, origins: readonly string[], matcher: ScopeMatcher, captures: ReadonlySet<string>, label: string): void { const captured = exactCapture.exec(template); if (captured) { if (!captures.has(captured[1]!)) throw new AppError(`Captured URL in ${label} must come from an earlier step.`, "OPERATIONAL_ENDPOINT_CAPTURE_INVALID"); return; } const parsed = templateUrl(template); if (!origins.includes(parsed.origin)) throw new AppError(`URL origin in ${label} is not endpoint-approved.`, "OPERATIONAL_ENDPOINT_ORIGIN_INVALID"); const decision = matcher.decide(parsed.toString(), method); if (!decision.allowed) throw new AppError(`URL in ${label} is outside scope: ${decision.reason}.`, "OPERATIONAL_ENDPOINT_SCOPE_INVALID"); }
function validateReferences(template: string, headers: Record<string, string>, fields: unknown, source: OperationalAuthSlot, profiles: Readonly<Record<OperationalAuthSlot, AuthProfile | undefined>>, captures: ReadonlySet<string>, label: string): void { const values = [template, ...Object.values(headers), ...leafStrings(fields)]; for (const value of values) for (const match of value.matchAll(reference)) { if (match[1] === "CAPTURE") { if (!captures.has(match[2]!)) throw new AppError(`Unknown capture in ${label}.`, "OPERATIONAL_ENDPOINT_CAPTURE_INVALID"); } else requireSecret(profiles, source, match[2]!, label); } for (const value of values) if (value.includes("{{") && !(value.match(reference)?.length)) throw new AppError(`Invalid template in ${label}.`, "OPERATIONAL_ENDPOINT_TEMPLATE_INVALID"); }
function requireSecret(profiles: Readonly<Record<OperationalAuthSlot, AuthProfile | undefined>>, slot: OperationalAuthSlot, name: string, label: string): void { const profile = profiles[slot]; if (!profile || !Object.prototype.hasOwnProperty.call(authenticationLifecycleSecrets(profile), name)) throw new AppError(`Secret ${name} for ${label} is unavailable from ${slot}.`, "OPERATIONAL_ENDPOINT_SECRET_REQUIRED"); }
function hasNumericBound(value: z.infer<typeof caseSchema>): boolean { return value.steps.some((step) => step.assertions.some((assertion) => assertion.kind === "NUMERIC_DELTA" && ["EQ", "LTE"].includes(assertion.operator) && assertion.expected <= 1)); }
function hasStateValueAssertion(value: z.infer<typeof caseSchema>): boolean { return value.steps.some((step) => step.assertions.some((assertion) => ["JSON_EQUALS_SECRET", "CAPTURE_EQUALS_SECRET", "CAPTURE_NOT_EQUALS_SECRET"].includes(assertion.kind))); }
function secretBackedAssertionCount(value: z.infer<typeof caseSchema>): number { return value.steps.flatMap((step) => step.assertions).filter((assertion) => ["JSON_EQUALS_SECRET", "CAPTURE_EQUALS_SECRET"].includes(assertion.kind)).length; }
function replayFingerprint(step: z.infer<typeof stepSchema>): string { const hmac = step.request.hmac ? { ...step.request.hmac, tamper: false } : undefined; return createHash("sha256").update(JSON.stringify({ endpointId: step.endpointId, actorId: step.actorId, method: step.request.method, urlTemplate: step.request.urlTemplate, secretSource: step.request.secretSource, headers: step.request.headers, bodyFormat: step.request.bodyFormat, fields: step.request.fields, hmac })).digest("hex"); }
function safePath(path: string): void { parseSafeFieldPath(path, { maxDepth: 8, maxArrayIndex: 100, code: "OPERATIONAL_ENDPOINT_FIELD_PATH_INVALID" }); }
function templateUrl(template: string): URL { try { const parsed = new URL(template.replace(reference, "routecairn-placeholder")); if (!['http:', 'https:'].includes(parsed.protocol) || parsed.username || parsed.password) throw new Error(); return parsed; } catch { throw new AppError("Operational URL template is invalid.", "OPERATIONAL_ENDPOINT_TEMPLATE_INVALID"); } }
function normalizeOrigin(value: string): string { const parsed = new URL(value); if (!['http:', 'https:'].includes(parsed.protocol) || parsed.pathname !== "/" || parsed.search || parsed.hash || parsed.username || parsed.password) throw new AppError(`Allowed origin ${value} must be exact.`, "OPERATIONAL_ENDPOINT_ORIGIN_INVALID"); return parsed.origin; }
function profileMap(context: PlannerContext): Readonly<Record<OperationalAuthSlot, AuthProfile | undefined>> { return { anonymous: undefined, primary: context.authProfile, account_a: context.authProfileSet?.accountA, account_b: context.authProfileSet?.accountB }; }
function validateActorIsolation(actors: readonly z.infer<typeof actorSchema>[], profiles: Readonly<Record<OperationalAuthSlot, AuthProfile | undefined>>): void {
  const slots = new Set(actors.map((actor) => actor.authSlot));
  if (!slots.has("account_a") || !slots.has("account_b")) return;
  const left = profiles.account_a; const right = profiles.account_b;
  if (!left || !right) return;
  if (left.principalId && right.principalId && left.principalId === right.principalId) throw new AppError("Account A and Account B must declare different principals.", "OPERATIONAL_ENDPOINT_ACTOR_ISOLATION_REQUIRED");
  if (credentialFingerprint(left) === credentialFingerprint(right)) throw new AppError("Account A and Account B must use different authentication material.", "OPERATIONAL_ENDPOINT_ACTOR_ISOLATION_REQUIRED");
}
function credentialFingerprint(profile: AuthProfile): string { return digest(JSON.stringify({ headers: Object.entries(profile.headers).sort(([left], [right]) => left.localeCompare(right)), cookies: [...profile.cookies].map((cookie) => ({ name: cookie.name, value: cookie.value, domain: cookie.domain ?? "", path: cookie.path ?? "" })).sort((left, right) => JSON.stringify(left).localeCompare(JSON.stringify(right))) })); }
function ensureUnique(values: readonly string[], label: string): void { if (new Set(values).size !== values.length) throw new AppError(`Duplicate ${label} identifier.`, "OPERATIONAL_ENDPOINT_DUPLICATE_ID"); }
function assertSafeLabel(value: string, label: string): void { if (/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value) || /bearer\s|https?:\/\/|[?&=]/i.test(value) || /^[A-Za-z0-9_-]{40,}$/.test(value)) throw new AppError(`${label} appears identifying or secret-like.`, "OPERATIONAL_ENDPOINT_UNSAFE_LABEL"); }
function walk(value: unknown, visit: (entry: unknown, key: string) => void, key = ""): void { visit(value, key); if (Array.isArray(value)) value.forEach((entry, index) => walk(entry, visit, String(index))); else if (value && typeof value === "object") for (const [child, entry] of Object.entries(value as Record<string, unknown>)) walk(entry, visit, child); }
function leafStrings(value: unknown): string[] { const result: string[] = []; walk(value, (entry) => { if (typeof entry === "string") result.push(entry); }); return result; }
function digest(value: string): string { return createHash("sha256").update(`routecairn-operational-v1\0${value}`).digest("hex"); }
function caseFingerprint(value: z.infer<typeof caseSchema>, actors: OperationalEndpointSecurityPlan["actors"], endpoints: OperationalEndpointSecurityPlan["endpoints"]): string {
  const actorIds = new Set(value.steps.map((step) => step.actorId));
  const endpointIds = new Set(value.steps.map((step) => step.endpointId));
  return securityContractFingerprint("operational-endpoint-security", {
    schemaVersion: 1,
    category: value.category,
    actors: actors.filter((actor) => actorIds.has(actor.id)),
    endpoints: endpoints.filter((endpoint) => endpointIds.has(endpoint.id)),
    authorization: value.authorization,
    cleanupRequired: value.cleanupRequired,
    steps: value.steps
  });
}
