import { createHmac, timingSafeEqual } from "node:crypto";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import type { AddressInfo } from "node:net";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { runScanCommand } from "../../src/cli/commands/scan.js";
import { exampleScope } from "../../src/config/defaults.js";
import type { BillingEntitlementReport } from "../../src/reports/BillingEntitlementReport.js";

const hmacKey = "billing-hmac-private-411"; const hmacTimestamp = "1788100000";
let server: Server | undefined; const directories: string[] = [];
afterEach(async () => { if (server) await new Promise<void>((resolve, reject) => server!.close((error) => error ? reject(error) : resolve())); server = undefined; await Promise.all(directories.splice(0).map((directory) => rm(directory, { recursive: true, force: true }))); });

describe("checkout, billing, entitlement, and premium security integration", () => {
  it("executes all ten categories against synthetic fixtures and proves the no-real-payment boundary", async () => {
    const states = initialStates(); let validSignatures = 0; let realPaymentBoundaryViolations = 0;
    server = createServer(async (request, response) => {
      const url = new URL(request.url ?? "/", "http://localhost"); const auth = String(request.headers.authorization ?? "");
      if (url.pathname === "/") return json(response, 200, { ok: true });
      if (url.pathname.startsWith("/__routecairn__/billing-fixtures/") && request.method === "POST") {
        if (request.headers["x-routecairn-real-payment"] !== "forbidden" || !String(request.headers["x-routecairn-synthetic-billing"] ?? "").startsWith("CUSTOM_SYNTHETIC:")) { realPaymentBoundaryViolations++; return json(response, 400, { error: "fixture-boundary" }); }
        const raw = await body(request); const value = raw ? JSON.parse(raw) as Record<string, unknown> : {};
        if (url.pathname.startsWith("/__routecairn__/billing-fixtures/reset/")) { const name = url.pathname.split("/").at(-1)!; states[name] = structuredClone(initialStates()[name]!); return void response.writeHead(204).end(); }
        if (url.pathname === "/__routecairn__/billing-fixtures/checkout/price") return json(response, 422, { accepted: false });
        if (url.pathname === "/__routecairn__/billing-fixtures/checkout/product") { states.product.product = String(value.product); return json(response, 200, { accepted: true }); }
        if (url.pathname === "/__routecairn__/billing-fixtures/cancel") { states.cancel.subscriptionStatus = "canceled"; return json(response, 200, { accepted: true }); }
        if (url.pathname === "/__routecairn__/billing-fixtures/refund") { states.refund.refundStatus = "refunded"; return json(response, 200, { accepted: true }); }
        if (url.pathname.startsWith("/__routecairn__/billing-fixtures/events/")) {
          if (!validSignature(request, raw)) return json(response, 401, { accepted: false }); validSignatures++;
          const name = url.pathname.split("/").at(-1)!; const current = states[name]!; const eventId = String(value.eventId);
          if (name === "duplicate") { current.seen ??= []; if (!current.seen.includes(eventId)) { current.seen.push(eventId); current.eventCount++; } }
          else { current.eventCount++; }
          if (name === "unverified") { current.paymentVerified = false; current.entitlement = true; }
          return json(response, 202, { accepted: true });
        }
      }
      if (url.pathname.startsWith("/state/")) { const name = url.pathname.split("/").at(-1)!; return json(response, 200, states[name]); }
      if (url.pathname === "/premium/owner") return auth === "Bearer account-a-private-211" ? json(response, 200, { access: true }) : json(response, 403, { access: false });
      if (url.pathname === "/subscriptions/subscription-private-771") return auth.includes("account-") ? json(response, 200, { access: true, owner: "owner-private-311" }) : json(response, 401, { access: false });
      return void response.writeHead(404).end();
    });
    await new Promise<void>((resolve) => server!.listen(0, "127.0.0.1", resolve)); const origin = `http://127.0.0.1:${(server.address() as AddressInfo).port}`; const directory = await mkdtemp(join(tmpdir(), "routecairn-billing-")); directories.push(directory);
    const scope = await writeJson(directory, "scope.json", { ...exampleScope, allowedDomains: ["127.0.0.1"], disallowedPaths: [], allowedMethods: ["GET", "HEAD", "OPTIONS", "POST"], rateLimitPerSecond: 50, concurrency: 5 });
    const primary = await writeJson(directory, "primary.json", profile("service", "ops", "service-private-111", primarySecrets()));
    const accountA = await writeJson(directory, "account-a.json", profile("account-a", "tenant-a", "account-a-private-211", { subscription_id: "subscription-private-771", owner_id: "owner-private-311" }));
    const accountB = await writeJson(directory, "account-b.json", profile("account-b", "tenant-b", "account-b-private-411", {}));
    const manifest = await writeJson(directory, "billing.json", manifestFor(origin)); const result = await runScanCommand(`${origin}/`, { scope, auth: primary, authA: accountA, authB: accountB, billingEntitlement: manifest, output: join(directory, "reports") });
    const raw = await readFile(result.reportPath, "utf8"); const markdown = await readFile(result.markdownReportPath, "utf8"); const html = await readFile(result.htmlReportPath, "utf8"); const journal = await readFile(join(process.env.ROUTECAIRN_MUTATION_DIR!, "mutation-journal.json"), "utf8"); const report = JSON.parse(raw) as { billingEntitlement: BillingEntitlementReport; findings: Array<{ type: string }>; requestAudit: Array<{ requestedUrl: string; requestHeaders: Record<string, string> }> };
    expect(report.billingEntitlement).toMatchObject({ enabled: true, providerKind: "CUSTOM_SYNTHETIC", providerMode: "TEST", realPaymentExecution: "FORBIDDEN", plannedCases: 10, executedCases: 10, passedCases: 3, failedCases: 7, inconclusiveCases: 0, blockedCases: 0, requestsTransmitted: 47, requestBudget: 60, synchronizedGroups: 1, cleanupRequired: 8, cleanupFailed: 0 });
    expect(Object.values(report.billingEntitlement.coverage).filter((entry) => entry.planned === 1)).toHaveLength(10); expect(report.billingEntitlement.observations.find((item) => item.caseId === "payment-race")).toMatchObject({ outcome: "FAIL", cleanupOutcome: "ROLLBACK_VERIFIED", steps: expect.arrayContaining([expect.objectContaining({ synchronized: true, attemptsPlanned: 2 })]) });
    expect(validSignatures).toBe(7); expect(realPaymentBoundaryViolations).toBe(0); expect(report.findings.map((finding) => finding.type)).toEqual(expect.arrayContaining(["Checkout Integrity Issue", "Payment Entitlement Issue", "Payment Event Idempotency Issue", "Premium Access Authorization Issue", "Subscription State Consistency Issue", "Payment Event Race Condition"]));
    expect(report.requestAudit.filter((entry) => (entry.requestedUrl === "redacted://billing-entitlement-request" || entry.requestedUrl === "redacted://workflow-cleanup"))).toHaveLength(47); for (const entry of report.requestAudit) for (const value of Object.values(entry.requestHeaders)) expect(value).toBe("<redacted>"); expect(journal.match(/ROLLBACK_VERIFIED/g)?.length).toBeGreaterThanOrEqual(8); expect(markdown).toContain("## Checkout, Billing, Entitlement, and Premium Security"); expect(html).toContain("billingEntitlement");
    const secrets = [hmacKey, hmacTimestamp, "service-private-111", "account-a-private-211", "account-b-private-411", "subscription-private-771", "owner-private-311", "event-duplicate-private", "event-race-private", "operator-private-511", "BILL-private-811"];
    for (const secret of secrets) for (const artifact of [raw, markdown, html, journal]) expect(artifact, `persisted ${secret}`).not.toContain(secret);
  }, 45_000);
});

type FixtureState = Record<string, any>;
function initialStates(): FixtureState { return { price: { price: "1250" }, product: { product: "premium-plan" }, unverified: { paymentVerified: false, entitlement: false, eventCount: 0 }, cancel: { subscriptionStatus: "active", entitlement: true }, duplicate: { eventCount: 0, seen: [] }, replay: { eventCount: 0 }, refund: { refundStatus: "none", entitlement: true }, race: { eventCount: 0 } }; }
function manifestFor(origin: string): unknown {
  const controlled = { mode: "CONTROLLED_SYNTHETIC_BILLING", environment: "TEST", confirmation: "I_AUTHORIZE_SYNTHETIC_BILLING_TESTING", authorizedBy: "operator-private-511", changeTicket: "BILL-private-811", authorizedAt: new Date(Date.now() - 60_000).toISOString(), expiresAt: new Date(Date.now() + 3_600_000).toISOString(), disposableFixtures: true }; const observeOnly = { mode: "OBSERVE_ONLY", environment: "TEST" };
  const actors = [{ id: "public", safeAlias: "public", authSlot: "anonymous", relationship: "PUBLIC" }, { id: "service", safeAlias: "service", authSlot: "primary", relationship: "FIXTURE_OPERATOR", principalId: "service", tenantId: "ops" }, { id: "owner", safeAlias: "owner", authSlot: "account_a", relationship: "OWNER", principalId: "account-a", tenantId: "tenant-a" }, { id: "foreign", safeAlias: "foreign", authSlot: "account_b", relationship: "CROSS_TENANT", principalId: "account-b", tenantId: "tenant-b" }];
  const endpoint = (id: string, kind: string, pathTemplate: string) => ({ id, safeAlias: id, kind, pathTemplate, allowedOrigins: [origin] }); const endpoints = [endpoint("checkout", "CHECKOUT_VALIDATION", "/__routecairn__/billing-fixtures/checkout/{case}"), endpoint("webhook", "SYNTHETIC_WEBHOOK", "/__routecairn__/billing-fixtures/events/{case}"), endpoint("state", "ENTITLEMENT_STATE", "/state/{case}"), endpoint("premium", "PREMIUM_ACCESS", "/premium/{account}"), endpoint("subscription", "SUBSCRIPTION_STATE", "/subscriptions/{subscription}"), endpoint("control", "FIXTURE_CONTROL", "/__routecairn__/billing-fixtures/{operation}")];
  const expectation = (businessRule: "ACCEPT" | "REJECT" | "NOT_EVALUATED", authorization: "ALLOW" | "DENY" = "ALLOW") => ({ authorization, businessRule }); const request = (method: string, urlTemplate: string, secretSource = "anonymous", fields?: unknown) => ({ method, urlTemplate, secretSource, ...(fields === undefined ? {} : { stateChanging: true, bodyFormat: "JSON", fields }) }); const signed = (name: string, eventRef: string) => ({ ...request("POST", `${origin}/__routecairn__/billing-fixtures/events/${name}`, "primary", { eventId: `{{SECRET:${eventRef}}}`, paymentStatus: "{{SECRET:synthetic_payment_status}}" }), hmac: { kind: "HMAC", algorithm: "sha256", secretSource: "primary", secretRef: "billing_hmac", header: "X-Test-Signature", encoding: "HEX", prefix: "sha256=", messageFormat: "TIMESTAMP_DOT_BODY", timestampHeader: "X-Test-Timestamp", timestampSecretRef: "billing_timestamp", tamper: false } });
  const step = (id: string, phase: string, actorId: string, endpointId: string, operation: string, req: unknown, options: Record<string, unknown> = {}) => ({ id, phase, actorId, endpointId, operation, request: req, ...options }); const state = (name: string, phase: string, captureFields: Array<[string, string]>) => step(`${phase.toLowerCase()}-${name}`, phase, "service", "state", "OBSERVE", request("GET", `${origin}/state/${name}`), { captures: captureFields.map(([capture, path]) => ({ name: capture, source: "JSON", path })) }); const reset = (name: string) => step(`reset-${name}`, "CLEANUP", "service", "control", "RESET_FIXTURE", request("POST", `${origin}/__routecairn__/billing-fixtures/reset/${name}`, "primary", { fixture: "{{SECRET:fixture_marker}}" })); const cleanupState = (name: string, capture: string, path: string) => state(name, "CLEANUP", [[capture, path]]); const valueSecret = (id: string, scope: string, dimension: string, capture: string, secretRef: string) => ({ id, scope, kind: "VALUE_EQUALS_SECRET", dimension, capture, secretSource: "primary", secretRef }); const delta = (id: string, scope: string, before: string, after: string, expected = 1) => ({ id, scope, kind: "EVENT_COUNT_DELTA", dimension: "EVENT_COUNT", before, after, operator: "LTE", expected });
  const cases = [
    { id: "price-manipulation", label: "client price manipulation", category: "CLIENT_PRICE_MANIPULATION", authorization: controlled, cleanupRequired: true, steps: [state("price", "PRE_STATE", [["price_before", "price"]]), step("price-attempt", "ACTION", "service", "checkout", "CHECKOUT_VALIDATION", request("POST", `${origin}/__routecairn__/billing-fixtures/checkout/price`, "primary", { price: "{{SECRET:manipulated_price}}" }), { expectation: expectation("REJECT") }), state("price", "VERIFY", [["price_after", "price"]]), reset("price"), cleanupState("price", "price_restored", "price")], assertions: [valueSecret("price-authoritative", "MAIN", "PRICE", "price_after", "expected_price"), valueSecret("price-cleanup", "CLEANUP", "PRICE", "price_restored", "expected_price")] },
    { id: "product-substitution", label: "product plan substitution", category: "PRODUCT_PLAN_SUBSTITUTION", authorization: controlled, cleanupRequired: true, steps: [state("product", "PRE_STATE", [["product_before", "product"]]), step("product-attempt", "ACTION", "service", "checkout", "CHECKOUT_VALIDATION", request("POST", `${origin}/__routecairn__/billing-fixtures/checkout/product`, "primary", { product: "{{SECRET:substituted_product}}" }), { expectation: expectation("REJECT") }), state("product", "VERIFY", [["product_after", "product"]]), reset("product"), cleanupState("product", "product_restored", "product")], assertions: [valueSecret("product-authoritative", "MAIN", "PRODUCT", "product_after", "expected_product"), valueSecret("product-cleanup", "CLEANUP", "PRODUCT", "product_restored", "expected_product")] },
    { id: "unverified-entitlement", label: "unverified payment entitlement", category: "UNVERIFIED_PAYMENT_ENTITLEMENT", authorization: controlled, cleanupRequired: true, steps: [state("unverified", "PRE_STATE", [["unverified_before", "entitlement"]]), step("failed-event", "ACTION", "public", "webhook", "SYNTHETIC_PAYMENT_EVENT", signed("unverified", "event_unverified"), { expectation: expectation("ACCEPT") }), state("unverified", "VERIFY", [["payment_verified_after", "paymentVerified"], ["unverified_after", "entitlement"]]), reset("unverified"), cleanupState("unverified", "unverified_restored", "entitlement")], assertions: [{ id: "payment-not-verified", scope: "MAIN", kind: "VALUE_EQUALS_LITERAL", dimension: "PAYMENT_VERIFICATION", capture: "payment_verified_after", expected: false }, { id: "no-entitlement", scope: "MAIN", kind: "VALUE_EQUALS_LITERAL", dimension: "ENTITLEMENT", capture: "unverified_after", expected: false }, { id: "unverified-cleanup", scope: "CLEANUP", kind: "VALUE_EQUALS_LITERAL", dimension: "ENTITLEMENT", capture: "unverified_restored", expected: false }] },
    { id: "cancellation-persistence", label: "cancellation entitlement persistence", category: "CANCELLATION_ENTITLEMENT_PERSISTENCE", authorization: controlled, cleanupRequired: true, steps: [state("cancel", "PRE_STATE", [["cancel_before", "subscriptionStatus"]]), step("cancel-action", "ACTION", "service", "control", "CANCEL_FIXTURE", request("POST", `${origin}/__routecairn__/billing-fixtures/cancel`, "primary", { subscriptionId: "{{SECRET:subscription_fixture}}" }), { expectation: expectation("ACCEPT") }), state("cancel", "VERIFY", [["cancel_status_after", "subscriptionStatus"], ["cancel_entitlement_after", "entitlement"]]), reset("cancel"), cleanupState("cancel", "cancel_restored", "subscriptionStatus")], assertions: [valueSecret("cancel-status", "MAIN", "SUBSCRIPTION_STATUS", "cancel_status_after", "canceled_status"), { id: "cancel-entitlement", scope: "MAIN", kind: "VALUE_EQUALS_LITERAL", dimension: "ENTITLEMENT", capture: "cancel_entitlement_after", expected: false }, valueSecret("cancel-cleanup", "CLEANUP", "SUBSCRIPTION_STATUS", "cancel_restored", "active_status")] },
    duplicateCase("duplicate-webhook", "DUPLICATE_WEBHOOK_PROCESSING", "duplicate", "event_duplicate"), duplicateCase("replayed-event", "REPLAYED_PAYMENT_EVENT", "replay", "event_replay"),
    { id: "cross-account-premium", label: "cross account premium access", category: "CROSS_ACCOUNT_PREMIUM_ACCESS", authorization: observeOnly, steps: [step("owner-premium", "ACTION", "owner", "premium", "PREMIUM_ACCESS_PROBE", request("GET", `${origin}/premium/owner`), { expectation: expectation("NOT_EVALUATED", "ALLOW") }), step("foreign-premium", "ACTION", "foreign", "premium", "PREMIUM_ACCESS_PROBE", request("GET", `${origin}/premium/owner`), { expectation: expectation("NOT_EVALUATED", "DENY") })], assertions: [{ id: "premium-denied", scope: "MAIN", kind: "ACTION_OUTCOME_COUNT", dimension: "ACCESS", stepId: "foreign-premium", outcome: "DENIED", operator: "EQ", expected: 1 }] },
    { id: "refund-consistency", label: "refund downgrade consistency", category: "REFUND_DOWNGRADE_CONSISTENCY", authorization: controlled, cleanupRequired: true, steps: [state("refund", "PRE_STATE", [["refund_before", "refundStatus"]]), step("refund-action", "ACTION", "service", "control", "REFUND_FIXTURE", request("POST", `${origin}/__routecairn__/billing-fixtures/refund`, "primary", { subscriptionId: "{{SECRET:subscription_fixture}}" }), { expectation: expectation("ACCEPT") }), state("refund", "VERIFY", [["refund_status_after", "refundStatus"], ["refund_entitlement_after", "entitlement"]]), reset("refund"), cleanupState("refund", "refund_restored", "refundStatus")], assertions: [valueSecret("refund-status", "MAIN", "REFUND_STATUS", "refund_status_after", "refunded_status"), { id: "refund-entitlement", scope: "MAIN", kind: "VALUE_EQUALS_LITERAL", dimension: "ENTITLEMENT", capture: "refund_entitlement_after", expected: false }, valueSecret("refund-cleanup", "CLEANUP", "REFUND_STATUS", "refund_restored", "none_status")] },
    { id: "subscription-ownership", label: "subscription ownership confusion", category: "SUBSCRIPTION_OWNERSHIP_CONFUSION", authorization: observeOnly, steps: [step("owner-subscription", "ACTION", "owner", "subscription", "SUBSCRIPTION_ACCESS_PROBE", request("GET", `${origin}/subscriptions/{{SECRET:subscription_id}}`, "account_a"), { expectation: expectation("NOT_EVALUATED", "ALLOW"), captures: [{ name: "subscription_owner", source: "JSON", path: "owner" }] }), step("foreign-subscription", "ACTION", "foreign", "subscription", "SUBSCRIPTION_ACCESS_PROBE", request("GET", `${origin}/subscriptions/{{SECRET:subscription_id}}`, "account_a"), { expectation: expectation("NOT_EVALUATED", "DENY") })], assertions: [{ id: "owner-binding", scope: "MAIN", kind: "VALUE_EQUALS_SECRET", dimension: "OWNER", capture: "subscription_owner", secretSource: "account_a", secretRef: "owner_id" }, { id: "foreign-denied", scope: "MAIN", kind: "ACTION_OUTCOME_COUNT", dimension: "ACCESS", stepId: "foreign-subscription", outcome: "DENIED", operator: "EQ", expected: 1 }] },
    { id: "payment-race", label: "payment event race", category: "PAYMENT_EVENT_RACE", authorization: controlled, cleanupRequired: true, steps: [state("race", "PRE_STATE", [["race_before", "eventCount"]]), step("race-events", "ACTION", "public", "webhook", "SYNTHETIC_PAYMENT_EVENT", signed("race", "event_race"), { execution: { mode: "SYNCHRONIZED", attempts: 2, maxDispatchSkewMs: 1000 }, expectation: expectation("ACCEPT") }), state("race", "VERIFY", [["race_after", "eventCount"]]), reset("race"), cleanupState("race", "race_restored", "eventCount")], assertions: [delta("race-once", "MAIN", "race_before", "race_after"), { id: "race-cleanup", scope: "CLEANUP", kind: "VALUE_EQUALS_LITERAL", dimension: "EVENT_COUNT", capture: "race_restored", expected: 0 }] }
  ];
  function duplicateCase(id: string, category: string, name: string, eventRef: string) { return { id, label: id, category, authorization: controlled, cleanupRequired: true, steps: [state(name, "PRE_STATE", [[`${name}_before`, "eventCount"]]), step(`${name}-events`, "ACTION", "public", "webhook", "SYNTHETIC_PAYMENT_EVENT", signed(name, eventRef), { execution: { mode: "SEQUENTIAL_DUPLICATE", attempts: 2, maxDispatchSkewMs: 250 }, expectation: expectation("ACCEPT") }), state(name, "VERIFY", [[`${name}_after`, "eventCount"]]), reset(name), cleanupState(name, `${name}_restored`, "eventCount")], assertions: [delta(`${name}-once`, "MAIN", `${name}_before`, `${name}_after`), { id: `${name}-cleanup`, scope: "CLEANUP", kind: "VALUE_EQUALS_LITERAL", dimension: "EVENT_COUNT", capture: `${name}_restored`, expected: 0 }] }; }
  return { schemaVersion: 1, maxCases: 20, maxRequests: 60, maxResponseBytes: 65536, maxConcurrency: 3, provider: { kind: "CUSTOM_SYNTHETIC", mode: "TEST", fixturePathPrefix: "/__routecairn__/billing-fixtures", realPaymentExecution: "FORBIDDEN" }, actors, endpoints, cases };
}
function primarySecrets(): Record<string, string> { return { billing_hmac: hmacKey, billing_timestamp: hmacTimestamp, fixture_marker: "synthetic-fixture-private", manipulated_price: "1", expected_price: "1250", substituted_product: "basic-plan", expected_product: "premium-plan", synthetic_payment_status: "failed", event_unverified: "event-unverified-private", event_duplicate: "event-duplicate-private", event_replay: "event-replay-private", event_race: "event-race-private", subscription_fixture: "subscription-fixture-private", canceled_status: "canceled", active_status: "active", refunded_status: "refunded", none_status: "none" }; }
function profile(principalId: string, tenantId: string, token: string, lifecycleSecrets: Record<string, string>): unknown { return { label: principalId, safeAlias: principalId, principalId, tenantId, headers: { Authorization: `Bearer ${token}` }, cookies: [], lifecycleSecrets, notes: [] }; }
function validSignature(request: IncomingMessage, raw: string): boolean { const supplied = Buffer.from(String(request.headers["x-test-signature"] ?? "")); const expected = Buffer.from(`sha256=${createHmac("sha256", hmacKey).update(`${hmacTimestamp}.${raw}`).digest("hex")}`); return String(request.headers["x-test-timestamp"] ?? "") === hmacTimestamp && supplied.length === expected.length && timingSafeEqual(supplied, expected); }
function json(response: ServerResponse, status: number, value: unknown): void { response.writeHead(status, { "content-type": "application/json" }).end(JSON.stringify(value)); }
async function body(request: IncomingMessage): Promise<string> { const chunks: Buffer[] = []; for await (const chunk of request) chunks.push(Buffer.from(chunk)); return Buffer.concat(chunks).toString("utf8"); }
async function writeJson(directory: string, name: string, value: unknown): Promise<string> { const path = join(directory, name); await writeFile(path, JSON.stringify(value)); return path; }
