import { beforeAll,afterAll,describe,it,expect } from "vitest";
import { createHash,createHmac,generateKeyPairSync,randomBytes,randomUUID,sign } from "node:crypto";
import { exportJWK,SignJWT } from "jose";
import { Agent } from "undici";
import { mkdir,readFile,writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { PostgresControlPlane,PostgresLeaderElection } from "../../src/controlPlane/PostgresControlPlane.js";
import { PostgresRemoteWorkerService } from "../../src/controlPlane/PostgresRemoteWorkerService.js";
import { ControlPlaneTelemetry } from "../../src/controlPlane/Telemetry.js";
import { controlPlaneConfigFromEnv } from "../../src/controlPlane/ControlPlaneConfig.js";
import { S3EvidenceObjectStore } from "../../src/controlPlane/ObjectStorage.js";
import { KmsEnvelopeKeyManager } from "../../src/controlPlane/KeyManagement.js";
import { acquireDashboardSingleton } from "../../src/controlPlane/DashboardSingleton.js";
import { KMSClient,CreateKeyCommand } from "@aws-sdk/client-kms";
import { S3Client,PutObjectCommand } from "@aws-sdk/client-s3";
// The JavaScript harness owns native service processes, or consumes explicitly supplied CI service endpoints.
// @ts-expect-error test-only service harness is JavaScript
import { startNativeScaleLab,startFleetReplica,eventually,startIdentityLab } from "../helpers/control-plane-lab.mjs";

const enabled=process.env.ROUTECAIRN_SCALE_LIVE==="true";
describe.runIf(enabled)("live distributed control plane",()=>{
  let lab:any,control:PostgresControlPlane,peer:PostgresControlPlane,service:PostgresRemoteWorkerService,other:PostgresRemoteWorkerService,replicas:any[],store:S3EvidenceObjectStore;
  let environment:NodeJS.ProcessEnv;
  const organization=randomUUID(),foreign=randomUUID(),keys=generateKeyPairSync("ed25519");
  let worker:any;const workers:any[]=[];
  const checks:string[]=[];
  let identityLab:any;
  const identityKeys=generateKeyPairSync('ed25519'),identityDisposers:Array<()=>Promise<unknown>>=[];
  function passed(name:string){checks.push(name);}
  beforeAll(async()=>{
    lab=await startNativeScaleLab();environment=lab.environment;
    const config=controlPlaneConfigFromEnv(environment),telemetry=new ControlPlaneTelemetry({...config.telemetry,otlpEndpoint:undefined} as any);
    control=new PostgresControlPlane(config.postgres!,telemetry);peer=new PostgresControlPlane(config.postgres!,telemetry);
    await Promise.all([control.start(),peer.start()]);
    service=new PostgresRemoteWorkerService(control,telemetry,15_000,0);other=new PostgresRemoteWorkerService(peer,telemetry,15_000,0);
    const enrollment=await service.createEnrollment({organizationId:organization,expiresInMinutes:5},"lab-operator");
    const enrolled=await service.enroll({token:enrollment.token,name:"private-zone-worker",publicKeyPem:keys.publicKey.export({format:"pem",type:"spki"}).toString(),capabilities:["ping"],labels:{networkZone:"private"}});
    worker=await authenticated(service,enrolled.workerId,keys.privateKey);
    workers.push(worker);
    for(let i=0;i<3;i++){const pair=generateKeyPairSync('ed25519');const enrollment=await service.createEnrollment({organizationId:organization,expiresInMinutes:5},'operator');const enrolled=await service.enroll({token:enrollment.token,name:`parallel-${i}`,publicKeyPem:pair.publicKey.export({format:'pem',type:'spki'}).toString(),capabilities:['ping'],labels:{networkZone:'private'}});workers.push(await authenticated(service,enrolled.workerId,pair.privateKey));}
    store=new S3EvidenceObjectStore(config.objectStorage as any,control);
    replicas=await Promise.all([startFleetReplica({...environment,ROUTECAIRN_INSTANCE_ID:`lab-a-${randomUUID()}`}),startFleetReplica({...environment,ROUTECAIRN_INSTANCE_ID:`lab-b-${randomUUID()}`})]);
    identityLab=await startIdentityLab(lab.directory,{keys:[{...await exportJWK(identityKeys.publicKey),kid:'owned-lab',alg:'EdDSA',use:'sig'}]});
  },120_000);
  afterAll(async()=>{
    await Promise.all((replicas??[]).map((item)=>item.stop()));
    await Promise.all(identityDisposers.map((dispose)=>dispose()));await identityLab?.close();
    await Promise.all([store?.shutdown(),control?.shutdown(),peer?.shutdown()]);await lab?.close();
    if(lab){const telemetry=await readFile(lab.telemetryPath,'utf8').catch(()=>"");await writeFile(resolve(process.env.ROUTECAIRN_SCALE_PROOF??'.routecairn-scale-lab/runtime-proof.json'),JSON.stringify({schemaVersion:1,createdAt:new Date().toISOString(),classification:"SELF_MAINTAINED_LOOPBACK_DEPLOYMENT",postgres:"native PostgreSQL 17.11",objectStorage:"native MinIO source 07c3a429bfed; provider encryption policy",kms:"Moto 5.1.12 emulator; no AWS/HSM claim",telemetry:"OpenTelemetry Collector 0.135.0",replicas:2,checks,cleanup:'CONFIRMED',telemetryReceived:{traces:telemetry.includes('resourceSpans'),metrics:telemetry.includes('resourceMetrics')},binaries:lab.provenance,kubernetesExecuted:false,publicDeployment:false},null,2));}
  },60_000);

  const enqueue=(extra:Record<string,unknown>={})=>service.enqueue({organizationId:organization,kind:"PING",payload:{caseId:randomUUID()},requiredCapabilities:[],priority:0,maxAttempts:3,...extra},"lab-operator");
  it("migrates shared PostgreSQL schema idempotently",async()=>{expect(await control.ready()).toBe(true);expect(await peer.ready()).toBe(true);passed("shared schema migration");});
  it("runs two independent built CLI replica processes",async()=>{expect(replicas[0].process.pid).not.toBe(replicas[1].process.pid);for(const replica of replicas)expect((await(await fetch(`${replica.url}/readyz`)).json()).role).toBe("fleet");passed("two CLI replicas");});
  it("claims concurrent jobs exactly once across replicas",async()=>{const ids=await Promise.all(Array.from({length:24},()=>enqueue()));const claims=await Promise.all(ids.map((_,i)=>(i%2?other:service).claim(workers[i%4],0)));const jobs=claims.map((item:any)=>item.job);expect(new Set(jobs.map((job:any)=>job.id)).size).toBe(24);expect(jobs.every((job:any)=>ids.includes(job.id))).toBe(true);await Promise.all(jobs.map((job:any,i:number)=>service.complete(workers[i%4],job.id,{leaseToken:job.leaseToken,status:"COMPLETED",result:{ok:true}})));passed("24 concurrent claims across four workers without duplicate leasing");});
  it("preserves tenant, capability and network zone placement",async()=>{const ids=await Promise.all([enqueue({organizationId:foreign}),enqueue({requiredCapabilities:["scan"]}),enqueue({networkZone:"public"})]);expect(await service.claim(worker,0)).toEqual({job:null});await control.pool.query("DELETE FROM routecairn_control.jobs WHERE id=ANY($1::uuid[])",[ids]);passed("tenant capability zone isolation");});
  it("atomically commits job state and outbox events",async()=>{const id=await enqueue();const result=await control.pool.query("SELECT COUNT(*)::int AS count FROM routecairn_control.outbox WHERE payload->>'jobId'=$1 AND payload->>'type'='queued'",[id]);expect(result.rows[0].count).toBe(1);const claim:any=await other.claim(worker,0);await service.complete(worker,id,{leaseToken:claim.job.leaseToken,status:"COMPLETED"});passed("transactional job outbox");});
  it("recovers an expired worker lease and rejects its stale token",async()=>{const id=await enqueue();const initial:any=await service.claim(worker,0);await control.pool.query("UPDATE routecairn_control.jobs SET lease_expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[id]);const next:any=await other.claim(worker,0);expect(next.job.id).toBe(id);expect(next.job.leaseToken).not.toBe(initial.job.leaseToken);await expect(service.complete(worker,id,{leaseToken:initial.job.leaseToken,status:"COMPLETED"})).rejects.toThrow("LEASE_REJECTED");await other.complete(worker,id,{leaseToken:next.job.leaseToken,status:"COMPLETED"});passed("lease recovery and stale completion rejection");});
  it("exhausts attempts with a terminal timestamp",async()=>{const id=await enqueue({maxAttempts:1});await service.claim(worker,0);await control.pool.query("UPDATE routecairn_control.jobs SET lease_expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[id]);expect(await other.claim(worker,0)).toEqual({job:null});const row=await control.pool.query("SELECT status,completed_at FROM routecairn_control.jobs WHERE id=$1",[id]);expect(row.rows[0].status).toBe("FAILED");expect(row.rows[0].completed_at).toBeInstanceOf(Date);passed("bounded attempt exhaustion");});
  it("renews leases against database time",async()=>{const id=await enqueue();const claim:any=await service.claim(worker,0);expect(Date.parse((await other.renew(worker,id,claim.job.leaseToken)).leaseExpiresAt)).toBeGreaterThan(Date.now());await other.complete(worker,id,{leaseToken:claim.job.leaseToken,status:"COMPLETED"});passed("cross-replica lease renewal");});
  it("rejects signed request replay globally across replicas",async()=>{const input=signed(worker.id,keys.privateKey,'/api/remote-agents/worker/heartbeat',{status:"ONLINE",resources:{cpuPercent:0,memoryBytes:1,activeJobs:0}});expect((await send(replicas[0].url,input)).status).toBe(200);expect((await send(replicas[1].url,input)).status).toBe(401);passed("global nonce replay rejection");});
  it("completes jobs through a second HTTP replica",async()=>{const id=await enqueue();const claimResponse=await send(replicas[0].url,signed(worker.id,keys.privateKey,'/api/remote-agents/worker/claim',{}));const claim=await claimResponse.json();expect(claim.job.id).toBe(id);const completion=await send(replicas[1].url,signed(worker.id,keys.privateKey,`/api/remote-agents/worker/jobs/${id}/complete`,{status:"COMPLETED",leaseToken:claim.job.leaseToken,result:{ok:true}}));expect(completion.status).toBe(200);passed("HTTP claim and completion across replicas");});
  it("fails over after one ingress replica stops",async()=>{await replicas[0].stop();const response=await send(replicas[1].url,signed(worker.id,keys.privateKey,'/api/remote-agents/worker/heartbeat',{status:"ONLINE",resources:{cpuPercent:0,memoryBytes:1,activeJobs:0}}));expect(response.status).toBe(200);passed("ingress process failover");});
  it("wakes long polls on new work",async()=>{const pending=other.claim(worker,5000);await new Promise(done=>setTimeout(done,100));const id=await enqueue();const claim:any=await pending;expect(claim.job.id).toBe(id);await service.complete(worker,id,{leaseToken:claim.job.leaseToken,status:"COMPLETED"});passed("event-driven bounded long polling");});
  it("recovers notifications after listener disconnect",async()=>{const events:string[]=[];const unsubscribe=peer.subscribe("lab-events",(_partition,payload)=>events.push(String(payload.caseId)));try{await control.pool.query("SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE application_name='routecairn-events'");const id=randomUUID();await control.publish("lab-events",organization,{caseId:id});await eventually(()=>events.includes(id));expect(events.filter(item=>item===id)).toHaveLength(1);passed("durable outbox recovery after LISTEN disconnect");}finally{unsubscribe();}});
  it("serializes event commits so cursors cannot skip lower IDs",async()=>{const received:number[]=[];const unsubscribe=peer.subscribe("lab-order",(_partition,payload)=>received.push(Number(payload.position)));try{const first=control.transaction(async(client)=>{await control.publishInTransaction(client,"lab-order",organization,{position:1});await client.query("SELECT pg_sleep(0.2)");});await new Promise(done=>setTimeout(done,30));const second=peer.publish("lab-order",organization,{position:2});await Promise.all([first,second]);await eventually(()=>received.length===2);expect(received).toEqual([1,2]);passed("ordered outbox commit cursors");}finally{unsubscribe();}});
  it("elects one leader and increases fencing after failover",async()=>{const a=new PostgresLeaderElection(control,'leader-a',5000),b=new PostgresLeaderElection(peer,'leader-b',5000),key=`lab-${randomUUID()}`;try{await a.start(key,async()=>{});await b.start(key,async()=>{});expect(a.isLeader()).toBe(true);expect(b.isLeader()).toBe(false);const fence=a.token();await a.shutdown();await eventually(()=>b.isLeader(),8000);expect(b.token()).toBeGreaterThan(fence);await expect(control.fencedTransaction(key,'leader-a',fence,async()=>{})).rejects.toThrow("FENCE_REJECTED");await peer.fencedTransaction(key,'leader-b',b.token(),async(client)=>{await client.query('SELECT 1');});passed("leader failover and stale fencing rejection");}finally{await a.shutdown();await b.shutdown();}});
  it("blocks a second SQLite dashboard owner before it mutates local state",async()=>{const owner=await acquireDashboardSingleton(environment);try{await expect(acquireDashboardSingleton(environment)).rejects.toThrow("SINGLETON_REQUIRED");}finally{await owner.release();}const next=await acquireDashboardSingleton(environment);await next.release();passed("dashboard singleton ownership and restart");});
  it("uploads and retrieves evidence from MinIO through another replica",async()=>{const item=await evidence(lab.directory,organization);await store.put(item);const config=controlPlaneConfigFromEnv(environment);const second=new S3EvidenceObjectStore(config.objectStorage as any,peer);try{const metadata=await second.lookup(item.artifactId,organization);expect(metadata?.sha256).toBe(item.sha256);const path=await second.materialize({...item,path:""},resolve(lab.directory,'cache'));expect(await readFile(path,'utf8')).toBe('redacted evidence\n');expect(await second.lookup(item.artifactId,foreign)).toBeUndefined();passed("cross-replica S3 evidence and tenant isolation");}finally{await second.shutdown();}});
  it("rejects artifact identity overwrite and metadata spoofing",async()=>{const item=await evidence(lab.directory,organization);await store.put(item);await expect(store.put({...item,organizationId:foreign})).rejects.toThrow("IDENTITY_CONFLICT");await expect(store.materialize({...item,size:item.size+1},resolve(lab.directory,'bad-cache'))).rejects.toThrow("UNAVAILABLE");passed("immutable artifact ownership and metadata");});
  it("rejects object tampering and leaves no downloaded evidence",async()=>{const item=await evidence(lab.directory,organization);const result=await store.put(item);const s3=new S3Client({region:'us-east-1',endpoint:environment.ROUTECAIRN_EVIDENCE_S3_ENDPOINT,forcePathStyle:true,credentials:{accessKeyId:environment.AWS_ACCESS_KEY_ID!,secretAccessKey:environment.AWS_SECRET_ACCESS_KEY!}});try{await s3.send(new PutObjectCommand({Bucket:environment.ROUTECAIRN_EVIDENCE_S3_BUCKET,Key:result.key,Body:'tampered'}));await expect(store.materialize({...item,path:""},resolve(lab.directory,'tampered-cache'))).rejects.toThrow("METADATA_MISMATCH");passed("S3 tamper rejection");}finally{s3.destroy();}});
  it("wraps and unwraps data keys over the real AWS SDK HTTP path to Moto",async()=>{const previous={access:process.env.AWS_ACCESS_KEY_ID,secret:process.env.AWS_SECRET_ACCESS_KEY};process.env.AWS_ACCESS_KEY_ID=environment.AWS_ACCESS_KEY_ID;process.env.AWS_SECRET_ACCESS_KEY=environment.AWS_SECRET_ACCESS_KEY;const client=new KMSClient({region:'us-east-1',endpoint:environment.ROUTECAIRN_LAB_KMS_ENDPOINT});let manager:KmsEnvelopeKeyManager|undefined;try{const key=await client.send(new CreateKeyCommand({}));manager=new KmsEnvelopeKeyManager(key.KeyMetadata!.KeyId!,'us-east-1',environment.ROUTECAIRN_LAB_KMS_ENDPOINT);const envelope=await manager.encrypt(Buffer.from('bounded private fixture'),{organizationId:organization,purpose:'scale-lab'});expect((await manager.decrypt(envelope)).toString()).toBe('bounded private fixture');await expect(manager.decrypt({...envelope,context:{...envelope.context,organizationId:foreign}})).rejects.toThrow();await expect(manager.decrypt({...envelope,iv:'bad'})).rejects.toThrow();passed("KMS emulator envelope context and tamper validation");}finally{manager?.shutdown();client.destroy();if(previous.access===undefined)delete process.env.AWS_ACCESS_KEY_ID;else process.env.AWS_ACCESS_KEY_ID=previous.access;if(previous.secret===undefined)delete process.env.AWS_SECRET_ACCESS_KEY;else process.env.AWS_SECRET_ACCESS_KEY=previous.secret;}});
  it("exports traces and metrics to an actual collector",async()=>{await eventually(async()=>{const data=await readFile(lab.telemetryPath,'utf8');return data.includes('resourceSpans')&&data.includes('resourceMetrics');},25000);passed("OTLP traces and metrics collector receipt");});
  it("retains durable jobs across an actual PostgreSQL restart",async()=>{const id=await enqueue();await lab.restartDatabase();await eventually(()=>control.ready());await eventually(()=>peer.ready());const claim:any=await service.claim(worker,0);expect(claim.job.id).toBe(id);await service.complete(worker,id,{leaseToken:claim.job.leaseToken,status:'COMPLETED'});passed("PostgreSQL process restart and durable job recovery");});
  it("binds issuer and subject to an enrolled workload over HTTPS JWKS discovery",async()=>{
    const subject='system:serviceaccount:owned:worker',pair=generateKeyPairSync('ed25519');
    const enrollment=await service.createEnrollment({organizationId:organization,expiresInMinutes:5,workloadIdentity:{kind:'oidc',issuer:identityLab.issuer,subject}},'operator');
    const enrolled=await service.enroll({token:enrollment.token,name:'oidc-worker',publicKeyPem:pair.publicKey.export({format:'pem',type:'spki'}).toString(),capabilities:['ping'],labels:{}});
    const replica=await startFleetReplica({...environment,ROUTECAIRN_INSTANCE_ID:`oidc-${randomUUID()}`,NODE_EXTRA_CA_CERTS:identityLab.caFile,ROUTECAIRN_WORKLOAD_IDENTITY_REQUIRED:'true',ROUTECAIRN_WORKLOAD_IDENTITY_ISSUERS:identityLab.issuer,ROUTECAIRN_WORKLOAD_IDENTITY_AUDIENCE:'routecairn-fleet'});identityDisposers.push(()=>replica.stop());
    const token=(value:string,issuer=identityLab.issuer,expiration='5m')=>new SignJWT({}).setProtectedHeader({alg:'EdDSA',kid:'owned-lab'}).setIssuer(issuer).setSubject(value).setAudience('routecairn-fleet').setIssuedAt().setExpirationTime(expiration).sign(identityKeys.privateKey);
    const request=async(bearer?:string)=>{const input=signed(enrolled.workerId,pair.privateKey,'/api/remote-agents/worker/heartbeat',{status:'ONLINE',resources:{cpuPercent:0,memoryBytes:1,activeJobs:0}});return fetch(replica.url+input.path,{method:'POST',headers:{...input.headers,...(bearer?{authorization:`Bearer ${bearer}`}:{})},body:input.body});};
    expect((await request(await token(subject))).status).toBe(200);
    expect((await request()).status).toBe(401);expect((await request(await token('different-subject'))).status).toBe(401);expect((await request(await token(subject,'https://untrusted.invalid'))).status).toBe(401);expect((await request(await token(subject,identityLab.issuer,'-2m'))).status).toBe(401);
    passed("HTTPS OIDC workload binding, missing identity, issuer, subject and expiration rejection");
  },30000);
  it("binds actual mutually authenticated TLS certificates to workers",async()=>{
    const ca=await readFile(identityLab.caFile),first=identityLab.certificates['worker-a'],second=identityLab.certificates['worker-b'];
    const dispatcher=new Agent({connect:{ca,cert:await readFile(first.certFile),key:await readFile(first.keyFile)}}),wrong=new Agent({connect:{ca,cert:await readFile(second.certFile),key:await readFile(second.keyFile)}});identityDisposers.push(()=>dispatcher.close(),()=>wrong.close());
    const replica=await startFleetReplica({...environment,ROUTECAIRN_INSTANCE_ID:`mtls-${randomUUID()}`,ROUTECAIRN_WORKLOAD_IDENTITY_REQUIRED:'true',ROUTECAIRN_WORKLOAD_IDENTITY_DIRECT_MTLS:'true'},{...identityLab.certificates.server,caFile:identityLab.caFile,dispatcher});identityDisposers.push(()=>replica.stop());
    const pair=generateKeyPairSync('ed25519'),enrollment=await service.createEnrollment({organizationId:organization,expiresInMinutes:5,workloadIdentity:{kind:'mtls',fingerprint:first.fingerprint}},'operator');const enrolled=await service.enroll({token:enrollment.token,name:'mtls-worker',publicKeyPem:pair.publicKey.export({format:'pem',type:'spki'}).toString(),capabilities:['ping'],labels:{}});
    const request=(agent:Agent)=>{const input=signed(enrolled.workerId,pair.privateKey,'/api/remote-agents/worker/heartbeat',{status:'ONLINE',resources:{cpuPercent:0,memoryBytes:1,activeJobs:0}});return fetch(replica.url+input.path,{method:'POST',headers:input.headers,body:input.body,dispatcher:agent} as any);};
    expect((await request(dispatcher)).status).toBe(200);expect((await request(wrong)).status).toBe(401);passed("native mTLS handshake and certificate-to-worker binding");
  },30000);
  it("requires a fresh proxy attestation and a matching enrolled certificate",async()=>{
    const proxySecret=randomBytes(32).toString('hex'),fingerprint=identityLab.certificates['worker-a'].fingerprint,pair=generateKeyPairSync('ed25519');
    const enrollment=await service.createEnrollment({organizationId:organization,expiresInMinutes:5,workloadIdentity:{kind:'mtls',fingerprint}},'operator');const enrolled=await service.enroll({token:enrollment.token,name:'proxy-worker',publicKeyPem:pair.publicKey.export({format:'pem',type:'spki'}).toString(),capabilities:['ping'],labels:{}});
    const replica=await startFleetReplica({...environment,ROUTECAIRN_INSTANCE_ID:`proxy-${randomUUID()}`,ROUTECAIRN_WORKLOAD_IDENTITY_REQUIRED:'true',ROUTECAIRN_MTLS_PROXY_SECRET:proxySecret});identityDisposers.push(()=>replica.stop());
    const request=async(fp:string,proofSecret:string)=>{const input=signed(enrolled.workerId,pair.privateKey,'/api/remote-agents/worker/heartbeat',{status:'ONLINE',resources:{cpuPercent:0,memoryBytes:1,activeJobs:0}});const proof=createHmac('sha256',proofSecret).update(`${input.headers['x-routecairn-timestamp']}\n${enrolled.workerId}\n${fp}`).digest('base64url');return fetch(replica.url+input.path,{method:'POST',headers:{...input.headers,'x-routecairn-client-cert-fingerprint':fp,'x-routecairn-mtls-proof':proof},body:input.body});};
    expect((await request(fingerprint,proxySecret)).status).toBe(200);expect((await request(fingerprint,'incorrect-proxy-key')).status).toBe(401);expect((await request(identityLab.certificates['worker-b'].fingerprint,proxySecret)).status).toBe(401);passed("proxy mTLS proof and worker certificate binding");
  },30000);
  it("does not resurrect revoked workers or accept their stale job leases",async()=>{const id=await enqueue();const claim:any=await service.claim(worker,0);await other.setStatus(worker.id,"REVOKED");await expect(service.heartbeat(worker,{status:"ONLINE",resources:{cpuPercent:0,memoryBytes:1,activeJobs:0}})).rejects.toThrow("WORKER_REJECTED");expect(await service.claim(worker,0)).toEqual({job:null});await expect(service.renew(worker,id,claim.job.leaseToken)).rejects.toThrow("WORKER_REJECTED");await expect(service.complete(worker,id,{leaseToken:claim.job.leaseToken,status:"COMPLETED"})).rejects.toThrow("WORKER_REJECTED");passed("revocation fencing across stale authenticated requests");});
});

function canonical(value:unknown):string{return JSON.stringify(sort(value));}function sort(value:any):any{return Array.isArray(value)?value.map(sort):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,sort(item)])):value;}
function signed(workerId:string,key:any,path:string,body:unknown){const timestamp=new Date().toISOString(),nonce=randomBytes(24).toString('base64url'),serialized=canonical(body),hash=createHash('sha256').update(serialized).digest('hex');return{path,body:serialized,headers:{'content-type':'application/json','x-routecairn-worker-id':workerId,'x-routecairn-timestamp':timestamp,'x-routecairn-nonce':nonce,'x-routecairn-signature':sign(null,Buffer.from(['routecairn-agent-ed25519-v1','POST',path,timestamp,nonce,hash].join('\n')),key).toString('base64url')}};}
async function send(url:string,input:ReturnType<typeof signed>){return fetch(url+input.path,{method:'POST',headers:input.headers,body:input.body,signal:AbortSignal.timeout(10000)});}
async function authenticated(service:PostgresRemoteWorkerService,id:string,key:any){const input=signed(id,key,'/api/remote-agents/worker/claim',{});return service.authenticate('POST',input.path,{},input.headers);}
async function evidence(directory:string,organizationId:string){await mkdir(directory,{recursive:true});const artifactId=randomUUID(),path=resolve(directory,`${artifactId}.txt`),body='redacted evidence\n';await writeFile(path,body);return{artifactId,organizationId,path,sha256:createHash('sha256').update(body).digest('hex'),size:Buffer.byteLength(body),contentType:'text/plain'};}
