import { createServer, type IncomingMessage, type Server } from "node:http";
import type { AddressInfo } from "node:net";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { createHash } from "node:crypto";
import { gzipSync } from "node:zlib";
import { afterEach, describe, expect, it } from "vitest";
import { runScanCommand } from "../../src/cli/commands/scan.js";
import { exampleScope } from "../../src/config/defaults.js";
import type { ProtocolSecurityReport } from "../../src/modules/protocolSecurity/ProtocolSecurityTypes.js";

let server: Server | undefined; const directories: string[] = [];
afterEach(async () => { if (server) await new Promise<void>((resolve) => server!.close(() => resolve())); server = undefined; await Promise.all(directories.splice(0).map((value) => rm(value, { recursive: true, force: true }))); });

describe("protocol security integration", () => {
  it("executes bounded SSE plus an authorized GraphQL mutation and verified cleanup without payload persistence", async () => {
    let mutated = false; let cleanupCount = 0; let binaryUploadObserved = false; let multipartCreated = false; let multipartCleanupCount = 0;
    server = createServer(async (request, response) => {
      if (request.url === "/") return void response.writeHead(200).end("ok");
      if (request.url === "/events") { response.writeHead(200, { "content-type": "text/event-stream" }); response.end("event: ready\ndata: {\"scope\":\"member-private-value\"}\n\n"); return; }
      if (request.url === "/graphql" && request.method === "POST") { const raw = await body(request); mutated = raw.includes("UpdateFixture"); response.writeHead(200, { "content-type": "application/json" }).end('{"data":{"updateFixture":{"ok":true,"token":"response-private-value"}}}'); return; }
      if (request.url === "/inspect-upload" && request.method === "POST") { const raw = await rawBody(request); binaryUploadObserved = raw.indexOf(Buffer.from([0, 255, 1])) >= 0; multipartCreated = binaryUploadObserved; response.writeHead(binaryUploadObserved ? 201 : 400, { "content-type": "application/json" }).end('{"ok":true}'); return; }
      if (request.url === "/uploads/reset" && request.method === "POST") { if (request.headers.authorization !== "Bearer header-private-value") return void response.writeHead(401).end(); multipartCreated = false; multipartCleanupCount += 1; response.writeHead(204).end(); return; }
      if (request.url === "/fixtures/reset" && request.method === "POST") { if (request.headers.authorization !== "Bearer header-private-value") return void response.writeHead(401).end(); mutated = false; cleanupCount += 1; response.writeHead(204).end(); return; }
      response.writeHead(404).end();
    });
    server.on("upgrade", (_request, socket) => socket.end("HTTP/1.1 403 Forbidden\r\nContent-Length: 0\r\nConnection: close\r\n\r\n"));
    await new Promise<void>((resolve) => server!.listen(0, "127.0.0.1", resolve)); const origin = `http://127.0.0.1:${(server.address() as AddressInfo).port}`; const directory = await mkdtemp(join(tmpdir(), "routecairn-protocol-")); directories.push(directory); const now = Date.now();
    const approval = { environment: "TEST", operator: "operator-private-name", ticket: "ticket-private-123", authorizedAt: new Date(now - 1000).toISOString(), expiresAt: new Date(now + 60_000).toISOString(), confirmation: "I_AUTHORIZE_PROTOCOL_STATE_CHANGES", disposableResources: true } as const;
    const manifest = { schemaVersion: 1, maxRequests: 6, maxDurationMs: 3000, actors: [{ id: "member", safeAlias: "member", authSlot: "primary", relationship: "self" }], cases: [
      { id: "events", label: "events", kind: "SSE", actorId: "member", requireVerifiedIdentity: false, url: `${origin}/events`, headers: {}, method: "GET", maxEvents: 1, expectation: { decision: "ALLOW", allowedStatuses: [200], deniedStatuses: [401, 403], messageType: "ready", minMessages: 1 } },
      { id: "denied-socket", label: "denied socket", kind: "WEBSOCKET", actorId: "member", requireVerifiedIdentity: false, url: origin.replace(/^http:/, "ws:") + "/denied-socket", headers: {}, subprotocols: ["routecairn-test"], messages: [], maxMessages: 1, readOnly: true, expectation: { decision: "DENY", allowedStatuses: [101], deniedStatuses: [401, 403], minMessages: 0 } },
      { id: "upload", label: "controlled upload with cleanup", kind: "MULTIPART_UPLOAD", actorId: "member", requireVerifiedIdentity: false, url: `${origin}/inspect-upload`, headers: {}, fields: { purpose: "fixture" }, files: [{ fieldName: "file", fileName: "fixture.bin", contentType: "application/octet-stream", contentSecretRef: "upload_fixture" }], readOnly: false, expectation: { decision: "ALLOW", allowedStatuses: [201], deniedStatuses: [400, 401, 403], minMessages: 0 }, authorization: approval, cleanup: { url: `${origin}/uploads/reset`, method: "POST", headers: {}, body: { fixture: "{{SECRET:fixture_id}}" }, statusIn: [204] } },
      { id: "mutation", label: "controlled mutation", kind: "GRAPHQL_MUTATION", actorId: "member", requireVerifiedIdentity: false, url: `${origin}/graphql`, headers: {}, operationName: "UpdateFixture", document: "mutation UpdateFixture { updateFixture { ok } }", variables: { input: "{{SECRET:mutation_input}}" }, expectation: { decision: "ALLOW", allowedStatuses: [200], deniedStatuses: [400, 401, 403], jsonPath: "data.updateFixture.ok", equals: true, minMessages: 0 }, authorization: approval, cleanup: { url: `${origin}/fixtures/reset`, method: "POST", headers: {}, body: { fixture: "{{SECRET:fixture_id}}" }, statusIn: [204] } }
    ] };
    const scope = await writeJson(directory, "scope.json", { ...exampleScope, allowedDomains: ["127.0.0.1"], disallowedPaths: [], allowedMethods: ["GET", "HEAD", "OPTIONS", "POST"], rateLimitPerSecond: 50, concurrency: 2 });
    const auth = await writeJson(directory, "auth.json", { label: "member", safeAlias: "member", principalId: "member-private-id", headers: { Authorization: "Bearer header-private-value" }, lifecycleSecrets: { mutation_input: "input-private-value", fixture_id: "fixture-private-value", upload_fixture: "base64:AP8B" } });
    const result = await runScanCommand(`${origin}/`, { scope, auth, protocolSecurity: await writeJson(directory, "protocol.json", manifest), output: join(directory, "reports") }); const text = await readFile(result.reportPath, "utf8"); const markdown = await readFile(result.markdownReportPath, "utf8"); const html = await readFile(result.htmlReportPath, "utf8"); const report = JSON.parse(text) as { protocolSecurity: ProtocolSecurityReport };
    expect(report.protocolSecurity).toMatchObject({ plannedCases: 4, executedCases: 4, passedCases: 4, failedCases: 0, blockedCases: 0 }); expect(report.protocolSecurity.observations.find((value) => value.caseId === "denied-socket")).toMatchObject({ outcome: "PASS", statusCode: 403 }); expect(report.protocolSecurity.observations.find((value) => value.caseId === "upload")).toMatchObject({ cleanupOutcome: "ROLLBACK_VERIFIED" }); expect(report.protocolSecurity.observations.find((value) => value.caseId === "mutation")).toMatchObject({ cleanupOutcome: "ROLLBACK_VERIFIED" }); expect(mutated).toBe(false); expect(cleanupCount).toBe(1); expect(binaryUploadObserved).toBe(true); expect(multipartCreated).toBe(false); expect(multipartCleanupCount).toBe(1); expect(markdown).toContain("## Protocol-Level Security"); expect(html).toContain("Protocol-Level Security");
    for (const secret of ["member-private-value", "response-private-value", "operator-private-name", "ticket-private-123", "member-private-id", "header-private-value", "input-private-value", "fixture-private-value"]) { expect(text).not.toContain(secret); expect(html).not.toContain(secret); }
  }, 30_000);

  it("executes incremental, persisted, federation, compression, and cross-protocol identity contracts", async () => {
    let persistedRegistrations = 0; let persistedHits = 0; const document = "query Viewer { viewer { id } }"; const sha256Hash = createHash("sha256").update(document).digest("hex");
    server = createServer(async (request, response) => {
      if (request.url === "/") return void response.writeHead(200).end("ok");
      if (request.url === "/identity") return void response.writeHead(200, { "content-type": "application/json" }).end('{"subject":"stable-subject","role":"member"}');
      if (request.url === "/compressed") { const compressed = gzipSync(Buffer.from('{"ok":true}')); response.writeHead(200, { "content-type": "application/json", "content-encoding": "gzip" }).end(compressed); return; }
      if (request.url === "/graphql" && request.method === "POST") { const parsed = JSON.parse(await body(request)) as { query?: string; extensions?: { persistedQuery?: { sha256Hash?: string } } };
        if (parsed.query?.includes("@stream")) { const boundary = "routecairn-incremental"; response.writeHead(200, { "content-type": `multipart/mixed; boundary=${boundary}` }); response.end(`--${boundary}\r\ncontent-type: application/json\r\n\r\n{"data":{"feed":[{"id":"one"}]},"hasNext":true}\r\n--${boundary}\r\ncontent-type: application/json\r\n\r\n{"incremental":[{"path":["feed",1],"items":[{"id":"two"}]}],"hasNext":false}\r\n--${boundary}--\r\n`); return; }
        if (parsed.query?.includes("_service")) return void response.writeHead(200, { "content-type": "application/json" }).end('{"data":{"_service":{"sdl":"type Query { viewer: String }"}}}');
        if (parsed.extensions?.persistedQuery?.sha256Hash === sha256Hash) { if (parsed.query) persistedRegistrations += 1; else persistedHits += 1; return void response.writeHead(200, { "content-type": "application/json" }).end('{"data":{"viewer":{"id":"stable-id"}}}'); }
      }
      response.writeHead(404).end();
    });
    server.on("upgrade", (request, socket) => { const key = String(request.headers["sec-websocket-key"] ?? ""); const accept = createHash("sha1").update(`${key}258EAFA5-E914-47DA-95CA-C5AB0DC85B11`).digest("base64"); socket.write(`HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: ${accept}\r\nSec-WebSocket-Protocol: graphql-transport-ws\r\n\r\n`); let pending = Buffer.alloc(0), authorized = false; socket.on("data", (chunk) => { pending = Buffer.concat([pending, chunk]); while (true) { const frame = parseClientFrame(pending); if (!frame) break; pending = pending.subarray(frame.bytes); if (frame.opcode === 8) { socket.destroy(); return; } const message = JSON.parse(frame.payload.toString("utf8")) as { type: string; id?: string; payload?: { authorization?: string } }; if (message.type === "connection_init") { authorized = message.payload?.authorization === "new-session-secret"; if (authorized) socket.write(serverFrame({ type: "connection_ack" })); else socket.write(Buffer.concat([serverFrame({ type: "error", payload: { code: "UNAUTHORIZED" } }), Buffer.from([0x88, 0x00])])); } else if (authorized && message.type === "subscribe") { socket.write(Buffer.concat([serverFrame({ id: message.id, type: "next", payload: { data: { events: { __typename: "Event" } } } }), Buffer.from([0x88, 0x00])])); } } }); });
    await new Promise<void>((resolve) => server!.listen(0, "127.0.0.1", resolve)); const origin = `http://127.0.0.1:${(server.address() as AddressInfo).port}`; const directory = await mkdtemp(join(tmpdir(), "routecairn-protocol-expanded-")); directories.push(directory); const allow = { decision: "ALLOW", allowedStatuses: [200], deniedStatuses: [400, 401, 403], minMessages: 0 } as const;
    const manifest = { schemaVersion: 1, maxRequests: 12, maxDurationMs: 3000, actors: [{ id: "member", safeAlias: "member", authSlot: "primary", relationship: "self" }], cases: [
      { id: "incremental", label: "incremental", kind: "GRAPHQL_INCREMENTAL", actorId: "member", requireVerifiedIdentity: false, url: `${origin}/graphql`, headers: {}, document: "query Feed { feed @stream(initialCount: 1) { id } }", variables: {}, maxParts: 4, expectedPaths: ["feed.1"], expectation: { ...allow, minMessages: 2 } },
      { id: "persisted", label: "persisted", kind: "GRAPHQL_PERSISTED_QUERY", actorId: "member", requireVerifiedIdentity: false, url: `${origin}/graphql`, headers: {}, document, variables: {}, sha256Hash, negotiation: "REGISTER_THEN_HASH", expectation: { ...allow, jsonPath: "data.viewer.id", equals: "stable-id" } },
      { id: "federation", label: "federation", kind: "GRAPHQL_FEDERATION", actorId: "member", requireVerifiedIdentity: false, url: `${origin}/graphql`, headers: {}, operation: "SERVICE_SDL", expectation: { ...allow, jsonPath: "data._service.sdl" } },
      { id: "subscription-reauth", label: "subscription reauth", kind: "GRAPHQL_SUBSCRIPTION_REAUTH", actorId: "member", requireVerifiedIdentity: false, url: origin.replace(/^http:/, "ws:") + "/graphql", headers: {}, transport: "GRAPHQL_TRANSPORT_WS", document: "subscription Watch { events { __typename } }", variables: {}, initialConnectionPayload: { authorization: "{{SECRET:old_session}}" }, reauthConnectionPayload: { authorization: "{{SECRET:new_session}}" }, initialDecision: "DENY", maxMessages: 4, expectation: { decision: "ALLOW", allowedStatuses: [101], deniedStatuses: [401, 403], messageType: "next", minMessages: 1 } },
      { id: "compression", label: "compression", kind: "COMPRESSION_BOUNDARY", actorId: "member", requireVerifiedIdentity: false, url: `${origin}/compressed`, headers: {}, method: "GET", encoding: "gzip", maxExpandedBytes: 4096, readOnly: true, expectation: allow },
      { id: "identity", label: "identity", kind: "CROSS_PROTOCOL_IDENTITY", actorId: "member", requireVerifiedIdentity: false, url: `${origin}/identity`, headers: {}, legs: [{ protocol: "HTTP1", url: `${origin}/identity`, method: "GET", headers: {}, jsonPath: "subject" }, { protocol: "HTTP1", url: `${origin}/identity`, method: "GET", headers: {}, jsonPath: "subject" }], readOnly: true, expectation: allow }
    ] };
    const scope = await writeJson(directory, "scope.json", { ...exampleScope, allowedDomains: ["127.0.0.1"], disallowedPaths: [], allowedMethods: ["GET", "HEAD", "OPTIONS", "POST"], rateLimitPerSecond: 50, concurrency: 2 }); const auth = await writeJson(directory, "auth.json", { label: "member", safeAlias: "member", principalId: "member-id", headers: { Authorization: "Bearer api-session" }, lifecycleSecrets: { old_session: "old-session-secret", new_session: "new-session-secret" } }); const result = await runScanCommand(`${origin}/`, { scope, auth, protocolSecurity: await writeJson(directory, "protocol.json", manifest), output: join(directory, "reports") }); const report = JSON.parse(await readFile(result.reportPath, "utf8")) as { protocolSecurity: ProtocolSecurityReport };
    expect(report.protocolSecurity).toMatchObject({ plannedCases: 6, executedCases: 6, passedCases: 6, failedCases: 0, inconclusiveCases: 0 }); expect(persistedRegistrations).toBe(1); expect(persistedHits).toBe(1); expect(report.protocolSecurity.observations.find((value) => value.caseId === "incremental")).toMatchObject({ messageCount: 2, structuralCount: 1 }); expect(report.protocolSecurity.observations.find((value) => value.caseId === "subscription-reauth")).toMatchObject({ reason: "SUBSCRIPTION_REAUTH_CONTRACT_MATCHED" }); expect(JSON.stringify(report)).not.toContain("stable-subject"); expect(JSON.stringify(report)).not.toContain("stable-id"); expect(JSON.stringify(report)).not.toContain("new-session-secret");
  }, 30_000);
});

async function body(request: IncomingMessage): Promise<string> { const chunks: Buffer[] = []; for await (const chunk of request) chunks.push(Buffer.from(chunk)); return Buffer.concat(chunks).toString("utf8"); }
async function rawBody(request: IncomingMessage): Promise<Buffer> { const chunks: Buffer[] = []; for await (const chunk of request) chunks.push(Buffer.from(chunk)); return Buffer.concat(chunks); }
async function writeJson(directory: string, name: string, value: unknown): Promise<string> { const path = join(directory, name); await writeFile(path, JSON.stringify(value)); return path; }
function serverFrame(value: unknown): Buffer { const payload = Buffer.from(JSON.stringify(value)); return Buffer.concat([Buffer.from([0x81, payload.length]), payload]); }
function parseClientFrame(buffer: Buffer): { payload: Buffer; bytes: number; opcode: number } | undefined { if (buffer.length < 6) return; let length = buffer[1]! & 0x7f, offset = 2; if (length === 126) { if (buffer.length < 8) return; length = buffer.readUInt16BE(2); offset = 4; } if (length === 127) return; const mask = buffer.subarray(offset, offset + 4); offset += 4; if (buffer.length < offset + length) return; const payload = Buffer.alloc(length); for (let i = 0; i < length; i++) payload[i] = buffer[offset + i]! ^ mask[i % 4]!; return { payload, bytes: offset + length, opcode: buffer[0]! & 0x0f }; }
