import type { FindingType } from "../../core/findings/Finding.js";

export const recommendationRules: Record<FindingType, string> = {
  "Privilege Mutation Issue": "Authorize every authority-changing field server-side, derive identity and tenant from trusted session state, and regression-test the exact mutation and protected action.",
  "Admin/Login Panel": "Review whether this route is intended to be public and test access-control behavior within the authorized scope.",
  "API Endpoint": "Verify intended exposure and manually test authorization, object access, data exposure, and rate limiting.",
  "GraphQL Endpoint": "Verify intended exposure and manually test introspection, batching, depth limits, and authorization behavior.",
  "Security Header Issue": "Tune security headers according to application behavior and deployment requirements.",
  "Cookie Issue": "Set appropriate Secure, HttpOnly, SameSite, and Domain attributes based on cookie purpose.",
  "CORS Issue": "Restrict allowed origins to trusted origins and avoid credentials with wildcard or reflected origins.",
  "HTTP Method Issue": "Verify unsafe methods are required and protected by authentication and authorization controls.",
  "Object Authorization Issue": "Enforce server-side object authorization by checking owner, tenant, sharing, or role permission before returning private object fields.",
  "Field Exposure Issue": "Apply field-level authorization and response shaping before serializing sensitive fields for non-owner, public, tenant, or lower-privileged actors.",
  "Authorization Matrix Issue": "Enforce server-side authorization decisions consistently across declared roles, tenants, account states, relationships, and object states before returning protected objects.",
  "Equivalent Route Authorization Issue": "Apply the same centralized authorization policy across canonical, legacy, versioned, nested, export, mobile, alias, and compatibility routes that expose the same protected object.",
  "Collection Authorization Issue": "Filter collection, listing, search, count, and summary responses server-side using trusted principal, tenant, role, account-state, object-owner, and object-state authorization before returning results.",
  "Bulk Authorization Issue": "Authorize every object in non-mutating bulk preview, validation, dry-run, and summary workflows using trusted principal, tenant, role, account-state, owner, and object-state policy before returning bulk results.",
  "File Authorization Issue": "Authorize every file metadata, preview, download, and signed-URL issuance request using trusted principal, tenant, role, account-state, owner, sharing, and file-state policy before returning file data.",
  "Supabase Authorization Issue": "Enforce least-privilege Postgres grants and operation-specific RLS policies, then verify the exact anonymous, authenticated, cross-user, cross-tenant, storage, RPC, and service-role matrix cells.",
  "Supabase Configuration Risk": "Review the exact Supabase catalog object, revoke broad grants, enable and force RLS where appropriate, and harden storage policies and SECURITY DEFINER functions.",
  "Authentication Lifecycle Issue": "Enforce authentication lifecycle transitions atomically, bind and rotate tokens correctly, invalidate superseded sessions, and regression-test the explicit failed case.",
  "Business Logic Invariant Issue": "Enforce the invariant atomically in the authoritative data layer, add uniqueness or idempotency controls where applicable, and regression-test the exact failed workflow.",
  "Controlled Race Condition": "Enforce the raced operation atomically with transactions, locking, compare-and-swap state transitions, idempotency controls, and appropriate uniqueness constraints.",
  "API Authorization Issue": "Enforce object, function, field, and tenant authorization on every API route before returning data.",
  "GraphQL Authorization Issue": "Enforce authorization in every resolver and data-loader path, including aliases and batched queries.",
  "API Method Confusion": "Apply authorization before method dispatch and reject unsupported or overridden methods consistently.",
  "GraphQL Introspection Exposure": "Apply the intended introspection policy consistently for each environment and actor.",
  "GraphQL Limit Issue": "Enforce bounded alias, batch, depth, and complexity limits before resolver execution.",
  "API Schema Drift": "Validate deployed API routes and methods against the authoritative schema in CI.",
  "API Version Boundary Issue": "Apply equivalent authorization and field policy across versions and retire unsupported versions.",
  "Signed Link Security Issue": "Bind signatures to the canonical resource, audience, tenant, and expiry; enforce revocation and one-time use atomically where required.",
  "Invitation Security Issue": "Bind invitations to the intended identity and tenant, enforce expiry and atomic one-time acceptance, and invalidate them after use or revocation.",
  "Portal Tenant Isolation Issue": "Resolve portal tenant identity server-side and authorize every requested object against that trusted tenant context.",
  "Export Authorization Issue": "Authorize export retrieval at download time and bind short-lived export capabilities to the intended principal, tenant, and artifact.",
  "Evidence Artifact Authorization Issue": "Authorize every evidence-artifact request using trusted project, tenant, role, and ownership context instead of possession of an identifier alone.",
  "Object Path Authorization Issue": "Canonicalize the requested path and enforce ownership and tenant authorization on the resolved object before returning content.",
  "Webhook Security Issue": "Verify an HMAC over the exact raw body before parsing, reject stale or replayed event identifiers atomically, and validate payload values against authoritative business data.",
  "Cron Security Issue": "Require a dedicated scheduler identity, enforce replay protection and job-level authorization, and cap each run's scope and workload server-side.",
  "Job Authorization Issue": "Authorize job creation, inspection, cancellation, retry, and result access using trusted role, tenant, and job ownership context.",
  "Operational Endpoint Authorization Issue": "Apply centralized role, tenant, service-identity, and resource authorization to every incident, admin, and worker operational endpoint.",
  "Checkout Integrity Issue": "Resolve price, currency, product, and plan exclusively from authoritative server-side catalog state; never trust client-supplied commercial terms.",
  "Payment Entitlement Issue": "Activate entitlement only after an independently verified test-provider payment state and reconcile it atomically with subscription ownership.",
  "Payment Event Idempotency Issue": "Persist provider event identities atomically, reject replay, and make payment-event effects idempotent at the authoritative data layer.",
  "Premium Access Authorization Issue": "Bind premium and subscription access to the authenticated principal and tenant on every request.",
  "Subscription State Consistency Issue": "Reconcile cancellation, refund, downgrade, subscription, and entitlement transitions atomically from authoritative state.",
  "Payment Event Race Condition": "Use transactional uniqueness and atomic state transitions so synchronized duplicate synthetic events can produce at most one effect.",
  "Server Credential Exposure": "Remove the server-only credential from every client-visible artifact and public response, rotate or revoke it, purge affected build artifacts and caches, and add boundary checks in CI.",
  "Session Secret Exposure": "Stop serializing session, refresh, recovery, invitation, or one-time token material into public/client-visible responses; revoke affected tokens and bind replacements to the intended user and flow.",
  "Client-Side Session Secret Exposure": "Keep reusable session material in Secure, HttpOnly, appropriately SameSite cookies where the architecture permits, minimize token lifetime, and apply strong XSS defenses.",
  "Sensitive Response Exposure": "Apply server-side response shaping and authorization so public API, GraphQL, error, debug, and log responses contain only fields intended for that audience.",
  "Operational Information Exposure": "Keep public health responses minimal and protect detailed diagnostics, configuration, topology, and dependency state behind operational authorization.",
  "Sensitive File Exposure": "Remove the file from the public web root, rotate exposed secrets, and verify deployment rules prevent recurrence.",
  "Backup File Exposure": "Remove public backup/archive files and store backups outside the web root with access controls.",
  "Config Exposure": "Remove public configuration files and verify they do not contain sensitive environment or service details.",
  "Debug/Dev Path": "Disable debug tooling in production or restrict it to authenticated administrative networks.",
  "Directory Listing": "Disable directory listing and ensure only intended files are publicly served.",
  "Source Map Exposure": "Review whether source maps should be public; remove or restrict them if they expose source code or sensitive comments.",
  "Next.js Public Serialized Sensitive Data Exposure": "Remove server-only fields before serialization, return only data required by the client, and enforce authorization before producing the payload.",
  "Next.js Source Map Sensitive Data Exposure": "Remove the secret from source and history, rotate exposed credentials, prevent sensitive values from entering browser bundles/maps, and apply an appropriate production source-map policy.",
  "Next.js Public Runtime Secret Exposure": "Remove non-public secrets from browser runtime configuration, rotate exposed credentials, and keep server-only configuration on the server.",
  "Next.js Cross-Actor Data Exposure": "Enforce authorization before serializing the representation and ensure each actor receives only its permitted fields and values.",
  "Next.js Shared Cache Private Data Exposure": "Prevent shared caching of user-specific representations and ensure cache keys and directives account for relevant authentication state.",
  "Public Cloud Reference": "Review referenced cloud resources for intended public exposure and least-privilege access controls.",
  "Interesting But Needs Manual Testing": "Review manually for intended public exposure and access-control behavior."
};
