import { describe, expect, it } from "vitest";
import { compileProductionMutationCase } from "../../../src/dashboard/execution/ProductionMutationCaseCompiler.js";
import { productionMutationCaseSchema } from "../../../src/dashboard/contracts/ProductionMutationCaseSchemas.js";

const input = productionMutationCaseSchema.parse({ schemaVersion: 1, caseId: "prod-role-001", targetId: "00000000-0000-4000-8000-000000000001", environment: "PRODUCTION", productionAcknowledged: true, actorCredentialProfileId: "00000000-0000-4000-8000-000000000002", disposableTargetAlias: "test-user-001", authorityField: "role", mutationValue: "admin", allowedValues: ["admin"], identity: { method: "GET", path: "/api/users/test-user-001", assertions: [{ path: "id", operator: "EQUALS", expectedValue: "test-user-001" }] }, precondition: { method: "GET", path: "/api/users/test-user-001", assertions: [{ path: "role", operator: "EQUALS", expectedValue: "user" }] }, mutation: { method: "PATCH", path: "/api/users/test-user-001", body: { role: "admin" } }, impactVerification: { method: "GET", path: "/api/users/test-user-001", assertions: [{ path: "role", operator: "EQUALS", expectedValue: "admin" }] }, rollback: { method: "PATCH", path: "/api/users/test-user-001", body: { role: "user" } }, restorationVerification: { method: "GET", path: "/api/users/test-user-001", assertions: [{ path: "role", operator: "EQUALS", expectedValue: "user" }] }, authorizationExpiresAt: "2099-01-01T00:00:00.000Z" });
const target = { id: input.targetId, displayName: "Production", baseOrigin: "https://app.example.com", productionEnabled: true, approvedScope: { program: "https://app.example.com", allowedDomains: ["app.example.com"], disallowedPaths: [], allowedMethods: ["GET", "HEAD", "OPTIONS", "POST", "PATCH", "PUT", "DELETE"], sameOriginOnly: true, includeSubdomains: false, rateLimitPerSecond: 1, concurrency: 1, maxRequests: 100, userAgent: "RouteCairn", bodyPreviewBytes: 1024, maxResponseBytes: 1024 } } as any;

describe("production mutation compiler", () => {
  it("compiles relative links to same-origin contracts and redacted previews", () => { const result = compileProductionMutationCase(input, target, "2026-01-01T00:00:00.000Z", "owner"); expect(result.contract.attack.request.url).toBe("https://app.example.com/api/users/test-user-001"); expect(result.preview.endpoints).toContain("/api/users/test-user-001"); expect(JSON.stringify(result.preview)).not.toContain("admin"); });
  it("rejects a target that is not classified production", () => { expect(() => compileProductionMutationCase(input, { ...target, productionEnabled: false }, "2026-01-01T00:00:00.000Z", "owner")).toThrow("PRODUCTION_TARGET_REQUIRED"); });
});
