import type { ModuleId, ModuleMetadata } from "./ScanPlan.js";

const defaults = {
  dependencies: [] as const,
  orderAfter: [] as const,
  defaultSettings: {},
  supportedSettings: [] as const,
  readiness: "production" as const
};

export const moduleCatalog = {
  baseline: {
    ...defaults,
    id: "baseline",
    displayName: "Baseline Detector",
    description: "Soft-404 and wildcard baseline probes.",
    phase: "baseline",
    capabilities: ["baseline"],
    requiresAuthentication: "none",
    monitoringCompatible: true,
    supportsEvidence: true,
    cost: "low"
  },
  "tech-fingerprint": {
    ...defaults,
    id: "tech-fingerprint",
    displayName: "Technology Fingerprint",
    description: "Classifies technologies from collected responses.",
    phase: "fingerprint",
    capabilities: ["fingerprint"],
    requiresAuthentication: "none",
    monitoringCompatible: true,
    supportsEvidence: true,
    dependencies: ["baseline"],
    cost: "low"
  },
  "js-intelligence": {
    ...defaults,
    id: "js-intelligence",
    displayName: "JavaScript Intelligence",
    description: "Downloads same-origin JavaScript and extracts routes/config signals.",
    phase: "intelligence",
    capabilities: ["javascript", "discovery"],
    requiresAuthentication: "none",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: ["baseline"],
    cost: "medium"
  },
  "browser-crawler": {
    ...defaults,
    id: "browser-crawler",
    displayName: "Browser Crawler",
    description: "Renders the target with Playwright.",
    phase: "intelligence",
    capabilities: ["browser", "discovery"],
    requiresAuthentication: "none",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: ["baseline"],
    defaultSettings: {
      browserMaxPages: 3,
      browserMaxLinksPerPage: 25,
      browserMaxPolicyEvents: 200,
      browserMaxRequestsPerPage: 80,
      browserBlockThirdParty: true,
      browserAllowedResourceTypes: ["document", "stylesheet", "script", "xhr", "fetch", "manifest"],
      browserCaptureScreenshot: true,
      browserAllowPopups: false,
      browserAllowDownloads: false,
      browserAllowUploads: false,
      browserAllowServiceWorkers: false,
      browserAllowWebSockets: false,
      browserAllowPrivateNetwork: false,
      browserAllowedPrivateOrigins: [],
      browserAllowedThirdPartyOrigins: []
    },
    supportedSettings: [
      "browserMaxPages",
      "browserMaxLinksPerPage",
      "browserMaxPolicyEvents",
      "browserMaxRequestsPerPage",
      "browserBlockThirdParty",
      "browserAllowedResourceTypes",
      "browserCaptureScreenshot",
      "browserAllowPopups",
      "browserAllowDownloads",
      "browserAllowUploads",
      "browserAllowServiceWorkers",
      "browserAllowWebSockets",
      "browserAllowPrivateNetwork",
      "browserAllowedPrivateOrigins",
      "browserAllowedThirdPartyOrigins"
    ],
    cost: "high"
  },
  "path-discovery": {
    ...defaults,
    id: "path-discovery",
    displayName: "Path Discovery",
    description: "Checks configured path sources and queued candidates.",
    phase: "discovery",
    capabilities: ["discovery"],
    requiresAuthentication: "none",
    monitoringCompatible: true,
    supportsEvidence: true,
    dependencies: ["baseline"],
    orderAfter: ["js-intelligence", "browser-crawler", "tech-fingerprint"],
    defaultSettings: { pathSources: ["wordlist:common", "wordlist:admin", "wordlist:api"] },
    supportedSettings: ["pathSources"],
    cost: "medium"
  },
  "api-mapper": {
    ...defaults,
    id: "api-mapper",
    displayName: "API Mapper",
    description: "Classifies discovered API endpoints.",
    phase: "analysis",
    capabilities: ["api"],
    requiresAuthentication: "none",
    monitoringCompatible: true,
    supportsEvidence: true,
    dependencies: [],
    cost: "low"
  },
  "api-probe": {
    ...defaults,
    id: "api-probe",
    displayName: "API Probe",
    description: "Safely probes API behavior with GET, HEAD, and OPTIONS.",
    phase: "analysis",
    capabilities: ["api"],
    requiresAuthentication: "none",
    monitoringCompatible: true,
    supportsEvidence: true,
    dependencies: ["api-mapper"],
    defaultSettings: { maxEndpoints: 40, safeMethods: ["OPTIONS", "HEAD", "GET"] },
    supportedSettings: ["maxEndpoints", "safeMethods"],
    cost: "medium"
  },
  "auth-surface": {
    ...defaults,
    id: "auth-surface",
    displayName: "Auth Surface",
    description: "Detects login, registration, reset, and session routes.",
    phase: "analysis",
    capabilities: ["auth-surface"],
    requiresAuthentication: "none",
    monitoringCompatible: true,
    supportsEvidence: true,
    dependencies: ["api-mapper"],
    cost: "low"
  },
  "parameter-analysis": {
    ...defaults,
    id: "parameter-analysis",
    displayName: "Parameter Analysis",
    description: "Classifies URL and API parameters.",
    phase: "analysis",
    capabilities: ["api"],
    requiresAuthentication: "none",
    monitoringCompatible: true,
    supportsEvidence: true,
    dependencies: ["api-mapper"],
    cost: "low"
  },
  "nextjs-review": {
    ...defaults,
    id: "nextjs-review",
    displayName: "Next.js Deep Review",
    description: "Safely correlates Next.js router metadata, manifests, known data/RSC surfaces, referenced source maps, serialized data, and cache evidence.",
    phase: "analysis",
    capabilities: ["nextjs"],
    requiresAuthentication: "none",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: ["tech-fingerprint"],
    defaultSettings: {
      maxNextJsManifestRequests: 4,
      maxNextJsDataSurfaceRequests: 8,
      maxNextJsSourceMapRequests: 4,
      maxNextJsCacheDifferentialRequests: 0,
      maxNextJsAssetsInspected: 50,
      maxNextJsRoutesProcessed: 200,
      inspectNextJsSourceMaps: true,
      inspectKnownNextJsDataSurfaces: true,
      nextJsCacheReviewMode: "PASSIVE_CACHE_REVIEW"
    },
    supportedSettings: ["maxDataRoutes", "maxNextJsManifestRequests", "maxNextJsDataSurfaceRequests", "maxNextJsSourceMapRequests", "maxNextJsCacheDifferentialRequests", "maxNextJsAssetsInspected", "maxNextJsRoutesProcessed", "inspectNextJsSourceMaps", "inspectKnownNextJsDataSurfaces", "nextJsCacheReviewMode"],
    cost: "medium"
  },
  "vulnerability-workflows": {
    ...defaults,
    id: "vulnerability-workflows",
    displayName: "Vulnerability Workflows",
    description: "Builds manual verification workflow candidates.",
    phase: "analysis",
    capabilities: ["workflow"],
    requiresAuthentication: "none",
    monitoringCompatible: true,
    supportsEvidence: true,
    dependencies: ["api-mapper", "auth-surface", "parameter-analysis"],
    cost: "low"
  },
  "workflow-validation": {
    ...defaults,
    id: "workflow-validation",
    displayName: "Workflow Validation",
    description: "Creates safe evidence templates.",
    phase: "analysis",
    capabilities: ["workflow"],
    requiresAuthentication: "none",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: ["vulnerability-workflows"],
    cost: "low"
  },
  "authenticated-testing": {
    ...defaults,
    id: "authenticated-testing",
    displayName: "Authenticated Testing",
    description: "Compares anonymous and authenticated responses.",
    phase: "analysis",
    capabilities: ["auth-comparison"],
    requiresAuthentication: "single-profile",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: ["auth-surface"],
    defaultSettings: { maxComparisons: 40 },
    supportedSettings: ["maxComparisons"],
    cost: "medium"
  },
  "role-comparison": {
    ...defaults,
    id: "role-comparison",
    displayName: "Role Comparison",
    description: "Compares anonymous, Account A, and Account B access.",
    phase: "analysis",
    capabilities: ["role-comparison"],
    requiresAuthentication: "account-pair",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: ["authenticated-testing"],
    defaultSettings: { maxComparisons: 40 },
    supportedSettings: ["maxComparisons"],
    cost: "medium"
  },
  "state-aware-api": {
    ...defaults,
    id: "state-aware-api",
    displayName: "State-Aware API",
    description: "Safely reviews API access-control behavior with non-mutating methods.",
    phase: "analysis",
    capabilities: ["state-aware-api"],
    requiresAuthentication: "none",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: ["api-mapper"],
    defaultSettings: { maxEndpointReviews: 30 },
    supportedSettings: ["maxEndpointReviews"],
    cost: "medium"
  },
  "object-pair-testing": {
    ...defaults,
    id: "object-pair-testing",
    displayName: "Object Pair Testing",
    description: "Verifies supplied Account A/Account B object pairs with a fixed read-only request matrix.",
    phase: "analysis",
    capabilities: ["object-pair", "auth-comparison"],
    requiresAuthentication: "account-pair",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: [],
    defaultSettings: { maxObjectPairs: 5 },
    supportedSettings: ["maxObjectPairs"],
    cost: "medium"
  },
  "field-exposure-testing": {
    ...defaults,
    id: "field-exposure-testing",
    displayName: "Field Exposure Testing",
    description: "Verifies explicitly supplied field-visibility expectations for one supplied object across declared principals.",
    phase: "analysis",
    capabilities: ["field-exposure", "auth-comparison"],
    requiresAuthentication: "account-pair",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: [],
    defaultSettings: { maxFieldExposureCases: 5, maxFieldExposureFields: 20 },
    supportedSettings: ["maxFieldExposureCases", "maxFieldExposureFields"],
    cost: "medium"
  },
  "authorization-matrix-testing": {
    ...defaults,
    id: "authorization-matrix-testing",
    displayName: "Authorization Matrix Testing",
    description: "Verifies explicitly supplied role, tenant, account-state, and object-state authorization matrix cells.",
    phase: "analysis",
    capabilities: ["authorization-matrix", "auth-comparison"],
    requiresAuthentication: "account-pair",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: [],
    defaultSettings: { maxAuthorizationMatrixCases: 20 },
    supportedSettings: ["maxAuthorizationMatrixCases"],
    cost: "medium"
  },
  "equivalent-route-testing": {
    ...defaults,
    id: "equivalent-route-testing",
    displayName: "Equivalent Route Testing",
    description: "Verifies explicitly supplied equivalent routes enforce the same configured authorization boundary.",
    phase: "analysis",
    capabilities: ["equivalent-route", "auth-comparison"],
    requiresAuthentication: "account-pair",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: [],
    defaultSettings: { maxEquivalentRouteSets: 5, maxEquivalentRouteCells: 40 },
    supportedSettings: ["maxEquivalentRouteSets", "maxEquivalentRouteCells"],
    cost: "medium"
  },
  "collection-authorization-testing": {
    ...defaults,
    id: "collection-authorization-testing",
    displayName: "Collection Authorization Testing",
    description: "Verifies explicitly supplied collection/list/search/count/summary authorization membership cases.",
    phase: "analysis",
    capabilities: ["collection-authorization", "auth-comparison"],
    requiresAuthentication: "account-pair",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: [],
    defaultSettings: { maxCollectionAuthorizationCollections: 3, maxCollectionAuthorizationCases: 20 },
    supportedSettings: ["maxCollectionAuthorizationCollections", "maxCollectionAuthorizationCases"],
    cost: "medium"
  },
  "bulk-authorization-testing": {
    ...defaults,
    id: "bulk-authorization-testing",
    displayName: "Bulk Authorization Testing",
    description: "Verifies explicitly supplied non-mutating bulk preview, validation, dry-run, and summary authorization cases.",
    phase: "analysis",
    capabilities: ["bulk-authorization", "auth-comparison"],
    requiresAuthentication: "account-pair",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: [],
    defaultSettings: { maxBulkAuthorizationCases: 10 },
    supportedSettings: ["maxBulkAuthorizationCases"],
    cost: "medium"
  },
  "file-authorization-testing": {
    ...defaults,
    id: "file-authorization-testing",
    displayName: "File Authorization Testing",
    description: "Verifies explicitly supplied metadata, preview, content, and signed URL file authorization cases.",
    phase: "analysis",
    capabilities: ["file-authorization", "auth-comparison"],
    requiresAuthentication: "account-pair",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: [],
    defaultSettings: { maxFileAuthorizationCases: 10 },
    supportedSettings: ["maxFileAuthorizationCases"],
    cost: "medium"
  },
  "header-review": {
    ...defaults,
    id: "header-review",
    displayName: "Header Review",
    description: "Reviews security headers.",
    phase: "analysis",
    capabilities: ["headers"],
    requiresAuthentication: "none",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: ["baseline"],
    cost: "low"
  },
  "cookie-review": {
    ...defaults,
    id: "cookie-review",
    displayName: "Cookie Review",
    description: "Reviews Set-Cookie attributes.",
    phase: "analysis",
    capabilities: ["cookies"],
    requiresAuthentication: "none",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: ["baseline"],
    cost: "low"
  },
  "cors-review": {
    ...defaults,
    id: "cors-review",
    displayName: "CORS Review",
    description: "Reviews CORS behavior with controlled safe requests.",
    phase: "analysis",
    capabilities: ["cors"],
    requiresAuthentication: "none",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: ["baseline"],
    cost: "low"
  },
  "method-review": {
    ...defaults,
    id: "method-review",
    displayName: "Method Review",
    description: "Checks advertised HTTP methods through safe OPTIONS requests.",
    phase: "analysis",
    capabilities: ["methods"],
    requiresAuthentication: "none",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: ["baseline"],
    cost: "low"
  },
  "exposure-review": {
    ...defaults,
    id: "exposure-review",
    displayName: "Exposure Review",
    description: "Checks sensitive files, backups, debug paths, and source maps.",
    phase: "analysis",
    capabilities: ["exposure"],
    requiresAuthentication: "none",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: ["baseline"],
    cost: "medium"
  },
  "proof-mode": {
    ...defaults,
    id: "proof-mode",
    displayName: "Proof Mode",
    description: "Re-tests selected targets and creates reproducible proof blocks.",
    phase: "analysis",
    capabilities: ["proof"],
    requiresAuthentication: "none",
    monitoringCompatible: false,
    supportsEvidence: true,
    dependencies: ["vulnerability-workflows"],
    orderAfter: ["state-aware-api"],
    defaultSettings: { enabled: false, maxProofTargets: 12 },
    supportedSettings: ["enabled", "maxProofTargets"],
    cost: "medium"
  }
} satisfies Record<ModuleId, ModuleMetadata>;

export function moduleMetadata(id: ModuleId): ModuleMetadata {
  return moduleCatalog[id];
}
