import { spawn } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repository = resolve(dirname(fileURLToPath(import.meta.url)), ".."); const flags = new Map();
for (let i = 2; i < process.argv.length; i += 2) { const name = process.argv[i], value = process.argv[i + 1]; if (!["--python", "--python-path", "--output"].includes(name) || !value || flags.has(name)) throw new Error("Use --python-path DIRECTORY [--python EXECUTABLE] [--output FRESH_DIRECTORY]."); flags.set(name, value); }
if (!flags.has("--python-path")) throw new Error("Supply an isolated Python dependency directory containing Jinja2 3.1.6 and MarkupSafe 3.0.3.");
const output = resolve(flags.get("--output") ?? ".routecairn-oast-lab/results");
await mkdir(dirname(output), { recursive: true }); await mkdir(output); // Never overwrite retained evidence.
const testFiles = ["tests/integration/oast-hosted.test.ts", "tests/integration/oast-runtime-proof.test.ts", "tests/integration/oast-service.test.ts", "tests/integration/active-vulnerability-oast.test.ts", "tests/unit/oast-config.test.ts", "tests/unit/oast-store.test.ts", "tests/unit/oast-client.test.ts", "tests/unit/oast-dns.test.ts", "tests/unit/oast-deployment-verification.test.ts"];
const snapshot = async () => { const sources = {}; for (const folder of ["src/oast"]) for (const name of (await readdir(join(repository, folder))).sort()) { const path = `${folder}/${name}`; sources[path] = sha256(await readFile(join(repository, path))); } for (const path of [...testFiles, "tests/helpers/oast-runtime.py", "tests/helpers/oast-lab.ts", "src/modules/activeVulnerability/ActiveVulnerabilityModule.ts", "src/modules/activeVulnerability/ActiveVulnerabilityPlanner.ts", "src/modules/activeVulnerability/ActiveVulnerabilityTypes.ts", "src/modules/protocolSecurity/ProtocolTransports.ts", "src/core/http/PinnedHttpTransport.ts", "src/cli/commands/oast.ts", "scripts/oast-lab.mjs", "package-lock.json", "deploy/oast/Dockerfile", "deploy/oast/compose.yaml"]) sources[path] = sha256(await readFile(join(repository, path))); return sources; };
const sources = await snapshot(), transient = join(repository, ".routecairn-oast-lab", `vitest-${randomUUID()}.json`); await mkdir(dirname(transient), { recursive: true });
const runtimeSnapshot = async () => { const files = {}; const root = resolve(flags.get("--python-path")); const walk = async (folder, prefix) => { for (const entry of (await readdir(folder, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) { if (entry.isSymbolicLink()) throw new Error("Runtime dependencies must not use symbolic links."); if (entry.name === "__pycache__") continue; const name = `${prefix}${entry.name}`; if (entry.isDirectory()) await walk(join(folder, entry.name), `${name}/`); else if (!entry.name.endsWith(".pyc")) files[name] = sha256(await readFile(join(folder, entry.name))); } }; await walk(root, ""); return files; };
const runtimeSources = await runtimeSnapshot();
const env = { ...process.env, ROUTECAIRN_OAST_PYTHON_PATH: resolve(flags.get("--python-path")), ROUTECAIRN_PYTHON: flags.get("--python") ?? "python", ROUTECAIRN_OAST_LAB_OUTPUT: output };
const exitCode = await new Promise((done, reject) => { const child = spawn(process.execPath, [join(repository, "node_modules/vitest/vitest.mjs"), "run", ...testFiles, "--pool=forks", "--maxWorkers=1", "--reporter=json", `--outputFile=${transient}`], { cwd: repository, env, windowsHide: true, stdio: "inherit" }); child.once("error", reject); child.once("exit", (code) => done(code ?? 1)); });
let tests = {}; let complete = exitCode === 0; const artifacts = {};
try { const result = JSON.parse(await readFile(transient, "utf8")); tests = { total: result.numTotalTests, passed: result.numPassedTests, failed: result.numFailedTests, skipped: result.numPendingTests }; if (tests.skipped !== 0 || tests.failed !== 0 || tests.total !== tests.passed) complete = false; } catch { complete = false; } finally { await rm(transient, { force: true }); }
for (const [name, count] of [["runtime-proof.json", process.platform === "win32" ? 14 : 16], ["hosted-service-proof.json", 7]]) { try { const bytes = await readFile(join(output, name)), value = JSON.parse(bytes), rows = value.cases ?? value.checks; if (rows.length !== count || value.cleanup !== "CONFIRMED" || value.externalTargetsTested !== false || value.independentlyOperated !== false || (value.runtimeFailures ?? []).length > 0) complete = false; artifacts[name] = { sha256: sha256(bytes), checks: rows.length }; } catch { complete = false; artifacts[name] = { missingOrInvalid: true }; } }
const sourcesUnchanged = JSON.stringify(sources) === JSON.stringify(await snapshot()); const runtimeSourcesUnchanged = JSON.stringify(runtimeSources) === JSON.stringify(await runtimeSnapshot()); if (!sourcesUnchanged || !runtimeSourcesUnchanged) complete = false;
const report = { schemaVersion: 1, generatedAt: new Date().toISOString(), status: complete ? "COMPLETED" : "FAILED", testExitCode: exitCode, tests, sourcesUnchanged, runtimeSourcesUnchanged, nodeVersion: process.version, provenance: "SELF_MAINTAINED_LOOPBACK", publicDeploymentVerified: false, externalTargetsTested: false, independentlyOperated: false, artifacts, sources, runtimeSources, limitations: ["Hosted-mode service is exercised on loopback with a private fixture CA; no public authoritative deployment is implied.", "Windows PowerShell injection uses HTTP; HTTPS is exercised by urllib, SAX and real Jinja-to-shell execution with an isolated curl CA adapter.", "Missing callbacks are inconclusive, not proof of security.", "A public domain delegation, reachable DNS host and owner-authorized public verifier run are required for retained public deployment evidence."] };
const bytes = Buffer.from(`${JSON.stringify(report, null, 2)}\n`); await writeFile(join(output, "oast-lab-result.json"), bytes); await writeFile(join(output, "SHA256SUMS"), `${Object.entries(artifacts).filter(([, value]) => value.sha256).map(([name, value]) => `${value.sha256}  ${name}`).join("\n")}\n${sha256(bytes)}  oast-lab-result.json\n`);
process.stdout.write(`OAST lab: ${report.status}; ${join(output, "oast-lab-result.json")}\n`); if (!complete) process.exitCode = 1;
function sha256(value) { return createHash("sha256").update(value).digest("hex"); }
