import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { officialSourceSchema } from "../src/standards/OfficialCatalogSchema.js";
import { parseOfficialCatalog } from "../src/standards/OfficialCatalogParser.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const write = process.argv.includes("--write");
const refresh = process.argv.includes("--refresh");
if (!write && !process.argv.includes("--check")) throw new Error("Use --check or --write; --refresh fetches only the pinned publisher bytes.");
const lockBytes = await readFile(resolve(root, "standards/sources.lock.json"));
const lock = z.object({ schemaVersion: z.literal(1), sources: z.array(officialSourceSchema).length(5) }).strict().parse(JSON.parse(lockBytes.toString("utf8")));
const inputs = new Map<string, Buffer>();
for (const source of lock.sources) {
  const path = resolve(root, "standards/sources", source.file);
  let bytes: Buffer;
  if (refresh) {
    const url = new URL(source.url);
    if (url.protocol !== "https:" || !["raw.githubusercontent.com", "cwe.mitre.org", "capec.mitre.org"].includes(url.hostname) || url.username || url.password || url.port) throw new Error("STANDARDS_SOURCE_URL_INVALID");
    const response = await fetch(url, { redirect: "error", signal: AbortSignal.timeout(30_000) });
    if (!response.ok) throw new Error(`STANDARDS_SOURCE_FETCH_FAILED ${source.framework} ${response.status}`);
    const chunks: Uint8Array[] = []; let size = 0;
    for await (const chunk of response.body!) { size += chunk.byteLength; if (size > source.bytes) { await response.body?.cancel().catch(() => undefined); throw new Error("STANDARDS_SOURCE_TOO_LARGE"); } chunks.push(chunk); }
    bytes = Buffer.concat(chunks);
  } else bytes = await readFile(path);
  if (bytes.length !== source.bytes || createHash("sha256").update(bytes).digest("hex") !== source.sha256) throw new Error(`STANDARDS_SOURCE_INTEGRITY_FAILED ${source.framework}`);
  if (refresh) { await mkdir(dirname(path), { recursive: true }); await writeFile(path, bytes); }
  inputs.set(source.framework, bytes);
}
const catalog = parseOfficialCatalog(lock.sources, inputs);
const bytes = `${JSON.stringify(catalog, null, 2)}\n`;
const digest = createHash("sha256").update(bytes).digest("hex");
const counts = Object.fromEntries(lock.sources.map((source) => [source.framework, catalog.entries.filter((entry) => entry.framework === source.framework).length]));
const mappingDigest = createHash("sha256").update(await readFile(resolve(root, "src/standards/StandardsMappings.ts"))).digest("hex");
const identity = `// Generated by scripts/standards-catalog.ts from hash-verified official sources.\nexport const officialCatalogSha256 = "${digest}";\nexport const officialCatalogCounts = ${JSON.stringify(counts)} as const;\nexport const officialSourceLockSha256 = "${createHash("sha256").update(lockBytes).digest("hex")}";\nexport const standardsMappingSha256 = "${mappingDigest}";\n`;
for (const [file, content] of [["src/standards/catalog/official-catalog.json", bytes], ["src/standards/OfficialCatalogIdentity.ts", identity]]) {
  const path = resolve(root, file!);
  if (write) { await mkdir(dirname(path), { recursive: true }); await writeFile(path, content!); }
  else if (await readFile(path, "utf8") !== content) throw new Error(`STANDARDS_GENERATED_CATALOG_STALE ${file}`);
}
process.stdout.write(`${JSON.stringify({ catalogSha256: digest, counts, sourceIntegrity: "VERIFIED", mode: write ? "WRITE" : "CHECK" })}\n`);
