import { useEffect, useMemo, useState } from "react";
import { apiGet, apiMutation, type ScanSummary, type TargetSummary } from "./api";

const laneKinds = [
  "PUBLIC_BASELINE", "AUTHENTICATED_IDENTITY", "ACCOUNT_PAIR_AUTHORIZATION", "BROWSER_LEARNING",
  "AUTHENTICATION_LIFECYCLE", "API_GRAPHQL_AUTHORIZATION", "DATA_AUTHORIZATION", "BUSINESS_LOGIC",
  "OPERATIONAL_ENDPOINTS", "BILLING_ENTITLEMENTS", "MUTATION_ACCEPTANCE", "RECOVERY_ACCEPTANCE"
] as const;

interface AdaptiveState {
  targetId: string;
  policy: { requiredLanes: string[]; requireEvidenceForNotApplicable: boolean; detectRemovedSurfaces: boolean };
  coverage: { complete: boolean; required: number; gaps: number; runId?: string; modelGate?: { state: string; snapshotId?: string; openDriftCount?: number; reason?: string }; lanes: Array<{ kind: string; state: string; reason?: string; scanId?: string; evidenceScanId?: string }> };
  snapshots: Array<{ id: string; sourceScanId: string; status: string; modelDigest: string; buildFingerprint: string; createdAt: string; acceptedAt?: string }>;
  drifts: Array<{ id: string; snapshot_id: string; drift_type: string; severity: string; semantic_key: string; safe_summary: string; status: string; created_at: string }>;
  recommendations: Array<{ id: string; category: string; engineId: string; laneKind: string; status: string; mutationHypothesis: boolean; sourceFingerprint: string; draft: Record<string, unknown>; requiredBindings: string[]; rationale?: string; linkedScanId?: string; linkedCaseFingerprint?: string; executionOutcome?: string; adapterProfileId?: string; adapterVersionId?: string; executionCandidates: Array<{ scanId: string; caseAlias: string; caseFingerprint: string; executionState: string; evidenceStrength: string; scanStatus: string; createdAt: string }> }>;
}

export function AdaptiveSecurityWorkspace({ onOpenBuilder, canApprove = true }: { onOpenBuilder?: (draft: { target: TargetSummary; engineId: string }) => void; canApprove?: boolean }) {
  const [targets, setTargets] = useState<TargetSummary[]>([]);
  const [scans, setScans] = useState<ScanSummary[]>([]);
  const [targetId, setTargetId] = useState("");
  const [scanId, setScanId] = useState("");
  const [state, setState] = useState<AdaptiveState>();
  const [required, setRequired] = useState<string[]>([...laneKinds]);
  const [requireNaEvidence, setRequireNaEvidence] = useState(true);
  const [detectRemoved, setDetectRemoved] = useState(true);
  const [rationale, setRationale] = useState("");
  const [executionBindings, setExecutionBindings] = useState<Record<string, string>>({});
  const [message, setMessage] = useState("");

  useEffect(() => { void Promise.all([apiGet<{ targets: TargetSummary[] }>("/api/targets"), apiGet<{ scans: ScanSummary[] }>("/api/scans?limit=100")]).then(([targetBody, scanBody]) => { setTargets(targetBody.targets); setScans(scanBody.scans); if (targetBody.targets[0]) setTargetId(targetBody.targets[0].id); }).catch(fail(setMessage)); }, []);
  useEffect(() => { if (!targetId) return; void load(targetId).catch(fail(setMessage)); }, [targetId]);

  const target = targets.find((item) => item.id === targetId);
  const targetScans = useMemo(() => scans.filter((item) => item.target === target?.baseOrigin && ["COMPLETED", "IMPORTED"].includes(item.status)), [scans, target?.baseOrigin]);

  async function load(id: string) {
    const body = await apiGet<{ adaptiveSecurity: AdaptiveState }>(`/api/adaptive-security/targets/${id}`);
    setState(body.adaptiveSecurity); setRequired(body.adaptiveSecurity.policy.requiredLanes); setRequireNaEvidence(body.adaptiveSecurity.policy.requireEvidenceForNotApplicable); setDetectRemoved(body.adaptiveSecurity.policy.detectRemovedSurfaces);
  }
  async function analyze() { const body = await apiMutation<{ snapshot: { state: AdaptiveState } }>("/api/adaptive-security/analyze", "POST", { targetId, scanId }); setState(body.snapshot.state); setMessage("Completed evidence converted into a candidate security model and safe test recommendations."); }
  async function savePolicy() { const body = await apiMutation<{ adaptiveSecurity: AdaptiveState }>("/api/adaptive-security/policy", "PUT", { targetId, requiredLanes: required, requireEvidenceForNotApplicable: requireNaEvidence, detectRemovedSurfaces: detectRemoved, confirmation: "I_CONFIRM_TARGET_SECURITY_MODEL_POLICY" }); setState(body.adaptiveSecurity); setMessage("Adaptive coverage and drift policy saved."); }
  async function accept(snapshot: AdaptiveState["snapshots"][number]) { if (!window.confirm("Accept this exact observed model as the expected target baseline? Future scans will be compared with it.")) return; const body = await apiMutation<{ adaptiveSecurity: AdaptiveState }>(`/api/adaptive-security/snapshots/${snapshot.id}/accept`, "POST", { modelDigest: snapshot.modelDigest, confirmation: "I_CONFIRM_EXPECTED_SECURITY_MODEL_BASELINE" }); setState(body.adaptiveSecurity); setMessage("Exact model baseline accepted."); }
  async function decide(id: string, decision: "APPROVED" | "DISMISSED") { const body = await apiMutation<{ adaptiveSecurity: AdaptiveState }>(`/api/adaptive-security/recommendations/${id}/decision`, "POST", { decision, rationale, confirmation: "I_CONFIRM_ADAPTIVE_RECOMMENDATION_DECISION" }); setState(body.adaptiveSecurity); setRationale(""); setMessage(`${decision === "APPROVED" ? "Approved" : "Dismissed"} recommendation. Approval does not execute a request.`); }
  async function link(id: string) { const selected = executionBindings[id]; if (!selected) throw new Error("Select an eligible post-approval workflow case."); const [selectedScanId, caseFingerprint] = selected.split(":"); if (!selectedScanId || !caseFingerprint) throw new Error("The exact execution binding is invalid."); const body = await apiMutation<{ adaptiveSecurity: AdaptiveState }>(`/api/adaptive-security/recommendations/${id}/link`, "POST", { scanId: selectedScanId, caseFingerprint, confirmation: "I_CONFIRM_LINK_EXACT_RECOMMENDATION_EXECUTION" }); setState(body.adaptiveSecurity); setMessage("Exact post-approval workflow case linked and verified against the recommended engine."); }
  async function refresh(id: string) { const body = await apiMutation<{ adaptiveSecurity: AdaptiveState }>(`/api/adaptive-security/recommendations/${id}/refresh`, "POST", {}); setState(body.adaptiveSecurity); }

  return <section>
    <header><h2>Adaptive Security</h2><p>Observe completed evidence, maintain the expected target model, review drift, approve proposed tests, and verify coverage without granting automatic mutation authority.</p></header>
    {message && <p aria-live="polite">{message}</p>}
    <div className="cleanup-emergency" role="note"><div><strong>Learning never authorizes mutation</strong><p>Learned traffic and drift create non-executable proposals. Operators must supply exact actor, assertion, fixture, cleanup, and authorization bindings in the relevant dashboard builder before execution.</p></div><span>EXPLICIT APPROVAL</span></div>
    <div className="form"><label>Registered target<select value={targetId} onChange={(event) => { setTargetId(event.target.value); setScanId(""); }}><option value="">Select target</option>{targets.map((item) => <option value={item.id} key={item.id}>{item.displayName} · {item.baseOrigin}</option>)}</select></label><label>Completed evidence scan<select value={scanId} onChange={(event) => setScanId(event.target.value)}><option value="">Select scan</option>{targetScans.map((item) => <option value={item.id} key={item.id}>{item.shortId} · {item.profile} · {item.createdAt}</option>)}</select></label><button className="primary" disabled={!targetId || !scanId} onClick={() => void analyze().catch(fail(setMessage))}>Analyze evidence</button></div>
    <section className="panel"><h3>Coverage and drift policy</h3><div className="form"><fieldset><legend>Required acceptance lanes</legend>{laneKinds.map((kind) => <label className="inline-check" key={kind}><input type="checkbox" checked={required.includes(kind)} onChange={(event) => setRequired(event.target.checked ? [...required, kind] : required.filter((item) => item !== kind))} /> {kind.replaceAll("_", " ")}</label>)}</fieldset><label className="inline-check"><input type="checkbox" checked={requireNaEvidence} onChange={(event) => setRequireNaEvidence(event.target.checked)} /> Require completed evidence before NOT_APPLICABLE satisfies coverage</label><label className="inline-check"><input type="checkbox" checked={detectRemoved} onChange={(event) => setDetectRemoved(event.target.checked)} /> Detect removed security surfaces and contracts</label><button disabled={!targetId || required.length === 0} onClick={() => void savePolicy().catch(fail(setMessage))}>Save policy</button></div>
      {!canApprove && <p className="muted">Owner access is required to change sign-off policy, accept baselines, approve proposals, or bind execution evidence.</p>}
      {state && <div className="cards"><div className="metric"><strong>{state.coverage.complete ? "COMPLETE" : "GAPS"}</strong><span>Acceptance coverage</span></div><div className="metric"><strong>{state.coverage.required}</strong><span>Required lanes</span></div><div className="metric"><strong>{state.coverage.gaps}</strong><span>Evidence gaps</span></div></div>}
      {state?.coverage.modelGate?.state === "STALE" && <p className="error" role="alert">{state.coverage.modelGate.reason} ({state.coverage.modelGate.openDriftCount} open model change(s))</p>}
      {state && <div className="table compact-table"><div className="row"><span>Lane</span><span>State</span><span>Evidence</span><span>Reason</span></div>{state.coverage.lanes.map((lane) => <div className="row" key={lane.kind}><span>{lane.kind}</span><span><strong>{lane.state}</strong></span><span>{lane.scanId?.slice(0, 8) ?? lane.evidenceScanId?.slice(0, 8) ?? "—"}</span><span>{lane.reason ?? "Evidence-backed"}</span></div>)}</div>}
    </section>
    <section className="panel"><h3>Expected model snapshots</h3>{state?.snapshots.length ? <div className="table compact-table"><div className="row"><span>Observed</span><span>Status</span><span>Model binding</span><span>Action</span></div>{state.snapshots.map((item) => <div className="row" key={item.id}><span>{item.createdAt}<small>scan {item.sourceScanId.slice(0, 8)}</small></span><span><strong>{item.status}</strong></span><span><code>{item.modelDigest.slice(0, 16)}…</code><small>build {item.buildFingerprint.slice(0, 12)}…</small></span><span>{item.status === "CANDIDATE" ? <button onClick={() => void accept(item).catch(fail(setMessage))}>Accept exact baseline</button> : item.acceptedAt ?? "—"}</span></div>)}</div> : <p className="muted">No model snapshots yet. Completed registered-target scans are captured automatically; existing scans can be analyzed above.</p>}</section>
    <section className="panel"><h3>Security-model drift</h3>{state?.drifts.length ? <div className="table compact-table"><div className="row"><span>Severity</span><span>Change</span><span>Surface</span><span>Status</span></div>{state.drifts.map((item) => <div className="row" key={item.id}><span><strong>{item.severity}</strong></span><span>{item.drift_type}<small>{item.safe_summary}</small></span><span><code>{item.semantic_key}</code></span><span>{item.status}</span></div>)}</div> : <p className="muted">No drift recorded.</p>}</section>
    <section className="panel"><h3>Recommended tests</h3><label>Decision rationale<textarea value={rationale} onChange={(event) => setRationale(event.target.value)} placeholder="Why this proposal should become an explicit test, or why it is not applicable." /></label>{state?.recommendations.length ? <div className="table compact-table"><div className="row"><span>Recommendation</span><span>Required bindings</span><span>State</span><span>Review and evidence</span></div>{state.recommendations.map((item) => <div className="row" key={item.id}><span><strong>{item.category}</strong><small>{item.engineId} · {item.laneKind}</small>{item.mutationHypothesis && <small className="error">Mutation hypothesis — never auto-executable</small>}<details><summary>Safe draft</summary><pre>{JSON.stringify(item.draft, null, 2)}</pre></details></span><span>{item.requiredBindings.map((binding) => <small key={binding}>{binding}</small>)}</span><span><strong>{item.status}</strong><small><code>{item.sourceFingerprint.slice(0, 12)}…</code></small>{item.executionOutcome && <small>{item.executionOutcome}</small>}</span><span>{item.status === "PROPOSED" && <><button disabled={rationale.trim().length < 12} onClick={() => void decide(item.id, "APPROVED").catch(fail(setMessage))}>Approve proposal</button><button disabled={rationale.trim().length < 12} onClick={() => void decide(item.id, "DISMISSED").catch(fail(setMessage))}>Dismiss</button></>}{item.status === "APPROVED" && <>{target && onOpenBuilder && <button onClick={() => onOpenBuilder({ target, engineId: item.engineId })}>Open dedicated builder</button>}{item.executionCandidates.length ? <><select aria-label={`Execution case for ${item.category}`} value={executionBindings[item.id] ?? ""} onChange={(event) => setExecutionBindings({ ...executionBindings, [item.id]: event.target.value })}><option value="">Select exact post-approval case</option>{item.executionCandidates.map((candidate) => <option key={`${candidate.scanId}:${candidate.caseFingerprint}`} value={`${candidate.scanId}:${candidate.caseFingerprint}`}>{candidate.scanId.slice(0, 8)} · {candidate.caseAlias} · {candidate.executionState}</option>)}</select><button onClick={() => void link(item.id).catch(fail(setMessage))}>Link exact execution</button></> : <small>Run the approved proposal in its dedicated dashboard builder. Eligible exact case fingerprints will appear here after ingestion.</small>}</>}{item.linkedScanId && <><small>scan {item.linkedScanId.slice(0, 8)} · case {item.linkedCaseFingerprint?.slice(0, 12)}…</small><button onClick={() => void refresh(item.id).catch(fail(setMessage))}>Refresh verification</button></>}</span></div>)}</div> : <p className="muted">No test recommendations have been proposed.</p>}</section>
  </section>;
}

function fail(setter: (value: string) => void) { return (error: unknown) => setter(error instanceof Error ? error.message : "Adaptive security operation failed."); }
