import React, { useEffect, useMemo, useState } from "react";
import { apiGet, apiMutation, DashboardApiError, type ScanSummary, type TargetSummary } from "./api";

type Adapter = { id:string;name:string;targetId:string;provider:string;engineId:string;enabled:boolean;activeVersionId?:string };
type Baseline = { adapterProfileId:string;scanId:string };
type RequiredCase = { adapterProfileId:string;workflowId:string;caseFingerprint:string };
type PolicyInput = { schemaVersion:1;name:string;description:string;targetId:string;authorization:{proofReference:string;proofDigest:string;validFrom:string;expiresAt:string};triggers:{scheduleEnabled:boolean;intervalMinutes:number;deploymentEnabled:boolean;quietWhenHealthy:true};adapterProfileIds:string[];baselines:Baseline[];requiredCases:RequiredCase[];gates:{failOnRegression:true;failOnNewFinding:boolean;failOnOpenDrift:boolean;requireExactCases:true;requireCleanupResolved:true};evidence:{retentionDays:number;autoExportOn:Array<"REGRESSION"|"FAILED"|"CLEANUP_REQUIRED"|"APPROVAL_REQUIRED">;preserveFailures:true;preserveCleanupEvidence:true} };
type Preview = {policyDigest:string;target:{origin:string;rowVersion:number};adapterBindings:Array<{profileId:string;versionId:string;adapterDigest:string;maximumDurationMs:number;maxRequests:number;cleanupReservedRequests:number}>;authorization:{validNow:boolean;validThroughEstimatedCompletion:boolean;expiresAt:string};estimate:{maximumDurationMs:number;maxRequests:number;cleanupReservedRequests:number};blockers:string[];warnings:string[]};
type Policy = {id:string;name:string;targetId:string;status:string;activeVersionId?:string;pendingVersionId?:string;nextDueAt?:string;lastRunAt?:string;impact:{activeRuns:number;canDisable:boolean;impactDigest:string};versions:Array<{id:string;revision:number;status:string;policyDigest:string}>;pendingInput?:PolicyInput;activeInput?:PolicyInput;runs:Array<{id:string;triggerType:string;status:string;gateStatus:string;safeSummary:Record<string,unknown>;createdAt:string;completedAt?:string}>};
type Notice = {id:string;runId:string;category:string;severity:string;safeSummary:string;createdAt:string;acknowledgedAt?:string};
type Governance = {available:boolean;policy:{retentionDays:number;maximumExportBytes:number;rowVersion:number};exports:Array<{id:string;status:string;scanCount:number;artifactCount:number;manifestDigest:string;signature:string;verifiedAt?:string}>;purgePreview:{previewDigest:string;cutoff:string;candidates:Array<{id:string;name:string;size:number}>;protectedCounts:Record<string,number>}};

const emptyDigest = "";
const initialInput = ():PolicyInput => { const from=new Date(Date.now()-60_000).toISOString(), until=new Date(Date.now()+30*86_400_000).toISOString(); return {schemaVersion:1,name:"Continuous authorized assurance",description:"",targetId:"",authorization:{proofReference:"",proofDigest:emptyDigest,validFrom:from,expiresAt:until},triggers:{scheduleEnabled:true,intervalMinutes:1440,deploymentEnabled:true,quietWhenHealthy:true},adapterProfileIds:[],baselines:[],requiredCases:[],gates:{failOnRegression:true,failOnNewFinding:true,failOnOpenDrift:true,requireExactCases:true,requireCleanupResolved:true},evidence:{retentionDays:90,autoExportOn:["REGRESSION","FAILED","CLEANUP_REQUIRED","APPROVAL_REQUIRED"],preserveFailures:true,preserveCleanupEvidence:true}}; };

export function ContinuousAssuranceWorkspace({canManage}:{canManage:boolean}) {
  const [targets,setTargets]=useState<TargetSummary[]>([]),[adapters,setAdapters]=useState<Adapter[]>([]),[scans,setScans]=useState<ScanSummary[]>([]),[policies,setPolicies]=useState<Policy[]>([]),[notices,setNotices]=useState<Notice[]>([]);
  const [input,setInput]=useState<PolicyInput>(initialInput),[selected,setSelected]=useState<Policy>(),[preview,setPreview]=useState<Preview>(),[proofText,setProofText]=useState<string>(),[message,setMessage]=useState(""),[diagnostics,setDiagnostics]=useState<Array<{path:string[];message:string}>>([]),[token,setToken]=useState("");
  const [governance,setGovernance]=useState<Governance>(),[retention,setRetention]=useState(90),[maxExportMb,setMaxExportMb]=useState(50),[exportScans,setExportScans]=useState<string[]>([]);
  const selectedTarget=targets.find(t=>t.id===input.targetId), targetAdapters=adapters.filter(a=>a.targetId===input.targetId&&a.enabled&&a.activeVersionId), targetScans=scans.filter(s=>s.target===selectedTarget?.baseOrigin&&["COMPLETED","IMPORTED"].includes(s.status));
  const load=async()=>{const [t,a,s,p,g]=await Promise.all([apiGet<{targets:TargetSummary[]}>("/api/targets"),apiGet<{adapters:Adapter[]}>("/api/provider-adapters"),apiGet<{scans:ScanSummary[]}>("/api/scans?limit=100"),apiGet<{policies:Policy[];notifications:Notice[]}>("/api/continuous-assurance"),apiGet<Governance>("/api/evidence-governance")]);setTargets(t.targets);setAdapters(a.adapters);setScans(s.scans);setPolicies(p.policies);setNotices(p.notifications);setGovernance(g);setRetention(g.policy.retentionDays);setMaxExportMb(Math.round(g.policy.maximumExportBytes/1048576));};
  useEffect(()=>{void load().catch(fail);},[]);
  useEffect(()=>{if(proofText===undefined)return;if(proofText===""){setInput(v=>({...v,authorization:{...v.authorization,proofDigest:""}}));return;}void sha256(proofText).then(proofDigest=>setInput(v=>({...v,authorization:{...v.authorization,proofDigest}})));},[proofText]);
  const mutate=(patch:Partial<PolicyInput>)=>{setInput(v=>({...v,...patch}));setPreview(undefined);}; const fail=(e:unknown)=>{if(e instanceof DashboardApiError)setDiagnostics(e.diagnostics);setMessage(e instanceof Error?e.message:"Operation failed.");}; const action=async(fn:()=>Promise<void>)=>{try{setDiagnostics([]);await fn();}catch(e){fail(e);}};
  const doPreview=()=>action(async()=>{const b=await apiMutation<{preview:Preview}>("/api/continuous-assurance/preview","POST",input);setPreview(b.preview);setMessage(b.preview.blockers.length?"Policy preview is blocked.":"Policy contract is valid. No target request was sent.");});
  const save=()=>action(async()=>{const path=selected?`/api/continuous-assurance/policies/${selected.id}`:"/api/continuous-assurance/policies",method=selected?"PATCH":"POST";const b=await apiMutation<any>(path,method,input);const policy=b.policy as Policy;setSelected(policy);if(b.deploymentTriggerToken)setToken(b.deploymentTriggerToken);setMessage(selected?"New immutable policy draft created; automation paused pending review.":"Draft created. Save the one-time deployment token, then review the exact policy.");await load();});
  const review=()=>action(async()=>{if(!selected?.pendingVersionId||!preview)return;const b=await apiMutation<{policy:Policy}>(`/api/continuous-assurance/policies/${selected.id}/review`,"POST",{versionId:selected.pendingVersionId,policyDigest:preview.policyDigest,confirmation:"I_CONFIRM_CONTINUOUS_ASSURANCE_POLICY"});setSelected(b.policy);setMessage("Exact continuous assurance policy reviewed and activated.");await load();});
  const open=(id:string)=>action(async()=>{const b=await apiGet<{policy:Policy}>(`/api/continuous-assurance/policies/${id}`);setSelected(b.policy);const v=b.policy.pendingInput??b.policy.activeInput;if(v)setInput(v);setProofText(undefined);setPreview(undefined);setToken("");setMessage("Policy opened. Editing creates a new immutable draft and pauses automation until review.");});
  const run=()=>action(async()=>{if(!selected)return;await apiMutation(`/api/continuous-assurance/policies/${selected.id}/run`,"POST",{confirmation:"I_CONFIRM_CONTINUOUS_ASSURANCE_RUN"});setMessage("Assurance run queued from the exact reviewed adapters.");await load();});
  const toggle=()=>action(async()=>{if(!selected)return;const b=await apiMutation<{policy:Policy}>(`/api/continuous-assurance/policies/${selected.id}/state`,"POST",{enabled:selected.status!=="ACTIVE",impactDigest:selected.impact.impactDigest,confirmation:"I_CONFIRM_CONTINUOUS_ASSURANCE_STATE_CHANGE"});setSelected(b.policy);await load();});
  const rotate=()=>action(async()=>{if(!selected)return;const b=await apiMutation<any>(`/api/continuous-assurance/policies/${selected.id}/rotate-token`,"POST",{confirmation:"I_CONFIRM_CONTINUOUS_ASSURANCE_TOKEN_ROTATION"});setToken(b.deploymentTriggerToken);setMessage("Deployment token rotated. The old token is invalid.");});
  const updateGovernance=()=>action(async()=>{if(!governance)return;await apiMutation("/api/evidence-governance/policy","PUT",{retentionDays:retention,preserveFailedScans:true,preserveUnresolvedCleanup:true,preserveUnreviewedFindings:true,maximumExportBytes:maxExportMb*1048576,expectedVersion:governance.policy.rowVersion,confirmation:"I_CONFIRM_EVIDENCE_GOVERNANCE_POLICY"});await load();setMessage("Evidence retention policy updated.");});
  const exportEvidence=()=>action(async()=>{await apiMutation("/api/evidence-governance/exports","POST",{scanIds:exportScans,confirmation:"I_CONFIRM_ENCRYPTED_EVIDENCE_EXPORT"});await load();setMessage("Encrypted evidence bundle created.");});
  const purge=()=>action(async()=>{if(!governance)return;await apiMutation("/api/evidence-governance/purge","POST",{previewDigest:governance.purgePreview.previewDigest,confirmation:"I_CONFIRM_EVIDENCE_PURGE"});await load();setMessage("Digest-bound retention purge completed. Protected evidence was retained.");});
  const exportDraft=()=>{const blob=new Blob([JSON.stringify(input,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="routecairn-continuous-assurance-policy.json";link.click();URL.revokeObjectURL(url);};
  const importDraft=(file?:File)=>{if(!file)return;if(file.size>1024*1024){setMessage("Policy import is limited to 1 MiB.");return;}void file.text().then(text=>{setInput(JSON.parse(text) as PolicyInput);setSelected(undefined);setPreview(undefined);setProofText(undefined);setMessage("JSON draft imported. Preview and owner review are still required before activation.");}).catch(fail);};
  const selectBaseline=(adapterProfileId:string,scanId:string)=>{mutate({baselines:[...input.baselines.filter(b=>b.adapterProfileId!==adapterProfileId),...(scanId?[{adapterProfileId,scanId}]:[])],requiredCases:input.requiredCases.filter(c=>c.adapterProfileId!==adapterProfileId)});if(scanId)void apiGet<{cases:Array<{workflowId:string;caseFingerprint:string;executionState:string;requestTransmitted:boolean;matchedExpectation:boolean|null}>}>(`/api/scans/${scanId}/workflow-cases`).then(body=>{const exact=body.cases.filter(c=>c.executionState==="COMPLETED"&&c.requestTransmitted&&c.matchedExpectation===true).map(c=>({adapterProfileId,workflowId:c.workflowId,caseFingerprint:c.caseFingerprint}));setInput(v=>({...v,requiredCases:[...v.requiredCases.filter(c=>c.adapterProfileId!==adapterProfileId),...exact]}));setMessage(`Loaded ${exact.length} exact executable case fingerprint(s) from the selected baseline.`);}).catch(fail);};
  const estimated=useMemo(()=>preview?`${Math.ceil(preview.estimate.maximumDurationMs/60000)} min · ${preview.estimate.maxRequests} requests (${preview.estimate.cleanupReservedRequests} cleanup reserved)`:"Preview required",[preview]);
  return <section><div className="page-header"><h2>Continuous Assurance & Evidence Governance</h2><p>Schedule or deployment-trigger exact reviewed provider adapters, gate remediation with stable case fingerprints, and retain encrypted evidence.</p></div>
    <div className="cleanup-emergency" role="note"><div><strong>Automation never creates authorization</strong><p>Every run rechecks authorization expiry, target revision, credential health, adapter contract, request budget, cleanup state, and exact baselines. Healthy runs stay quiet.</p></div><span>FAIL CLOSED</span></div>
    {!canManage&&<p className="review-owner-warning">Owner review is required to create, activate, run, rotate, disable, export, or purge.</p>}
    <div className="production-mutation-builder form"><fieldset><legend>1. Authorization and target</legend><label>Registered target<select value={input.targetId} onChange={e=>mutate({targetId:e.target.value,adapterProfileIds:[],baselines:[]})}><option value="">Select target</option>{targets.map(t=><option key={t.id} value={t.id}>{t.displayName} · {t.classification}</option>)}</select></label><label>Policy name<input value={input.name} onChange={e=>mutate({name:e.target.value})}/></label><label>Authorization proof reference<input value={input.authorization.proofReference} onChange={e=>mutate({authorization:{...input.authorization,proofReference:e.target.value}})} placeholder="Approval ticket, scope document, or program reference"/></label><label>Authorization proof attestation (hashed locally; not stored)<textarea value={proofText??""} onChange={e=>setProofText(e.target.value)} placeholder="Paste the exact authorization attestation to derive its SHA-256 binding."/></label><small>Digest: <code>{input.authorization.proofDigest||"pending"}</code></small><label>Valid from<input type="datetime-local" value={localDate(input.authorization.validFrom)} onChange={e=>mutate({authorization:{...input.authorization,validFrom:new Date(e.target.value).toISOString()}})}/></label><label>Expires at<input type="datetime-local" value={localDate(input.authorization.expiresAt)} onChange={e=>mutate({authorization:{...input.authorization,expiresAt:new Date(e.target.value).toISOString()}})}/></label></fieldset>
    <fieldset><legend>2. Triggers and hard gates</legend><label className="inline-check"><input type="checkbox" checked={input.triggers.scheduleEnabled} onChange={e=>mutate({triggers:{...input.triggers,scheduleEnabled:e.target.checked}})}/> Scheduled reassessment</label><label>Interval minutes<input type="number" min={15} value={input.triggers.intervalMinutes} onChange={e=>mutate({triggers:{...input.triggers,intervalMinutes:Number(e.target.value)}})}/></label><label className="inline-check"><input type="checkbox" checked={input.triggers.deploymentEnabled} onChange={e=>mutate({triggers:{...input.triggers,deploymentEnabled:e.target.checked}})}/> Deployment-triggered reassessment</label><label className="inline-check"><input type="checkbox" checked={input.gates.failOnNewFinding} onChange={e=>mutate({gates:{...input.gates,failOnNewFinding:e.target.checked}})}/> Fail on new finding</label><label className="inline-check"><input type="checkbox" checked={input.gates.failOnOpenDrift} onChange={e=>mutate({gates:{...input.gates,failOnOpenDrift:e.target.checked}})}/> Fail on unreviewed adaptive drift</label><small>Regression, exact-case, and cleanup gates cannot be disabled.</small></fieldset></div>
    <section className="panel"><h3>3. Reviewed fixture/provider adapters</h3>{targetAdapters.map(a=><label className="inline-check" key={a.id}><input type="checkbox" checked={input.adapterProfileIds.includes(a.id)} onChange={e=>mutate({adapterProfileIds:e.target.checked?[...input.adapterProfileIds,a.id]:input.adapterProfileIds.filter(id=>id!==a.id),baselines:e.target.checked?input.baselines:input.baselines.filter(b=>b.adapterProfileId!==a.id),requiredCases:e.target.checked?input.requiredCases:input.requiredCases.filter(c=>c.adapterProfileId!==a.id)})}/><strong>{a.name}</strong> · {a.provider} · {a.engineId}</label>)}{input.adapterProfileIds.map(id=>{const a=targetAdapters.find(x=>x.id===id);const baseline=input.baselines.find(b=>b.adapterProfileId===id);return <label key={id}>Baseline for {a?.name??id}<select value={baseline?.scanId??""} onChange={e=>selectBaseline(id,e.target.value)}><option value="">Select exact prior scan (required to pass)</option>{targetScans.map(s=><option key={s.id} value={s.id}>{s.shortId} · {s.profile} · {s.createdAt}</option>)}</select></label>})}</section>
    <section className="panel"><h3>4. Exact remediation cases</h3><p className="muted">Baseline selection loads safe fingerprints automatically. A case passes only in its bound adapter lane when the identical fingerprint was transmitted, completed, and matched its expectation.</p>{input.requiredCases.map((c,i)=><div className="inline-form" key={`${c.adapterProfileId}:${i}`}><select aria-label="Case adapter" value={c.adapterProfileId} onChange={e=>mutate({requiredCases:input.requiredCases.map((x,n)=>n===i?{...x,adapterProfileId:e.target.value}:x)})}>{input.adapterProfileIds.map(id=><option key={id} value={id}>{targetAdapters.find(a=>a.id===id)?.name??id}</option>)}</select><input aria-label="Workflow ID" value={c.workflowId} onChange={e=>mutate({requiredCases:input.requiredCases.map((x,n)=>n===i?{...x,workflowId:e.target.value}:x)})}/><input aria-label="Case fingerprint" value={c.caseFingerprint} onChange={e=>mutate({requiredCases:input.requiredCases.map((x,n)=>n===i?{...x,caseFingerprint:e.target.value.trim().toLowerCase()}:x)})}/><button onClick={()=>mutate({requiredCases:input.requiredCases.filter((_,n)=>n!==i)})}>Remove</button></div>)}<button disabled={!input.adapterProfileIds.length} onClick={()=>mutate({requiredCases:[...input.requiredCases,{adapterProfileId:input.adapterProfileIds[0]!,workflowId:"",caseFingerprint:""}]})}>Add exact case</button></section>
    {diagnostics.length>0&&<div className="workflow-diagnostic-summary" role="alert">{diagnostics.map((d,i)=><span key={i}><code>{d.path.join(".")||"root"}</code> — {d.message}</span>)}</div>}
    <div className="actions"><button onClick={()=>void doPreview()}>Preview policy and budgets</button><button onClick={exportDraft}>Export JSON alternative</button><label className="button-like">Import JSON alternative<input hidden type="file" accept="application/json,.json" onChange={e=>importDraft(e.target.files?.[0])}/></label><button className="primary" disabled={!canManage||!preview||preview.blockers.length>0} onClick={()=>void save()}>{selected?"Create revised draft":"Save policy draft"}</button><button disabled={!canManage||!selected?.pendingVersionId||!preview||preview.blockers.length>0} onClick={()=>void review()}>Review exact policy</button><button disabled={!canManage||selected?.status!=="ACTIVE"} onClick={()=>void run()}>Run now</button>{selected&&["ACTIVE","DISABLED"].includes(selected.status)&&<button disabled={!canManage||(!selected.impact.canDisable&&selected.status==="ACTIVE")} onClick={()=>void toggle()}>{selected.status==="ACTIVE"?"Disable":"Enable"}</button>}<button disabled={!canManage||!selected} onClick={()=>void rotate()}>Rotate deployment token</button></div>
    {message&&<p aria-live="polite">{message}</p>}{token&&<div className="cleanup-emergency" role="alert"><div><strong>One-time deployment token</strong><p><code>{token}</code></p><p>Store this in the deployment provider's secret vault. RouteCairn stores only its SHA-256 verifier.</p></div><button onClick={()=>void navigator.clipboard.writeText(token)}>Copy</button></div>}
    {preview&&<section className="panel"><h3>Binding and capacity preview</h3><p><strong>{estimated}</strong></p><p>Policy digest <code>{preview.policyDigest}</code></p>{preview.adapterBindings.map(b=><p key={b.profileId}><code>{b.profileId.slice(0,8)}</code> → version <code>{b.versionId.slice(0,8)}</code> · {b.maxRequests} requests</p>)}{preview.blockers.map(x=><p className="error" key={x}>{x}</p>)}{preview.warnings.map(x=><p className="review-owner-warning" key={x}>{x}</p>)}</section>}
    <section className="panel"><h3>Policies and regression runs</h3>{policies.map(p=><div className="panel" key={p.id}><div className="actions"><button onClick={()=>void open(p.id)}>Open</button><strong>{p.name}</strong><span>{p.status} · next {p.nextDueAt??"not scheduled"}</span></div>{p.runs.map(r=><p key={r.id}><code>{r.id.slice(0,8)}</code> · {r.triggerType} · <strong>{r.status}/{r.gateStatus}</strong> · {r.createdAt}</p>)}</div>)}</section>
    <section className="panel"><h3>Actionable notifications</h3>{notices.filter(n=>!n.acknowledgedAt).map(n=><div className="cleanup-warning" key={n.id}><strong>{n.severity} · {n.category}</strong><p>{n.safeSummary}</p><button disabled={!canManage} onClick={()=>void action(async()=>{await apiMutation(`/api/continuous-assurance/notifications/${n.id}/acknowledge`,"POST",{confirmation:"I_ACKNOWLEDGE_CONTINUOUS_ASSURANCE_NOTIFICATION"});await load();})}>Acknowledge</button></div>)}{!notices.some(n=>!n.acknowledgedAt)&&<p className="muted">No regressions, failures, cleanup obligations, or approval requests. Healthy results remain quiet.</p>}</section>
    <section className="panel"><h3>Evidence governance</h3><p>Exports are AES-256-GCM encrypted, installation-bound, and locally HMAC-signed. Failed scans, unresolved cleanup, and unreviewed findings are never eligible for automatic purge.</p><div className="inline-form"><label>Retention days<input type="number" value={retention} onChange={e=>setRetention(Number(e.target.value))}/></label><label>Max export MiB<input type="number" value={maxExportMb} onChange={e=>setMaxExportMb(Number(e.target.value))}/></label><button disabled={!canManage} onClick={()=>void updateGovernance()}>Save retention</button></div><h4>Create encrypted export</h4>{scans.filter(s=>["COMPLETED","FAILED","CANCELLED","INTERRUPTED","IMPORTED"].includes(s.status)).slice(0,25).map(s=><label className="inline-check" key={s.id}><input type="checkbox" checked={exportScans.includes(s.id)} onChange={e=>setExportScans(e.target.checked?[...exportScans,s.id]:exportScans.filter(id=>id!==s.id))}/>{s.shortId} · {s.status} · {s.target}</label>)}<button disabled={!canManage||!exportScans.length} onClick={()=>void exportEvidence()}>Create encrypted export</button>{governance?.exports.map(x=><p key={x.id}><code>{x.id.slice(0,8)}</code> · {x.status} · {x.scanCount} scans · <a href={`/api/evidence-governance/exports/${x.id}/download`}>Download</a> · <button onClick={()=>void action(async()=>{await apiMutation(`/api/evidence-governance/exports/${x.id}/verify`,"POST",{});await load();})}>Verify</button></p>)}<h4>Digest-bound purge</h4><p>{governance?.purgePreview.candidates.length??0} eligible · protected failed {governance?.purgePreview.protectedCounts.failed??0} · cleanup {governance?.purgePreview.protectedCounts.cleanup??0} · review {governance?.purgePreview.protectedCounts.review??0}</p><button disabled={!canManage||!(governance?.purgePreview.candidates.length)} onClick={()=>void purge()}>Purge exact preview</button></section>
  </section>;
}

async function sha256(value:string):Promise<string>{const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("");}
function localDate(value:string):string{return new Date(value).toISOString().slice(0,16);}
