import React, { useEffect, useMemo, useRef, useState } from "react";
import { apiGet, apiMutation, DashboardApiError, type ScanSummary, type TargetSummary } from "./api";

type Credential = { id: string; safeAlias: string; enabled: boolean; targetId?: string; health?: { classification?: string } };
type PlanSummary = { id: string; name: string; targetId: string; targetName: string; targetOrigin: string; environment: string; status: string; planDigest: string; authorizationExpiresAt: string; laneCount: number; rowVersion: number; latestRunId?: string };
type ProofResult = { verified: boolean; missing: string[]; completedModules: string[]; completedWorkflows: string[]; features: string[]; completedCases: number; transmittedCases: number; providerAdapterBound: boolean; comparison?: { compatibility: string; unresolvedCases: number; unresolvedFindings: number } };
type LaneResult = { id: string; label: string; kind: string; required: boolean; disposition: string; scanId?: string; scanStatus?: string; findingCount: number; outcome: string; reason?: string; cleanupUnresolved: boolean; proof?: ProofResult };
type AcceptanceRun = { id: string; planId: string; standard: string; status: string; createdAt: string; completedAt?: string; coverage: { assessed: number; notAssessed: number; inconclusive: number; notApplicable: number; running: number; total: number; requiredGaps: number; complete: boolean; findingCount: number; cleanupUnresolved: number }; lanes: LaneResult[] };
type Preview = { planDigest: string; standard: string; totalRequestBudget: number; cleanupReservedRequests: number; requiredValidThrough: string; blockers: string[]; authorization: { active: boolean; expiresAt: string }; lanes: Array<{ id: string; label: string; kind: string; disposition: string; previewIdentity?: string; moduleCount?: number; requestBudget?: number; warnings: string[]; proofResult?: ProofResult }> };
type ComparisonSummary = { id: string; olderScanId: string; newerScanId: string; state: string; compatibilityState: string };

const defaultKinds = [
  ["public", "PUBLIC_BASELINE", "Public baseline", "public"],
  ["identity", "AUTHENTICATED_IDENTITY", "Authenticated identity", "primary"],
  ["pair", "ACCOUNT_PAIR_AUTHORIZATION", "Account A/B authorization", "account-pair"],
  ["browser", "BROWSER_LEARNING", "Authenticated browser learning", "primary"]
] as const;
const broaderGridKinds = [
  ["multi-tenant", "MULTI_TENANT_APPLICATION", "Genuine multi-tenant authorization"],
  ["supabase", "SUPABASE_RLS_STORAGE_RPC", "Supabase RLS, storage, and RPC"],
  ["auth-fixtures", "OAUTH_MFA_PASSKEYS", "OAuth/OIDC, MFA, and passkeys"],
  ["graphql", "GRAPHQL_AUTHORIZATION", "GraphQL authorization"],
  ["signed-artifacts", "SIGNED_PORTALS_EXPORTS", "Signed links, portals, and exports"],
  ["synthetic-payment", "SYNTHETIC_PAYMENT_PROVIDER", "Synthetic payment-provider fixture"],
  ["operations", "WEBHOOKS_CRON", "Webhooks and cron"]
] as const;

export function LiveAcceptanceWorkspace() {
  const [targets, setTargets] = useState<TargetSummary[]>([]);
  const [credentials, setCredentials] = useState<Credential[]>([]);
  const [scans, setScans] = useState<ScanSummary[]>([]);
  const [plans, setPlans] = useState<PlanSummary[]>([]);
  const [comparisons, setComparisons] = useState<ComparisonSummary[]>([]);
  const [targetId, setTargetId] = useState("");
  const [name, setName] = useState("Authorized live-target acceptance");
  const [authorizedBy, setAuthorizedBy] = useState("");
  const [proofReference, setProofReference] = useState("");
  const [proofSha256, setProofSha256] = useState("");
  const [startsAt, setStartsAt] = useState(() => localDate(new Date(Date.now() - 5 * 60_000)));
  const [expiresAt, setExpiresAt] = useState(() => localDate(new Date(Date.now() + 4 * 60 * 60_000)));
  const [neverPaths, setNeverPaths] = useState("/checkout\n/payment\n/delete");
  const [authPermitted, setAuthPermitted] = useState(true);
  const [mutationPermitted, setMutationPermitted] = useState(false);
  const [actorA, setActorA] = useState("");
  const [actorB, setActorB] = useState("");
  const [enabled, setEnabled] = useState<Record<string, boolean>>({ public: true, identity: true, pair: true, browser: true });
  const [mutationScanId, setMutationScanId] = useState("");
  const [recoveryScanId, setRecoveryScanId] = useState("");
  const [billingReason, setBillingReason] = useState("No authorized synthetic provider fixture is configured for this target.");
  const [billingDisposition, setBillingDisposition] = useState<"NOT_ASSESSED" | "NOT_APPLICABLE">("NOT_ASSESSED");
  const [billingEvidenceScanId, setBillingEvidenceScanId] = useState("");
  const [standard, setStandard] = useState<"CUSTOM" | "BROADER_REAL_TARGET_V1">("BROADER_REAL_TARGET_V1");
  const [gridScans, setGridScans] = useState<Record<string, string>>({});
  const [remediationComparisonId, setRemediationComparisonId] = useState("");
  const [preview, setPreview] = useState<Preview>();
  const [savedPlan, setSavedPlan] = useState<PlanSummary>();
  const [run, setRun] = useState<AcceptanceRun>();
  const [message, setMessage] = useState("");
  const [diagnostics, setDiagnostics] = useState<Array<{ path: string[]; message: string }>>([]);
  const [mode, setMode] = useState<"guided" | "json">("guided");
  const [json, setJson] = useState("{}");
  const proofFileRef = useRef<HTMLInputElement>(null);
  const importRef = useRef<HTMLInputElement>(null);
  const selectedTarget = targets.find((item) => item.id === targetId);
  const targetCredentials = credentials.filter((item) => item.enabled && (!item.targetId || item.targetId === targetId));
  const targetScans = scans.filter((item) => !selectedTarget || item.target === selectedTarget.baseOrigin);
  const guided = useMemo(() => buildPlan({ selectedTarget, name, authorizedBy, proofReference, proofSha256, startsAt, expiresAt, neverPaths, authPermitted, mutationPermitted, actorA, actorB, enabled, mutationScanId, recoveryScanId, billingReason, billingDisposition, billingEvidenceScanId, standard, gridScans, remediationComparison: comparisons.find((item) => item.id === remediationComparisonId) }), [selectedTarget, name, authorizedBy, proofReference, proofSha256, startsAt, expiresAt, neverPaths, authPermitted, mutationPermitted, actorA, actorB, enabled, mutationScanId, recoveryScanId, billingReason, billingDisposition, billingEvidenceScanId, standard, gridScans, remediationComparisonId, comparisons]);
  const activeInput = () => mode === "guided" ? guided : safeJson(json);
  const changed = () => { setPreview(undefined); setSavedPlan(undefined); setRun(undefined); setDiagnostics([]); };
  useEffect(() => { if (mode === "guided") setJson(JSON.stringify(guided, null, 2)); }, [guided, mode]);
  const load = async () => {
    const [targetBody, credentialBody, scanBody, planBody, comparisonBody] = await Promise.all([
      apiGet<{ targets: TargetSummary[] }>("/api/targets"), apiGet<{ profiles: Credential[] }>("/api/credential-profiles"), apiGet<{ scans: ScanSummary[] }>("/api/scans?pageSize=100"), apiGet<{ plans: PlanSummary[] }>("/api/live-acceptance/plans"), apiGet<{ comparisons: ComparisonSummary[] }>("/api/comparisons?limit=100")
    ]);
    setTargets(targetBody.targets); setCredentials(credentialBody.profiles); setScans(scanBody.scans); setPlans(planBody.plans); setComparisons(comparisonBody.comparisons ?? []);
  };
  useEffect(() => { void load().catch(errorMessage(setMessage)); }, []);
  useEffect(() => {
    if (!run || run.status !== "RUNNING") return;
    const timer = window.setInterval(() => void apiGet<{ run: AcceptanceRun }>(`/api/live-acceptance/runs/${run.id}`).then((body) => setRun(body.run)).catch(() => undefined), 2000);
    return () => window.clearInterval(timer);
  }, [run?.id, run?.status]);
  const doPreview = async () => action(async () => { const body = await apiMutation<{ preview: Preview }>("/api/live-acceptance/preview", "POST", activeInput()); setPreview(body.preview); setMessage(body.preview.blockers.length ? "Preview resolved with blockers." : "All lane plans resolved without transmitting requests."); });
  const save = async () => action(async () => { const body = await apiMutation<{ plan: PlanSummary; preview: Preview }>("/api/live-acceptance/plans", "POST", activeInput()); setSavedPlan(body.plan); setPreview(body.preview); setMessage("Encrypted draft saved. Review is bound to this exact digest."); await load(); });
  const review = async () => action(async () => { if (!savedPlan || !preview) return; const body = await apiMutation<{ plan: PlanSummary }>(`/api/live-acceptance/plans/${savedPlan.id}/review`, "POST", { planDigest: preview.planDigest, confirmation: "I_CONFIRM_REVIEWED_LIVE_ACCEPTANCE_PLAN" }); setSavedPlan(body.plan); setMessage("Exact acceptance plan reviewed. Any edit requires a new plan and review."); await load(); });
  const execute = async () => action(async () => { if (!savedPlan || !preview) return; const body = await apiMutation<{ run: AcceptanceRun }>(`/api/live-acceptance/plans/${savedPlan.id}/execute`, "POST", { planDigest: preview.planDigest, confirmation: "I_CONFIRM_EXECUTE_REVIEWED_LIVE_ACCEPTANCE_PLAN" }); setRun(body.run); setMessage("Live acceptance lanes queued through isolated workers."); await load(); });
  const openPlan = async (id: string) => action(async () => { const body = await apiGet<{ plan: PlanSummary & { input: unknown; runs: AcceptanceRun[] } }>(`/api/live-acceptance/plans/${id}`); setSavedPlan(body.plan); setJson(JSON.stringify(body.plan.input, null, 2)); setMode("json"); setPreview(undefined); setRun(body.plan.runs[0]); setMessage("Stored encrypted plan opened. Resolve a fresh authoritative preview before review or execution."); });
  const action = async (work: () => Promise<void>) => { try { setDiagnostics([]); await work(); } catch (error) { if (error instanceof DashboardApiError) setDiagnostics([...error.diagnostics]); setMessage(error instanceof Error ? error.message : "Live acceptance operation failed."); } };
  const exportPlan = () => download(`${name || "live-acceptance"}.routecairn.json`, { format: "routecairn-live-acceptance", version: 1, input: activeInput() });
  const importPlan = async (file: File) => { if (file.size > 1024 * 1024) throw new Error("Acceptance plan import exceeds 1 MiB."); const parsed = safeJson(await file.text()) as Record<string, unknown>; const input = parsed.format === "routecairn-live-acceptance" ? parsed.input : parsed; if (!input || typeof input !== "object") throw new Error("Acceptance plan object required."); setJson(JSON.stringify(input, null, 2)); setMode("json"); changed(); setMessage("Imported locally. Resolve a server preview before saving or reviewing."); };
  return <section>
    <div className="page-header"><h2>Live Target Acceptance</h2><p>Build, review, execute, and monitor a reusable multi-lane acceptance plan against an explicitly authorized disposable staging or production target.</p></div>
    <div className="cleanup-emergency" role="note"><div><strong>Authorization and cleanup remain binding</strong><p>Mutation and recovery lanes can only link separately approved controlled-mutation scans. Real payments and destructive administration are prohibited.</p></div><span>IMMUTABLE REVIEW</span></div>
    <div className="workflow-editor-toolbar"><button className={mode === "guided" ? "selected" : ""} onClick={() => { setMode("guided"); changed(); }}>Guided builder</button><button className={mode === "json" ? "selected" : ""} onClick={() => { setJson(JSON.stringify(guided, null, 2)); setMode("json"); changed(); }}>JSON alternative</button><button onClick={exportPlan}>Export safe JSON</button><button onClick={() => importRef.current?.click()}>Import JSON</button><input ref={importRef} hidden type="file" accept="application/json,.json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importPlan(file).catch(errorMessage(setMessage)); event.currentTarget.value = ""; }} /></div>
    {mode === "guided" ? <div className="production-mutation-builder form">
      <fieldset><legend>1. Registered target</legend><label>Target<select value={targetId} onChange={(event) => { setTargetId(event.target.value); changed(); }}><option value="">Select target</option>{targets.map((target) => <option key={target.id} value={target.id}>{target.displayName} · {target.classification}</option>)}</select></label><label>Plan name<input value={name} onChange={(event) => { setName(event.target.value); changed(); }} /></label><p className="muted">Environment: {selectedTarget?.classification === "PRODUCTION" ? "PRODUCTION" : "STAGING"}. Scope is inherited from the registered target.</p></fieldset>
      <fieldset><legend>2. Authorization proof</legend><label>Authorized by<input value={authorizedBy} onChange={(event) => { setAuthorizedBy(event.target.value); changed(); }} /></label><label>Proof reference<input value={proofReference} onChange={(event) => { setProofReference(event.target.value); changed(); }} placeholder="Change ticket, contract, or owner approval" /></label><label>Proof SHA-256<input value={proofSha256} onChange={(event) => { setProofSha256(event.target.value.toLowerCase()); changed(); }} placeholder="64 hex characters" /></label><button type="button" onClick={() => proofFileRef.current?.click()}>Hash proof file locally</button><input ref={proofFileRef} hidden type="file" onChange={(event) => { const file = event.target.files?.[0]; if (file) void hashFile(file).then((hash) => { setProofSha256(hash); if (!proofReference) setProofReference(file.name); changed(); }); event.currentTarget.value = ""; }} /></fieldset>
      <fieldset><legend>3. Window and hard exclusions</legend><label>Starts<input type="datetime-local" value={startsAt} onChange={(event) => { setStartsAt(event.target.value); changed(); }} /></label><label>Expires<input type="datetime-local" value={expiresAt} onChange={(event) => { setExpiresAt(event.target.value); changed(); }} /></label><label>Never-test paths, one per line<textarea value={neverPaths} onChange={(event) => { setNeverPaths(event.target.value); changed(); }} /></label><label className="inline-check"><input type="checkbox" checked={authPermitted} onChange={(event) => { setAuthPermitted(event.target.checked); changed(); }} /> Authentication permitted</label><label className="inline-check"><input type="checkbox" checked={mutationPermitted} onChange={(event) => { setMutationPermitted(event.target.checked); changed(); }} /> Separately approved disposable mutation evidence permitted</label></fieldset>
      <fieldset><legend>4. Disposable actors</legend><label>Primary / Account A<select value={actorA} onChange={(event) => { setActorA(event.target.value); changed(); }}><option value="">Select credential</option>{targetCredentials.map(credentialOption)}</select></label><label>Account B<select value={actorB} onChange={(event) => { setActorB(event.target.value); changed(); }}><option value="">Select credential</option>{targetCredentials.map(credentialOption)}</select></label><p className="muted">Credential readiness and identity drift are rechecked for every child scan.</p></fieldset>
      <fieldset><legend>5. Acceptance standard</legend><label>Grid<select value={standard} onChange={(event) => { setStandard(event.target.value as typeof standard); changed(); }}><option value="BROADER_REAL_TARGET_V1">Broader real-target proof v1</option><option value="CUSTOM">Custom / legacy lanes</option></select></label>{standard === "BROADER_REAL_TARGET_V1" ? <><p className="muted">Each row must link completed same-target evidence. The server verifies completed modules, exact semantic cases, transmitted requests, strong evidence, provider-adapter binding, cleanup, and comparison coverage.</p>{broaderGridKinds.map(([key, , label]) => <label key={key}>{label}<select value={gridScans[key] ?? ""} onChange={(event) => { setGridScans({ ...gridScans, [key]: event.target.value }); changed(); }}><option value="">Not assessed</option>{targetScans.filter((scan) => ["COMPLETED", "IMPORTED"].includes(scan.status)).map(scanOption)}</select></label>)}<label>Remediation comparison<select value={remediationComparisonId} onChange={(event) => { setRemediationComparisonId(event.target.value); changed(); }}><option value="">Not assessed</option>{comparisons.filter((item) => !selectedTarget || targetScans.some((scan) => scan.id === item.newerScanId)).map(comparisonOption)}</select></label></> : <>{defaultKinds.map(([key, , label]) => <label className="inline-check" key={key}><input type="checkbox" checked={Boolean(enabled[key])} onChange={(event) => { setEnabled({ ...enabled, [key]: event.target.checked }); changed(); }} /> {label}</label>)}<p className="muted">Each enabled lane receives its own immutable worker plan, budget, evidence, findings, cleanup state, and automatic comparison.</p></>}</fieldset>
      <fieldset><legend>6. Controlled mutation and recovery evidence</legend><label>Mutation acceptance scan<select value={mutationScanId} onChange={(event) => { setMutationScanId(event.target.value); if (event.target.value) setMutationPermitted(true); changed(); }}><option value="">Not assessed in this plan</option>{targetScans.map(scanOption)}</select></label><label>Restart/recovery scan<select value={recoveryScanId} onChange={(event) => { setRecoveryScanId(event.target.value); if (event.target.value) setMutationPermitted(true); changed(); }}><option value="">Not assessed in this plan</option>{targetScans.map(scanOption)}</select></label><p className="muted">Only scans already launched through the controlled-mutation approval and recovery workspaces may be linked.</p></fieldset>
      <fieldset><legend>7. Provider-specific coverage</legend><label>Coverage decision<select value={billingDisposition} onChange={(event) => { setBillingDisposition(event.target.value as "NOT_ASSESSED" | "NOT_APPLICABLE"); setBillingEvidenceScanId(""); changed(); }}><option value="NOT_ASSESSED">Not assessed — fixture unavailable</option><option value="NOT_APPLICABLE">Not applicable — evidence required</option></select></label><label>Webhook/billing reason<textarea value={billingReason} onChange={(event) => { setBillingReason(event.target.value); changed(); }} /></label>{billingDisposition === "NOT_APPLICABLE" && <label>Completed same-target evidence scan<select value={billingEvidenceScanId} onChange={(event) => { setBillingEvidenceScanId(event.target.value); changed(); }}><option value="">No evidence attached</option>{targetScans.filter((scan) => ["COMPLETED", "IMPORTED"].includes(scan.status)).map(scanOption)}</select></label>}<p className="muted">NOT_ASSESSED preserves a fixture gap. NOT_APPLICABLE can satisfy adaptive completeness only when a completed same-target scan evidences the absence of this product surface. No real payment execution is allowed.</p></fieldset>
    </div> : <label className="advanced-json">Live acceptance JSON<textarea rows={34} value={json} spellCheck={false} onChange={(event) => { setJson(event.target.value); changed(); }} /></label>}
    {diagnostics.length > 0 && <div className="workflow-diagnostic-summary" role="alert"><strong>{diagnostics.length} field issue(s)</strong>{diagnostics.map((item, index) => <span key={`${item.path.join(".")}-${index}`}><code>{item.path.join(".") || "root"}</code> — {item.message}</span>)}</div>}
    <div className="actions"><button onClick={() => void doPreview()}>Preview all lanes</button><button className="primary" disabled={!preview || preview.blockers.length > 0} onClick={() => void save()}>Save encrypted plan</button><button disabled={!savedPlan || savedPlan.status !== "DRAFT" || !preview || preview.blockers.length > 0} onClick={() => void review()}>Review exact plan</button><button className="danger" disabled={!savedPlan || savedPlan.status !== "REVIEWED" || !preview} onClick={() => window.confirm("Execute every reviewed live acceptance lane now?") && void execute()}>Execute reviewed plan</button></div>
    {message && <p aria-live="polite">{message}</p>}
    {preview && <section className="panel"><h3>Plan and proof preview</h3><dl className="dense-dl"><dt>Standard</dt><dd>{preview.standard}</dd><dt>Digest</dt><dd><code>{preview.planDigest}</code></dd><dt>Request capacity</dt><dd>{preview.totalRequestBudget}</dd><dt>Cleanup reserve</dt><dd>{preview.cleanupReservedRequests}</dd><dt>Authorization</dt><dd>{preview.authorization.active ? "ACTIVE" : "INACTIVE"} until {preview.authorization.expiresAt}</dd><dt>Required valid through</dt><dd>{preview.requiredValidThrough}</dd></dl>{preview.blockers.map((item) => <p className="error" key={item}>{item}</p>)}<div className="table compact-table"><div className="row"><span>Lane</span><span>Disposition</span><span>Proof</span><span>Budget</span></div>{preview.lanes.map((lane) => <div className="row" key={lane.id}><span><strong>{lane.label}</strong><small>{lane.kind}</small></span><span>{lane.disposition}</span><span>{lane.proofResult ? `${lane.proofResult.transmittedCases} transmitted · ${lane.proofResult.features.length} features` : `${lane.moduleCount ?? 0} modules`}</span><span>{lane.requestBudget ?? "—"}{lane.warnings.map((warning) => <small className="error" key={warning}>{warning}</small>)}</span></div>)}</div></section>}
    {run && <RunPanel run={run} onCancel={() => void apiMutation<{ run: AcceptanceRun }>(`/api/live-acceptance/runs/${run.id}/cancel`, "POST", {}).then((body) => setRun(body.run)).catch(errorMessage(setMessage))} />}
    <section className="panel"><h3>Saved acceptance plans</h3>{plans.length ? <div className="table compact-table"><div className="row"><span>Plan</span><span>Target</span><span>Status</span><span>Action</span></div>{plans.map((plan) => <div className="row" key={plan.id}><span><strong>{plan.name}</strong><small>{plan.laneCount} lanes · expires {plan.authorizationExpiresAt}</small></span><span>{plan.targetName}</span><span>{plan.status}</span><span><button onClick={() => void openPlan(plan.id)}>Open</button></span></div>)}</div> : <p className="muted">No saved live acceptance plans.</p>}</section>
  </section>;
}

function RunPanel({ run, onCancel }: { run: AcceptanceRun; onCancel(): void }) { return <section className="panel"><h3>Acceptance run</h3><div className="cards"><div className="metric"><strong>{run.status}</strong><span>{run.standard}</span></div><div className="metric"><strong>{run.coverage.assessed}/{run.coverage.total}</strong><span>Assessed lanes</span></div><div className="metric"><strong>{run.coverage.requiredGaps}</strong><span>Required gaps</span></div><div className="metric"><strong>{run.coverage.findingCount}</strong><span>Findings</span></div><div className="metric"><strong>{run.coverage.cleanupUnresolved}</strong><span>Cleanup unresolved</span></div></div>{run.status === "RUNNING" && <button onClick={onCancel}>Cancel run safely</button>}<div className="table compact-table"><div className="row"><span>Lane</span><span>Outcome</span><span>Scan</span><span>Evidence</span></div>{run.lanes.map((lane) => <div className="row" key={lane.id}><span><strong>{lane.label}</strong><small>{lane.kind}</small></span><span>{lane.outcome}{lane.reason && <small>{lane.reason}</small>}</span><span>{lane.scanId ? <a href={`/scans/${lane.scanId}`}>{lane.scanId.slice(0, 8)}</a> : "—"}<small>{lane.scanStatus}</small></span><span>{lane.proof ? `${lane.proof.transmittedCases} case(s) · ${lane.proof.features.join(", ") || "no feature proof"}` : `${lane.findingCount} finding(s)`}{lane.cleanupUnresolved && <small className="error">Cleanup unresolved</small>}</span></div>)}</div></section>; }
function buildPlan(input: { selectedTarget?: TargetSummary; name: string; authorizedBy: string; proofReference: string; proofSha256: string; startsAt: string; expiresAt: string; neverPaths: string; authPermitted: boolean; mutationPermitted: boolean; actorA: string; actorB: string; enabled: Record<string, boolean>; mutationScanId: string; recoveryScanId: string; billingReason: string; billingDisposition: "NOT_ASSESSED" | "NOT_APPLICABLE"; billingEvidenceScanId: string; standard: "CUSTOM" | "BROADER_REAL_TARGET_V1"; gridScans: Record<string, string>; remediationComparison?: ComparisonSummary }) {
  const target = input.selectedTarget; const lanes: unknown[] = [];
  if (input.standard === "BROADER_REAL_TARGET_V1") {
    for (const [key, kind, label] of broaderGridKinds) lanes.push({ id: key, label, kind, required: true, execution: input.gridScans[key] ? { disposition: "LINK_SCAN", scanId: input.gridScans[key] } : { disposition: "NOT_ASSESSED", reason: `No completed same-target evidence scan is linked for ${label.toLowerCase()}.` } });
    const comparison = input.remediationComparison;
    lanes.push({ id: "remediation", label: "Real remediation rerun", kind: "REMEDIATION_RERUNS", required: true, execution: comparison ? { disposition: "LINK_REMEDIATION", baselineScanId: comparison.olderScanId, rerunScanId: comparison.newerScanId, comparisonId: comparison.id } : { disposition: "NOT_ASSESSED", reason: "No exact baseline-to-rerun comparison is linked for remediation acceptance." } });
    return { schemaVersion: 1, standard: input.standard, name: input.name, targetId: target?.id ?? "", environment: target?.classification === "PRODUCTION" ? "PRODUCTION" : "STAGING", authorization: { mode: target?.authorizationType === "BUG_BOUNTY" ? "BUG_BOUNTY_AUTHORIZED" : target?.classification === "PRODUCTION" ? "OWNED_PRODUCTION" : "INTERNAL_STAGING", proofReference: input.proofReference, proofSha256: input.proofSha256, authorizedBy: input.authorizedBy, startsAt: iso(input.startsAt), expiresAt: iso(input.expiresAt), neverTestPaths: lines(input.neverPaths), authenticationPermitted: input.authPermitted, mutationPermitted: input.mutationPermitted, disposableAccountsOnly: true, realPaymentsAllowed: false, destructiveAdministrationAllowed: false }, lanes };
  }
  for (const [key, kind, label, authMode] of defaultKinds) if (input.enabled[key]) {
    const authentication = authMode === "public" ? { mode: "public" } : authMode === "primary" ? { mode: "primary", credentialProfileId: input.actorA } : { mode: "account-pair", accountAProfileId: input.actorA, accountBProfileId: input.actorB };
    const includeModules = kind === "BROWSER_LEARNING" ? ["baseline", "browser-crawler"] : kind === "ACCOUNT_PAIR_AUTHORIZATION" ? ["baseline", "authenticated-testing", "state-aware-api"] : [];
    lanes.push({ id: key, label, kind, required: true, execution: { disposition: "EXECUTE_SCAN", profile: authMode === "public" ? "full" : "authenticated", authentication, includeModules, workflows: [], advancedEngines: [], maxRequests: kind === "BROWSER_LEARNING" ? 120 : 250, cleanupReservedRequests: 0, rateLimitPerSecond: 3, concurrency: 3, evidenceLevel: "strong" } });
  }
  lanes.push({ id: "mutation", label: "Controlled mutation and rollback", kind: "MUTATION_ACCEPTANCE", required: true, execution: input.mutationScanId ? { disposition: "LINK_SCAN", scanId: input.mutationScanId } : { disposition: "NOT_ASSESSED", reason: "No separately approved controlled-mutation acceptance scan has been linked." } });
  lanes.push({ id: "recovery", label: "Restart and encrypted recovery", kind: "RECOVERY_ACCEPTANCE", required: true, execution: input.recoveryScanId ? { disposition: "LINK_SCAN", scanId: input.recoveryScanId } : { disposition: "NOT_ASSESSED", reason: "No forced-interruption and fresh-credential recovery scan has been linked." } });
  lanes.push({ id: "synthetic-billing", label: "Webhook and synthetic billing", kind: "BILLING_ENTITLEMENTS", required: false, execution: input.billingDisposition === "NOT_APPLICABLE" ? { disposition: "NOT_APPLICABLE", reason: input.billingReason, ...(input.billingEvidenceScanId ? { evidenceScanId: input.billingEvidenceScanId } : {}) } : { disposition: "NOT_ASSESSED", reason: input.billingReason } });
  return { schemaVersion: 1, standard: input.standard, name: input.name, targetId: target?.id ?? "", environment: target?.classification === "PRODUCTION" ? "PRODUCTION" : "STAGING", authorization: { mode: target?.authorizationType === "BUG_BOUNTY" ? "BUG_BOUNTY_AUTHORIZED" : target?.classification === "PRODUCTION" ? "OWNED_PRODUCTION" : "INTERNAL_STAGING", proofReference: input.proofReference, proofSha256: input.proofSha256, authorizedBy: input.authorizedBy, startsAt: iso(input.startsAt), expiresAt: iso(input.expiresAt), neverTestPaths: lines(input.neverPaths), authenticationPermitted: input.authPermitted, mutationPermitted: input.mutationPermitted, disposableAccountsOnly: true, realPaymentsAllowed: false, destructiveAdministrationAllowed: false }, lanes };
}
function credentialOption(item: Credential) { return <option key={item.id} value={item.id}>{item.safeAlias} · {item.health?.classification ?? "UNVERIFIED"}</option>; }
function scanOption(item: ScanSummary) { return <option key={item.id} value={item.id}>{item.shortId} · {item.status} · {item.profile}</option>; }
function comparisonOption(item: ComparisonSummary) { return <option key={item.id} value={item.id}>{item.olderScanId.slice(0, 8)} → {item.newerScanId.slice(0, 8)} · {item.compatibilityState}</option>; }
function localDate(value: Date): string { return new Date(value.getTime() - value.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }
function iso(value: string): string { try { return new Date(value).toISOString(); } catch { return ""; } }
function lines(value: string): string[] { return [...new Set(value.split(/\r?\n/).map((item) => item.trim()).filter(Boolean))]; }
function safeJson(value: string): any { const parsed = JSON.parse(value); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed) || prohibited(parsed)) throw new Error("A safe live acceptance object is required."); return parsed; }
function prohibited(value: unknown): boolean { return Boolean(value) && typeof value === "object" && (Array.isArray(value) ? value.some(prohibited) : Object.entries(value as Record<string, unknown>).some(([key, child]) => ["__proto__", "prototype", "constructor"].includes(key) || prohibited(child))); }
async function hashFile(file: File): Promise<string> { const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer()); return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
function download(name: string, value: unknown): void { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = name.replace(/[^A-Za-z0-9._-]/g, "-"); link.click(); URL.revokeObjectURL(url); }
function errorMessage(setter: (value: string) => void) { return (error: unknown) => setter(error instanceof Error ? error.message : "Operation failed."); }
