import React, { useEffect, useMemo, useState } from "react";
import { apiGet, apiMutation, DashboardApiError, type TargetSummary } from "./api";
import { AdvancedEngineStudio, type AdvancedEngineDraft, type AdvancedEngineId } from "./AdvancedEngineStudio";

type Credential = { id: string; safeAlias: string; enabled: boolean; targetId?: string; health?: { classification?: string } };
type AdapterVersion = { id: string; revision: number; status: string; adapterDigest: string; createdAt: string; reviewedAt?: string };
type Adapter = { id: string; name: string; description?: string; targetId: string; provider: string; engineId: AdvancedEngineId; enabled: boolean; activeVersionId?: string; pendingVersionId?: string; rowVersion: number; impact: { recommendationBindings: number; scanBindings: number; activeScans: number; canDisable: boolean; impactDigest: string }; versions?: AdapterVersion[]; pendingInput?: AdapterInput; activeInput?: AdapterInput };
type AdapterInput = { schemaVersion: 1; name: string; description: string; targetId: string; environment: "LOCAL" | "TEST" | "STAGING" | "PRODUCTION"; provider: string; engineId: AdvancedEngineId; capabilities: string[]; authentication: { mode: "public" } | { mode: "primary"; credentialProfileId: string } | { mode: "account-pair"; accountAProfileId: string; accountBProfileId: string }; engineConfiguration: Record<string, unknown>; fixture: { disposableOnly: true; realPaymentExecution: "FORBIDDEN"; allowedPathPrefixes: string[]; cleanupRequired: boolean; cleanupEvidenceRequired: boolean; operatorNotes: string }; limits: { maxRequests: number; cleanupReservedRequests: number; rateLimitPerSecond: number; concurrency: number; evidenceLevel: "minimal" | "normal" | "strong" }; recommendationId?: string };
type Preview = { adapterDigest: string; blockers: string[]; warnings: string[]; engine: { id: string; capability: string; provider: string }; credentialBindings: Array<{ role: string; safeAlias: string; health: string }>; plan?: { previewIdentity: string; modules: unknown[]; controlledWorkflowRequests: Array<{ workflowId: string; exactRequests: number }>; credentialReadiness: { ready: boolean; blockers: unknown[]; warnings: unknown[] } } };
type Materialized = { target: TargetSummary; input: AdapterInput; binding: { profileId: string; versionId: string; adapterDigest: string } };

const providers = ["GENERIC_HTTP", "SUPABASE", "STRIPE_TEST", "ADYEN_TEST", "BRAINTREE_SANDBOX", "PAYPAL_SANDBOX", "PADDLE_SANDBOX", "CUSTOM_SYNTHETIC"];
const capabilityByEngine: Record<AdvancedEngineId, string> = { "supabase-authorization": "DATA_AUTHORIZATION", "authentication-lifecycle": "AUTHENTICATION_LIFECYCLE", "authentication-lifecycle-automation": "AUTHENTICATION_LIFECYCLE", "business-invariant": "BUSINESS_INVARIANT", "controlled-race": "CONTROLLED_RACE", "api-graphql-authorization": "API_GRAPHQL_AUTHORIZATION", "link-portal-export-security": "CAPABILITY_LINKS", "operational-endpoint-security": "OPERATIONAL_ENDPOINTS", "billing-entitlement-security": "SYNTHETIC_BILLING", "assisted-review": "ASSISTED_REVIEW", "pre-handover-assault": "PRE_HANDOVER", "bug-bounty-authorization": "BUG_BOUNTY_SCOPE" };

export function ProviderAdapterWorkspace({ canManage, onUse }: { canManage: boolean; onUse(materialized: Materialized): void }) {
  const [targets, setTargets] = useState<TargetSummary[]>([]); const [credentials, setCredentials] = useState<Credential[]>([]); const [adapters, setAdapters] = useState<Adapter[]>([]);
  const [targetId, setTargetId] = useState(""); const [name, setName] = useState("Reusable authorized fixture"); const [description, setDescription] = useState(""); const [provider, setProvider] = useState("GENERIC_HTTP"); const [engineId, setEngineId] = useState<AdvancedEngineId>("api-graphql-authorization");
  const [authMode, setAuthMode] = useState<"public" | "primary" | "account-pair">("public"); const [actorA, setActorA] = useState(""); const [actorB, setActorB] = useState(""); const [pathPrefixes, setPathPrefixes] = useState("/api/"); const [cleanupRequired, setCleanupRequired] = useState(false); const [operatorNotes, setOperatorNotes] = useState("");
  const [maxRequests, setMaxRequests] = useState(100); const [cleanupReserve, setCleanupReserve] = useState(0); const [rate, setRate] = useState(2); const [concurrency, setConcurrency] = useState(2); const [drafts, setDrafts] = useState<AdvancedEngineDraft[]>([]); const [modules, setModules] = useState<string[]>([]);
  const [preview, setPreview] = useState<Preview>(); const [selected, setSelected] = useState<Adapter>(); const [message, setMessage] = useState(""); const [diagnostics, setDiagnostics] = useState<Array<{ path: string[]; message: string }>>([]); const [recommendations, setRecommendations] = useState<Array<{ id: string; category: string; engineId: string; status: string }>>([]); const [recommendationId, setRecommendationId] = useState("");
  const target = targets.find((item) => item.id === targetId); const targetCredentials = credentials.filter((item) => item.enabled && (!item.targetId || item.targetId === targetId)); const engineDraft = drafts.find((item) => item.id === engineId && item.enabled);
  const input = useMemo<AdapterInput>(() => ({ schemaVersion: 1, name, description, targetId, environment: target?.classification === "PRODUCTION" ? "PRODUCTION" : "STAGING", provider, engineId, capabilities: [capabilityByEngine[engineId]], authentication: authMode === "public" ? { mode: "public" } : authMode === "primary" ? { mode: "primary", credentialProfileId: actorA } : { mode: "account-pair", accountAProfileId: actorA, accountBProfileId: actorB }, engineConfiguration: engineDraft?.value ?? {}, fixture: { disposableOnly: true, realPaymentExecution: "FORBIDDEN", allowedPathPrefixes: pathPrefixes.split(/\r?\n/).map((item) => item.trim()).filter(Boolean), cleanupRequired, cleanupEvidenceRequired: cleanupRequired, operatorNotes }, limits: { maxRequests, cleanupReservedRequests: cleanupReserve, rateLimitPerSecond: rate, concurrency, evidenceLevel: "strong" }, ...(recommendationId ? { recommendationId } : {}) }), [name, description, targetId, target?.classification, provider, engineId, authMode, actorA, actorB, engineDraft?.value, pathPrefixes, cleanupRequired, operatorNotes, maxRequests, cleanupReserve, rate, concurrency, recommendationId]);
  const load = async () => { const [targetBody, credentialBody, adapterBody] = await Promise.all([apiGet<{ targets: TargetSummary[] }>("/api/targets"), apiGet<{ profiles: Credential[] }>("/api/credential-profiles"), apiGet<{ adapters: Adapter[] }>("/api/provider-adapters")]); setTargets(targetBody.targets); setCredentials(credentialBody.profiles); setAdapters(adapterBody.adapters); };
  useEffect(() => { void load().catch(fail(setMessage)); }, []);
  useEffect(() => { if (!targetId) { setRecommendations([]); return; } void apiGet<{ adaptiveSecurity: { recommendations: typeof recommendations } }>(`/api/adaptive-security/targets/${targetId}`).then((body) => setRecommendations(body.adaptiveSecurity.recommendations.filter((item) => item.status === "APPROVED"))).catch(() => setRecommendations([])); }, [targetId]);
  const changed = () => { setPreview(undefined); setDiagnostics([]); };
  const doPreview = async () => action(async () => { const body = await apiMutation<{ preview: Preview }>("/api/provider-adapters/preview", "POST", input); setPreview(body.preview); setMessage(body.preview.blockers.length ? "Adapter preview contains blockers." : "Adapter and complete scan plan are valid. No requests were transmitted."); });
  const save = async () => action(async () => { const path = selected ? `/api/provider-adapters/${selected.id}` : "/api/provider-adapters"; const method = selected ? "PATCH" : "POST"; const body = await apiMutation<{ adapter: Adapter }>(path, method, input); setSelected(body.adapter); setMessage(selected ? "New encrypted immutable draft version created." : "Encrypted adapter draft created."); await load(); });
  const review = async () => action(async () => { if (!selected?.pendingVersionId || !preview) return; const body = await apiMutation<{ adapter: Adapter }>(`/api/provider-adapters/${selected.id}/review`, "POST", { versionId: selected.pendingVersionId, adapterDigest: preview.adapterDigest, confirmation: "I_CONFIRM_REVIEWED_PROVIDER_ADAPTER" }); setSelected(body.adapter); setMessage("Exact adapter version reviewed and activated."); await load(); });
  const use = async (id: string) => action(async () => { const body = await apiMutation<{ materialized: Materialized }>(`/api/provider-adapters/${id}/materialize`, "POST", {}); onUse(body.materialized); });
  const open = async (id: string) => action(async () => { const body = await apiGet<{ adapter: Adapter }>(`/api/provider-adapters/${id}`); const adapter = body.adapter; const value = adapter.pendingInput ?? adapter.activeInput; setSelected(adapter); if (value) hydrate(value); setPreview(undefined); setMessage("Adapter opened. A new edit creates a separate immutable draft version."); });
  const toggle = async (adapter: Adapter) => action(async () => { await apiMutation(`/api/provider-adapters/${adapter.id}/state`, "POST", { enabled: !adapter.enabled, impactDigest: adapter.impact.impactDigest, confirmation: "I_CONFIRM_PROVIDER_ADAPTER_STATE_CHANGE" }); await load(); setMessage(`Adapter ${adapter.enabled ? "disabled" : "enabled"}.`); });
  const bind = async () => action(async () => { if (!selected || !recommendationId) return; await apiMutation(`/api/provider-adapters/${selected.id}/recommendation`, "POST", { recommendationId }); setMessage("Adapter bound to the exact approved adaptive recommendation."); await load(); });
  const hydrate = (value: AdapterInput) => { setTargetId(value.targetId); setName(value.name); setDescription(value.description); setProvider(value.provider); setEngineId(value.engineId); setAuthMode(value.authentication.mode); setActorA(value.authentication.mode === "primary" ? value.authentication.credentialProfileId : value.authentication.mode === "account-pair" ? value.authentication.accountAProfileId : ""); setActorB(value.authentication.mode === "account-pair" ? value.authentication.accountBProfileId : ""); setPathPrefixes(value.fixture.allowedPathPrefixes.join("\n")); setCleanupRequired(value.fixture.cleanupRequired); setOperatorNotes(value.fixture.operatorNotes); setMaxRequests(value.limits.maxRequests); setCleanupReserve(value.limits.cleanupReservedRequests); setRate(value.limits.rateLimitPerSecond); setConcurrency(value.limits.concurrency); setRecommendationId(value.recommendationId ?? ""); setDrafts([{ id: value.engineId, enabled: true, editorMode: "guided", value: value.engineConfiguration } as AdvancedEngineDraft]); };
  const action = async (fn: () => Promise<void>) => { try { setDiagnostics([]); await fn(); } catch (error) { if (error instanceof DashboardApiError) setDiagnostics([...error.diagnostics]); setMessage(error instanceof Error ? error.message : "Provider adapter operation failed."); } };
  return <section><div className="page-header"><h2>Fixture & Provider Adapters</h2><p>Build reusable target-bound provider fixtures, review an immutable version, and materialize it directly into Scan Studio.</p></div>
    <div className="cleanup-emergency" role="note"><div><strong>Reusable does not mean pre-authorized</strong><p>Adapters bind configuration and fixtures. Every scan still requires a current preview, target authorization, credential readiness, request budgets, mutation approval, and verified cleanup.</p></div><span>REAL PAYMENTS FORBIDDEN</span></div>
    {!canManage && <p className="review-owner-warning">Only an owner can create, review, bind, enable, or disable adapter versions. Reviewed adapters may still be used according to scan permissions.</p>}
    <div className="production-mutation-builder form"><fieldset><legend>1. Identity and target</legend><label>Registered target<select value={targetId} onChange={(event) => { setTargetId(event.target.value); setSelected(undefined); changed(); }}><option value="">Select target</option>{targets.map((item) => <option key={item.id} value={item.id}>{item.displayName} · {item.classification}</option>)}</select></label><label>Name<input value={name} onChange={(event) => { setName(event.target.value); changed(); }} /></label><label>Description<textarea value={description} onChange={(event) => { setDescription(event.target.value); changed(); }} /></label><label>Provider<select value={provider} onChange={(event) => { setProvider(event.target.value); changed(); }}>{providers.map((item) => <option key={item}>{item}</option>)}</select></label></fieldset>
    <fieldset><legend>2. Actors and reusable fixture</legend><label>Authentication<select value={authMode} onChange={(event) => { setAuthMode(event.target.value as typeof authMode); changed(); }}><option value="public">Public</option><option value="primary">Primary actor</option><option value="account-pair">Account A/B</option></select></label>{authMode !== "public" && <label>{authMode === "primary" ? "Primary actor" : "Account A"}<select value={actorA} onChange={(event) => { setActorA(event.target.value); changed(); }}><option value="">Select credential</option>{targetCredentials.map(option)}</select></label>}{authMode === "account-pair" && <label>Account B<select value={actorB} onChange={(event) => { setActorB(event.target.value); changed(); }}><option value="">Select credential</option>{targetCredentials.map(option)}</select></label>}<label>Allowed fixture path prefixes<textarea value={pathPrefixes} onChange={(event) => { setPathPrefixes(event.target.value); changed(); }} /></label><label className="inline-check"><input type="checkbox" checked={cleanupRequired} onChange={(event) => { setCleanupRequired(event.target.checked); if (!event.target.checked) setCleanupReserve(0); changed(); }} /> Fixture mutates disposable state and requires cleanup</label><label>Operator notes<textarea value={operatorNotes} onChange={(event) => { setOperatorNotes(event.target.value); changed(); }} /></label></fieldset>
    <fieldset><legend>3. Global safety limits</legend><label>Max requests<input type="number" value={maxRequests} onChange={(event) => { setMaxRequests(Number(event.target.value)); changed(); }} /></label><label>Cleanup reserve<input type="number" value={cleanupReserve} onChange={(event) => { setCleanupReserve(Number(event.target.value)); changed(); }} /></label><label>Requests/second<input type="number" value={rate} onChange={(event) => { setRate(Number(event.target.value)); changed(); }} /></label><label>Concurrency<input type="number" value={concurrency} onChange={(event) => { setConcurrency(Number(event.target.value)); changed(); }} /></label><label>Approved 51C recommendation<select value={recommendationId} onChange={(event) => { setRecommendationId(event.target.value); changed(); }}><option value="">No recommendation binding</option>{recommendations.filter((item) => item.engineId === engineId).map((item) => <option key={item.id} value={item.id}>{item.category}</option>)}</select></label></fieldset></div>
    {target && <section className="panel"><label>Engine<select value={engineId} onChange={(event) => { setEngineId(event.target.value as AdvancedEngineId); setDrafts([]); setSelected(undefined); changed(); }}><option value="api-graphql-authorization">API / GraphQL authorization</option><option value="supabase-authorization">Supabase authorization</option><option value="authentication-lifecycle">Authentication lifecycle</option><option value="business-invariant">Business invariants</option><option value="controlled-race">Controlled race</option><option value="link-portal-export-security">Links, portals, exports</option><option value="operational-endpoint-security">Operational endpoints</option><option value="billing-entitlement-security">Synthetic billing</option></select></label><AdvancedEngineStudio key={`${targetId}:${engineId}`} target={target.baseOrigin} initialEngineId={engineId} drafts={drafts} selectedModules={modules} onChange={(value) => { setDrafts(value); changed(); }} onEnableModule={(id) => setModules((items) => [...new Set([...items,id])])} onPreview={doPreview} /></section>}
    {diagnostics.length > 0 && <div className="workflow-diagnostic-summary" role="alert">{diagnostics.map((item,index) => <span key={index}><code>{item.path.join(".") || "root"}</code> — {item.message}</span>)}</div>}
    <div className="actions"><button disabled={!target || !engineDraft} onClick={() => void doPreview()}>Preview adapter + scan</button><button className="primary" disabled={!canManage || !preview || preview.blockers.length > 0} onClick={() => void save()}>{selected ? "Create new version" : "Save encrypted draft"}</button><button disabled={!canManage || !selected?.pendingVersionId || !preview || preview.blockers.length > 0} onClick={() => void review()}>Review exact version</button><button disabled={!canManage || !selected?.activeVersionId || !recommendationId} onClick={() => void bind()}>Bind approved recommendation</button></div>{message && <p aria-live="polite">{message}</p>}
    {preview && <section className="panel"><h3>Authoritative preview</h3><dl className="dense-dl"><dt>Adapter digest</dt><dd><code>{preview.adapterDigest}</code></dd><dt>Engine</dt><dd>{preview.engine.id} · {preview.engine.capability}</dd><dt>Provider</dt><dd>{preview.engine.provider}</dd><dt>Modules</dt><dd>{preview.plan?.modules.length ?? 0}</dd><dt>Planner identity</dt><dd><code>{preview.plan?.previewIdentity ?? "blocked"}</code></dd></dl>{preview.blockers.map((item) => <p className="error" key={item}>{item}</p>)}{preview.warnings.map((item) => <p className="review-owner-warning" key={item}>{item}</p>)}</section>}
    <section className="panel"><h3>Reusable adapters</h3>{adapters.length ? <div className="table compact-table"><div className="row"><span>Adapter</span><span>Binding</span><span>Dependencies</span><span>Actions</span></div>{adapters.map((item) => <div className="row" key={item.id}><span><strong>{item.name}</strong><small>{item.provider} · {item.engineId}</small></span><span>{item.enabled ? "ENABLED" : "DISABLED"}<small>{item.activeVersionId ? "Reviewed version active" : "Draft only"}</small></span><span>{item.impact.scanBindings} scans · {item.impact.recommendationBindings} recommendations<small>{item.impact.activeScans} active</small></span><span><button onClick={() => void open(item.id)}>Open</button><button disabled={!item.enabled || !item.activeVersionId} onClick={() => void use(item.id)}>Use in Scan Studio</button><button disabled={!canManage || (!item.enabled && item.impact.activeScans > 0)} onClick={() => void toggle(item)}>{item.enabled ? "Disable" : "Enable"}</button></span></div>)}</div> : <p className="muted">No reusable fixture/provider adapters exist.</p>}</section>
  </section>;
}

function option(item: Credential) { return <option key={item.id} value={item.id}>{item.safeAlias} · {item.health?.classification ?? "UNVERIFIED"}</option>; }
function fail(setter: (value: string) => void) { return (error: unknown) => setter(error instanceof Error ? error.message : "Request failed."); }
