import { createHash } from "node:crypto";
import { scopeSchema } from "../../config/ConfigSchema.js";
import { ScopeMatcher } from "../../core/scope/ScopeMatcher.js";
import { controlledMutationContractSchema, type ControlledMutationContract } from "../../core/offensive/ControlledMutationTypes.js";
import type { ProductionMutationCase } from "../contracts/ProductionMutationCaseSchemas.js";
import type { TargetSummary } from "../db/DashboardRepositories.js";

export interface ProductionMutationCompilation { contract: ControlledMutationContract; preview: { caseId: string; targetOrigin: string; environment: "PRODUCTION"; intent: ProductionMutationCase["intent"]; securityCategory: ProductionMutationCase["securityCategory"]; expectedOutcome: "MUST_BE_REJECTED" | "MUST_SUCCEED_AND_RESTORE"; actorCredentialProfileId: string; identityEndpoint: string; preconditionEndpoint: string; actorIdentityAssertionPath: string; disposableObjectIdentityAssertionPath: string; endpoints: string[]; authorityField: string; mutationValueHash: string; protectedActionConfigured: boolean; }; }

export function productionMutationPlanIdentity(input: ProductionMutationCase, target: TargetSummary): string { return hash({ schemaVersion: input.schemaVersion, caseId: input.caseId, targetId: input.targetId, targetOrigin: target.baseOrigin, targetRowVersion: target.rowVersion, scope: target.approvedScope, intent: input.intent, securityCategory: input.securityCategory, actorCredentialProfileId: input.actorCredentialProfileId, authorityField: input.authorityField, mutationValue: input.mutationValue, allowedValues: input.allowedValues, identity: input.identity, actorIdentityAssertionPath: input.actorIdentityAssertionPath, precondition: input.precondition, disposableObjectIdentityAssertionPath: input.disposableObjectIdentityAssertionPath, mutation: input.mutation, impactVerification: input.impactVerification, protectedAction: input.protectedAction, rollback: input.rollback, restorationVerification: input.restorationVerification, authorizationExpiresAt: input.authorizationExpiresAt, productionAcknowledged: input.productionAcknowledged }); }

export function compileProductionMutationCase(input: ProductionMutationCase, target: TargetSummary, authorizedAt: string, authorizedBy: string): ProductionMutationCompilation {
  if (!target.productionEnabled) throw new Error("PRODUCTION_TARGET_REQUIRED");
  if (target.id !== input.targetId) throw new Error("TARGET_ID_MISMATCH");
  if (Date.parse(input.authorizationExpiresAt) <= Date.now()) throw new Error("AUTHORIZATION_EXPIRED");
  const scope = scopeSchema.parse(target.approvedScope); const matcher = new ScopeMatcher(target.baseOrigin, scope);
  const absolute = (path: string, method: string): string => { const url = new URL(path, target.baseOrigin); if (url.origin !== new URL(target.baseOrigin).origin || !matcher.isAllowed(url.toString(), method)) throw new Error("PRODUCTION_ENDPOINT_OUT_OF_SCOPE"); return url.toString(); };
  const identityUrl = absolute(input.identity.path, "GET"); const preconditionUrl = absolute(input.precondition.path, "GET"); const mutationUrl = absolute(input.mutation.path, input.mutation.method); const impactUrl = absolute(input.impactVerification.path, "GET"); const rollbackUrl = absolute(input.rollback.path, input.rollback.method); const restorationUrl = absolute(input.restorationVerification.path, "GET"); const protectedUrl = input.protectedAction ? absolute(input.protectedAction.path, "GET") : undefined;
  const actorIdentityAssertion = input.identity.assertions.find((assertion) => assertion.path === input.actorIdentityAssertionPath && assertion.operator === "EQUALS" && assertion.expectedValue !== undefined); if (!actorIdentityAssertion) throw new Error("PRODUCTION_ACTOR_IDENTITY_ASSERTION_REQUIRED");
  const targetIdentityAssertion = input.precondition.assertions.find((assertion) => assertion.path === input.disposableObjectIdentityAssertionPath && assertion.operator === "EQUALS" && assertion.expectedValue !== undefined); if (!targetIdentityAssertion) throw new Error("PRODUCTION_TARGET_IDENTITY_ASSERTION_REQUIRED");
  const jsonGet = (url: string) => ({ url, method: "GET" as const, headers: { accept: "application/json" } });
  const jsonMutation = (url: string, method: "POST" | "PATCH" | "PUT", body: Record<string, unknown>) => ({ url, method, headers: { accept: "application/json", "content-type": "application/json" }, body: JSON.stringify(body) });
  const contract = controlledMutationContractSchema.parse({ schemaVersion: 1, caseId: input.caseId, targetOrigin: target.baseOrigin, mode: "CONTROLLED_MUTATION", intent: input.intent, securityCategory: input.securityCategory, environment: "PRODUCTION", productionAcknowledged: true, authorization: { authorizedBy, changeTicket: `ROUTECAIRN-${input.caseId}`, confirmation: "I_CONFIRM_EXPLICIT_AUTHORIZATION_AND_CLEANUP_DUTY", authorizedAt, expiresAt: input.authorizationExpiresAt }, actor: { credentialReferenceFingerprint: hash(input.actorCredentialProfileId), identityFingerprint: hash(actorIdentityAssertion.expectedValue), identityAssertion: actorIdentityAssertion }, identity: { request: jsonGet(identityUrl), assertions: input.identity.assertions, attempts: input.identity.attempts, delayMs: input.identity.delayMs }, target: { disposable: true, type: "production-disposable-target", alias: input.disposableTargetAlias, identityFingerprint: hash(targetIdentityAssertion.expectedValue), identityAssertion: targetIdentityAssertion }, attack: { request: jsonMutation(mutationUrl, input.mutation.method, input.mutation.body), allowedFields: [input.authorityField], allowedValues: { [input.authorityField]: input.allowedValues }, semanticEffect: "UPDATE_EXISTING" }, precondition: { request: jsonGet(preconditionUrl), assertions: input.precondition.assertions, attempts: input.precondition.attempts, delayMs: input.precondition.delayMs }, impact: { request: jsonGet(impactUrl), assertions: input.impactVerification.assertions, attempts: input.impactVerification.attempts, delayMs: input.impactVerification.delayMs }, ...(protectedUrl && input.protectedAction ? { protectedAction: { request: jsonGet(protectedUrl), assertions: input.protectedAction.assertions, attempts: input.protectedAction.attempts, delayMs: input.protectedAction.delayMs } } : {}), rollback: { request: jsonMutation(rollbackUrl, input.rollback.method, input.rollback.body), verification: { request: jsonGet(restorationUrl), assertions: input.restorationVerification.assertions, attempts: input.restorationVerification.attempts, delayMs: input.restorationVerification.delayMs } } });
  return { contract, preview: { caseId: input.caseId, targetOrigin: target.baseOrigin, environment: "PRODUCTION", intent: input.intent, securityCategory: input.securityCategory, expectedOutcome: input.intent === "SECURITY_NEGATIVE" ? "MUST_BE_REJECTED" : "MUST_SUCCEED_AND_RESTORE", actorCredentialProfileId: input.actorCredentialProfileId, identityEndpoint: new URL(identityUrl).pathname, preconditionEndpoint: new URL(preconditionUrl).pathname, actorIdentityAssertionPath: input.actorIdentityAssertionPath, disposableObjectIdentityAssertionPath: input.disposableObjectIdentityAssertionPath, endpoints: [identityUrl, preconditionUrl, mutationUrl, impactUrl, ...(protectedUrl ? [protectedUrl] : []), rollbackUrl, restorationUrl].map((url) => new URL(url).pathname), authorityField: input.authorityField, mutationValueHash: hash(input.mutationValue), protectedActionConfigured: Boolean(protectedUrl) } };
}
function hash(value: unknown): string { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
