import { createHash } from "node:crypto";
import { scopeSchema } from "../../config/ConfigSchema.js";
import { ScopeMatcher } from "../../core/scope/ScopeMatcher.js";
import { controlledMutationContractSchema, type ControlledMutationContract } from "../../core/offensive/ControlledMutationTypes.js";
import type { ProductionMutationCase } from "../contracts/ProductionMutationCaseSchemas.js";
import type { TargetSummary } from "../db/DashboardRepositories.js";

export interface ProductionMutationCompilation { contract: ControlledMutationContract; preview: { caseId: string; targetOrigin: string; environment: "PRODUCTION"; actorCredentialProfileId: string; endpoints: string[]; authorityField: string; mutationValueHash: string; protectedActionConfigured: boolean; }; }

export function productionMutationPlanIdentity(input: ProductionMutationCase, target: TargetSummary): string { return hash({ schemaVersion: input.schemaVersion, caseId: input.caseId, targetId: input.targetId, targetOrigin: target.baseOrigin, targetRowVersion: target.rowVersion, scope: target.approvedScope, actorCredentialProfileId: input.actorCredentialProfileId, authorityField: input.authorityField, mutationValue: input.mutationValue, allowedValues: input.allowedValues, identity: input.identity, precondition: input.precondition, mutation: input.mutation, impactVerification: input.impactVerification, protectedAction: input.protectedAction, rollback: input.rollback, restorationVerification: input.restorationVerification, authorizationExpiresAt: input.authorizationExpiresAt, productionAcknowledged: input.productionAcknowledged }); }

export function compileProductionMutationCase(input: ProductionMutationCase, target: TargetSummary, authorizedAt: string, authorizedBy: string): ProductionMutationCompilation {
  if (!target.productionEnabled) throw new Error("PRODUCTION_TARGET_REQUIRED");
  if (target.id !== input.targetId) throw new Error("TARGET_ID_MISMATCH");
  if (Date.parse(input.authorizationExpiresAt) <= Date.now()) throw new Error("AUTHORIZATION_EXPIRED");
  const scope = scopeSchema.parse(target.approvedScope); const matcher = new ScopeMatcher(target.baseOrigin, scope);
  const absolute = (path: string, method: string): string => { const url = new URL(path, target.baseOrigin); if (url.origin !== new URL(target.baseOrigin).origin || !matcher.isAllowed(url.toString(), method)) throw new Error("PRODUCTION_ENDPOINT_OUT_OF_SCOPE"); return url.toString(); };
  const identityUrl = absolute(input.identity.path, "GET"); const preconditionUrl = absolute(input.precondition.path, "GET"); const mutationUrl = absolute(input.mutation.path, input.mutation.method); const impactUrl = absolute(input.impactVerification.path, "GET"); const rollbackUrl = absolute(input.rollback.path, input.rollback.method); const restorationUrl = absolute(input.restorationVerification.path, "GET"); const protectedUrl = input.protectedAction ? absolute(input.protectedAction.path, "GET") : undefined;
  const identityAssertion = input.identity.assertions.find((assertion) => assertion.operator === "EQUALS" && assertion.expectedValue !== undefined); if (!identityAssertion) throw new Error("PRODUCTION_IDENTITY_ASSERTION_REQUIRED");
  const contract = controlledMutationContractSchema.parse({ schemaVersion: 1, caseId: input.caseId, targetOrigin: target.baseOrigin, mode: "CONTROLLED_MUTATION", environment: "PRODUCTION", productionAcknowledged: true, authorization: { authorizedBy, changeTicket: `ROUTECAIRN-${input.caseId}`, confirmation: "I_CONFIRM_EXPLICIT_AUTHORIZATION_AND_CLEANUP_DUTY", authorizedAt, expiresAt: input.authorizationExpiresAt }, target: { disposable: true, type: "production-disposable-target", alias: input.disposableTargetAlias, identityFingerprint: hash(identityAssertion.expectedValue), identityAssertion }, attack: { request: { url: mutationUrl, method: input.mutation.method, body: JSON.stringify(input.mutation.body) }, allowedFields: [input.authorityField], allowedValues: { [input.authorityField]: input.allowedValues }, semanticEffect: "UPDATE_EXISTING" }, precondition: { request: { url: preconditionUrl, method: "GET" }, assertions: [...input.precondition.assertions, identityAssertion], attempts: input.precondition.attempts, delayMs: input.precondition.delayMs }, impact: { request: { url: impactUrl, method: "GET" }, assertions: input.impactVerification.assertions, attempts: input.impactVerification.attempts, delayMs: input.impactVerification.delayMs }, ...(protectedUrl && input.protectedAction ? { protectedAction: { request: { url: protectedUrl, method: "GET" }, assertions: input.protectedAction.assertions, attempts: input.protectedAction.attempts, delayMs: input.protectedAction.delayMs } } : {}), rollback: { request: { url: rollbackUrl, method: input.rollback.method, body: JSON.stringify(input.rollback.body) }, verification: { request: { url: restorationUrl, method: "GET" }, assertions: input.restorationVerification.assertions, attempts: input.restorationVerification.attempts, delayMs: input.restorationVerification.delayMs } } });
  return { contract, preview: { caseId: input.caseId, targetOrigin: target.baseOrigin, environment: "PRODUCTION", actorCredentialProfileId: input.actorCredentialProfileId, endpoints: [identityUrl, preconditionUrl, mutationUrl, impactUrl, ...(protectedUrl ? [protectedUrl] : []), rollbackUrl, restorationUrl].map((url) => new URL(url).pathname), authorityField: input.authorityField, mutationValueHash: hash(input.mutationValue), protectedActionConfigured: Boolean(protectedUrl) } };
}
function hash(value: unknown): string { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
